#!/usr/bin/env python3
"""One-off Step 2 round 6 migration of hand-authored fixtures to contracts/fixture-place-kinds.json.

Evidence for docs/execution/step2r-round6/README.md, not a gate: ./verify prepare
(ContractValidator.placeKindProblems) is the gate. Generator-owned fixtures are skipped and
regenerated by their own generators (T01/T20/T25 author_cases.py, T06/T22/T24
author_contracts.py, T23/V8 build_cases.py, T26 autonomous/forged copies).

Rules (contracts/fixture-place-kinds.md):
1. A Place alias kind INTERNAL_WAREHOUSE/WAREHOUSE -> INTERNAL_STORAGE, PORT -> EXTERNAL_PORT,
   TRANSPORT -> TRANSIT, EXTERNAL_CUSTOMER -> CUSTOMER. A kind-less Place takes the (mapped)
   baseline.places kind, else the meaning of its alias key (W* storage, TRANSIT, CUSTOMER*,
   C_PLACE customer, SUPPLIER_PLACE/IT-origin supplier, *port external port).
2. baseline.places[].kind gets the same contract kind as its alias.
3. The Organization alias of kind WAREHOUSE that segments name as custodian (CUSTODIAN) is the
   fixture organization's own warehouse custodian, so it becomes an internal Human custodian.
4. A segment at INTERNAL_STORAGE, TRANSIT or EXTERNAL_PORT (the importer's own cargo) without a
   custodian gets the internal custodian `warehouse` (else `receiver`, else a new Human
   alias `warehouse`). Segments at CUSTOMER/SUPPLIER places keep their custody as authored.
Run: python3 -I docs/execution/step2r-round6/migrate_place_kinds.py [--write]
"""
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]
CONTRACT = json.loads((ROOT / 'contracts/fixture-place-kinds.json').read_text())
KINDS = {k['kind'] for k in CONTRACT['kinds']}
RETIRED = {r['kind']: r['replacement'] for r in CONTRACT['retiredFixtureKinds']}
INTERNAL = set(CONTRACT['internalCustodianAliasTypes'])
NAME_KIND = {'W': 'INTERNAL_STORAGE', 'W2': 'INTERNAL_STORAGE', 'W-B': 'INTERNAL_STORAGE', 'W-alt': 'INTERNAL_STORAGE',
             'TRANSIT': 'TRANSIT', 'CUSTOMER': 'CUSTOMER', 'CUSTOMER-PLACE': 'CUSTOMER', 'C_PLACE': 'CUSTOMER',
             'SUPPLIER_PLACE': 'SUPPLIER', 'IT-origin': 'SUPPLIER', 'PORT': 'EXTERNAL_PORT', 'IT-port': 'EXTERNAL_PORT',
             'KR-port': 'EXTERNAL_PORT'}
CUSTODY_NEEDED = {'INTERNAL_STORAGE', 'TRANSIT', 'EXTERNAL_PORT'}
GENERATED = {'verification/cases/T01/fixture.json', 'verification/cases/T20/fixture.json', 'verification/cases/T25/fixture.json',
             'verification/cases/T26/fixtures/safe-retry-forged-original-actor.json',
             'verification/cases/T26/fixtures/due-wait-autonomous-loop.json',
             'verification/cases/T26/fixtures/lot-expiry-autonomous-loop.json',
             'verification/cases/T26/fixtures/orphan-intake-autonomous-loop.json'}
GENERATED_DIRS = ('verification/cases/T06/fixtures/', 'verification/cases/T22/fixtures/', 'verification/cases/T24/fixtures/',
                  'verification/cases/T23/fixtures/', 'verification/cases/V8/fixtures/')


def fixture_files():
    # Product case fixtures only. The HARNESS-EXAMPLE selftest fixture is not a product case and keeps its bytes.
    roots = [ROOT / 'verification/cases']
    for base in roots:
        for p in sorted(base.rglob('*.json')):
            rel = p.relative_to(ROOT).as_posix()
            if rel in GENERATED or rel.startswith(GENERATED_DIRS):
                continue
            try:
                d = json.loads(p.read_text())
            except ValueError:
                continue
            if isinstance(d, dict) and 'fixtureId' in d and isinstance(d.get('aliases'), dict):
                yield p, rel, d


def contract_kind(kind):
    return RETIRED.get(kind, kind)


def normalize(f, log):
    al = f['aliases']
    places_b = {e.get('alias'): e for e in f.get('baseline', {}).get('places', []) if isinstance(e, dict)}
    for name, a in al.items():
        if not isinstance(a, dict) or a.get('type') != 'Place' or 'kindControl' in a:
            continue
        old = a.get('kind')
        if old is not None:
            new = contract_kind(old)
        elif name in places_b and places_b[name].get('kind'):
            new = contract_kind(places_b[name]['kind'])
        elif name in NAME_KIND:
            new = NAME_KIND[name]
        else:
            raise SystemExit(f'{f["fixtureId"]}: no contract kind for Place {name}')
        if new not in KINDS:
            raise SystemExit(f'{f["fixtureId"]}: Place {name} kind {old} has no contract replacement')
        if new != old:
            a['kind'] = new
            log.append(f'place {name}: {old} -> {new}')
    for name, e in places_b.items():
        if name in al and e.get('kind') is not None and e['kind'] != al[name].get('kind'):
            log.append(f'baseline.places {name}: {e["kind"]} -> {al[name]["kind"]}')
            e['kind'] = al[name]['kind']
    reps = {}
    for name, a in al.items():
        if isinstance(a, dict) and a.get('type') == 'QuantitySegment':
            reps.setdefault(name, []).append(a)
    for e in f.get('baseline', {}).get('segments', []) or []:
        if isinstance(e, dict) and e.get('alias'):
            reps.setdefault(e['alias'], []).append(e)
    custodians = {r.get('custodianAlias') for rs in reps.values() for r in rs if r.get('custodianAlias')}
    for name in sorted(custodians):
        a = al.get(name)
        if isinstance(a, dict) and a.get('type') == 'Organization' and a.get('kind') == 'WAREHOUSE':
            new = {'type': 'Human', 'name': '내부 창고 보관 담당'}
            if 'organizationAlias' in a:
                new['organizationAlias'] = a['organizationAlias']
            al[name] = new
            log.append(f'custodian {name}: Organization(WAREHOUSE) -> internal Human')
    for seg, rs in reps.items():
        location = next((r.get('locationAlias') or r.get('placeAlias') for r in rs if r.get('locationAlias') or r.get('placeAlias')), None)
        if location is None or not isinstance(al.get(location), dict):
            continue
        kind = al[location].get('kind')
        if kind not in CUSTODY_NEEDED or any(r.get('custodianAlias') for r in rs):
            continue
        custodian = next((c for c in ('warehouse', 'receiver') if isinstance(al.get(c), dict) and al[c].get('type') in INTERNAL), None)
        if custodian is None:
            custodian = 'warehouse'
            new = {'type': 'Human', 'name': '내부 창고 보관 담당'}
            if 'organizationAlias' in al[location]:
                new['organizationAlias'] = al[location]['organizationAlias']
            al[custodian] = new
            log.append('alias warehouse: new internal Human custodian')
        for r in rs:
            if r.get('locationAlias') or r.get('placeAlias'):
                r['custodianAlias'] = custodian
        log.append(f'segment {seg}@{location}({kind}): custodian {custodian}')


def main():
    write = '--write' in sys.argv
    changed = 0
    for p, rel, d in fixture_files():
        log = []
        normalize(d, log)
        if log:
            changed += 1
            print(rel)
            for line in log:
                print('   ', line)
            if write:
                p.write_text(json.dumps(d, ensure_ascii=False, indent=2) + '\n')
    print(('WRITTEN ' if write else 'DRY ') + str(changed) + ' fixture files')


if __name__ == '__main__':
    main()
