package com.mulino.quality;
import com.mulino.application.core.*;
import com.mulino.application.quality.*;
import com.mulino.application.runtime.InventoryValiditySweeper;
import com.mulino.domain.inventory.InventoryRepository;
import com.mulino.domain.definitions.*;
import com.sap.cds.services.runtime.CdsRuntime;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.nio.file.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.test.context.*;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@SpringBootTest
@ActiveProfiles("local")
class FulfillmentPostgresTest {
 static final PostgreSQLContainer PG=new PostgreSQLContainer("postgres@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280");
 static final Path BLOBS;static{try{BLOBS=Files.createTempDirectory("mulino-s4-inventory-",java.nio.file.attribute.PosixFilePermissions.asFileAttribute(java.nio.file.attribute.PosixFilePermissions.fromString("rwx------")));PG.start();}catch(Exception e){throw new IllegalStateException(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",PG::getJdbcUrl);r.add("spring.datasource.username",PG::getUsername);r.add("spring.datasource.password",PG::getPassword);r.add("mulino.evidence.blob-root",BLOBS::toString);r.add("JWT_PUBLIC_KEY",()->System.getenv("JWT_PUBLIC_KEY"));r.add("JWT_ISSUER",()->"https://fixture.invalid");r.add("JWT_AUDIENCE",()->"mulino-acceptance");}
 @Autowired DefinitionValidator validator;@Autowired JdbcTemplate jdbc;@Autowired ApplicationCommands gateway;@Autowired QualityEligibility eligibility;@Autowired InventoryRepository inventory;@Autowired CdsRuntime runtime;@Autowired InventoryValiditySweeper sweeper;@Autowired org.springframework.transaction.PlatformTransactionManager transactions;
 @MockitoBean org.springframework.security.oauth2.jwt.JwtDecoder decoder;
 @MockitoBean ExecutionClock clock;
 final ObjectMapper json=new ObjectMapper();String org,actor,item,lot,place,segment,work,grant,definition,profile,regPolicy;Instant now=Instant.parse("2026-10-08T00:00:00Z");
 String id(){return UUID.randomUUID().toString();}Map<String,Object>map(Object...v){var m=new LinkedHashMap<String,Object>();for(int i=0;i<v.length;i+=2)m.put(v[i].toString(),v[i+1]);return m;}
 void insert(String table,Map<String,Object>r){jdbc.update("INSERT INTO "+table+"("+String.join(",",r.keySet())+") VALUES("+String.join(",",Collections.nCopies(r.size(),"?"))+")",r.values().toArray());}
 Map<String,Object>base(String id){return map("organizationId",org,"ID",id,"revision",0,"createdAt",Timestamp.from(now.minusSeconds(10)),"recordedAt",Timestamp.from(now.minusSeconds(10)));}
 void record(String table,String id,Map<String,Object>values){var r=base(id);r.putAll(values);insert(table,r);}
 @BeforeEach void seed(org.junit.jupiter.api.TestInfo info)throws Exception{
  when(clock.instant()).thenAnswer(x->now);jdbc.execute("TRUNCATE mulino_identity_Organizations CASCADE");org=id();actor=id();item=id();lot=id();place=id();segment=id();work=id();grant=id();definition=id();profile=id();regPolicy=id();
  insert("mulino_identity_Organizations",map("ID",org,"externalAlias",org));insert("mulino_identity_Actors",map("organizationId",org,"ID",actor,"kind","HUMAN","stableRequestOwner",actor));insert("mulino_identity_AuthorityFences",map("organizationId",org,"actorId",actor,"revision",1));insert("mulino_identity_ExternalIdentities",map("organizationId",org,"ID",id(),"actorId",actor,"issuer","https://fixture.invalid","subject","quality","organizationAlias",org));
  insert("mulino_identity_Memberships",map("organizationId",org,"ID",id(),"actorId",actor,"validFrom",Timestamp.from(now.minusSeconds(1000)),"validUntil",Timestamp.from(now.plusSeconds(10000))));insert("mulino_identity_Grants",map("organizationId",org,"ID",grant,"actorId",actor,"delegatorId",actor,"validFrom",Timestamp.from(now.minusSeconds(1000)),"validUntil",Timestamp.from(now.plusSeconds(10000))));insert("mulino_identity_GrantScopes",map("organizationId",org,"grantId",grant,"scopeKind","ORGANIZATION","scopeId",org));
  var caps=List.of("createDraft","activateWork","placeHold","releaseHold","recordDispositionBasis","revokeDispositionBasis","attachEvidence","recordActivity","matchSourceIdentity","linkCanonicalOccurrence","getEvidence","getWork","decideQuality","confirmCustomerConditions","confirmCommercialDisposition","decideRecallRestriction","reserveQuantity","prepareRegulatoryProcedure","recordSubmission","recordRegulatoryDecision","createSalesOrder","reviseSalesOrder","splitQuantity","adjustQuantity","recordStocktake","pickQuantity","dispatchQuantity","replaceAllocation","releaseAllocation","getInventory");for(String cap:caps){insert("mulino_identity_CapabilityAssignments",map("organizationId",org,"ID",id(),"actorId",actor,"capabilityId",cap,"scopeKind","ORGANIZATION","scopeId",org,"validFrom",Timestamp.from(now.minusSeconds(1000)),"validUntil",Timestamp.from(now.plusSeconds(10000))));insert("mulino_identity_GrantActions",map("organizationId",org,"grantId",grant,"capabilityId",cap));}
  String product=id(),spec=id(),pack=id(),maker=id();record("mulino_inventory_Products",product,map("name","biscuit"));for(var type:List.of("SpecificationVersions","PackagingVersions"))record("mulino_inventory_"+type,type.startsWith("Spec")?spec:pack,map("productId",product,"version","1","contentHash","a".repeat(64)));record("mulino_inventory_TradeItems",item,map("productId",product,"name","biscuit","baseUnit","EA","decimalPlaces",info.getTestMethod().orElseThrow().getName().startsWith("decimal")?12:0,"specificationVersionId",spec,"packagingVersionId",pack));record("mulino_inventory_Manufacturers",maker,map("name","maker"));record("mulino_inventory_ManufacturingLots",lot,map("manufacturerId",maker,"itemId",item,"originalLot","LOT","expiresAt",Timestamp.from(now.plusSeconds(100))));record("mulino_inventory_Places",place,map("name","warehouse","kind","INTERNAL_STORAGE"));record("mulino_inventory_QuantitySegments",segment,map("itemId",item,"lotId",lot,"identificationStatus","CONFIRMED","quantity",new BigDecimal(info.getTestMethod().orElseThrow().getName().startsWith("actual50")||info.getTestMethod().orElseThrow().getName().startsWith("v2")?"60":"100"),"unit","EA","placeId",place,"controlScope","quality","validFrom",Timestamp.from(now.minusSeconds(10)),"mixtureStatus","IDENTIFIED","ownerId",actor,"custodianId",actor));
  var d=new Definition(org,definition,"definition-v1",null,"PUBLISHED",null,"core-v1","1.0.0",List.of(new Definition.NounType("QuantitySegment",true),new Definition.NounType("TradeItem",true),new Definition.NounType("Work",true),new Definition.NounType("Receipt",true),new Definition.NounType("SalesOrderLine",true),new Definition.NounType("SalesOrder",true)),List.of(new Definition.Attribute("Receipt","quantity",Definition.ValueType.DECIMAL,null,"EA",0,1,1,"READ",true)),caps.stream().filter(c->gateway.operations().contains(c)||Set.of("getWork","getEvidence").contains(c)).map(c->new Definition.Verb(c,kind(c),c,"ACTIVE",Map.of())).toList(),List.of(),List.of(new Definition.Goal("Arrival","CUMULATIVE_EVENT","ARRIVED","core-v1",map("operator","quantitySum","property","Receipt.quantity","minimum",map("value","1","unit","EA"),"unit","EA","evidenceSelector","VERIFIED_DISTINCT"))),caps.stream().filter(c->gateway.operations().contains(c)||Set.of("getWork","getEvidence").contains(c)).map(c->new Definition.Capability(c,"1.0.0","core-v1","1.0.0","1.0.0",List.of())).toList());assertEquals("VALID",validator.validate(d).outcome(),validator.validate(d).problems().toString());String content=json.writeValueAsString(d);insert("mulino_definitions_DefinitionVersions",map("organizationId",org,"ID",definition,"createdAt",Timestamp.from(now.minusSeconds(10)),"version",d.version(),"state","PUBLISHED","contentHash",DefinitionRepository.sha256(content),"content",content,"evaluatorVersion","core-v1","schemaVersion","1.0.0"));
  record("mulino_evidence_SourceProfiles",profile,map("revision",1,"recordedBy",actor,"namespace","quality-source","policyVersion","fixture-v1","intakeOwnerId",actor,"supervisorId",actor,"nextAction","Review source","nextCheckAt",Timestamp.from(now.plusSeconds(60))));
  var rules=new TreeMap<String,Object>();for(String cap:caps){String effect=List.of("createDraft","activateWork").contains(cap)?"WORK":List.of("attachEvidence","recordActivity").contains(cap)?"RECORD":List.of("matchSourceIdentity","linkCanonicalOccurrence").contains(cap)?"RECONCILIATION":cap.startsWith("recordRegulatory")||cap.equals("recordSubmission")||cap.equals("prepareRegulatoryProcedure")?"REGULATORY_RECORD":Set.of("reserveQuantity","replaceAllocation").contains(cap)?"RESERVE":Set.of("pickQuantity","releaseAllocation").contains(cap)?"ALLOCATION":cap.equals("dispatchQuantity")?"DISPATCH":cap.equals("splitQuantity")?"SPLIT":cap.equals("adjustQuantity")?"ADJUSTMENT":cap.equals("recordStocktake")?"RECORD_STOCKTAKE":Set.of("createSalesOrder","reviseSalesOrder").contains(cap)?"SALES_ORDER":"QUALITY_CONTROL";rules.put(cap,map("effectClass",effect,"approvalAction",null,"categoryCapabilities",map("QC","decideQuality","CUSTOMER","confirmCustomerConditions","COMMERCIAL","confirmCommercialDisposition","RECALL","decideRecallRestriction")));}
  policy("COMMAND",json.writeValueAsString(map("rules",rules)));policy("EVIDENCE","{}");policy("ELIGIBILITY","{\"actions\":{\"SELL\":{\"requiredCategories\":[\"QC\",\"CUSTOMER\",\"COMMERCIAL\"]},\"DISPATCH\":{\"requiredCategories\":[\"QC\",\"CUSTOMER\",\"COMMERCIAL\"]}}}");
  record("mulino_trade_regulatory_Policies",regPolicy,map("recordedBy",actor,"version","fixture-v1","authority","FICTIONAL_TEST_AUTHORITY","sourceNamespace","quality-source","action","SELL","validFrom",Timestamp.from(now.minusSeconds(10)),"validUntil",Timestamp.from(now.plusSeconds(1000)),"fictional",true,"status","ACTIVE","requiresLabel",false));
  SecurityContextHolder.getContext().setAuthentication(new JwtAuthenticationToken(Jwt.withTokenValue("local-test").header("alg","RS256").issuer("https://fixture.invalid").subject("quality").claim("organizationId",org).build(),List.of()));
  var goal=map("quantityMode","CUMULATIVE_EVENT","targetQuantity","100","unit","EA","endpoint","ARRIVED","dueAt","2026-10-31T00:00:00Z","scope",Map.of("itemId",item),"timezone","UTC","evidencePolicyVersion","fixture-v1","periodStartInclusive",true,"periodEndInclusive",true,"periodStart","2026-10-01T00:00:00Z","periodEnd","2026-10-31T00:00:00Z","eventKind","RECEIPT","contributionScope",Map.of("itemId",item),"deduplication","CANONICAL_OCCURRENCE","conditions",List.of(Map.of("id","Arrival")),"evaluatorVersion","core-v1");work=effects(run("createDraft",map("itemId",item,"lotId",lot,"definitionVersionId",definition,"kind","QUALITY","ownerId",actor,"supervisorId",actor,"goal",goal),0)).get("workId").toString();run("activateWork",map("workId",work),0);
 }
 void policy(String kind,String content){String id=id();insert("mulino_governance_PolicyVersions",map("organizationId",org,"ID",id,"revision",1,"createdAt",Timestamp.from(now.minusSeconds(10)),"kind",kind,"version","fixture-v1","content",content,"contentHash",DefinitionRepository.sha256(content),"effectiveFrom",Timestamp.from(now.minusSeconds(10))));insert("mulino_governance_ActivePolicies",map("organizationId",org,"kind",kind,"policyId",id,"revision",1));}
 String kind(String cap){return Set.of("recordDispositionBasis","recordActivity","attachEvidence","recordSubmission","recordRegulatoryDecision","recordStocktake").contains(cap)?"RECORD":"COMMAND";}
 Map<String,Object>run(String cap,Map<String,Object>slots,Integer revision){var i=map("intentKind",kind(cap),"definitionVersion","definition-v1","capabilityId",cap,"commandIdempotencyKey",id(),"subjectRefs",List.of(),"slots",slots,"provenance",map("sourceNamespace","USER"));if(revision!=null)i.put("expectedRevision",revision);var result=runtime.requestContext().run(ctx->{return {return gateway.execute(i);};});assertEquals("APPLIED",result.get("outcome"),result.toString());return result;}
 String evidence(Map<String,Object>payload,String kind){try{if(Set.of("REGULATORY_SUBMISSION","REGULATORY_DECISION","LABEL_VERIFICATION").contains(kind))payload.put("regulatoryEventId",id());String bytes=json.writeValueAsString(payload);if(payload.get("operation")!=null&&Set.of("placeHold","recordDispositionBasis").contains(payload.get("operation")))kind="QUALITY_DECISION_"+payload.get("operation")+"_"+payload.get("category");String observedQuantity=payload.containsKey("quantity")&&(kind.equals("REGULATORY_DECISION")||kind.startsWith("QUALITY_DECISION_"))?payload.get("quantity").toString():Set.of("REGULATORY_SUBMISSION","LABEL_VERIFICATION").contains(kind)?null:scopeAmount();String observedUnit=observedQuantity==null?null:"EA";var doc=run("attachEvidence",map("subject",map("kind","SEGMENT","id",segment),"sourceNamespace","quality-source","sourceReference",id(),"mediaType","application/json","expectedHash",com.mulino.adapters.blob.LocalBlobStore.hash(bytes.getBytes()),"provenance","SYNTHETIC","contentBase64",Base64.getEncoder().encodeToString(bytes.getBytes())),null).get("id").toString();String eventKey=payload.containsKey("sourceDecisionId")?payload.get("sourceDecisionId").toString():id();var event=run("recordActivity",map("subject",map("kind","SEGMENT","id",segment),"kind",kind,"sourceNamespace","quality-source","externalEventId",eventKey,"sourceVersion","1","effectiveFrom",now.toString(),"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","payload",bytes,"documentId",doc,"assertion","Fixture source","quantity",observedQuantity,"unit",observedUnit),null);var review=run("matchSourceIdentity",map("claimId",event.get("claimId"),"basisDocumentId",doc,"physicalScopeId",segment,"policyVersion","fixture-v1","sourceIdentity","quality-source:"+eventKey+":1","quantity",observedQuantity,"unit",observedUnit,"effectiveFrom",now.toString(),"reason","Synthetic original scope review"),1);run("linkCanonicalOccurrence",map("reconciliationId",review.get("id")),1);return doc;}catch(Exception e){throw new IllegalStateException(e);}}
 String scopeAmount(){return jdbc.queryForObject("SELECT quantity FROM mulino_inventory_QuantitySegments WHERE id=?",BigDecimal.class,segment).stripTrailingZeros().toPlainString();}
 String occurrence(String doc){return jdbc.queryForObject("SELECT canonicalOccurrenceId FROM mulino_evidence_Verifications WHERE basisDocumentId=?",String.class,doc);}
 Map<String,Object>effects(Map<String,Object>r){return (Map<String,Object>)r.get("effects");}
 Map<String,Object>permission(String operation,String category,String q){return map("segmentId",segment,"sourceDecisionId",id(),"sourceVersion","1","workId",work,"operation",operation,"action","SELL","category",category,"startQuantity","0","quantity",q,"unit","EA","validFrom",now.toString(),"validUntil",now.plusSeconds(1000).toString());}
 String basis(String category,String q){var s=permission("recordDispositionBasis",category,q);String doc=evidence(s,"QUALITY_"+category);s.remove("operation");s.remove("sourceDecisionId");s.remove("sourceVersion");s.putAll(map("evidenceId",doc,"reason","Current exact scoped decision","workId",work,"nextCheckAt",now.plusSeconds(60).toString()));return effects(run("recordDispositionBasis",s,0)).get("dispositionBasisId").toString();}
 QualityEligibility.Result assess(){return runtime.requestContext().run(ctx->{return {return eligibility.assess(new DomainContext(org,actor,actor,now,now),inventory.current(new DomainContext(org,actor,actor,now,now),"QuantitySegments",segment),"SELL",null);};});}
 void regulatory(String q){String preparation=evidence(map("purpose","fixture procedure"),"REG_PREPARATION");var prep=run("prepareRegulatoryProcedure",map("itemId",item,"lotId",lot,"physicalScopeId",segment,"workId",work,"policyId",regPolicy,"documentVersionId",preparation),null);String proc=effects(prep).get("procedureId").toString();var payload=map("procedureId",proc,"procedureVersionId",effects(prep).get("procedureVersionId"),"occurredAt",now.toString(),"itemId",item,"lotId",lot,"physicalScopeId",segment,"authority","FICTIONAL_TEST_AUTHORITY","policyVersion","fixture-v1");String submit=evidence(payload,"REGULATORY_SUBMISSION");var submitted=run("recordSubmission",map("procedureId",proc,"occurredAt",now.toString(),"occurrenceId",occurrence(submit)),1);var decision=map("procedureId",proc,"procedureVersionId",effects(submitted).get("procedureVersionId"),"decision","ALLOWED","action","SELL","startQuantity","0","quantity",q,"unit","EA","validFrom",now.toString(),"validUntil",now.plusSeconds(1000).toString(),"itemId",item,"lotId",lot,"physicalScopeId",segment,"authority","FICTIONAL_TEST_AUTHORITY","policyVersion","fixture-v1");String doc=evidence(decision,"REGULATORY_DECISION");for(String key:List.of("procedureVersionId","itemId","lotId","physicalScopeId","authority","policyVersion","regulatoryEventId"))decision.remove(key);decision.put("occurrenceId",occurrence(doc));run("recordRegulatoryDecision",decision,2);}

 void regulatoryAction(String q,String action){String preparation=evidence(map("purpose","fixture procedure"),"REG_PREPARATION");var prep=run("prepareRegulatoryProcedure",map("itemId",item,"lotId",lot,"physicalScopeId",segment,"workId",work,"policyId",regPolicy,"documentVersionId",preparation),null);String proc=effects(prep).get("procedureId").toString();var payload=map("procedureId",proc,"procedureVersionId",effects(prep).get("procedureVersionId"),"occurredAt",now.toString(),"itemId",item,"lotId",lot,"physicalScopeId",segment,"authority","FICTIONAL_TEST_AUTHORITY","policyVersion","fixture-v1");String submit=evidence(payload,"REGULATORY_SUBMISSION");var submitted=run("recordSubmission",map("procedureId",proc,"occurredAt",now.toString(),"occurrenceId",occurrence(submit)),1);var decision=map("procedureId",proc,"procedureVersionId",effects(submitted).get("procedureVersionId"),"decision","ALLOWED","action",action,"startQuantity","0","quantity",q,"unit","EA","validFrom",now.toString(),"validUntil",now.plusSeconds(1000).toString(),"itemId",item,"lotId",lot,"physicalScopeId",segment,"authority","FICTIONAL_TEST_AUTHORITY","policyVersion","fixture-v1");String doc=evidence(decision,"REGULATORY_DECISION");for(String key:List.of("procedureVersionId","itemId","lotId","physicalScopeId","authority","policyVersion","regulatoryEventId"))decision.remove(key);decision.put("occurrenceId",occurrence(doc));run("recordRegulatoryDecision",decision,2);}

 @Autowired com.mulino.domain.inventory.StockPrimitives stock;
 @Autowired com.mulino.domain.inventory.FulfillmentStockPrimitives physical;
 String salesLine,customer,destination,transit;
 @BeforeEach void saleFixture(){customer=id();destination=id();transit=id();record("mulino_trade_sales_Customers",customer,map("name","synthetic B2B"));record("mulino_inventory_Places",destination,map("name","customer","kind","CUSTOMER"));record("mulino_inventory_Places",transit,map("name","transit","kind","TRANSIT"));salesLine=effects(run("createSalesOrder",map("workId",work,"customerId",customer,"itemId",item,"quantity","100","unit","EA","price","1","currency","KRW","dueAt",now.plusSeconds(90).toString(),"destinationId",destination,"deliveryEndpoint","DELIVERED","qualityTerms","fixture","packageTerms","fixture"),null)).get("salesLineId").toString();}
 DomainContext c(){return new DomainContext(org,actor,actor,now,now);}
 Map<String,Object> envelope(String cap,Map<String,Object> slots,int rev){return map("intentKind",kind(cap),"definitionVersion","definition-v1","capabilityId",cap,"commandIdempotencyKey",id(),"subjectRefs",List.of(),"slots",slots,"expectedRevision",rev,"provenance",map("sourceNamespace","USER"));}
 Map<String,Object> apply(Map<String,Object> input){return runtime.requestContext().run(ctx->{return gateway.execute(input);});}
 String reserve(String start,String amount){return effects(run("reserveQuantity",map("segmentId",segment,"salesLineId",salesLine,"startQuantity",start,"quantity",amount,"unit","EA"),0)).get("allocationId").toString();}
 void allow(String amount){regulatory(amount);for(String category:List.of("QC","CUSTOMER","COMMERCIAL"))basis(category,amount);}
 void allowDispatch(){String original=regPolicy;regPolicy=id();record("mulino_trade_regulatory_Policies",regPolicy,map("recordedBy",actor,"version","fixture-v1","authority","FICTIONAL_TEST_AUTHORITY","sourceNamespace","quality-source","action","DISPATCH","validFrom",Timestamp.from(now.minusSeconds(10)),"validUntil",Timestamp.from(now.plusSeconds(1000)),"fictional",true,"status","ACTIVE","requiresLabel",false));regulatoryAction("100","DISPATCH");regPolicy=original;for(String category:List.of("QC","CUSTOMER","COMMERCIAL")){var slots=permission("recordDispositionBasis",category,"100");slots.put("action","DISPATCH");String doc=evidence(slots,"QUALITY_DISPATCH");slots.remove("operation");slots.remove("sourceDecisionId");slots.remove("sourceVersion");slots.putAll(map("evidenceId",doc,"reason","Exact dispatch basis","nextCheckAt",now.plusSeconds(60).toString()));run("recordDispositionBasis",slots,0);}}
 void hold(String quantity){var slots=permission("placeHold","QC",quantity);String doc=evidence(slots,"HOLD");slots.remove("operation");slots.remove("sourceDecisionId");slots.remove("sourceVersion");slots.putAll(map("evidenceId",doc,"reason","Independent hold","nextCheckAt",now.plusSeconds(60).toString()));run("placeHold",slots,0);}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void exactSplitProjectsPermissionsAndDisjointHold(){allow("100");hold("20");var out=run("splitQuantity",map("segmentId",segment,"quantities",List.of("20","80"),"unit","EA","occurredAt",now.toString(),"evidenceRef","synthetic physical partition"),0);var children=(List<String>)effects(out).get("segmentIds");var result=runtime.requestContext().run(ctx->{return eligibility.assess(c(),inventory.current(c(),"QuantitySegments",children.getLast()),"SELL",customer);});assertEquals(0,new BigDecimal("80").compareTo(result.eligibleQuantity()));assertEquals(BigDecimal.ZERO,runtime.requestContext().run(ctx->{return eligibility.assess(c(),inventory.current(c(),"QuantitySegments",children.getFirst()),"SELL",customer);}).eligibleQuantity());}
 @Test void actual50KeepsExecutable50AndExactShortage10WithHumanResponsibility(){allow("60");reserve("0","40");reserve("40","20");String count=effects(run("recordStocktake",map("segmentId",segment,"observedQuantity","50","unit","EA","occurredAt",now.toString(),"evidenceRef","synthetic count50"),0)).get("stocktakeIds") instanceof List<?> list?list.getFirst().toString():null;run("adjustQuantity",map("segmentId",segment,"stocktakeId",count,"direction","DECREASE","quantity","10","unit","EA","occurredAt",now.toString(),"reason","Count reconciled","evidenceRef","synthetic approved correction"),0);assertEquals(0,new BigDecimal("50").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_SegmentAllocations WHERE state='EXECUTABLE'",BigDecimal.class)));assertEquals(0,new BigDecimal("10").compareTo(jdbc.queryForObject("SELECT quantity FROM mulino_inventory_SegmentAllocations WHERE suspensionReason='PHYSICAL_SHORTAGE'",BigDecimal.class)));assertEquals(0,new BigDecimal("50").compareTo(jdbc.queryForObject("SELECT startQuantity FROM mulino_inventory_SegmentAllocations WHERE suspensionReason='PHYSICAL_SHORTAGE'",BigDecimal.class)));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_work_read_ObligationReferences WHERE kind='ALLOCATION_SHORTAGE' AND ownerId=? AND nextCheckAt IS NOT NULL",Integer.class,actor));assertEquals(0,new BigDecimal("10").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantityMovements WHERE kind='ADJUST_DECREASE'",BigDecimal.class)));}
 @Test void publicReservationIdempotencyAndCurrentRoleDenial(){allow("100");var input=envelope("reserveQuantity",map("segmentId",segment,"salesLineId",salesLine,"startQuantity","0","quantity","40","unit","EA"),0);assertEquals("APPLIED",apply(input).get("outcome"));assertEquals("APPLIED",apply(input).get("outcome"));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_SegmentAllocations",Integer.class));var changed=new LinkedHashMap<String,Object>(input);changed.put("slots",map("segmentId",segment,"salesLineId",salesLine,"startQuantity","0","quantity","41","unit","EA"));assertEquals("CONFLICT",apply(changed).get("outcome"));jdbc.update("UPDATE mulino_identity_CapabilityAssignments SET revokedAt=? WHERE capabilityId='reserveQuantity'",Timestamp.from(now));assertEquals("REJECTED",apply(envelope("reserveQuantity",map("segmentId",segment,"salesLineId",salesLine,"startQuantity","40","quantity","20","unit","EA"),0)).get("outcome"));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_SegmentAllocations",Integer.class));}

 <T>T tx(java.util.function.Supplier<T> effect){return new org.springframework.transaction.support.TransactionTemplate(transactions).execute(status->runtime.requestContext().run(ctx->{return effect.get();}));}
 @Test void exactMiddleDisposalPreservesMissing20to30AndRemoved10(){allow("100");String a=reserve("0","60");tx(()->{stock.disposeRange(c(),segment,new BigDecimal("20"),new BigDecimal("10"),now,"synthetic middle disposal",id());return null;});assertEquals(0,new BigDecimal("20").compareTo(jdbc.queryForObject("SELECT startQuantity FROM mulino_inventory_SegmentAllocations WHERE suspensionReason='PHYSICAL_SHORTAGE'",BigDecimal.class)));assertEquals(0,new BigDecimal("10").compareTo(jdbc.queryForObject("SELECT quantity FROM mulino_inventory_SegmentAllocations WHERE suspensionReason='PHYSICAL_SHORTAGE'",BigDecimal.class)));assertEquals(0,new BigDecimal("50").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_SegmentAllocations WHERE state='EXECUTABLE'",BigDecimal.class)));assertEquals(0,new BigDecimal("10").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantityMovements WHERE kind='DISPOSE'",BigDecimal.class)));assertEquals("REPLACED",jdbc.queryForObject("SELECT state FROM mulino_inventory_SegmentAllocations WHERE ID=?",String.class,a));}
 @Test void dispatchMovementCountsOnlySelected20AndObserved10KeepsTransit10(){allow("100");allowDispatch();String allocation=reserve("20","20");run("pickQuantity",map("allocationId",allocation),0);var out=run("dispatchQuantity",map("allocationId",allocation,"transitPlaceId",transit,"occurredAt",now.toString(),"evidenceRef","synthetic dispatch"),1);String dispatch=effects(out).get("dispatchId").toString();assertEquals(0,new BigDecimal("20").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantityMovements WHERE kind='DISPATCH'",BigDecimal.class)));var delivered=tx(()->physical.observeDelivery(c(),dispatch,id(),new BigDecimal("20"),new BigDecimal("10"),now,id()));assertEquals(0,new BigDecimal("10").compareTo((BigDecimal)delivered.get("legitimateQuantity")));assertEquals(0,new BigDecimal("10").compareTo(jdbc.queryForObject("SELECT SUM(s.quantity) FROM mulino_inventory_QuantitySegments s JOIN mulino_inventory_Places p ON s.placeId=p.ID AND s.organizationId=p.organizationId WHERE s.retiredAt IS NULL AND p.kind='TRANSIT'",BigDecimal.class)));assertEquals(0,new BigDecimal("10").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantityMovements WHERE kind='DELIVERY'",BigDecimal.class)));}
 // Two real transactions hold the common physical fence before the second command starts.
 // The barrier fixes the serial order; it does not rely on timing or thread sleeps.
 Map<String,Object> race(Map<String,Object> first,Map<String,Object> second)throws Exception{
  var firstPid=new java.util.concurrent.atomic.AtomicInteger();var firstLocked=new java.util.concurrent.CountDownLatch(1);var secondStarted=new java.util.concurrent.CountDownLatch(1);var release=new java.util.concurrent.CountDownLatch(1);var security=SecurityContextHolder.getContext().getAuthentication();var pool=java.util.concurrent.Executors.newFixedThreadPool(2);
  try{var one=pool.submit(()->{SecurityContextHolder.getContext().setAuthentication(security);return tx(()->{inventory.fence(c(),stock.fences(inventory.current(c(),"QuantitySegments",segment)));firstPid.set(jdbc.queryForObject("SELECT pg_backend_pid()",Integer.class));firstLocked.countDown();await(release);return apply(first);});});assertTrue(firstLocked.await(10,java.util.concurrent.TimeUnit.SECONDS));var two=pool.submit(()->{SecurityContextHolder.getContext().setAuthentication(security);secondStarted.countDown();return apply(second);});assertTrue(secondStarted.await(10,java.util.concurrent.TimeUnit.SECONDS));long deadline=System.nanoTime()+java.util.concurrent.TimeUnit.SECONDS.toNanos(5);boolean waiting=false;while(System.nanoTime()<deadline){waiting=jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE ? = ANY(pg_blocking_pids(pid)))",Boolean.class,firstPid.get());if(waiting)break;Thread.onSpinWait();}assertTrue(waiting,"Second PostgreSQL transaction must be blocked by first before barrier release");release.countDown();assertEquals("APPLIED",one.get(20,java.util.concurrent.TimeUnit.SECONDS).get("outcome"));return two.get(20,java.util.concurrent.TimeUnit.SECONDS);}finally{release.countDown();pool.shutdownNow();}
 }
 void await(java.util.concurrent.CountDownLatch latch){try{if(!latch.await(10,java.util.concurrent.TimeUnit.SECONDS))throw new IllegalStateException("Barrier timeout");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}}
 @Test void v2SplitFirstRejectsStaleParentReserveAndPreservesExisting40Once()throws Exception{allow("60");String old=reserve("0","40");var split=envelope("splitQuantity",map("segmentId",segment,"quantities",List.of("30","30"),"unit","EA","occurredAt",now.toString(),"evidenceRef","synthetic split"),0);var reserve=envelope("reserveQuantity",map("segmentId",segment,"salesLineId",salesLine,"startQuantity","40","quantity","20","unit","EA"),0);assertEquals("REJECTED",race(split,reserve).get("outcome"));assertEquals(0,new BigDecimal("40").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_SegmentAllocations WHERE state='EXECUTABLE'",BigDecimal.class)));assertEquals("REPLACED",jdbc.queryForObject("SELECT state FROM mulino_inventory_SegmentAllocations WHERE ID=?",String.class,old));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_SegmentAllocations WHERE segmentId=? AND state='EXECUTABLE'",Integer.class,segment));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_GenealogyEdges WHERE sourceId=?",Integer.class,segment));}
 @Test void v2ReserveFirstThenSplitPreserves60OneTime()throws Exception{allow("60");String old=reserve("0","40");var split=envelope("splitQuantity",map("segmentId",segment,"quantities",List.of("30","30"),"unit","EA","occurredAt",now.toString(),"evidenceRef","synthetic split"),0);var reserve=envelope("reserveQuantity",map("segmentId",segment,"salesLineId",salesLine,"startQuantity","40","quantity","20","unit","EA"),0);assertEquals("APPLIED",race(reserve,split).get("outcome"));assertEquals(0,new BigDecimal("60").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_SegmentAllocations WHERE state='EXECUTABLE'",BigDecimal.class)));assertEquals(0,new BigDecimal("40").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_SegmentAllocations WHERE predecessorId=?",BigDecimal.class,old)));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_SegmentAllocations WHERE segmentId=? AND state='EXECUTABLE'",Integer.class,segment));}

 Map<String,Object> preparedHold(String quantity){var slots=permission("placeHold","QC",quantity);slots.put("action","ALL");String doc=evidence(slots,"HOLD");slots.remove("operation");slots.remove("sourceDecisionId");slots.remove("sourceVersion");slots.putAll(map("evidenceId",doc,"reason","Independent current hold","nextCheckAt",now.plusSeconds(60).toString()));return envelope("placeHold",slots,0);}
 @Test void v3HoldCommitsAfterEligibleQueryBeforeDispatchPhysicalEffectZero()throws Exception{allow("100");allowDispatch();String allocation=reserve("0","20");run("pickQuantity",map("allocationId",allocation),0);var hold=preparedHold("100");assertEquals(0,new BigDecimal("100").compareTo(assess().eligibleQuantity()));var dispatch=envelope("dispatchQuantity",map("allocationId",allocation,"transitPlaceId",transit,"occurredAt",now.toString(),"evidenceRef","synthetic dispatch"),1);assertEquals("REJECTED",race(hold,dispatch).get("outcome"));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_Dispatches",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_QuantityMovements",Integer.class));assertEquals("SUSPENDED",jdbc.queryForObject("SELECT state FROM mulino_inventory_SegmentAllocations WHERE ID=?",String.class,allocation));}
 @Test void v3DispatchFirstKeepsHistoryAndNewHoldResponsibilityAndOldReleaseCannotClearIt()throws Exception{allow("100");allowDispatch();String allocation=reserve("0","20");run("pickQuantity",map("allocationId",allocation),0);var hold=preparedHold("100");hold.put("expectedRevision",1);var dispatch=envelope("dispatchQuantity",map("allocationId",allocation,"transitPlaceId",transit,"occurredAt",now.toString(),"evidenceRef","synthetic dispatch"),1);assertEquals("APPLIED",race(dispatch,hold).get("outcome"));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_Dispatches",Integer.class));assertEquals("CONSUMED",jdbc.queryForObject("SELECT state FROM mulino_inventory_SegmentAllocations WHERE ID=?",String.class,allocation));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_work_read_ObligationReferences WHERE kind='QUALITY_REVIEW' AND ownerId=?",Integer.class,actor));String restriction=jdbc.queryForObject("SELECT ID FROM mulino_inventory_Restrictions",String.class);String doc=evidence(map("segmentId",segment,"operation","releaseHold","restrictionId",restriction),"OLD_RELEASE");run("releaseHold",map("restrictionId",restriction,"evidenceId",doc,"reason","Referenced old hold resolved"),0);var newer=preparedHold("100");newer.put("expectedRevision",1);assertEquals("APPLIED",apply(newer).get("outcome"));assertEquals("REJECTED",apply(envelope("releaseHold",map("restrictionId",restriction,"evidenceId",doc,"reason","Late old release"),0)).get("outcome"));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_Restrictions WHERE state='ACTIVE'",Integer.class));String dispatchId=jdbc.queryForObject("SELECT ID FROM mulino_inventory_Dispatches",String.class);var actual=tx(()->physical.observeDelivery(c(),dispatchId,id(),BigDecimal.ZERO,new BigDecimal("20"),now,id()));assertEquals(BigDecimal.ZERO,actual.get("legitimateQuantity"));assertEquals(0,new BigDecimal("20").compareTo((BigDecimal)actual.get("quantity")));}

 @Test void uncertainMergeNeverDropsAllocationResponsibilityOrInventsExecutableSubset(){allow("100");reserve("0","40");String uncertain=id();record("mulino_inventory_QuantitySegments",uncertain,map("itemId",item,"lotId",lot,"identificationStatus","CONFIRMED","quantity",new BigDecimal("20"),"unit","EA","placeId",place,"controlScope","quality","validFrom",Timestamp.from(now.minusSeconds(10)),"mixtureStatus","UNCERTAIN_MIXTURE","ownerId",actor,"custodianId",actor));String merged=tx(()->stock.merge(c(),List.of(segment,uncertain),now,"synthetic uncertain merge",id()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_SegmentAllocations WHERE state='EXECUTABLE'",Integer.class));assertEquals(0,new BigDecimal("40").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_SegmentAllocations WHERE state='SUSPENDED'",BigDecimal.class)));assertEquals("UNCERTAIN_MIXTURE",jdbc.queryForObject("SELECT mixtureStatus FROM mulino_inventory_QuantitySegments WHERE ID=?",String.class,merged));assertEquals(BigDecimal.ZERO,runtime.requestContext().run(ctx->{return eligibility.assess(c(),inventory.current(c(),"QuantitySegments",merged),"SELL",customer);}).eligibleQuantity());var facts=runtime.requestContext().run(ctx->{return eligibility.read(c(),"getInventory",item,Map.of("placeId",place),List.of(inventory.current(c(),"QuantitySegments",merged)));});assertEquals("40",facts.values().get("allocationShortageQuantity"));assertEquals("40",facts.values().get("reservationResponsibilityQuantity"));}
}
