package com.mulino.quality;
import com.mulino.application.core.*;
import com.mulino.application.quality.*;
import com.mulino.application.runtime.InventoryValiditySweeper;
import com.mulino.domain.inventory.InventoryRepository;
import com.mulino.domain.definitions.*;
import com.sap.cds.services.runtime.CdsRuntime;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.nio.file.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.test.context.*;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@SpringBootTest
@ActiveProfiles("local")
class QualityPostgresTest {
 static final PostgreSQLContainer PG=new PostgreSQLContainer("postgres@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280");
 static final Path BLOBS;static{try{BLOBS=Files.createTempDirectory("mulino-s3-quality-",java.nio.file.attribute.PosixFilePermissions.asFileAttribute(java.nio.file.attribute.PosixFilePermissions.fromString("rwx------")));PG.start();}catch(Exception e){throw new IllegalStateException(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",PG::getJdbcUrl);r.add("spring.datasource.username",PG::getUsername);r.add("spring.datasource.password",PG::getPassword);r.add("mulino.evidence.blob-root",BLOBS::toString);r.add("JWT_PUBLIC_KEY",()->System.getenv("JWT_PUBLIC_KEY"));r.add("JWT_ISSUER",()->"https://fixture.invalid");r.add("JWT_AUDIENCE",()->"mulino-acceptance");}
 @Autowired JdbcTemplate jdbc;@Autowired ApplicationCommands gateway;@Autowired QualityEligibility eligibility;@Autowired InventoryRepository inventory;@Autowired CdsRuntime runtime;@Autowired InventoryValiditySweeper sweeper;@Autowired org.springframework.transaction.PlatformTransactionManager transactions;
 @MockitoBean org.springframework.security.oauth2.jwt.JwtDecoder decoder;
 @MockitoBean ExecutionClock clock;
 final ObjectMapper json=new ObjectMapper();String org,actor,item,lot,place,segment,work,grant,definition,profile,regPolicy;Instant now=Instant.parse("2026-10-08T00:00:00Z");
 String id(){return UUID.randomUUID().toString();}Map<String,Object>map(Object...v){var m=new LinkedHashMap<String,Object>();for(int i=0;i<v.length;i+=2)m.put(v[i].toString(),v[i+1]);return m;}
 void insert(String table,Map<String,Object>r){jdbc.update("INSERT INTO "+table+"("+String.join(",",r.keySet())+") VALUES("+String.join(",",Collections.nCopies(r.size(),"?"))+")",r.values().toArray());}
 Map<String,Object>base(String id){return map("organizationId",org,"ID",id,"revision",0,"createdAt",Timestamp.from(now.minusSeconds(10)),"recordedAt",Timestamp.from(now.minusSeconds(10)));}
 void record(String table,String id,Map<String,Object>values){var r=base(id);r.putAll(values);insert(table,r);}
 @BeforeEach void seed(org.junit.jupiter.api.TestInfo info)throws Exception{
  when(clock.instant()).thenAnswer(x->now);jdbc.execute("TRUNCATE mulino_identity_Organizations CASCADE");org=id();actor=id();item=id();lot=id();place=id();segment=id();work=id();grant=id();definition=id();profile=id();regPolicy=id();
  insert("mulino_identity_Organizations",map("ID",org,"externalAlias",org));insert("mulino_identity_Actors",map("organizationId",org,"ID",actor,"kind","HUMAN","stableRequestOwner",actor));insert("mulino_identity_AuthorityFences",map("organizationId",org,"actorId",actor,"revision",1));insert("mulino_identity_ExternalIdentities",map("organizationId",org,"ID",id(),"actorId",actor,"issuer","https://fixture.invalid","subject","quality","organizationAlias",org));
  insert("mulino_identity_Memberships",map("organizationId",org,"ID",id(),"actorId",actor,"validFrom",Timestamp.from(now.minusSeconds(1000)),"validUntil",Timestamp.from(now.plusSeconds(10000))));insert("mulino_identity_Grants",map("organizationId",org,"ID",grant,"actorId",actor,"delegatorId",actor,"validFrom",Timestamp.from(now.minusSeconds(1000)),"validUntil",Timestamp.from(now.plusSeconds(10000))));insert("mulino_identity_GrantScopes",map("organizationId",org,"grantId",grant,"scopeKind","ORGANIZATION","scopeId",org));
  var caps=List.of("placeHold","releaseHold","recordDispositionBasis","revokeDispositionBasis","attachEvidence","recordActivity","matchSourceIdentity","linkCanonicalOccurrence","getEvidence","getWork","decideQuality","confirmCustomerConditions","confirmCommercialDisposition","decideRecallRestriction","reserveQuantity","prepareRegulatoryProcedure","recordSubmission","recordRegulatoryDecision");for(String cap:caps){insert("mulino_identity_CapabilityAssignments",map("organizationId",org,"ID",id(),"actorId",actor,"capabilityId",cap,"scopeKind","ORGANIZATION","scopeId",org,"validFrom",Timestamp.from(now.minusSeconds(1000)),"validUntil",Timestamp.from(now.plusSeconds(10000))));insert("mulino_identity_GrantActions",map("organizationId",org,"grantId",grant,"capabilityId",cap));}
  String product=id(),spec=id(),pack=id(),maker=id();record("mulino_inventory_Products",product,map("name","biscuit"));for(var type:List.of("SpecificationVersions","PackagingVersions"))record("mulino_inventory_"+type,type.startsWith("Spec")?spec:pack,map("productId",product,"version","1","contentHash","a".repeat(64)));record("mulino_inventory_TradeItems",item,map("productId",product,"name","biscuit","baseUnit","EA","decimalPlaces",0,"specificationVersionId",spec,"packagingVersionId",pack));record("mulino_inventory_Manufacturers",maker,map("name","maker"));record("mulino_inventory_ManufacturingLots",lot,map("manufacturerId",maker,"itemId",item,"originalLot","LOT","expiresAt",Timestamp.from(now.plusSeconds(100))));record("mulino_inventory_Places",place,map("name","warehouse","kind","INTERNAL_STORAGE"));record("mulino_inventory_QuantitySegments",segment,map("itemId",item,"lotId",lot,"identificationStatus","CONFIRMED","quantity",new BigDecimal(info.getTestMethod().orElseThrow().getName().startsWith("c1")?"40":"100"),"unit","EA","placeId",place,"controlScope","quality","validFrom",Timestamp.from(now.minusSeconds(10)),"mixtureStatus","IDENTIFIED","ownerId",actor,"custodianId",actor));
  var d=new Definition(org,definition,"quality-fixture-v1",null,"PUBLISHED",null,"core-v1","1.0.0",List.of(new Definition.NounType("QuantitySegment",true),new Definition.NounType("TradeItem",true),new Definition.NounType("Work",true)),List.of(),caps.stream().map(c->new Definition.Verb(c,kind(c),c,"ACTIVE",Map.of())).toList(),List.of(),List.of(),caps.stream().map(c->new Definition.Capability(c,"1.0.0","core-v1","1.0.0","1.0.0",List.of())).toList());String content=json.writeValueAsString(d);insert("mulino_definitions_DefinitionVersions",map("organizationId",org,"ID",definition,"createdAt",Timestamp.from(now.minusSeconds(10)),"version",d.version(),"state","PUBLISHED","contentHash",DefinitionRepository.sha256(content),"content",content,"evaluatorVersion","core-v1","schemaVersion","1.0.0"));
  record("mulino_work_read_Works",work,map("effectiveAt",Timestamp.from(now.minusSeconds(10)),"itemId",item,"lotId",lot,"definitionVersionId",definition,"kind","QUALITY","status","ACTIVE","ownerId",actor,"supervisorId",actor));
  record("mulino_evidence_SourceProfiles",profile,map("revision",1,"recordedBy",actor,"namespace","quality-source","policyVersion","fixture-v1","intakeOwnerId",actor,"supervisorId",actor,"nextAction","Review source","nextCheckAt",Timestamp.from(now.plusSeconds(60))));
  var rules=new TreeMap<String,Object>();for(String cap:caps){String effect=List.of("attachEvidence","recordActivity").contains(cap)?"RECORD":List.of("matchSourceIdentity","linkCanonicalOccurrence").contains(cap)?"RECONCILIATION":cap.startsWith("recordRegulatory")||cap.equals("recordSubmission")||cap.equals("prepareRegulatoryProcedure")?"REGULATORY_RECORD":cap.equals("reserveQuantity")?"RESERVE":"QUALITY_CONTROL";rules.put(cap,map("effectClass",effect,"approvalAction",null,"categoryCapabilities",map("QC","decideQuality","CUSTOMER","confirmCustomerConditions","COMMERCIAL","confirmCommercialDisposition","RECALL","decideRecallRestriction")));}
  policy("COMMAND",json.writeValueAsString(map("rules",rules)));policy("ELIGIBILITY","{\"actions\":{\"SELL\":{\"requiredCategories\":[\"QC\",\"CUSTOMER\",\"COMMERCIAL\"]}}}");
  record("mulino_trade_regulatory_Policies",regPolicy,map("recordedBy",actor,"version","fixture-v1","authority","FICTIONAL_TEST_AUTHORITY","sourceNamespace","quality-source","action","SELL","validFrom",Timestamp.from(now.minusSeconds(10)),"validUntil",Timestamp.from(now.plusSeconds(1000)),"fictional",true,"status","ACTIVE","requiresLabel",false));
  SecurityContextHolder.getContext().setAuthentication(new JwtAuthenticationToken(Jwt.withTokenValue("local-test").header("alg","RS256").issuer("https://fixture.invalid").subject("quality").claim("organizationId",org).build(),List.of()));
 }
 void policy(String kind,String content){String id=id();insert("mulino_governance_PolicyVersions",map("organizationId",org,"ID",id,"revision",1,"createdAt",Timestamp.from(now.minusSeconds(10)),"kind",kind,"version","fixture-v1","content",content,"contentHash",DefinitionRepository.sha256(content),"effectiveFrom",Timestamp.from(now.minusSeconds(10))));insert("mulino_governance_ActivePolicies",map("organizationId",org,"kind",kind,"policyId",id,"revision",1));}
 String kind(String cap){return Set.of("recordDispositionBasis","recordActivity","attachEvidence","recordSubmission","recordRegulatoryDecision").contains(cap)?"RECORD":"COMMAND";}
 Map<String,Object>run(String cap,Map<String,Object>slots,Integer revision){var i=map("intentKind",kind(cap),"definitionVersion","quality-fixture-v1","capabilityId",cap,"commandIdempotencyKey",id(),"subjectRefs",List.of(),"slots",slots,"provenance",map("sourceNamespace","USER"));if(revision!=null)i.put("expectedRevision",revision);var result=runtime.requestContext().run(ctx->{return gateway.execute(i);});assertEquals("APPLIED",result.get("outcome"),result.toString());return result;}
 String evidence(Map<String,Object>payload,String kind){try{String bytes=json.writeValueAsString(payload);if(Set.of("placeHold","recordDispositionBasis").contains(payload.get("operation")))kind="QUALITY_DECISION_"+payload.get("operation")+"_"+payload.get("category");String observedQuantity=payload.containsKey("quantity")&&(kind.equals("REGULATORY_DECISION")||kind.startsWith("QUALITY_DECISION_"))?payload.get("quantity").toString():Set.of("REGULATORY_SUBMISSION","LABEL_VERIFICATION").contains(kind)?null:scopeAmount();String observedUnit=observedQuantity==null?null:"EA";var doc=run("attachEvidence",map("subject",map("kind","SEGMENT","id",segment),"sourceNamespace","quality-source","sourceReference",id(),"mediaType","application/json","expectedHash",com.mulino.adapters.blob.LocalBlobStore.hash(bytes.getBytes()),"provenance","SYNTHETIC","contentBase64",Base64.getEncoder().encodeToString(bytes.getBytes())),null).get("id").toString();String eventKey=payload.containsKey("sourceDecisionId")?payload.get("sourceDecisionId").toString():id();var event=run("recordActivity",map("subject",map("kind","SEGMENT","id",segment),"kind",kind,"sourceNamespace","quality-source","externalEventId",eventKey,"sourceVersion","1","effectiveFrom",now.toString(),"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","payload",bytes,"documentId",doc,"assertion","Fixture source","quantity",observedQuantity,"unit",observedUnit),null);var review=run("matchSourceIdentity",map("claimId",event.get("claimId"),"basisDocumentId",doc,"physicalScopeId",segment,"policyVersion","fixture-v1","sourceIdentity","quality-source:"+eventKey+":1","quantity",observedQuantity,"unit",observedUnit,"effectiveFrom",now.toString(),"reason","Synthetic original scope review"),1);run("linkCanonicalOccurrence",map("reconciliationId",review.get("id")),1);return doc;}catch(Exception e){throw new IllegalStateException(e);}}
 String scopeAmount(){return jdbc.queryForObject("SELECT quantity FROM mulino_inventory_QuantitySegments WHERE id=?",BigDecimal.class,segment).stripTrailingZeros().toPlainString();}
 String occurrence(String doc){return jdbc.queryForObject("SELECT canonicalOccurrenceId FROM mulino_evidence_Verifications WHERE basisDocumentId=?",String.class,doc);}
 Map<String,Object>effects(Map<String,Object>r){return (Map<String,Object>)r.get("effects");}
 Map<String,Object>permission(String operation,String category,String q){return map("segmentId",segment,"sourceDecisionId",id(),"sourceVersion","1","workId",work,"operation",operation,"action","SELL","category",category,"startQuantity","0","quantity",q,"unit","EA","validFrom",now.toString(),"validUntil",now.plusSeconds(1000).toString());}
 String basis(String category,String q){var s=permission("recordDispositionBasis",category,q);String doc=evidence(s,"QUALITY_"+category);s.remove("operation");s.remove("sourceDecisionId");s.remove("sourceVersion");s.putAll(map("evidenceId",doc,"reason","Current exact scoped decision","workId",work,"nextCheckAt",now.plusSeconds(60).toString()));return effects(run("recordDispositionBasis",s,0)).get("dispositionBasisId").toString();}
 QualityEligibility.Result assess(){return runtime.requestContext().run(ctx->{return eligibility.assess(new DomainContext(org,actor,actor,now,now),inventory.current(new DomainContext(org,actor,actor,now,now),"QuantitySegments",segment),"SELL",null);});}
 void regulatory(String q){String preparation=evidence(map("purpose","fixture procedure"),"REG_PREPARATION");var prep=run("prepareRegulatoryProcedure",map("itemId",item,"lotId",lot,"physicalScopeId",segment,"workId",work,"policyId",regPolicy,"documentVersionId",preparation),null);String proc=effects(prep).get("procedureId").toString();var payload=map("procedureId",proc,"procedureVersionId",effects(prep).get("procedureVersionId"),"occurredAt",now.toString(),"itemId",item,"lotId",lot,"physicalScopeId",segment,"authority","FICTIONAL_TEST_AUTHORITY","policyVersion","fixture-v1");String submit=evidence(payload,"REGULATORY_SUBMISSION");var submitted=run("recordSubmission",map("procedureId",proc,"occurredAt",now.toString(),"occurrenceId",occurrence(submit)),1);var decision=map("procedureId",proc,"procedureVersionId",effects(submitted).get("procedureVersionId"),"decision","ALLOWED","action","SELL","startQuantity","0","quantity",q,"unit","EA","validFrom",now.toString(),"validUntil",now.plusSeconds(1000).toString(),"itemId",item,"lotId",lot,"physicalScopeId",segment,"authority","FICTIONAL_TEST_AUTHORITY","policyVersion","fixture-v1");String doc=evidence(decision,"REGULATORY_DECISION");for(String key:List.of("procedureVersionId","itemId","lotId","physicalScopeId","authority","policyVersion"))decision.remove(key);decision.put("occurrenceId",occurrence(doc));run("recordRegulatoryDecision",decision,2);}
 @Test void c1Consignment40AndCustomerCustody60OnlyCommercial40IsEligible(){
  String first=segment;regulatory("40");basis("QC","40");basis("CUSTOMER","40");String commercial=basis("COMMERCIAL","40");
  segment=id();record("mulino_inventory_QuantitySegments",segment,map("itemId",item,"lotId",lot,"identificationStatus","CONFIRMED","quantity",new BigDecimal("60"),"unit","EA","placeId",place,"controlScope","customer-custody","validFrom",Timestamp.from(now.minusSeconds(10)),"mixtureStatus","IDENTIFIED","ownerId",actor,"custodianId",actor));regulatory("60");basis("QC","60");basis("CUSTOMER","60");
  var c=new DomainContext(org,actor,actor,now,now);var facts=runtime.requestContext().run(ctx->{return eligibility.read(c,"getInventory",item,Map.of(),inventory.currentRows(c,"QuantitySegments"));});assertEquals("40",facts.values().get("eligibleQuantity"));assertEquals("40",facts.values().get("unreservedEligibleQuantity"));assertEquals(new BigDecimal("100.000000000000"),jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantitySegments",BigDecimal.class));
  segment=first;String doc=evidence(map("segmentId",segment,"operation","revokeDispositionBasis","dispositionBasisId",commercial),"COMMERCIAL_REVOKED");run("revokeDispositionBasis",map("dispositionBasisId",commercial,"evidenceId",doc,"reason","Consignment permission withdrawn"),0);assertEquals(BigDecimal.ZERO,assess().eligibleQuantity());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_work_read_ObligationReferences WHERE kind='QUALITY_REVIEW' AND status='OPEN' AND ownerId=?",Integer.class,actor));
 }
 @Test void qcDecisionRoleCannotRecordCommercialDisposition(){regulatory("100");jdbc.update("UPDATE mulino_identity_CapabilityAssignments SET revokedAt=? WHERE capabilityId='confirmCommercialDisposition'",Timestamp.from(now));var slots=permission("recordDispositionBasis","COMMERCIAL","100");String doc=evidence(slots,"COMMERCIAL_DENIED");slots.remove("operation");slots.remove("sourceDecisionId");slots.remove("sourceVersion");slots.putAll(map("evidenceId",doc,"reason","Missing commercial confirmer","workId",work,"nextCheckAt",now.plusSeconds(60).toString()));var input=map("intentKind","RECORD","definitionVersion","quality-fixture-v1","capabilityId","recordDispositionBasis","commandIdempotencyKey",id(),"subjectRefs",List.of(),"slots",slots,"expectedRevision",0,"provenance",map("sourceNamespace","USER"));var result=runtime.requestContext().run(ctx->{return gateway.execute(input);});assertEquals("REJECTED",result.get("outcome"));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_DispositionBases",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_quality_Decisions",Integer.class));}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void regulatory30IntersectQc100AndCommercialCustomer100Is30(){regulatory("30");basis("QC","100");basis("CUSTOMER","100");basis("COMMERCIAL","100");assertEquals(0,new BigDecimal("30").compareTo(assess().eligibleQuantity()));assertEquals("PARTIAL",assess().state());}
 @Test void ownerCustodianAndQcAloneDoNotPermitSale(){regulatory("100");basis("QC","100");assertEquals(BigDecimal.ZERO,assess().eligibleQuantity());assertTrue(assess().unknowns().contains("COMMERCIAL_AUTHORITY_UNCONFIRMED"));}
 @Test void overlappingHoldsReleaseOnlyReferencedRestriction(){regulatory("100");basis("QC","100");basis("CUSTOMER","100");basis("COMMERCIAL","100");var ids=new ArrayList<String>();for(String category:List.of("QC","RECALL")){var s=permission("placeHold",category,category.equals("QC")?"20":"100");String doc=evidence(s,"HOLD_"+category);s.remove("operation");s.remove("sourceDecisionId");s.remove("sourceVersion");s.putAll(map("evidenceId",doc,"reason","Independent hold","workId",work,"nextCheckAt",now.plusSeconds(60).toString()));ids.add(effects(run("placeHold",s,0)).get("restrictionId").toString());}String doc=evidence(map("segmentId",segment,"operation","releaseHold","restrictionId",ids.getFirst()),"RELEASE_QC");run("releaseHold",map("restrictionId",ids.getFirst(),"evidenceId",doc,"reason","QC resolved"),0);assertEquals("RELEASED",jdbc.queryForObject("SELECT state FROM mulino_inventory_Restrictions WHERE id=?",String.class,ids.getFirst()));assertEquals("ACTIVE",jdbc.queryForObject("SELECT state FROM mulino_inventory_Restrictions WHERE id=?",String.class,ids.getLast()));assertEquals(BigDecimal.ZERO,assess().eligibleQuantity());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_QuantityMovements",Integer.class));}
 @Test void noEventExpirySuspends20AndKeepsOwnerNextCheckExactlyOnce(){regulatory("100");basis("QC","100");basis("CUSTOMER","100");String commercial=basis("COMMERCIAL","100");String command=jdbc.queryForObject("SELECT commandId FROM mulino_inventory_DispositionBases WHERE id=?",String.class,commercial);record("mulino_inventory_SegmentAllocations",id(),map("rootId",id(),"segmentId",segment,"orderLineId",id(),"startQuantity",BigDecimal.ZERO,"quantity",new BigDecimal("20"),"unit","EA","state","EXECUTABLE","commandId",command,"action","SELL","workId",work,"authorizationActorId",actor,"nextValidityBoundary",Timestamp.from(now.plusSeconds(100))));assertEquals(0,new BigDecimal("100").compareTo(assess().eligibleQuantity()));now=now.plusSeconds(101);assertEquals(BigDecimal.ZERO,assess().eligibleQuantity());String allocationId=jdbc.queryForObject("SELECT ID FROM mulino_inventory_SegmentAllocations",String.class);var denied=assertThrows(DomainError.class,()->runtime.requestContext().run(ctx->{return new org.springframework.transaction.support.TransactionTemplate(transactions).execute(status->eligibility.requireExecutableAllocation(new DomainContext(org,actor,actor,now,now),allocationId,"reserveQuantity","SELL",null));}));assertEquals("SCOPE_INELIGIBLE",denied.code());assertEquals(1,runtime.requestContext().run(ctx->{return sweeper.sweep();}).intValue());assertEquals(0,runtime.requestContext().run(ctx->{return sweeper.sweep();}).intValue());assertEquals("SUSPENDED",jdbc.queryForObject("SELECT state FROM mulino_inventory_SegmentAllocations",String.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_work_read_ObligationReferences WHERE kind='INVENTORY_VALIDITY' AND status='OPEN' AND ownerId=? AND nextCheckAt IS NOT NULL AND nextAction IS NOT NULL",Integer.class,actor));assertEquals(new BigDecimal("20.000000000000"),jdbc.queryForObject("SELECT quantity FROM mulino_work_read_ObligationReferences WHERE kind='INVENTORY_VALIDITY'",BigDecimal.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mulino_inventory_QuantityMovements",Integer.class));}
}
