package com.mulino.application.trade.shipment;

import com.mulino.application.core.*;
import com.mulino.application.inventory.InventoryCommands;
import com.mulino.application.runtime.IntakeDutyPort;
import com.mulino.application.trade.purchase.PurchaseLinePort;
import com.mulino.domain.trade.shipment.ShipmentRepository;
import com.mulino.domain.inventory.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.inventory.InventoryCommands.*;

@Component
public class ShipmentCommands implements CommandHandler {
 private final ShipmentRepository r;private final InventoryRepository inventory;private final PurchaseLinePort purchase;private final ShipmentEvidence evidence;private final IntakeDutyPort duties;
 public ShipmentCommands(ShipmentRepository r,InventoryRepository inventory,PurchaseLinePort purchase,ShipmentEvidence evidence,IntakeDutyPort duties){this.r=r;this.inventory=inventory;this.purchase=purchase;this.evidence=evidence;this.duties=duties;}
 public Set<String> capabilities(){return Set.of("createShipment","recordLegEvent","recordHandover");}
 public Set<String> intentKinds(){return Set.of("COMMAND","RECORD");}
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object> intent,CommandPreparation preparation){if("createShipment".equals(intent.get("capabilityId")))return List.of();return List.of(SubjectBinding.required("Shipment",Set.of(uuid(slots(intent),"shipmentId"))));}
 public CommandPreparation prepare(DomainContext c,Map<String,Object> intent){
  String cap=text(intent,"capabilityId",100);var s=slots(intent);var scopes=new LinkedHashMap<String,List<String>>();var fences=new TreeSet<String>();
  if(cap.equals("createShipment")){
   if(!"COMMAND".equals(intent.get("intentKind"))||!Set.of("originId","destinationId","carrierRef","workId","cargo","legs").containsAll(s.keySet()))throw DomainError.invalid("Shipment plan slots required");
   String origin=uuid(s,"originId"),destination=uuid(s,"destinationId");inventory.current(c,"Places",origin);inventory.current(c,"Places",destination);text(s,"carrierRef",240);
   var cargos=maps(s,"cargo");var items=new TreeSet<String>();var lines=new TreeSet<String>();var aggregate=new HashMap<String,BigDecimal>();
   for(var cargo:cargos){if(!Set.of("itemId","quantity","unit","allocations").equals(cargo.keySet()))throw DomainError.invalid("Exact cargo slots required");String item=uuid(cargo,"itemId"),unit=text(cargo,"unit",40);var i=inventory.current(c,"TradeItems",item);if(!unit.equals(i.get("baseUnit")))throw DomainError.invalid("Cargo base unit required");BigDecimal quantity=InventoryQuantity.parse(cargo.get("quantity"),((Number)i.get("decimalPlaces")).intValue()),total=BigDecimal.ZERO;items.add(item);
    for(var allocation:maps(cargo,"allocations")){if(!Set.of("poLineId","quantity").equals(allocation.keySet()))throw DomainError.invalid("Exact allocation slots required");String line=uuid(allocation,"poLineId");var po=purchase.requireLine(c,line);if(!item.equals(po.get("itemId"))||!unit.equals(po.get("unit"))||!Set.of("DISPATCH_PENDING","SUPPLIER_ACCEPTED").contains(po.get("status")))throw DomainError.invalid("Accepted PO line matching cargo required");BigDecimal q=InventoryQuantity.parse(allocation.get("quantity"),((Number)i.get("decimalPlaces")).intValue());total=total.add(q);aggregate.merge(line,q,BigDecimal::add);lines.add(line);fences.add("purchase/line/"+line);}
    if(total.compareTo(quantity)!=0)throw DomainError.invalid("Cargo must equal PO allocations");
   }
   for(var allocation:aggregate.entrySet()){var line=purchase.requireLine(c,allocation.getKey());var assigned=r.rows(c,"CargoAllocations").stream().filter(a->allocation.getKey().equals(a.get("poLineId"))).map(a->(BigDecimal)a.get("quantity")).reduce(BigDecimal.ZERO,BigDecimal::add);if(assigned.add(allocation.getValue()).compareTo((BigDecimal)line.get("quantity"))>0)throw DomainError.invalid("Shipment allocations exceed accepted PO quantity");}
   var legs=maps(s,"legs");String previous=origin;Instant previousArrival=null;var places=new TreeSet<String>(List.of(origin,destination));
   for(var leg:legs){if(!Set.of("originId","destinationId","carrierRef","plannedDepartureAt","plannedArrivalAt").containsAll(leg.keySet()))throw DomainError.invalid("Unsupported leg slots");String from=uuid(leg,"originId"),to=uuid(leg,"destinationId");inventory.current(c,"Places",from);inventory.current(c,"Places",to);if(!previous.equals(from)||from.equals(to))throw DomainError.invalid("Continuous planned route required");text(leg,"carrierRef",240);Instant departure=planned(leg,"plannedDepartureAt"),arrival=planned(leg,"plannedArrivalAt");if(departure!=null&&arrival!=null&&arrival.isBefore(departure)||previousArrival!=null&&departure!=null&&departure.isBefore(previousArrival))throw DomainError.invalid("Chronological planned route required");previous=to;previousArrival=arrival;places.add(from);places.add(to);}
   if(!previous.equals(destination))throw DomainError.invalid("Route must end at planned destination");
   scopes.put("ITEM",List.copyOf(items));scopes.put("TARGET",List.copyOf(lines));scopes.put("PLACE",List.copyOf(places));if(s.containsKey("workId"))scopes.put("WORK",List.of(uuid(s,"workId")));fences.add("shipment/create");return CommandPreparation.ordinary(scopes,List.copyOf(fences),"SHIPMENT_PLAN",null,null);
  }
  if(!Set.of("recordLegEvent","recordHandover").contains(cap)||!"RECORD".equals(intent.get("intentKind")))throw DomainError.invalid("Shipment observation RECORD required");
  var allowed=new HashSet<>(Set.of("shipmentId","cargoId","legId","placeId","physicalScopeId","occurrenceId","quantity","unit","occurredAt"));allowed.addAll(cap.equals("recordHandover")?Set.of("fromCustodianId","toCustodianId"):Set.of("kind"));if(cap.equals("recordLegEvent")&&s.containsKey("lineAllocations"))allowed.add("lineAllocations");if(!allowed.equals(s.keySet()))throw DomainError.invalid("Exact observed shipment slots required");
  String shipment=uuid(s,"shipmentId"),cargoId=uuid(s,"cargoId"),legId=uuid(s,"legId"),place=uuid(s,"placeId"),scope=uuid(s,"physicalScopeId"),occurrence=uuid(s,"occurrenceId");var sh=r.currentShipment(c,shipment);var cargo=r.requireCargo(c,cargoId);var leg=r.require(c,"ShipmentLegs",legId);if(!shipment.equals(cargo.get("shipmentId"))||!shipment.equals(leg.get("shipmentId")))throw DomainError.invalid("Cargo and leg must belong to shipment");inventory.current(c,"Places",place);String item=cargo.get("itemId").toString(),unit=text(s,"unit",40);var i=inventory.current(c,"TradeItems",item);BigDecimal q=InventoryQuantity.parse(s.get("quantity"),((Number)i.get("decimalPlaces")).intValue());if(!unit.equals(cargo.get("unit"))||q.compareTo((BigDecimal)cargo.get("plannedQuantity"))>0)throw DomainError.invalid("Cargo observation quantity mismatch");Instant occurred=time(c,s);String kind=cap.equals("recordHandover")?"CUSTODY_HANDOVER":"SHIPMENT_"+text(s,"kind",40);
  if(cap.equals("recordLegEvent")){if(!Set.of("DEPARTURE","ARRIVAL","IN_TRANSIT","DELAY","TEMPERATURE_ANOMALY").contains(s.get("kind")))throw DomainError.invalid("Unsupported leg fact kind");if("DEPARTURE".equals(s.get("kind"))&&!place.equals(leg.get("originId"))||"ARRIVAL".equals(s.get("kind"))&&!place.equals(leg.get("destinationId")))throw DomainError.invalid("Actual endpoint does not match this leg");}
  else {if(uuid(s,"fromCustodianId").equals(uuid(s,"toCustodianId")))throw DomainError.invalid("Distinct custodians required");}
  evidence.require(c,occurrence,kind,item,scope,place,q,unit,occurred);evidence.requireObservationShape(c,occurrence,s);
  for(String table:List.of("LegEvents","CustodyHandovers"))if(r.rows(c,table).stream().anyMatch(e->scope.equals(e.get("physicalScopeId"))&&!cargoId.equals(e.get("cargoId"))))throw DomainError.invalid("Same physical identity cannot fulfill two cargo scopes");
  if("DEPARTURE".equals(s.get("kind"))){var allocations=departureAllocations(c,s,cargo);for(var a:allocations)fences.add("purchase/line/"+a.get("poLineId"));
   var prior=r.rows(c,"LegEvents").stream().filter(e->cargoId.equals(e.get("cargoId"))&&"DEPARTURE".equals(e.get("kind"))).toList();var physical=new HashMap<String,BigDecimal>();for(var e:prior)physical.putIfAbsent(e.get("physicalScopeId").toString(),(BigDecimal)e.get("quantity"));if(physical.containsKey(scope)&&physical.get(scope).compareTo(q)!=0)throw DomainError.invalid("Physical cargo quantity changed without reconciliation");physical.put(scope,q);if(physical.values().stream().reduce(BigDecimal.ZERO,BigDecimal::add).compareTo((BigDecimal)cargo.get("plannedQuantity"))>0)throw DomainError.invalid("Actual departures exceed allocated cargo");
  }else if(s.containsKey("lineAllocations"))throw DomainError.invalid("Only departure takes actual PO allocations");
  var canonical=evidence.canonical(c,occurrence);scopes.put("TARGET",List.of(shipment,cargoId,scope));scopes.put("ITEM",List.of(item));scopes.put("PLACE",List.of(place));scopes.put("SOURCE",List.of(canonical.get("sourceProfileId").toString()));if(sh.get("workId")!=null)scopes.put("WORK",List.of(sh.get("workId").toString()));
  fences.add("shipment/"+shipment);fences.add("shipment/canonical/"+occurrence);fences.add("shipment/physical/"+scope);
  // A later record may describe an earlier fact, but cannot claim arrival before a verified departure.
  if(cap.equals("recordLegEvent")&&"ARRIVAL".equals(s.get("kind"))&&r.rows(c,"LegEvents").stream().anyMatch(e->cargoId.equals(e.get("cargoId"))&&legId.equals(e.get("legId"))&&"DEPARTURE".equals(e.get("kind"))&&StockPrimitives.instant(e.get("occurredAt")).isAfter(occurred)))throw DomainError.invalid("Arrival predates departure");
  return CommandPreparation.ordinary(scopes,List.copyOf(fences),"SHIPMENT_OBSERVATION",shipment,((Number)sh.get("revision")).intValue());
 }
 public Map<String,Object> execute(DomainContext c,Map<String,Object> intent){prepare(c,intent);var s=slots(intent);String cap=text(intent,"capabilityId",100);
  if(cap.equals("createShipment")){var sh=ShipmentRepository.row(c);for(String key:List.of("originId","destinationId","carrierRef","workId"))if(s.containsKey(key))sh.put(key,s.get(key));sh.put("state","PLANNED");r.insert("Shipments",sh);String id=sh.get("ID").toString();var cargoIds=new ArrayList<String>();var legIds=new ArrayList<String>();
   for(var cargo:maps(s,"cargo")){var row=ShipmentRepository.row(c);row.put("shipmentId",id);row.put("itemId",cargo.get("itemId"));row.put("unit",cargo.get("unit"));row.put("plannedQuantity",new BigDecimal(cargo.get("quantity").toString()));r.insert("ShipmentCargo",row);cargoIds.add(row.get("ID").toString());for(var allocation:maps(cargo,"allocations")){var a=ShipmentRepository.row(c);a.put("shipmentId",id);a.put("cargoId",row.get("ID"));a.put("poLineId",allocation.get("poLineId"));a.put("quantity",new BigDecimal(allocation.get("quantity").toString()));a.put("unit",cargo.get("unit"));r.insert("CargoAllocations",a);}}
   int sequence=0;for(var leg:maps(s,"legs")){var row=ShipmentRepository.row(c);row.put("shipmentId",id);row.put("sequence",sequence++);for(String key:List.of("originId","destinationId","carrierRef"))row.put(key,leg.get(key));for(String key:List.of("plannedDepartureAt","plannedArrivalAt"))if(leg.containsKey(key))row.put(key,planned(leg,key));r.insert("ShipmentLegs",row);legIds.add(row.get("ID").toString());}return Map.of("outcome","APPLIED","revision",1,"detailStatus","PLANNED","effects",Map.of("shipmentId",id,"cargoIds",cargoIds,"legIds",legIds),"quantityEffects",List.of());
  }
  String entity=cap.equals("recordHandover")?"CustodyHandovers":"LegEvents",canonical=uuid(s,"occurrenceId");for(String table:List.of("LegEvents","CustodyHandovers"))for(var existing:r.rows(c,table))if(canonical.equals(existing.get("occurrenceId"))){if(!entity.equals(table)||!s.get("shipmentId").equals(existing.get("shipmentId"))||!s.get("cargoId").equals(existing.get("cargoId"))||!s.get("legId").equals(existing.get("legId")))throw DomainError.invalid("Canonical fact already bound to different shipment scope");return Map.of("outcome","APPLIED","revision",r.currentShipment(c,uuid(s,"shipmentId")).get("revision"),"detailStatus","ALREADY_RECORDED","effects",Map.of("observationId",existing.get("ID")),"quantityEffects",List.of());}
  var row=ShipmentRepository.row(c);row.putAll(s);row.remove("lineAllocations");row.put("quantity",new BigDecimal(s.get("quantity").toString()));row.put("occurredAt",time(c,s));row.put("detailStatus","VERIFIED_OBSERVATION");r.insert(entity,row);r.advance(c,uuid(s,"shipmentId"));
  if("DEPARTURE".equals(s.get("kind"))){var cargo=r.requireCargo(c,uuid(s,"cargoId"));
   boolean already=r.rows(c,"LegEvents").stream().anyMatch(e->!row.get("ID").equals(e.get("ID"))&&row.get("cargoId").equals(e.get("cargoId"))&&row.get("physicalScopeId").equals(e.get("physicalScopeId"))&&"DEPARTURE".equals(e.get("kind")));
   if(!already)for(var a:departureAllocations(c,s,cargo))purchase.recordExecutionEffect(c,a.get("poLineId").toString(),"SHIPPED",row.get("ID").toString(),new BigDecimal(a.get("quantity").toString()),cargo.get("unit").toString());
  }
  var followup=new LinkedHashMap<String,Object>();if(Set.of("DELAY","TEMPERATURE_ANOMALY").contains(s.get("kind"))){var profile=evidence.profile(c,canonical);var event=evidence.event(c,canonical);var sh=r.currentShipment(c,uuid(s,"shipmentId"));if(sh.get("workId")!=null)followup.putAll(duties.ensureEvidenceCorrectionDuty(c,sh.get("workId").toString(),event.get("ID").toString(),"EVENT",profile.get("nextAction").toString(),StockPrimitives.instant(profile.get("nextCheckAt"))));else {followup.put("intakeOwnerId",profile.get("intakeOwnerId"));followup.put("supervisorId",profile.get("supervisorId"));followup.put("nextAction",profile.get("nextAction"));followup.put("nextCheckAt",profile.get("nextCheckAt"));followup.put("eventId",event.get("ID"));followup.put("status","PENDING_INTAKE_LINK");}}
  return Map.of("outcome","APPLIED","revision",r.currentShipment(c,uuid(s,"shipmentId")).get("revision"),"detailStatus","VERIFIED_OBSERVATION","effects",Map.of("observationId",row.get("ID")),"responsibility",followup,"quantityEffects",List.of());
 }
 private List<Map<String,Object>> departureAllocations(DomainContext c,Map<String,Object>s,Map<String,Object>cargo){var planned=r.cargoAllocations(c,cargo.get("ID").toString());var result=s.containsKey("lineAllocations")?maps(s,"lineAllocations"):planned.stream().map(a->Map.of("poLineId",a.get("poLineId"),"quantity",((BigDecimal)a.get("quantity")).toPlainString())).toList();BigDecimal sum=BigDecimal.ZERO;var used=new HashSet<String>();for(var a:result){if(!Set.of("poLineId","quantity").equals(a.keySet()))throw DomainError.invalid("Exact actual line allocation required");String line=uuid(a,"poLineId");if(!used.add(line))throw DomainError.invalid("Duplicate actual PO allocation");BigDecimal q=InventoryQuantity.parse(a.get("quantity"),12);BigDecimal available=planned.stream().filter(x->line.equals(x.get("poLineId"))).map(x->(BigDecimal)x.get("quantity")).reduce(BigDecimal.ZERO,BigDecimal::add);if(q.compareTo(available)>0)throw DomainError.invalid("Actual PO allocation exceeds cargo plan");sum=sum.add(q);}if(sum.compareTo(new BigDecimal(s.get("quantity").toString()))!=0)throw DomainError.invalid("Actual departure needs exact PO allocations");return result;}
 @SuppressWarnings("unchecked") public static List<Map<String,Object>> maps(Map<String,Object>s,String key){if(!(s.get(key) instanceof List<?> list)||list.isEmpty()||list.size()>100||list.stream().anyMatch(x->!(x instanceof Map<?,?>)))throw DomainError.invalid("Nonempty typed "+key+" required");return list.stream().map(x->(Map<String,Object>)x).toList();}
 private static Instant planned(Map<String,Object>s,String key){if(!s.containsKey(key))return null;try{return Instant.parse(text(s,key,80));}catch(Exception e){throw DomainError.invalid("Planned UTC timestamp required");}}
}
