package com.mulino.application.trade.returns;
import com.mulino.application.core.*;
import com.mulino.application.trade.*;
import com.mulino.application.work.WorkAccess;
import com.mulino.application.policy.PolicyCommandGuard;
import com.mulino.domain.identity.IdentityRepository;
import com.mulino.domain.inventory.*;
import com.mulino.domain.trade.returns.ReturnRepository;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.inventory.InventoryCommands.*;
/** Returns preserve actual delivery history and never contribute to purchasing arrival. */
@Component
public class ReturnCommands implements CommandHandler,ReturnQuantityPort {
 private final ReturnRepository r;private final DeliveredCargoPort deliveries;private final InventoryRepository inventory;private final ReturnStockPrimitives stock;private final TradeEvidence evidence;private final TradeImpact impact;private final WorkAccess works;private final IdentityRepository identities;private final ReadAuthorizer auth;private final PolicyCommandGuard policy;private final TransactionalOutboxPort outbox;private final ExecutionClock clock;private final TradeObservationRemedy remedy;private final com.mulino.domain.evidence.EvidenceRepository sources;private final com.mulino.adapters.blob.LocalBlobStore blobs;
 public ReturnCommands(ReturnRepository r,DeliveredCargoPort deliveries,InventoryRepository inventory,ReturnStockPrimitives stock,TradeEvidence evidence,TradeImpact impact,WorkAccess works,IdentityRepository identities,ReadAuthorizer auth,PolicyCommandGuard policy,TransactionalOutboxPort outbox,ExecutionClock clock,TradeObservationRemedy remedy,com.mulino.domain.evidence.EvidenceRepository sources,com.mulino.adapters.blob.LocalBlobStore blobs){this.sources=sources;this.blobs=blobs;this.r=r;this.deliveries=deliveries;this.inventory=inventory;this.stock=stock;this.evidence=evidence;this.impact=impact;this.works=works;this.identities=identities;this.auth=auth;this.policy=policy;this.outbox=outbox;this.clock=clock;this.remedy=remedy;}
 public Set<String> capabilities(){return Set.of("authorizeReturn","receiveReturn","decideReturnDisposition");}
 public Set<String> intentKinds(){return Set.of("COMMAND","RECORD");}
 private Map<String,Object> target(DomainContext c,Map<String,Object>i){var s=slots(i);return switch(i.get("capabilityId").toString()){case "authorizeReturn"->deliveries.requireDelivery(c,uuid(s,"deliveryId"));case "receiveReturn"->s.containsKey("returnId")?r.require(c,"Observations",uuid(s,"returnId")):r.require(c,"Authorizations",uuid(s,"authorizationId"));default->r.require(c,"Receipts",uuid(s,"returnId"));};}
 public static Map<String,List<String>> scopes(Map<String,Object>t){return Map.of("TARGET",List.of(t.get("ID").toString()),"ITEM",List.of(t.get("itemId").toString()),"WORK",List.of(t.get("workId").toString()),"PLACE",List.of(Objects.toString(t.get("destinationId"),Objects.toString(t.get("placeId"),""))));}
 public CommandPreparation prepare(DomainContext c,Map<String,Object>i){var s=slots(i);String cap=text(i,"capabilityId",80);var t=target(c,i);boolean authorize=cap.equals("authorizeReturn"),receive=cap.equals("receiveReturn");Set<String> allowed=authorize?Set.of("deliveryId","startQuantity","quantity","unit","destinationId","validUntil","reason"):receive?(s.containsKey("returnId")?Set.of("returnId","nextCheckAt","canonicalOccurrenceId","receivingCustodianId","authorizationId"):Set.of("authorizationId","eventId","occurredAt","nextCheckAt","startQuantity","quantity","unit")):Set.of("returnId","decision","evidenceId","reason","nextCheckAt");if(!allowed.containsAll(s.keySet())||!Objects.equals(i.get("intentKind"),receive?"RECORD":"COMMAND"))throw DomainError.invalid("Return slots or intent kind mismatch");
  var sc=new LinkedHashMap<String,List<String>>(scopes(t));String destination=authorize?uuid(s,"destinationId"):sc.get("PLACE").getFirst();inventory.current(c,"Places",destination);var originalDelivery=authorize?t:deliveries.requireDelivery(c,t.get("deliveryId").toString());sc.put("PLACE",java.util.stream.Stream.of(destination,originalDelivery.get("placeId").toString()).distinct().sorted().toList());works.require(c,t.get("workId").toString(),false);
  if(authorize){var q=InventoryQuantity.parse(s.get("quantity"),((Number)inventory.current(c,"TradeItems",t.get("itemId").toString()).get("decimalPlaces")).intValue());var start=decimal(s,"startQuantity");if(!Objects.equals(t.get("unit"),text(s,"unit",40))||start.compareTo((BigDecimal)t.get("startQuantity"))<0||start.add(q).compareTo(((BigDecimal)t.get("startQuantity")).add(deliveries.currentDeliveryQuantity(c,t.get("ID").toString())))>0)throw DomainError.invalid("Return scope exceeds actual delivery");if(!instant(s,"validUntil").isAfter(clock.instant()))throw DomainError.invalid("Return authorization must expire in future");text(s,"reason",320);manager(c,"authorizeReturn",sc);}
  // Recording an observed physical arrival needs only RECORD capability and scope (plan §7.1); the authorizing manager's current authority gates confirmation, not the fact.
  else if(receive){var a=authorization(c,t,s);if(s.get("returnId")!=null)currentAuthorization(c,a,sc);if(!instant(s,"nextCheckAt").isAfter(clock.instant()))throw DomainError.invalid("Future return next check required");if(s.get("returnId")==null){uuid(s,"eventId");var at=instant(s,"occurredAt");if(at.isAfter(c.knownAt()))throw DomainError.invalid("Future receipt rejected");observed(c,t,s);}else{uuid(s,"canonicalOccurrenceId");if(s.get("receivingCustodianId")!=null)requireReceivingAuthority(c,uuid(s,"receivingCustodianId"),sc);}}
  else{String decision=text(s,"decision",40);if(!com.mulino.application.responsibility.ObligationClosureCatalog.RETURN_DECISIONS.contains(decision))throw DomainError.invalid("Unknown return disposition");text(s,"reason",320);uuid(s,"evidenceId");manager(c,"decideReturnDisposition",sc);if(decision.equals("RESALE")||decision.equals("DISPOSE")){var categories=policy.rule(c,cap).rule().get("categoryCapabilities");if(!(categories instanceof Map<?,?> rules)||!(rules.get(decision.equals("DISPOSE")?"ADMIN":"QC") instanceof String authority))throw new DomainError("HELD","POLICY_UNRESOLVED","Return quality/admin authority unresolved");every(c,authority,sc);}if(!instant(s,"nextCheckAt").isAfter(clock.instant()))throw DomainError.invalid("Future disposition check required");}
  String root=Objects.toString(t.get("rangeRootId"),Objects.toString(t.get("segmentId"),""));var fences=new TreeSet<String>(List.of("return/range/"+root,"return/delivery/"+(authorize?t.get("ID"):t.get("deliveryId")),"inventory/item/"+t.get("itemId"),"inventory/place/"+destination));for(String place:sc.get("PLACE"))fences.add("inventory/place/"+place);var actors=new HashSet<String>();if(receive)actors.add(authorization(c,t,s).get("actorId").toString());return new CommandPreparation(sc,new ArrayList<>(fences),actors,"RETURN",null,null,0,t.get("ID").toString(),((Number)t.get("revision")).intValue());
 }
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object>i,CommandPreparation p){return List.of(SubjectBinding.optional("TradeItem",Set.copyOf(p.scopes().get("ITEM"))),SubjectBinding.optional("Work",Set.copyOf(p.scopes().get("WORK"))));}
 public Map<String,Object> execute(DomainContext c,Map<String,Object>i){var p=prepare(c,i);inventory.fence(c,p.fenceKeys());var s=slots(i);var t=target(c,i);String cap=i.get("capabilityId").toString();var row=StockPrimitives.row(c,StockPrimitives.id(),c.asOf());
  if(cap.equals("authorizeReturn")){for(String k:List.of("workId","customerId","itemId","lotId"))row.put(k,t.get(k));row.putAll(Map.of("deliveryId",t.get("ID"),"rangeRootId",Objects.toString(t.get("rangeRootId"),Objects.toString(t.get("segmentId"),"")),"startQuantity",decimal(s,"startQuantity"),"quantity",new BigDecimal(s.get("quantity").toString()),"unit",s.get("unit"),"destinationId",s.get("destinationId"),"actorId",c.actorId(),"validUntil",instant(s,"validUntil"),"policyHash",policy.rule(c,cap).policyHash()));row.put("commandId",CommandExecution.commandId());row.put("reason",s.get("reason"));r.insert("Authorizations",row);return result("authorizationId",row);}
  if(cap.equals("receiveReturn")){if(!s.containsKey("returnId")){var range=observed(c,t,s);var same=r.currentRows(c,"Observations").stream().filter(x->uuid(s,"eventId").equals(x.get("eventId"))).findFirst();if(same.isPresent()){var prior=same.get();if(!t.get("ID").equals(prior.get("authorizationId"))||range.start().compareTo((BigDecimal)prior.get("startQuantity"))!=0||range.end().subtract(range.start()).compareTo((BigDecimal)prior.get("quantity"))!=0||!instant(s,"occurredAt").equals(StockPrimitives.instant(prior.get("occurredAt"))))throw conflict("Same physical return event already observed with a different scope");return result("returnId",prior);}
   for(String k:List.of("workId","deliveryId","customerId","itemId","lotId","rangeRootId","unit"))row.put(k,t.get(k));row.put("startQuantity",range.start());row.put("quantity",range.end().subtract(range.start()));row.putAll(Map.of("authorizationId",t.get("ID"),"eventId",uuid(s,"eventId"),"placeId",t.get("destinationId"),"occurredAt",instant(s,"occurredAt"),"nextCheckAt",instant(s,"nextCheckAt"),"state","PROVISIONAL"));validateOriginalRange(c,row);r.insert("Observations",row);impact.recorded(c,row.get("workId").toString(),row.get("ID").toString(),"RETURN_RECONCILIATION",row.get("rangeRootId").toString(),"반품 실물과 원 인도를 대조한다",instant(s,"nextCheckAt"));return result("returnId",row);}
   validateOriginalRange(c,t);String canonical=uuid(s,"canonicalOccurrenceId");var used=authorization(c,t,s);
   var existing=r.currentRows(c,"Receipts").stream().filter(x->t.get("rangeRootId").equals(x.get("rangeRootId"))&&overlap(t,x)).toList();if(!existing.isEmpty()){var prior=existing.getFirst();if(existing.size()!=1||!same(t,prior))throw conflict("Repeated physical return range cannot create inventory");
    if(t.get("ID").equals(prior.get("observationId"))){if(!canonical.equals(prior.get("canonicalOccurrenceId")))throw conflict("Repeated physical return range cannot create inventory");var fact=evidence.requireCanonical(c,canonical,"RETURN_RECEIPT",t.get("itemId").toString(),t.get("ID").toString(),(BigDecimal)t.get("quantity"),t.get("unit").toString());if(!t.get("eventId").equals(fact.get("occurrenceIdentity")))throw conflict("Return event identity mismatch");r.confirmed(c,t.get("ID").toString());remedy.reconcileReturnObservation(c,t.get("ID").toString(),prior.get("ID").toString());return result("receiptId",prior);}
    // Another report closes against the one receipt only when its own verified evidence (its own event identity and canonical,
    // an original and event that name the received return, the same occurrence time) identifies the received occurrence;
    // another observation's canonical never identifies it, and an unconfirmed link keeps the reconciliation duty
    // (plan §6 사실 기록과 실행 권한, §4.3). No stock moves.
    if(canonical.equals(prior.get("canonicalOccurrenceId")))throw new DomainError("HELD","EVIDENCE_UNVERIFIED","A second return report needs its own verified evidence; another observation's receipt does not identify it");
    var own=evidence.requireCanonical(c,canonical,"RETURN_RECEIPT",t.get("itemId").toString(),t.get("ID").toString(),(BigDecimal)t.get("quantity"),t.get("unit").toString());if(!t.get("eventId").equals(own.get("occurrenceIdentity")))throw conflict("Return event identity mismatch");
    var named=namedSameOccurrence(c,canonical,t);if(named.isEmpty())throw new DomainError("HELD","EVIDENCE_UNVERIFIED","The report's own verified evidence does not identify the received return");if(!named.equals(Set.of(prior.get("observationId").toString())))throw conflict("The report's own verified evidence names a different return");
    if(!StockPrimitives.instant(t.get("occurredAt")).equals(StockPrimitives.instant(prior.get("occurredAt"))))throw conflict("Return report occurred at a different time than the received return; it is not the same occurrence");
    evidence.requireCanonical(c,prior.get("canonicalOccurrenceId").toString(),"RETURN_RECEIPT",prior.get("itemId").toString(),prior.get("observationId").toString(),(BigDecimal)prior.get("quantity"),prior.get("unit").toString());r.confirmed(c,t.get("ID").toString());remedy.reconcileDuplicateReturnObservation(c,t.get("ID").toString(),prior.get("ID").toString(),canonical);return result("receiptId",prior);}
   var fact=evidence.requireCanonical(c,canonical,"RETURN_RECEIPT",t.get("itemId").toString(),t.get("ID").toString(),(BigDecimal)t.get("quantity"),t.get("unit").toString());if(!t.get("eventId").equals(fact.get("occurrenceIdentity")))throw conflict("Return event identity mismatch");
   var delivery=deliveries.requireDelivery(c,t.get("deliveryId").toString());String custodian=s.get("receivingCustodianId")==null?null:uuid(s,"receivingCustodianId");if(custodian!=null)requireEvidencedCustodian(c,canonical,t,custodian);var movement=stock.receive(c,t,delivery,canonical,((List<?>)fact.get("evidenceRefs")).get(4).toString(),CommandExecution.commandId(),policy.rule(c,cap).policyHash(),custodian);for(String k:List.of("eventId","workId","deliveryId","customerId","itemId","lotId","rangeRootId","startQuantity","quantity","unit","placeId","occurredAt"))row.put(k,t.get(k));row.put("authorizationId",used.get("ID"));row.putAll(Map.of("observationId",t.get("ID"),"canonicalOccurrenceId",canonical,"segmentId",movement.get("segmentId"),"restrictionId",movement.get("restrictionId"),"commandId",CommandExecution.commandId()));r.insert("Receipts",row);r.confirmed(c,t.get("ID").toString());remedy.reconcileReturnObservation(c,t.get("ID").toString(),row.get("ID").toString());for(String kind:List.of("RETURN_QC_REVIEW","RETURN_COMMERCIAL_REVIEW","RETURN_SETTLEMENT_REVIEW"))impact.recorded(c,t.get("workId").toString(),row.get("ID").toString(),kind,row.get("rangeRootId").toString(),"반품의 품질·교환·환불·정산 책임을 별도 검토한다",instant(s,"nextCheckAt"));impact.invalidate(c,t.get("workId").toString());return result("receiptId",row);
  }
  String decision=text(s,"decision",40);evidence.requireCanonical(c,uuid(s,"evidenceId"),"RETURN_DISPOSITION_"+decision,t.get("itemId").toString(),t.get("observationId").toString(),(BigDecimal)t.get("quantity"),t.get("unit").toString());var priorDecision=r.currentRows(c,"Dispositions").stream().filter(x->uuid(s,"evidenceId").equals(x.get("evidenceId"))).findFirst();if(priorDecision.isPresent())return result("decisionId",priorDecision.get());row.putAll(Map.of("returnId",t.get("ID"),"workId",t.get("workId"),"decision",decision,"actorId",c.actorId(),"evidenceId",s.get("evidenceId"),"policyHash",policy.rule(c,cap).policyHash(),"commandId",CommandExecution.commandId(),"reason",s.get("reason")));r.insert("Dispositions",row);impact.recorded(c,t.get("workId").toString(),row.get("ID").toString(),"RETURN_"+decision,t.get("rangeRootId").toString(),"결정 근거와 현재 품질·회수 제한을 확인해 별도 실행한다",instant(s,"nextCheckAt"));outbox.enqueue(c,CommandExecution.commandId(),row.get("ID").toString(),"returnDispositionReview",Map.of("returnId",t.get("ID"),"decision",decision));return result("decisionId",row);
 }
 /** Returned stock custody is known only from verified evidence naming an internal receiver; never the confirming actor (plan §4.1–§4.2). */
 private void requireReceivingAuthority(DomainContext c,String custodian,Map<String,List<String>> scopes){
  var actor=identities.actor(c.organizationId(),custodian).orElseThrow(DomainError::forbidden);
  if(!Set.of("HUMAN","AGENT").contains(actor.get("kind"))||!inventory.internalCustodian(c,custodian))throw new DomainError("REJECTED","SCOPE_INELIGIBLE","Receiving custodian must be an internal actor");
  var holder=new DomainContext(c.organizationId(),custodian,Objects.toString(actor.get("stableRequestOwner"),custodian),c.asOf(),c.knownAt());
  if(!everyPermitted(holder,"receiveReturn",scopes))throw new DomainError("REJECTED","SCOPE_INELIGIBLE","Receiving custodian lacks current return receipt authority for this place");
 }
 private void requireEvidencedCustodian(DomainContext c,String canonical,Map<String,Object> observation,String custodian){
  var chains=evidence.verifiedCanonical(c,canonical,"RETURN_RECEIPT",observation.get("itemId").toString(),observation.get("ID").toString(),(BigDecimal)observation.get("quantity"),observation.get("unit").toString());
  var named=new TreeSet<String>();var mapper=new com.fasterxml.jackson.databind.ObjectMapper();
  for(var chain:chains){var refs=(List<?>)chain.get("evidenceRefs");var event=sources.require("Events",c.organizationId(),refs.get(3).toString());var doc=sources.require("DocumentVersions",c.organizationId(),refs.get(4).toString());
   try{var payload=mapper.readTree(event.get("payload").toString());var original=mapper.readTree(blobs.read(UUID.fromString(doc.get("blobId").toString()),doc.get("sha256").toString()));
    var fromPayload=payload.path("receivingCustodianId");var fromOriginal=original.path("receivingCustodianId");
    if(fromPayload.isMissingNode()&&fromOriginal.isMissingNode())continue;
    if(!fromPayload.isTextual()||!fromOriginal.isTextual()||!fromPayload.asText().equals(fromOriginal.asText()))throw new DomainError("HELD","EVIDENCE_CONFLICT","Return original and event disagree on receiving custodian");
    named.add(fromPayload.asText());
   }catch(java.io.IOException malformed){throw new DomainError("HELD","EVIDENCE_UNVERIFIED","Receiving custodian requires parseable verified return evidence");}}
  if(named.size()>1)throw new DomainError("HELD","EVIDENCE_CONFLICT","Verified return sources name different receiving custodians");
  if(!named.equals(Set.of(custodian)))throw new DomainError("HELD","EVIDENCE_UNVERIFIED","Receiving custodian is not named by verified return evidence");
 }
 /** Received returns named by the report's own verified chains; original and event must agree on the named return. */
 private Set<String> namedSameOccurrence(DomainContext c,String canonical,Map<String,Object> observation){
  var named=new TreeSet<String>();var mapper=new com.fasterxml.jackson.databind.ObjectMapper();
  for(var chain:evidence.verifiedCanonical(c,canonical,"RETURN_RECEIPT",observation.get("itemId").toString(),observation.get("ID").toString(),(BigDecimal)observation.get("quantity"),observation.get("unit").toString())){var refs=(List<?>)chain.get("evidenceRefs");var event=sources.require("Events",c.organizationId(),refs.get(3).toString());var doc=sources.require("DocumentVersions",c.organizationId(),refs.get(4).toString());
   try{var fromPayload=mapper.readTree(event.get("payload").toString()).path("sameOccurrenceAsReturnId");var fromOriginal=mapper.readTree(blobs.read(UUID.fromString(doc.get("blobId").toString()),doc.get("sha256").toString())).path("sameOccurrenceAsReturnId");
    if(fromPayload.isMissingNode()&&fromOriginal.isMissingNode())continue;
    if(!fromPayload.isTextual()||!fromOriginal.isTextual()||!fromPayload.asText().equals(fromOriginal.asText()))throw conflict("Return original and event disagree on the received return");
    named.add(fromPayload.asText());
   }catch(java.io.IOException malformed){throw new DomainError("HELD","EVIDENCE_UNVERIFIED","Duplicate return identification requires parseable verified evidence");}}
  return named;
 }
 private Map<String,Object> authorization(DomainContext c,Map<String,Object>t){return t.get("authorizationId")==null?t:r.require(c,"Authorizations",t.get("authorizationId").toString());}
 /** Confirmation may use a later current authorization of the same delivery covering the observed range (late arrival after expiry or policy change). */
 private Map<String,Object> authorization(DomainContext c,Map<String,Object>t,Map<String,Object>s){if(t.get("authorizationId")==null||s.get("authorizationId")==null)return authorization(c,t);var a=r.require(c,"Authorizations",uuid(s,"authorizationId"));if(!Objects.equals(a.get("deliveryId"),t.get("deliveryId"))||!Objects.equals(a.get("destinationId"),t.get("placeId"))||!Objects.equals(a.get("unit"),t.get("unit"))||((BigDecimal)t.get("startQuantity")).compareTo((BigDecimal)a.get("startQuantity"))<0||((BigDecimal)t.get("startQuantity")).add((BigDecimal)t.get("quantity")).compareTo(((BigDecimal)a.get("startQuantity")).add((BigDecimal)a.get("quantity")))>0)throw conflict("Authorization does not cover the observed return");return a;}
 /** The observed physical range, defaulting to the authorized one; it must lie inside the authorization (plan §6 반품). */
 private QualityRanges.Range observed(DomainContext c,Map<String,Object>a,Map<String,Object>s){var from=(BigDecimal)a.get("startQuantity");var to=from.add((BigDecimal)a.get("quantity"));if(s.get("quantity")==null&&s.get("startQuantity")==null&&s.get("unit")==null)return new QualityRanges.Range(from,to);var q=InventoryQuantity.parse(s.get("quantity"),((Number)inventory.current(c,"TradeItems",a.get("itemId").toString()).get("decimalPlaces")).intValue());var start=decimal(s,"startQuantity");if(!Objects.equals(a.get("unit"),text(s,"unit",40))||start.compareTo(from)<0||start.add(q).compareTo(to)>0)throw DomainError.invalid("Observed return exceeds authorization");return new QualityRanges.Range(start,start.add(q));}
 private void every(DomainContext c,String cap,Map<String,List<String>>sc){for(var d:sc.entrySet())for(String v:d.getValue()){var one=new LinkedHashMap<String,List<String>>(sc);one.put(d.getKey(),List.of(v));auth.authorizeScopes(c,cap,one);}}
 private boolean everyPermitted(DomainContext c,String cap,Map<String,List<String>>sc){for(var d:sc.entrySet())for(String v:d.getValue()){var one=new LinkedHashMap<String,List<String>>(sc);one.put(d.getKey(),List.of(v));if(!auth.permittedScopes(c,cap,one))return false;}return true;}
 private void currentAuthorization(DomainContext c,Map<String,Object>a,Map<String,List<String>>sc){if(!clock.instant().isBefore(StockPrimitives.instant(a.get("validUntil")))||!policy.rule(c,"authorizeReturn").policyHash().equals(a.get("policyHash")))throw conflict("Return authorization expired or policy changed");var originalScopes=new LinkedHashMap<String,List<String>>(sc);originalScopes.put("TARGET",List.of(a.get("deliveryId").toString()));manager(new DomainContext(c.organizationId(),a.get("actorId").toString(),c.stableRequestOwner(),c.asOf(),c.knownAt()),"authorizeReturn",originalScopes);}
 private void manager(DomainContext c,String cap,Map<String,List<String>>sc){if(!"HUMAN".equals(identities.actor(c.organizationId(),c.actorId()).orElseThrow(DomainError::forbidden).get("kind")))throw DomainError.forbidden();every(c,cap,sc);Instant now=clock.instant();if(!com.mulino.application.trade.recall.ManagementCoverage.covers(identities.rows("ManagementAuthorities",c.organizationId()),c.organizationId(),c.actorId(),cap,sc,x->x.get("validFrom")!=null&&x.get("validUntil")!=null&&!now.isBefore(StockPrimitives.instant(x.get("validFrom")))&&now.isBefore(StockPrimitives.instant(x.get("validUntil")))&&(x.get("revokedAt")==null||now.isBefore(StockPrimitives.instant(x.get("revokedAt"))))))throw DomainError.forbidden();}
 private void validateOriginalRange(DomainContext c,Map<String,Object>t){var d=deliveries.requireDelivery(c,t.get("deliveryId").toString());if(!List.of("itemId","lotId","customerId","unit","workId","rangeRootId").stream().allMatch(k->Objects.equals(d.get(k),t.get(k)))||((BigDecimal)t.get("startQuantity")).compareTo((BigDecimal)d.get("startQuantity"))<0||((BigDecimal)t.get("startQuantity")).add((BigDecimal)t.get("quantity")).compareTo(((BigDecimal)d.get("startQuantity")).add(deliveries.currentDeliveryQuantity(c,d.get("ID").toString())))>0)throw conflict("Original delivery identity or actual range mismatch");}
 public BigDecimal returnedQuantity(DomainContext c,String deliveryId){deliveries.requireDelivery(c,deliveryId);return r.rows(c,"Receipts").stream().filter(x->deliveryId.equals(x.get("deliveryId"))&&!StockPrimitives.instant(x.get("occurredAt")).isAfter(c.asOf())).map(x->(BigDecimal)x.get("quantity")).reduce(BigDecimal.ZERO,BigDecimal::add);}
 public static boolean overlap(Map<String,Object>a,Map<String,Object>b){var x=(BigDecimal)a.get("startQuantity");var y=(BigDecimal)b.get("startQuantity");return x.compareTo(y.add((BigDecimal)b.get("quantity")))<0&&y.compareTo(x.add((BigDecimal)a.get("quantity")))<0;}
 private boolean same(Map<String,Object>a,Map<String,Object>b){return ((BigDecimal)a.get("startQuantity")).compareTo((BigDecimal)b.get("startQuantity"))==0&&((BigDecimal)a.get("quantity")).compareTo((BigDecimal)b.get("quantity"))==0&&List.of("deliveryId","customerId","itemId","lotId","unit","placeId").stream().allMatch(k->Objects.equals(a.get(k),b.get(k)));}
 private static DomainError conflict(String message){return new DomainError("HELD","EVIDENCE_CONFLICT",message);}
 private static BigDecimal decimal(Map<String,Object>s,String key){return com.mulino.application.quality.QualityCommands.decimal(s,key);}
 private static Instant instant(Map<String,Object>s,String key){return com.mulino.application.quality.QualityCommands.instant(s,key);}
 private Map<String,Object> result(String key,Map<String,Object>row){return Map.of("outcome","APPLIED","revision",row.get("revision"),"effects",Map.of(key,row.get("ID"),"inventoryCreated",false,"purchaseContribution","0"));}
}
