package com.mulino.application.trade.returns;
import com.mulino.application.core.*;
import com.mulino.application.trade.*;
import com.mulino.application.work.WorkAccess;
import com.mulino.application.policy.PolicyCommandGuard;
import com.mulino.domain.identity.IdentityRepository;
import com.mulino.domain.inventory.*;
import com.mulino.domain.trade.returns.ReturnRepository;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.inventory.InventoryCommands.*;
/** Returns preserve actual delivery history and never contribute to purchasing arrival. */
@Component
public class ReturnCommands implements CommandHandler,ReturnQuantityPort {
 private final ReturnRepository r;private final DeliveredCargoPort deliveries;private final InventoryRepository inventory;private final ReturnStockPrimitives stock;private final TradeEvidence evidence;private final TradeImpact impact;private final WorkAccess works;private final IdentityRepository identities;private final ReadAuthorizer auth;private final PolicyCommandGuard policy;private final TransactionalOutboxPort outbox;private final ExecutionClock clock;private final TradeObservationRemedy remedy;
 public ReturnCommands(ReturnRepository r,DeliveredCargoPort deliveries,InventoryRepository inventory,ReturnStockPrimitives stock,TradeEvidence evidence,TradeImpact impact,WorkAccess works,IdentityRepository identities,ReadAuthorizer auth,PolicyCommandGuard policy,TransactionalOutboxPort outbox,ExecutionClock clock,TradeObservationRemedy remedy){this.r=r;this.deliveries=deliveries;this.inventory=inventory;this.stock=stock;this.evidence=evidence;this.impact=impact;this.works=works;this.identities=identities;this.auth=auth;this.policy=policy;this.outbox=outbox;this.clock=clock;this.remedy=remedy;}
 public Set<String> capabilities(){return Set.of("authorizeReturn","receiveReturn","decideReturnDisposition");}
 public Set<String> intentKinds(){return Set.of("COMMAND","RECORD");}
 private Map<String,Object> target(DomainContext c,Map<String,Object>i){var s=slots(i);return switch(i.get("capabilityId").toString()){case "authorizeReturn"->deliveries.requireDelivery(c,uuid(s,"deliveryId"));case "receiveReturn"->s.containsKey("returnId")?r.require(c,"Observations",uuid(s,"returnId")):r.require(c,"Authorizations",uuid(s,"authorizationId"));default->r.require(c,"Receipts",uuid(s,"returnId"));};}
 public static Map<String,List<String>> scopes(Map<String,Object>t){return Map.of("TARGET",List.of(t.get("ID").toString()),"ITEM",List.of(t.get("itemId").toString()),"WORK",List.of(t.get("workId").toString()),"PLACE",List.of(Objects.toString(t.get("destinationId"),Objects.toString(t.get("placeId"),""))));}
 public CommandPreparation prepare(DomainContext c,Map<String,Object>i){var s=slots(i);String cap=text(i,"capabilityId",80);var t=target(c,i);boolean authorize=cap.equals("authorizeReturn"),receive=cap.equals("receiveReturn");Set<String> allowed=authorize?Set.of("deliveryId","startQuantity","quantity","unit","destinationId","validUntil","reason"):receive?(s.containsKey("returnId")?Set.of("returnId","nextCheckAt","canonicalOccurrenceId"):Set.of("authorizationId","eventId","occurredAt","nextCheckAt")):Set.of("returnId","decision","evidenceId","reason","nextCheckAt");if(!allowed.containsAll(s.keySet())||!Objects.equals(i.get("intentKind"),receive?"RECORD":"COMMAND"))throw DomainError.invalid("Return slots or intent kind mismatch");
  var sc=new LinkedHashMap<String,List<String>>(scopes(t));String destination=authorize?uuid(s,"destinationId"):sc.get("PLACE").getFirst();inventory.current(c,"Places",destination);var originalDelivery=authorize?t:deliveries.requireDelivery(c,t.get("deliveryId").toString());sc.put("PLACE",java.util.stream.Stream.of(destination,originalDelivery.get("placeId").toString()).distinct().sorted().toList());works.require(c,t.get("workId").toString(),false);
  if(authorize){var q=InventoryQuantity.parse(s.get("quantity"),((Number)inventory.current(c,"TradeItems",t.get("itemId").toString()).get("decimalPlaces")).intValue());var start=decimal(s,"startQuantity");if(!Objects.equals(t.get("unit"),text(s,"unit",40))||start.compareTo((BigDecimal)t.get("startQuantity"))<0||start.add(q).compareTo(((BigDecimal)t.get("startQuantity")).add(deliveries.currentDeliveryQuantity(c,t.get("ID").toString())))>0)throw DomainError.invalid("Return scope exceeds actual delivery");if(!instant(s,"validUntil").isAfter(clock.instant()))throw DomainError.invalid("Return authorization must expire in future");text(s,"reason",320);manager(c,"authorizeReturn",sc);}
  else if(receive){var a=authorization(c,t);currentAuthorization(c,a,sc);if(!instant(s,"nextCheckAt").isAfter(clock.instant()))throw DomainError.invalid("Future return next check required");if(s.get("returnId")==null){uuid(s,"eventId");var at=instant(s,"occurredAt");if(at.isAfter(c.knownAt()))throw DomainError.invalid("Future receipt rejected");}else uuid(s,"canonicalOccurrenceId");}
  else{String decision=text(s,"decision",40);if(!Set.of("REVIEW","RESALE","EXCHANGE","REFUND","DISPOSE").contains(decision))throw DomainError.invalid("Unknown return disposition");text(s,"reason",320);uuid(s,"evidenceId");manager(c,"decideReturnDisposition",sc);if(decision.equals("RESALE")||decision.equals("DISPOSE")){var categories=policy.rule(c,cap).rule().get("categoryCapabilities");if(!(categories instanceof Map<?,?> rules)||!(rules.get(decision.equals("DISPOSE")?"ADMIN":"QC") instanceof String authority))throw new DomainError("HELD","POLICY_UNRESOLVED","Return quality/admin authority unresolved");auth.authorizeScopes(c,authority,sc);}if(!instant(s,"nextCheckAt").isAfter(clock.instant()))throw DomainError.invalid("Future disposition check required");}
  String root=Objects.toString(t.get("rangeRootId"),Objects.toString(t.get("segmentId"),""));var fences=new TreeSet<String>(List.of("return/range/"+root,"return/delivery/"+(authorize?t.get("ID"):t.get("deliveryId")),"inventory/item/"+t.get("itemId"),"inventory/place/"+destination));for(String place:sc.get("PLACE"))fences.add("inventory/place/"+place);var actors=new HashSet<String>();if(receive)actors.add(authorization(c,t).get("actorId").toString());return new CommandPreparation(sc,new ArrayList<>(fences),actors,"RETURN",null,null,0,t.get("ID").toString(),((Number)t.get("revision")).intValue());
 }
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object>i,CommandPreparation p){return List.of(SubjectBinding.optional("TradeItem",Set.copyOf(p.scopes().get("ITEM"))),SubjectBinding.optional("Work",Set.copyOf(p.scopes().get("WORK"))));}
 public Map<String,Object> execute(DomainContext c,Map<String,Object>i){var p=prepare(c,i);inventory.fence(c,p.fenceKeys());var s=slots(i);var t=target(c,i);String cap=i.get("capabilityId").toString();var row=StockPrimitives.row(c,StockPrimitives.id(),c.asOf());
  if(cap.equals("authorizeReturn")){for(String k:List.of("workId","customerId","itemId","lotId"))row.put(k,t.get(k));row.putAll(Map.of("deliveryId",t.get("ID"),"rangeRootId",Objects.toString(t.get("rangeRootId"),Objects.toString(t.get("segmentId"),"")),"startQuantity",decimal(s,"startQuantity"),"quantity",new BigDecimal(s.get("quantity").toString()),"unit",s.get("unit"),"destinationId",s.get("destinationId"),"actorId",c.actorId(),"validUntil",instant(s,"validUntil"),"policyHash",policy.rule(c,cap).policyHash()));row.put("commandId",CommandExecution.commandId());row.put("reason",s.get("reason"));r.insert("Authorizations",row);return result("authorizationId",row);}
  if(cap.equals("receiveReturn")){if(!s.containsKey("returnId")){for(String k:List.of("workId","deliveryId","customerId","itemId","lotId","rangeRootId","startQuantity","quantity","unit"))row.put(k,t.get(k));row.putAll(Map.of("authorizationId",t.get("ID"),"eventId",uuid(s,"eventId"),"placeId",t.get("destinationId"),"occurredAt",instant(s,"occurredAt"),"nextCheckAt",instant(s,"nextCheckAt"),"state","PROVISIONAL"));validateOriginalRange(c,row);r.insert("Observations",row);impact.recorded(c,row.get("workId").toString(),row.get("ID").toString(),"RETURN_RECONCILIATION",row.get("rangeRootId").toString(),"반품 실물과 원 인도를 대조한다",instant(s,"nextCheckAt"));return result("returnId",row);}
   validateOriginalRange(c,t);String canonical=uuid(s,"canonicalOccurrenceId");var fact=evidence.requireCanonical(c,canonical,"RETURN_RECEIPT",t.get("itemId").toString(),t.get("ID").toString(),(BigDecimal)t.get("quantity"),t.get("unit").toString());if(!t.get("eventId").equals(fact.get("occurrenceIdentity")))throw conflict("Return event identity mismatch");
   var existing=r.currentRows(c,"Receipts").stream().filter(x->t.get("rangeRootId").equals(x.get("rangeRootId"))&&overlap(t,x)).toList();if(!existing.isEmpty()){var prior=existing.getFirst();if(existing.size()!=1||!same(t,prior)||!t.get("eventId").equals(prior.get("eventId"))||!canonical.equals(prior.get("canonicalOccurrenceId")))throw conflict("Repeated physical return range cannot create inventory");r.confirmed(c,t.get("ID").toString());remedy.reconcileReturnObservation(c,t.get("ID").toString(),prior.get("ID").toString());return result("receiptId",prior);}
   var delivery=deliveries.requireDelivery(c,t.get("deliveryId").toString());var movement=stock.receive(c,t,delivery,canonical,((List<?>)fact.get("evidenceRefs")).get(4).toString(),CommandExecution.commandId(),policy.rule(c,cap).policyHash());for(String k:List.of("authorizationId","eventId","workId","deliveryId","customerId","itemId","lotId","rangeRootId","startQuantity","quantity","unit","placeId","occurredAt"))row.put(k,t.get(k));row.putAll(Map.of("observationId",t.get("ID"),"canonicalOccurrenceId",canonical,"segmentId",movement.get("segmentId"),"restrictionId",movement.get("restrictionId"),"commandId",CommandExecution.commandId()));r.insert("Receipts",row);r.confirmed(c,t.get("ID").toString());remedy.reconcileReturnObservation(c,t.get("ID").toString(),row.get("ID").toString());for(String kind:List.of("RETURN_QC_REVIEW","RETURN_COMMERCIAL_REVIEW","RETURN_SETTLEMENT_REVIEW"))impact.recorded(c,t.get("workId").toString(),row.get("ID").toString(),kind,row.get("rangeRootId").toString(),"반품의 품질·교환·환불·정산 책임을 별도 검토한다",instant(s,"nextCheckAt"));impact.invalidate(c,t.get("workId").toString());return result("receiptId",row);
  }
  String decision=text(s,"decision",40);evidence.requireCanonical(c,uuid(s,"evidenceId"),"RETURN_DISPOSITION_"+decision,t.get("itemId").toString(),t.get("observationId").toString(),(BigDecimal)t.get("quantity"),t.get("unit").toString());var priorDecision=r.currentRows(c,"Dispositions").stream().filter(x->uuid(s,"evidenceId").equals(x.get("evidenceId"))).findFirst();if(priorDecision.isPresent())return result("decisionId",priorDecision.get());row.putAll(Map.of("returnId",t.get("ID"),"workId",t.get("workId"),"decision",decision,"actorId",c.actorId(),"evidenceId",s.get("evidenceId"),"policyHash",policy.rule(c,cap).policyHash(),"commandId",CommandExecution.commandId(),"reason",s.get("reason")));r.insert("Dispositions",row);impact.recorded(c,t.get("workId").toString(),row.get("ID").toString(),"RETURN_"+decision,t.get("rangeRootId").toString(),"결정 근거와 현재 품질·회수 제한을 확인해 별도 실행한다",instant(s,"nextCheckAt"));outbox.enqueue(c,CommandExecution.commandId(),row.get("ID").toString(),"returnDispositionReview",Map.of("returnId",t.get("ID"),"decision",decision));return result("decisionId",row);
 }
 private Map<String,Object> authorization(DomainContext c,Map<String,Object>t){return t.get("authorizationId")==null?t:r.require(c,"Authorizations",t.get("authorizationId").toString());}
 private void currentAuthorization(DomainContext c,Map<String,Object>a,Map<String,List<String>>sc){if(!clock.instant().isBefore(StockPrimitives.instant(a.get("validUntil")))||!policy.rule(c,"authorizeReturn").policyHash().equals(a.get("policyHash")))throw conflict("Return authorization expired or policy changed");var originalScopes=new LinkedHashMap<String,List<String>>(sc);originalScopes.put("TARGET",List.of(a.get("deliveryId").toString()));manager(new DomainContext(c.organizationId(),a.get("actorId").toString(),c.stableRequestOwner(),c.asOf(),c.knownAt()),"authorizeReturn",originalScopes);}
 private void manager(DomainContext c,String cap,Map<String,List<String>>sc){if(!"HUMAN".equals(identities.actor(c.organizationId(),c.actorId()).orElseThrow(DomainError::forbidden).get("kind")))throw DomainError.forbidden();auth.authorizeScopes(c,cap,sc);Instant now=clock.instant();if(identities.rows("ManagementAuthorities",c.organizationId()).stream().noneMatch(x->c.actorId().equals(x.get("actorId"))&&cap.equals(x.get("capabilityId"))&&x.get("validFrom")!=null&&x.get("validUntil")!=null&&!now.isBefore(StockPrimitives.instant(x.get("validFrom")))&&now.isBefore(StockPrimitives.instant(x.get("validUntil")))&&(x.get("revokedAt")==null||now.isBefore(StockPrimitives.instant(x.get("revokedAt"))))&&("ORGANIZATION".equals(x.get("scopeKind"))&&c.organizationId().equals(x.get("scopeId"))||sc.getOrDefault(x.get("scopeKind"),List.of()).contains(x.get("scopeId")))))throw DomainError.forbidden();}
 private void validateOriginalRange(DomainContext c,Map<String,Object>t){var d=deliveries.requireDelivery(c,t.get("deliveryId").toString());if(!List.of("itemId","lotId","customerId","unit","workId","rangeRootId").stream().allMatch(k->Objects.equals(d.get(k),t.get(k)))||((BigDecimal)t.get("startQuantity")).compareTo((BigDecimal)d.get("startQuantity"))<0||((BigDecimal)t.get("startQuantity")).add((BigDecimal)t.get("quantity")).compareTo(((BigDecimal)d.get("startQuantity")).add(deliveries.currentDeliveryQuantity(c,d.get("ID").toString())))>0)throw conflict("Original delivery identity or actual range mismatch");}
 public BigDecimal returnedQuantity(DomainContext c,String deliveryId){deliveries.requireDelivery(c,deliveryId);return r.rows(c,"Receipts").stream().filter(x->deliveryId.equals(x.get("deliveryId"))&&!StockPrimitives.instant(x.get("occurredAt")).isAfter(c.asOf())).map(x->(BigDecimal)x.get("quantity")).reduce(BigDecimal.ZERO,BigDecimal::add);}
 public static boolean overlap(Map<String,Object>a,Map<String,Object>b){var x=(BigDecimal)a.get("startQuantity");var y=(BigDecimal)b.get("startQuantity");return x.compareTo(y.add((BigDecimal)b.get("quantity")))<0&&y.compareTo(x.add((BigDecimal)a.get("quantity")))<0;}
 private boolean same(Map<String,Object>a,Map<String,Object>b){return ((BigDecimal)a.get("startQuantity")).compareTo((BigDecimal)b.get("startQuantity"))==0&&((BigDecimal)a.get("quantity")).compareTo((BigDecimal)b.get("quantity"))==0&&List.of("deliveryId","customerId","itemId","lotId","unit","placeId").stream().allMatch(k->Objects.equals(a.get(k),b.get(k)));}
 private static DomainError conflict(String message){return new DomainError("HELD","EVIDENCE_CONFLICT",message);}
 private static BigDecimal decimal(Map<String,Object>s,String key){return com.mulino.application.quality.QualityCommands.decimal(s,key);}
 private static Instant instant(Map<String,Object>s,String key){return com.mulino.application.quality.QualityCommands.instant(s,key);}
 private Map<String,Object> result(String key,Map<String,Object>row){return Map.of("outcome","APPLIED","revision",row.get("revision"),"effects",Map.of(key,row.get("ID"),"inventoryCreated",false,"purchaseContribution","0"));}
}
