package org.mulino.verification.actual;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import org.mulino.verification.*;

/** Bounded real command/idempotency/closure probe, separate from all normative cases. */
public final class NativeS2WorkMain {
    private static int assertions;
    public static void main(String[] args) throws Exception {
        Path root=Path.of(System.getProperty("repo.root",".")).toAbsolutePath().normalize();
        var report=Json.object();var actions=Json.object();report.set("actions",actions);
        report.put("recordType","S2_ACTUAL_NATIVE_WORK_RECEIPT").put("startedAt",Instant.now().toString()).put("status","NOT_RUN").put("gateComplete",false).put("fullCaseCoverageClaimed",false);
        int exit=3;
        try {
            var config=ActualConfiguration.environment(System.getenv());var driver=new ActualAcceptanceDriver(root,config);
            var validator=new ContractValidator(root);String ref="verification/actual/s2/fixture.json";var fixture=validator.fixture(ref);
            String hash=Json.sha256(root.resolve(ref));var bundle=Json.object();bundle.set("fixture",fixture);bundle.set("bases",Json.array());bundle.put("fixtureHash",hash);
            var setup=driver.installFixture("setup",bundle);capture(actions,setup);available(setup);validator.result(setup,"installFixture");
            var aliases=setup.data().path("aliasMap");var actor=fixture.path("actors").path("reader");
            // Explicit server clock control proves the verification profile is deployed.
            var control=Json.object();control.put("type","clock").put("operation","advanceTo");var parameters=Json.object();parameters.put("instant",fixture.path("clock").path("asOf").asText());control.set("parameters",parameters);
            var clock=driver.control("server-clock",control);capture(actions,clock);available(clock);validator.result(clock,"control");
            var scope=Json.object();scope.put("organizationId",aliases.path("ORG").asText()).put("itemId",aliases.path("P").asText());
            var goal=Json.object();goal.put("quantityMode","CUMULATIVE_EVENT").put("targetQuantity","100").put("unit","BOX").put("endpoint","ARRIVED").put("timezone","Asia/Seoul").put("evidencePolicyVersion","fixture-v1").put("periodStart","2026-10-01T00:00:00Z").put("periodEnd","2026-10-31T00:00:00Z").put("eventKind","CONFIRMED_RECEIPT").put("deduplication","CANONICAL_OCCURRENCE").put("evaluatorVersion","core-v1");
            var goalScope=Json.object();goalScope.put("itemId",aliases.path("P").asText());goal.set("scope",goalScope);goal.set("contributionScope",goalScope);goal.set("conditions",Json.parse("[{\"id\":\"arrived\"}]"));
            var slots=Json.object();slots.put("itemId",aliases.path("P").asText()).put("definitionVersionId",aliases.path("DEF").asText()).put("kind","PURCHASE").put("ownerId",aliases.path("reader").asText()).put("supervisorId",aliases.path("supervisor").asText());slots.set("goal",goal);
            var intent=envelope("createDraft",slots,0,UUID.randomUUID().toString(),aliases.path("P").asText());
            var first=driver.start("submit-1","api",actor,"createDraft",intent);capture(actions,first);available(first);
            var second=driver.start("submit-2","api",actor,"createDraft",intent);capture(actions,second);available(second);
            var a=driver.await("result-1",first.data().path("invocationHandle"),30);var b=driver.await("result-2",second.data().path("invocationHandle"),30);capture(actions,a);capture(actions,b);available(a);available(b);validator.result(a,"await");validator.result(b,"await");
            var ar=Json.read(root.resolve(a.artifactRefs().getFirst()));var br=Json.read(root.resolve(b.artifactRefs().getFirst()));
            boolean overlap=!Instant.parse(ar.path("capturedAt").asText()).isBefore(Instant.parse(br.path("submittedAt").asText()))&&!Instant.parse(br.path("capturedAt").asText()).isBefore(Instant.parse(ar.path("submittedAt").asText()));
            report.put("requestIntervalsOverlap",overlap).put("concurrencyBarrierControlled",false);
            require(a.data().path("httpStatus").asInt()==200&&b.data().path("httpStatus").asInt()==200,"Concurrent draft requests must return successful HTTP responses");
            require(a.response().path("outcome").asText().equals("APPLIED"),"Draft must be applied through the actual command gateway");
            String work=Json.required(a.response().path("effects"),"workId");require(work.equals(b.response().path("effects").path("workId").asText()),"Same stable command key created different works");
            var changed=intent.deepCopy();((ObjectNode)changed.path("slots").path("goal")).put("targetQuantity","101");
            var conflict=driver.invoke("different-payload","api",actor,"createDraft",changed);capture(actions,conflict);available(conflict);require(conflict.response().path("outcome").asText().equals("CONFLICT")&&conflict.response().path("error").path("code").asText().equals("IDEMPOTENCY_CONFLICT"),"Same key with changed payload must conflict");
            var observe=Json.object();observe.set("scope",scope);observe.put("asOf",fixture.path("clock").path("asOf").asText()).put("knownAt",fixture.path("clock").path("knownAt").asText());observe.set("sources",Json.parse("[\"works\",\"goals\"]"));
            var before=driver.observe("db-before-close",observe);capture(actions,before);available(before);validator.result(before,"observe");
            var works=before.data().path("rawRows").path("works");require(works.size()==1,"Independent PostgreSQL must contain exactly one draft");require(works.get(0).path("id").asText().equals(work),"Independent work ID differs");require(works.get(0).path("status").asText().equals("DRAFT"),"New work must remain DRAFT");
            require(before.data().path("rawRows").path("goals").size()==1,"Idempotent draft must have one canonical GoalVersion");
            var cancelSlots=Json.object();cancelSlots.put("workId",work).put("reason","DRAFT_CANCELLED");
            var cancelled=driver.invoke("cancel","api",actor,"cancelDraft",envelope("cancelDraft",cancelSlots,0,UUID.randomUUID().toString(),work));capture(actions,cancelled);available(cancelled);require(cancelled.data().path("httpStatus").asInt()==200,"Draft cancellation must succeed");
            var after=driver.observe("db-after-close",observe);capture(actions,after);available(after);validator.result(after,"observe");
            var closed=after.data().path("rawRows").path("works");require(closed.size()==1,"Cancellation must preserve canonical work identity");require(closed.get(0).path("id").asText().equals(work),"Cancellation replaced work identity");require(closed.get(0).path("status").asText().equals("CLOSED"),"Cancelled draft must be CLOSED");require(closed.get(0).path("closeReason").asText().equals("CANCELLED"),"Cancellation close reason must be preserved");
            workflow(root,driver,validator,actions,aliases,fixture,actor);
            report.put("status","PASS").put("boundedAssertions",assertions).put("fixtureHash",hash).put("buildCommit",config.buildVersion()).put("limitation","Native draft/idempotency plus authored90+10 canonical assessment/duty/closure/read subset only; no normative T/C/V/E full case PASS, paid model or BTP claim");exit=0;
        } catch(Throwable failure) {
            report.put("status",ActualAttemptStatus.classify(failure instanceof AssertionError,failure instanceof Unavailable,!(failure instanceof AssertionError)&&!(failure instanceof Unavailable))).put("failure",failure.getClass().getSimpleName()+": "+failure.getMessage());exit=failure instanceof AssertionError?1:failure instanceof Unavailable?2:3;
        } finally {
            report.put("finishedAt",Instant.now().toString()).put("exitCode",exit);
            Path out=Path.of(System.getProperty("verification.actual.output",root.resolve("verification/harness/target/evidence/actual-s2-native").toString())).toAbsolutePath().normalize();Files.createDirectories(out);Json.write(out.resolve("actual-s2-native.json"),report);
            for(JsonNode action:actions)for(JsonNode artifact:action.path("artifactRefs")){Path source=root.resolve(artifact.asText()).normalize();Path target=out.resolve(artifact.asText()).normalize();if(!source.startsWith(root)||!target.startsWith(out))throw new IllegalArgumentException("Artifact escapes custody");Files.createDirectories(target.getParent());Files.copy(source,target,StandardCopyOption.REPLACE_EXISTING);}
            System.out.println(report.toPrettyString());
        }
        System.exit(exit);
    }
    private static void workflow(Path root,ActualAcceptanceDriver driver,ContractValidator validator,ObjectNode actions,JsonNode aliases,JsonNode fixture,JsonNode actor)throws Exception {
        advance(driver,actions,"workflow-clock","2026-10-07T09:00:02Z");
        var flat=Json.object();flat.put("workType","PURCHASE").put("quantityMode","CUMULATIVE_EVENT").put("endpoint","ARRIVED").put("dueAt","2026-10-31T00:00:00Z").put("evidencePolicyVersion","fixture-v1").put("ownerId",aliases.path("reader").asText()).put("supervisorId",aliases.path("supervisor").asText());
        flat.set("quantity",Json.parse("{\"value\":\"100\",\"unit\":\"BOX\"}"));flat.set("period",Json.parse("{\"start\":\"2026-10-01T00:00:00Z\",\"end\":\"2026-10-31T00:00:00Z\",\"startInclusive\":true,\"endInclusive\":true}"));flat.set("eventKinds",Json.parse("[\"RECEIPT\"]"));var itemScope=Json.object();itemScope.put("itemId",aliases.path("P").asText());flat.set("distinctContributionScope",itemScope);
        var created=driver.invoke("create-work","api",actor,"createWork",envelope("createWork",flat,0,UUID.randomUUID().toString(),aliases.path("P").asText()));capture(actions,created);available(created);require(created.data().path("httpStatus").asInt()==200&&created.response().path("outcome").asText().equals("APPLIED"),"Actual public createWork must apply");
        String work=Json.required(created.response().path("effects"),"workId");
        var binding=Json.object();binding.put("organizationId",aliases.path("ORG").asText()).put("workId",work).put("itemId",aliases.path("P").asText()).put("actorId",aliases.path("reader").asText()).put("supervisorId",aliases.path("supervisor").asText());
        var ninety=evidence(root,driver,actions,"receipt-90",binding);String physical=Json.required(ninety.data().path("aliasMap"),"physicalScope");
        var documentQuery=Json.object();documentQuery.put("id",ninety.data().path("aliasMap").path("document").asText()).put("asOf","2026-10-07T09:00:02Z").put("knownAt","2026-10-07T09:00:02Z");var documentScope=Json.object();documentScope.put("organizationId",binding.path("organizationId").asText()).put("kind","DOCUMENT").put("subjectKind","WORK").put("subjectId",work);documentQuery.set("scope",documentScope);var sourceDocument=driver.query("document90","api",actor,"getEvidence",documentQuery);capture(actions,sourceDocument);available(sourceDocument);require(sourceDocument.data().path("httpStatus").asInt()==200,"Actual evidence query must read installed document");require(sourceDocument.response().path("data").path("availability").asText().equals("AVAILABLE"),"Actual server must verify source blob availability");require(sourceDocument.response().path("data").path("sha256").equals(ninety.data().path("sourceContentSha256")),"Server document hash differs from actual source bytes");
        advance(driver,actions,"assess90-clock","2026-10-07T09:00:03Z");
        var selected=Json.object();selected.put("workId",work);
        var preAssessment=raw(driver,validator,actions,"raw-before-assess90",binding,"2026-10-07T09:00:03Z");int createdRevision=preAssessment.data().path("rawRows").path("works").get(0).path("revision").asInt();
        var assessment90=driver.invoke("assess90","api",actor,"assessGoal",envelope("assessGoal",selected,createdRevision,UUID.randomUUID().toString(),work));capture(actions,assessment90);available(assessment90);require(assessment90.data().path("httpStatus").asInt()==200,"90 assessment HTTP must succeed");require(assessment90.response().path("assessment").path("outcome").asText().equals("UNSATISFIED"),"Verified90 cannot satisfy100 goal");String firstAssessment=Json.required(assessment90.response().path("effects"),"assessmentId");
        var raw90=raw(driver,validator,actions,"raw90",binding,"2026-10-07T09:00:03Z");require(raw90.data().path("rawRows").path("works").get(0).path("status").asText().equals("ACTIVE"),"Actual Work remains ACTIVE at90");
        int revision=raw90.data().path("rawRows").path("works").get(0).path("revision").asInt();var closeSlots=selected.deepCopy();closeSlots.put("reason","FULFILLED");
        var denied90=driver.invoke("close90","api",actor,"closeWork",envelope("closeWork",closeSlots,revision,UUID.randomUUID().toString(),work));capture(actions,denied90);available(denied90);require(denied90.response().path("outcome").asText().equals("HELD")&&denied90.response().path("error").path("code").asText().equals("ASSESSMENT_NOT_CURRENT"),"FULFILLED at90 must be rejected by actual gateway");
        var duty=Json.object();duty.put("workId",work).put("sourceKind","OCCURRENCE").put("sourceId",ninety.data().path("aliasMap").path("canonical").asText()).put("sourceVersion","1").put("kind","FOLLOWUP_REVIEW").put("quantity","90").put("unit","BOX").put("scopeJson","{\"physicalScopeId\":\""+physical+"\"}").put("nextAction","검증된 후속 응답 확인").put("nextCheckAt","2026-10-08T09:00:00Z");
        var opened=driver.invoke("open-duty","api",actor,"createObligation",envelope("createObligation",duty,revision,UUID.randomUUID().toString(),work));capture(actions,opened);available(opened);require(opened.data().path("httpStatus").asInt()==200,"Actual sourced duty must open");String assignment=Json.required(opened.response().path("effects").path("responsibility"),"ID");
        evidence(root,driver,actions,"receipt-10",binding);advance(driver,actions,"assess100-clock","2026-10-07T09:00:04Z");
        var assessment100=driver.invoke("assess100","api",actor,"assessGoal",envelope("assessGoal",selected,revision,UUID.randomUUID().toString(),work));capture(actions,assessment100);available(assessment100);require(assessment100.data().path("httpStatus").asInt()==200,"100 assessment HTTP must succeed");require(assessment100.response().path("assessment").path("outcome").asText().equals("SATISFIED"),"Verified90+10 must satisfy100 goal");
        var current100=raw(driver,validator,actions,"raw-after-assess100",binding,"2026-10-07T09:00:04Z");revision=current100.data().path("rawRows").path("works").get(0).path("revision").asInt();
        var retained=driver.invoke("close100-open-duty","api",actor,"closeWork",envelope("closeWork",closeSlots,revision,UUID.randomUUID().toString(),work));capture(actions,retained);available(retained);require(retained.response().path("outcome").asText().equals("REJECTED")&&retained.response().path("error").path("code").asText().equals("UNRESOLVED_DUTY"),"Satisfied goal cannot close with unresolved responsibility");
        var beforeResolution=raw(driver,validator,actions,"raw-open-duty",binding,"2026-10-07T09:00:04Z");var assignments=beforeResolution.data().path("rawRows").path("obligations");require(assignments.size()==1&&assignments.get(0).path("status").asText().equals("OPEN"),"Rejected closure must retain actual duty");require(assignments.get(0).path("ownerId").asText().equals(aliases.path("reader").asText()),"Retained duty owner differs");require(assignments.get(0).path("nextCheckAt").isTextual(),"Retained duty next check missing");
        var dutyRoot=beforeResolution.data().path("rawRows").path("dutyRoots").get(0);var dutyScope=beforeResolution.data().path("rawRows").path("dutyScopes").get(0);require(dutyRoot.path("id").equals(assignments.get(0).path("rootId"))&&dutyScope.path("id").equals(assignments.get(0).path("scopeId")),"Independent actual root/scope binding differs from retained assignment");
        var responseBinding=binding.deepCopy();responseBinding.put("physicalScopeId",physical).put("dutyRootId",Json.required(dutyRoot,"id")).put("startQuantity",Json.required(dutyScope,"startQuantity")).put("quantity",Json.required(dutyScope,"quantity")).put("unit",Json.required(dutyRoot,"unit"));var completed=evidence(root,driver,actions,"response-review",responseBinding);
        var review=Json.object();review.put("claimId",completed.data().path("aliasMap").path("claim").asText()).put("basisDocumentId",completed.data().path("aliasMap").path("document").asText()).put("physicalScopeId",physical).put("policyVersion","fixture-v1").put("sourceIdentity","native-fixture-response-review:s2-native-response-review:1").put("quantity",responseBinding.path("quantity").asText()).put("unit",responseBinding.path("unit").asText()).put("effectiveFrom","2026-10-07T08:59:59Z").put("reason","실제 duty root와 원본 응답 범위 대조");
        var matched=driver.invoke("review-response","api",actor,"matchSourceIdentity",envelope("matchSourceIdentity",review,1,UUID.randomUUID().toString(),work));capture(actions,matched);available(matched);require(matched.data().path("httpStatus").asInt()==200&&matched.response().path("evidenceStatus").asText().equals("MATCHED"),"Actual source review must match original duty range");
        var link=Json.object();link.put("reconciliationId",Json.required(matched.response(),"id"));var linked=driver.invoke("publish-response","api",actor,"linkCanonicalOccurrence",envelope("linkCanonicalOccurrence",link,1,UUID.randomUUID().toString(),work));capture(actions,linked);available(linked);require(linked.data().path("httpStatus").asInt()==200&&linked.response().path("evidenceStatus").asText().equals("VERIFIED_RECORD_ONLY"),"Actual review link must publish trusted canonical coverage");
        var linkedRaw=raw(driver,validator,actions,"raw-reviewed-response",binding,"2026-10-07T09:00:04Z");revision=linkedRaw.data().path("rawRows").path("works").get(0).path("revision").asInt();var reassessed=driver.invoke("reassess-after-response","api",actor,"assessGoal",envelope("assessGoal",selected,revision,UUID.randomUUID().toString(),work));capture(actions,reassessed);available(reassessed);require(reassessed.data().path("httpStatus").asInt()==200&&reassessed.response().path("assessment").path("outcome").asText().equals("SATISFIED"),"Actual linked evidence invalidation must be reassessed before closure");
        var resolve=Json.object();resolve.put("assignmentId",assignment).put("evidenceId",Json.required(linked.response(),"id"));
        var resolved=driver.invoke("resolve-duty","api",actor,"resolveObligation",envelope("resolveObligation",resolve,0,UUID.randomUUID().toString(),work));capture(actions,resolved);available(resolved);require(resolved.data().path("httpStatus").asInt()==200,"Real verified response must resolve duty");
        var resolvedRaw=raw(driver,validator,actions,"raw-resolved-duty",binding,"2026-10-07T09:00:04Z");revision=resolvedRaw.data().path("rawRows").path("works").get(0).path("revision").asInt();
        var close=driver.invoke("close100-resolved","api",actor,"closeWork",envelope("closeWork",closeSlots,revision,UUID.randomUUID().toString(),work));capture(actions,close);available(close);require(close.data().path("httpStatus").asInt()==200,"Satisfied Work with settled duty must close");
        var finalRaw=raw(driver,validator,actions,"raw-final",binding,"2026-10-07T09:00:04Z");java.math.BigDecimal actualReceipts=java.math.BigDecimal.ZERO;int receiptRows=0;for(JsonNode row:finalRaw.data().path("rawRows").path("canonicalOccurrences"))if(row.path("kind").asText().equals("RECEIPT")){actualReceipts=actualReceipts.add(new java.math.BigDecimal(row.path("quantity").asText()));receiptRows++;}require(receiptRows==2&&actualReceipts.compareTo(new java.math.BigDecimal("100"))==0,"Independent actual canonical90+10 source rows must total100");
        var coverage=finalRaw.data().path("rawRows").path("completionCoverages");require(coverage.size()==1&&coverage.get(0).path("rootId").equals(dutyRoot.path("id"))&&coverage.get(0).path("originalHash").equals(completed.data().path("sourceContentSha256")),"Independent coverage must bind actual root and original bytes");require(finalRaw.data().path("rawRows").path("resolutionCredits").size()==1,"Independent actual resolution credit required");
        require(finalRaw.data().path("rawRows").path("works").get(0).path("status").asText().equals("CLOSED"),"Independent canonical Work must be CLOSED");require(finalRaw.data().path("rawRows").path("obligations").get(0).path("status").asText().equals("RESOLVED"),"Resolved duty history must remain");boolean preserved=false;for(JsonNode row:finalRaw.data().path("rawRows").path("assessments"))if(row.path("id").asText().equals(firstAssessment))preserved=row.path("outcome").asText().equals("UNSATISFIED");require(preserved,"Immutable90 assessment must remain UNSATISFIED");require(!finalRaw.data().path("rawRows").path("assessmentInputs").isEmpty(),"Independent input snapshots required");
        var query=Json.object();var scope=Json.object();scope.put("organizationId",binding.path("organizationId").asText()).put("itemId",binding.path("itemId").asText());query.set("scope",scope);query.put("asOf","2026-10-07T09:00:04Z").put("knownAt","2026-10-07T09:00:04Z").put("id",binding.path("itemId").asText());var noun=driver.query("noun-final","api",actor,"getObject",query);capture(actions,noun);available(noun);require(noun.data().path("httpStatus").asInt()==200,"Actual noun read must succeed");query.put("id",work);query.put("snapshotRef",Json.required(noun.response(),"snapshotRevision"));var verb=driver.query("verb-final","api",actor,"getWork",query);capture(actions,verb);available(verb);require(verb.data().path("httpStatus").asInt()==200,"Actual same-snapshot Work read must succeed");require(noun.response().path("snapshotRevision").equals(verb.response().path("snapshotRevision")),"Noun/verb world snapshot differs");require(noun.response().path("data").path("assessmentReferences").equals(verb.response().path("data").path("assessmentReferences")),"Noun/verb immutable assessment histories differ");
    }
    private static StepResult evidence(Path root,ActualAcceptanceDriver driver,ObjectNode actions,String name,JsonNode binding)throws Exception {String ref="verification/actual/s2/"+name+".json";var bundle=Json.object();bundle.put("fixturePhase","EVIDENCE").put("fixtureHash",Json.sha256(root.resolve(ref)));bundle.set("fixture",Json.read(root.resolve(ref)));bundle.set("binding",binding);if(name.equals("response-review")){var original=Json.object();for(String field:List.of("dutyRootId","startQuantity","quantity","unit"))original.put(field,Json.required(binding,field));bundle.set("preparedOriginal",original);}var result=driver.installFixture(name,bundle);capture(actions,result);available(result);require(result.data().path("sourceContentSha256").equals(result.data().path("blobReadbackSha256")),"Source blob hash differs from independent readback");return result;}
    private static void advance(ActualAcceptanceDriver driver,ObjectNode actions,String name,String instant){var control=Json.object();control.put("type","clock").put("operation","advanceTo");var parameters=Json.object();parameters.put("instant",instant);control.set("parameters",parameters);var result=driver.control(name,control);capture(actions,result);available(result);}
    private static StepResult raw(ActualAcceptanceDriver driver,ContractValidator validator,ObjectNode actions,String name,JsonNode binding,String time)throws Exception {var request=Json.object();var scope=Json.object();for(String field:List.of("organizationId","workId","itemId"))scope.set(field,binding.path(field));request.set("scope",scope);request.put("asOf",time).put("knownAt",time);request.set("sources",Json.parse("[\"works\",\"goals\",\"assessments\",\"assessmentInputs\",\"obligations\",\"canonicalOccurrences\",\"documents\",\"dutyRoots\",\"dutyScopes\",\"completionCoverages\",\"resolutionCredits\"]"));var result=driver.observe(name,request);capture(actions,result);available(result);validator.result(result,"observe");return result;}
    private static ObjectNode envelope(String capability,JsonNode slots,int revision,String key,String subject) {
        var intent=Json.object();intent.put("intentKind","COMMAND").put("definitionVersion","definition-v1").put("capabilityId",capability).put("expectedRevision",revision).put("commandIdempotencyKey",key);intent.set("slots",slots);intent.set("provenance",Json.object());var refs=Json.array();var ref=Json.object();ref.put("type",Set.of("createDraft","createWork").contains(capability)?"TradeItem":"Work").put("id",subject);refs.add(ref);intent.set("subjectRefs",refs);return intent;
    }
    private static void capture(ObjectNode actions,StepResult result){actions.set(result.actionId(),result.toJson());}
    private static final class Unavailable extends RuntimeException {Unavailable(String reason){super(reason);}}
    private static void available(StepResult result){if(result.driverStatus()!=StepResult.DriverStatus.EXECUTED)throw new Unavailable(result.reason());}
    private static void require(boolean condition,String message){if(!condition)throw new AssertionError(message);assertions++;}
}
