package com.mulino.application.evidence;
import com.mulino.application.core.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
class CompletionCoverageGatewayTest extends EvidenceGatewayTest {
 @Autowired com.mulino.application.responsibility.ResponsibilityService responsibility;
 @Autowired VerifiedResponsibilityCompletionEvidence completion;
 @BeforeEach void reviewGrants(){for(String cap:List.of("matchSourceIdentity","linkCanonicalOccurrence","resolveEvidenceConflict")){jdbc.update("INSERT INTO mulino_identity_CapabilityAssignments(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,?,'ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,cap,ORG);jdbc.update("INSERT INTO mulino_identity_GrantActions VALUES(?,?,?) ON CONFLICT DO NOTHING",ORG,GRANT,cap);}}
 String[] rootFixture(){String work=uuid(),root=uuid(),physical=uuid(),firstScope=uuid(),secondScope=uuid(),firstAssignment=uuid(),secondAssignment=uuid();String definition=jdbc.queryForObject("SELECT ID FROM mulino_definitions_DefinitionVersions WHERE organizationId=? AND version='evidence-gateway-v1'",String.class,ORG);
  jdbc.update("INSERT INTO mulino_work_read_Works(organizationId,ID,createdAt,recordedAt,effectiveAt,itemId,definitionVersionId,kind,status,ownerId,supervisorId) VALUES(?,?,now(),now(),now(),?,?,'FOLLOWUP','ACTIVE',?,?)",ORG,work,ITEM,definition,ACTOR,ACTOR);String scopeJson="{\"physicalScopeId\":\""+physical+"\"}";
  new TransactionTemplate(tx).execute(status->{jdbc.update("INSERT INTO mulino_responsibility_Roots(organizationId,ID,createdAt,recordedAt,dutyKey,sourceId,sourceKind,sourceVersion,kind,scopeJson,quantity,unit) VALUES(?,?,now(),now(),?,?,'EVENT','1','FOLLOWUP_REVIEW',?,100,'BOX')",ORG,root,uuid(),uuid(),scopeJson);
   for(Object[] part:List.of(new Object[]{firstScope,firstAssignment,0},new Object[]{secondScope,secondAssignment,50})){jdbc.update("INSERT INTO mulino_responsibility_Scopes(organizationId,ID,createdAt,recordedAt,rootId,startQuantity,quantity,unit,scopeJson) VALUES(?,?,now(),now(),?,?,50,'BOX',?)",ORG,part[0],root,part[2],scopeJson);jdbc.update("INSERT INTO mulino_work_read_ObligationReferences(organizationId,ID,createdAt,recordedAt,effectiveAt,workId,kind,status,ownerId,supervisorId,nextAction,nextCheckAt,quantity,unit,scopeJson,rootId,scopeId,valid) VALUES(?,?,now(),now(),now(),?,'FOLLOWUP_REVIEW','OPEN',?,?,'Check completion',now()+interval '1 hour',50,'BOX',?,?,?,true)",ORG,part[1],work,ACTOR,ACTOR,scopeJson,root,part[0]);}return null;});return new String[]{work,root,physical,firstAssignment,secondAssignment};
 }
 Map<String,Object> workEnvelope(String cap,String key,Map<String,Object> slots,Integer rev,String work){var result=new LinkedHashMap<>(envelope(cap,key,slots,rev));result.put("subjectRefs",List.of(Map.of("type","Work","id",work)));if(cap.equals("matchSourceIdentity")||cap.equals("linkCanonicalOccurrence"))result.put("intentKind","COMMAND");return result;}
 String completed(String[] duty,String quantity)throws Exception{
  String bytes=new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(Map.of("dutyRootId",duty[1],"startQuantity","0","quantity",quantity,"unit","BOX"));var doc=new LinkedHashMap<String,Object>();doc.put("subject",Map.of("kind","WORK","id",duty[0]));doc.put("sourceNamespace","warehouse");doc.put("sourceReference","completion.json");doc.put("mediaType","application/json");doc.put("expectedHash",com.mulino.adapters.blob.LocalBlobStore.hash(bytes.getBytes()));doc.put("provenance","SYNTHETIC original completion");doc.put("contentBase64",Base64.getEncoder().encodeToString(bytes.getBytes()));var attached=execute(workEnvelope("attachEvidence","completion-original",doc,null,duty[0]));assertEquals("APPLIED",attached.get("outcome"));
  var event=slots(bytes);event.put("subject",Map.of("kind","WORK","id",duty[0]));event.put("kind","RESPONSE_COMPLETED");event.put("externalEventId","complete");event.put("documentId",attached.get("id"));event.put("assertion","Completed exact duty range");event.put("quantity",quantity);event.put("unit","BOX");var recorded=execute(workEnvelope("recordActivity","completion-record",event,null,duty[0]));assertEquals("APPLIED",recorded.get("outcome"));
  var review=Map.<String,Object>of("claimId",recorded.get("claimId"),"basisDocumentId",attached.get("id"),"physicalScopeId",duty[2],"policyVersion","synthetic-v1","sourceIdentity","warehouse:complete:1","quantity",quantity,"unit","BOX","effectiveFrom",OCCURRED.toString(),"reason","Scoped human reviewed original root and range");var matched=execute(workEnvelope("matchSourceIdentity","completion-review",review,1,duty[0]));assertEquals("APPLIED",matched.get("outcome"));assertEquals("MATCHED",matched.get("evidenceStatus"));var linked=execute(workEnvelope("linkCanonicalOccurrence","completion-link",Map.of("reconciliationId",matched.get("id")),1,duty[0]));assertEquals("APPLIED",linked.get("outcome"));assertEquals("VERIFIED_RECORD_ONLY",linked.get("evidenceStatus"));return linked.get("id").toString();
 }
 void resolve(String assignment,String canonical){request(()->new TransactionTemplate(tx).execute(status->responsibility.settle(auth.context(null,null),Map.of("assignmentId",assignment,"evidenceId",canonical),false)));}
 @Test void trustedPartialFiftyCompletesOnlyItsExactDutyLeaf()throws Exception{var duty=rootFixture();String canonical=completed(duty,"50");var coverage=request(()->new TransactionTemplate(tx).execute(status->completion.requireCoverage(auth.context(null,null),canonical)));assertEquals(duty[1],coverage.rootId());assertEquals(0,coverage.quantity().compareTo(new java.math.BigDecimal("50")));resolve(duty[3],canonical);assertThrows(DomainError.class,()->resolve(duty[4],canonical));assertEquals("RESOLVED",jdbc.queryForObject("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,duty[3]));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,duty[4]));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_responsibility_ResolutionCredits",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_evidence_CompletionCoverages",Integer.class));}
 @Test void trustedFullHundredCreditsTwoDisjointFiftyLeavesOnlyOnce()throws Exception{var duty=rootFixture();String canonical=completed(duty,"100");resolve(duty[3],canonical);resolve(duty[4],canonical);assertThrows(DomainError.class,()->resolve(duty[3],canonical));assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM mulino_responsibility_ResolutionCredits",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_responsibility_ResolutionCredits",java.math.BigDecimal.class).compareTo(new java.math.BigDecimal("100")));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantityMovements",Integer.class));}
}
