package com.mulino.application.evidence;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.mulino.application.core.*;
import com.mulino.application.policy.PolicyCommandGuard;
import com.mulino.domain.evidence.*;
import com.mulino.adapters.blob.LocalBlobStore;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.transaction.support.TransactionTemplate;
import static com.mulino.domain.evidence.EvidenceTypes.*;
import static com.mulino.application.evidence.EvidenceRecords.*;
/** Public original→claim→match→canonical and common gateway, real PG quantities and auth.
 * The inherited fixture isolates policy selection with a mock; domain ADMIN authority is real. */
class RecallGatewayPostgresTest extends RecallGatewayFixture {
 static final List<String> CAPS=List.of("openInvestigation","proposeRecall","approveRecall","recordRecallNotice","recordRecovery","closeRecall","getRecall","getRecalls","traceRecall");
 String segment,basis,investigation,scope,scopeHash,approval;int version;
 @BeforeEach void recallFixture() throws Exception{
  for(String cap:CAPS){jdbc.update("INSERT INTO mulino_identity_CapabilityAssignments(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,?,'ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,cap,ORG);jdbc.update("INSERT INTO mulino_identity_GrantActions VALUES(?,?,?)",ORG,GRANT,cap);}
  jdbc.update("INSERT INTO mulino_identity_ManagementAuthorities(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,'approveRecall','ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,ORG);
  var mapper=new com.fasterxml.jackson.databind.ObjectMapper();String body=jdbc.queryForObject("SELECT content FROM mulino_definitions_DefinitionVersions WHERE organizationId=? LIMIT 1",String.class,ORG);var d=mapper.readValue(body,com.mulino.domain.definitions.Definition.class);var caps=new ArrayList<>(d.capabilities());for(String cap:CAPS)caps.add(new com.mulino.domain.definitions.Definition.Capability(cap,"1.0.0","core-v1","1.0.0","1.0.0",List.of()));var verbs=new ArrayList<>(d.verbs());for(String cap:CAPS)verbs.add(new com.mulino.domain.definitions.Definition.Verb(cap,Set.of("recordRecovery","recordRecallNotice").contains(cap)?"RECORD":"COMMAND",cap,"ACTIVE",Map.of()));var updated=new com.mulino.domain.definitions.Definition(d.organizationId(),d.id(),d.version(),d.parentVersionId(),d.state(),d.contentHash(),d.evaluatorVersion(),d.schemaVersion(),d.nouns(),d.attributes(),verbs,d.relations(),d.goals(),caps);String content=mapper.writeValueAsString(updated);jdbc.update("UPDATE mulino_definitions_DefinitionVersions SET content=?,contentHash=? WHERE organizationId=? AND ID=?",content,com.mulino.domain.definitions.DefinitionRepository.sha256(content),ORG,d.id());
  when(localPolicy.rule(any(),anyString())).thenReturn(new PolicyCommandGuard.Selection(Map.of("effectClass","RECALL"),"a".repeat(64),uuid(),"synthetic-v1"));
  var input=provisional(uuid(),"60",true,null);basis=input.event();var received=confirm(input,canonical(input,null),uuid());assertEquals("APPLIED",received.get("outcome"),received.toString());segment=((Map<?,?>)received.get("effects")).get("segmentId").toString();
 }
 Map<String,Object> recall(String cap,Map<String,Object> slots){var cmd=new LinkedHashMap<>(command(cap,uuid(),slots,null));cmd.put("intentKind",Set.of("recordRecovery","recordRecallNotice").contains(cap)?"RECORD":"COMMAND");return request(()->gateway.execute(cmd));}
 Map<String,Object> effects(Map<String,Object>x){assertEquals("APPLIED",x.get("outcome"),x.toString());return (Map<String,Object>)x.get("effects");}
 Map<String,Object>values(Object... kv){var result=new LinkedHashMap<String,Object>();for(int n=0;n<kv.length;n+=2)result.put(kv[n].toString(),kv[n+1]);return result;}
 void open(){investigation=effects(recall("openInvestigation",values("segmentId",segment,"lotId",LOT,"itemId",ITEM,"workId",WORK,"startQuantity","0","quantity","60","unit","BOX","basisEvidenceId",basis,"occurredAt",Instant.now().minusSeconds(1).toString(),"nextAction","Investigate candidate LOT","nextCheckAt",Instant.now().plusSeconds(7200).toString()))).get("investigationId").toString();}
 void propose(String q){var p=effects(recall("proposeRecall",Map.of("investigationId",investigation,"startQuantity","0","quantity",q,"unit","BOX","reason","Exact candidate recall scope")));scope=p.get("scopeId").toString();scopeHash=p.get("scopeHash").toString();version=((Number)p.get("scopeVersion")).intValue();}
 void approve(){approval=effects(recall("approveRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"decision","APPROVE","validUntil",Instant.now().plusSeconds(3600).toString()))).get("approvalId").toString();}
 record Proof(String canonical,Map<String,Object> slots){}
 Proof proof(String kind,String start,String qty,String source,Map<String,Object> extra){String eventKind="RECALL_"+switch(kind){case "RECOVERED"->"RECOVERY";case "DISPOSED"->"DISPOSAL";default->kind;};String actual=uuid();Instant occurred=Instant.now().minusSeconds(1).truncatedTo(java.time.temporal.ChronoUnit.MICROS);var p=new LinkedHashMap<String,Object>();p.putAll(Map.of("scopeId",scope,"scopeVersion",version,"scopeHash",scopeHash,"rootSegmentId",segment,"itemId",ITEM,"lotId",LOT,"startQuantity",start,"quantity",qty,"unit","BOX","actualEventId",actual));p.putAll(Map.of("eventKind",eventKind,"occurredAt",occurred.toString(),"currentPlaceId",PLACE));if(source!=null)p.put("sourceSegmentId",source);p.putAll(extra);String json;try{json=new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(p);}catch(Exception e){throw new IllegalStateException(e);}
  var subject=new Subject(SubjectKind.RECALL_SCOPE,scope);String doc=request(()->records.attachDocument(new DocumentInput(subject,"warehouse",uuid(),"application/json",LocalBlobStore.hash(json.getBytes()),"SYNTHETIC recall fixture",null),json.getBytes())).get("id").toString();String event=request(()->records.recordActivity(new EventInput(subject,eventKind,"warehouse",uuid(),"1",new EffectiveTime(occurred,null,"UTC","INSTANT"),ValueState.KNOWN,json,null,null))).get("id").toString();String claim=request(()->records.recordClaim(new ClaimInput(event,doc,"Recall original",qty,"BOX",ValueState.KNOWN,null))).get("id").toString();String canonical=request(()->new TransactionTemplate(tx).execute(status->{var evt=repository.require("Events",ORG,event);var c=auth.context(Instant.now(),Instant.now());var matched=reconciliation.match(c,new EvidenceReconciliation.Review(claim,doc,scope,null,"synthetic-v1",evt.get("sourceNamespace")+":"+evt.get("externalEventId")+":"+evt.get("sourceVersion"),qty,"BOX",occurred,"Original exact recall range checked"),"matchSourceIdentity");assertEquals("MATCHED",matched.get("outcome"),matched.toString());return reconciliation.link(c,matched.get("id").toString()).get("id").toString();}));
  var slots=new LinkedHashMap<String,Object>();for(String k:List.of("scopeId","scopeHash","rootSegmentId","actualEventId","startQuantity","quantity","unit","currentPlaceId","sourceSegmentId","reason"))if(p.get(k)!=null)slots.put(k,p.get(k));slots.putAll(Map.of("approvalId",approval,"canonicalOccurrenceId",canonical,"kind",kind));return new Proof(canonical,slots);
 }
 @Test void exact25RecoveredThenSame25DisposedLeavesUnknown25AndCannotClose(){open();propose("50");approve();assertEquals(3,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_Restrictions WHERE category='RECALL_INVESTIGATION' AND state='ACTIVE'",Integer.class));assertEquals("CANDIDATE",jdbc.queryForObject("SELECT impactState FROM mulino_trade_recall_Investigations WHERE ID=?",String.class,investigation));var recovery=proof("RECOVERED","0","25",segment,Map.of());var recovered=effects(recall("recordRecovery",recovery.slots()));String leaf=recovered.get("currentSegmentId").toString();assertEquals("25",((Map<?,?>)recovered.get("partition")).get("RECOVERED").toString());var disposal=proof("DISPOSED","0","25",leaf,Map.of());var disposed=effects(recall("recordRecovery",disposal.slots()));var partition=(Map<?,?>)disposed.get("partition");assertEquals("25",partition.get("ACCOUNTED").toString());assertEquals("25",partition.get("UNKNOWN").toString());assertEquals(0,new java.math.BigDecimal("35").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantitySegments WHERE retiredAt IS NULL",java.math.BigDecimal.class)));assertNotEquals("APPLIED",recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",disposal.canonical(),"partitionHash",disposed.get("partitionHash"))).get("outcome"));assertEquals(0,count("mulino_trade_recall_Closures"));assertNotEquals("APPLIED",recall("recordRecovery",recovery.slots()).get("outcome"));assertEquals(2,count("mulino_trade_recall_Actions"));}
 @Test void exceptionNeedsAdminAndRetainsHumanResidualAtClosure(){open();propose("50");approve();var recovery=proof("RECOVERED","0","25",segment,Map.of());String leaf=effects(recall("recordRecovery",recovery.slots())).get("currentSegmentId").toString();effects(recall("recordRecovery",proof("DISPOSED","0","25",leaf,Map.of()).slots()));var exception=proof("EXCEPTION","25","25",null,Map.of("reason","Verified unreachable customer evidence and explicit ADMIN exception"));var result=effects(recall("recordRecovery",exception.slots()));assertEquals("0",((Map<?,?>)result.get("partition")).get("UNKNOWN").toString());String duty=result.get("residualDutyId").toString();assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,duty));var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",result.get("partitionHash")));var closed=effects(recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",result.get("partitionHash"))));assertEquals(true,closed.get("residualResponsibilityRetained"));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,duty));}
 @Test void changedScopeInvalidatesApprovalAndAdminCannotBypassIndependentQc(){open();propose("50");approve();String previousScope=scope,previousHash=scopeHash;String oldApproval=approval;propose("40");assertNotEquals("APPLIED",recall("approveRecall",Map.of("scopeId",previousScope,"scopeHash",previousHash,"decision","APPROVE","validUntil",Instant.now().plusSeconds(600).toString())).get("outcome"));approve();var rec=proof("RECOVERED","0","25",segment,Map.of());var moved=effects(recall("recordRecovery",rec.slots())).get("currentSegmentId").toString();jdbc.update("INSERT INTO mulino_inventory_Restrictions(organizationId,ID,revision,createdAt,recordedAt,controlScope,action,state,validFrom,validUntil,segmentId,startQuantity,quantity,unit,category,workId,commandId,policyHash) SELECT organizationId,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,controlScope,'ALL','ACTIVE',CURRENT_TIMESTAMP-INTERVAL '1 second',CURRENT_TIMESTAMP+INTERVAL '1 day',ID,0,20,unit,'QC',?,?,? FROM mulino_inventory_QuantitySegments WHERE ID=?",uuid(),WORK,uuid(),"a".repeat(64),moved);var disposal=proof("DISPOSED","0","25",moved,Map.of());assertNotEquals("APPLIED",recall("recordRecovery",disposal.slots()).get("outcome"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantityMovements WHERE kind='DISPOSE'",Integer.class));jdbc.update("UPDATE mulino_identity_ManagementAuthorities SET revokedAt=CURRENT_TIMESTAMP WHERE organizationId=?",ORG);assertNotEquals("APPLIED",recall("recordRecovery",proof("SAFE","25","15",null,Map.of()).slots()).get("outcome"));}
 @Test void simulatedPostconditionFailureRollsBackRecallRecovery(){open();propose("50");approve();var p=proof("RECOVERED","0","25",segment,Map.of());int before=count("mulino_inventory_QuantitySegments");doThrow(new IllegalStateException("audit-fail")).when(localPolicy).verifyCommit(any(),eq("recordRecovery"),anyString(),any(),anyMap(),eq(false));assertThrows(IllegalStateException.class,()->recall("recordRecovery",p.slots()));assertEquals(before,count("mulino_inventory_QuantitySegments"));assertEquals(0,count("mulino_trade_recall_Actions"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantitySegments WHERE retiredAt IS NOT NULL",Integer.class));}
 @Test void malformedOriginalAndPartialOutOfScopeCannotCreateCanonicalOrEffect(){open();propose("50");approve();assertThrows(AssertionError.class,()->proof("RECOVERED","40","25",segment,Map.of()));assertEquals(0,count("mulino_trade_recall_Actions"));}
}
