package com.mulino.application.evidence;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.mulino.application.core.*;
import com.mulino.application.policy.PolicyCommandGuard;
import com.mulino.domain.evidence.*;
import com.mulino.adapters.blob.LocalBlobStore;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.transaction.support.TransactionTemplate;
import static com.mulino.domain.evidence.EvidenceTypes.*;
import static com.mulino.application.evidence.EvidenceRecords.*;
/** Public original→claim→match→canonical and common gateway, real PG quantities and auth.
 * The inherited fixture isolates policy selection with a mock; domain ADMIN authority is real. */
class RecallGatewayPostgresTest extends RecallGatewayFixture {
 static final List<String> CAPS=List.of("openInvestigation","proposeRecall","approveRecall","recordRecallNotice","recordRecovery","closeRecall","getRecall","getRecalls","traceRecall");
 @org.springframework.beans.factory.annotation.Autowired com.mulino.application.trade.recall.RecallCommands recallCommands;
 @org.springframework.beans.factory.annotation.Autowired com.mulino.application.responsibility.ResponsibilityService responsibilityService;
 String segment,basis,investigation,scope,scopeHash,approval;int version;
 @BeforeEach void recallFixture() throws Exception{
  for(String cap:CAPS){jdbc.update("INSERT INTO mulino_identity_CapabilityAssignments(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,?,'ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,cap,ORG);jdbc.update("INSERT INTO mulino_identity_GrantActions VALUES(?,?,?)",ORG,GRANT,cap);}
  jdbc.update("INSERT INTO mulino_identity_ManagementAuthorities(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,'approveRecall','ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,ORG);
  // Plan §7.1: recall disposal is a stock decrease that also needs the current human MANAGER confirmation.
  jdbc.update("INSERT INTO mulino_identity_CapabilityAssignments(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,'disposeQuantity','ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,ORG);jdbc.update("INSERT INTO mulino_identity_GrantActions VALUES(?,?,'disposeQuantity')",ORG,GRANT);
  jdbc.update("INSERT INTO mulino_identity_ManagementAuthorities(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,'disposeQuantity','ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,ORG);
  var mapper=new com.fasterxml.jackson.databind.ObjectMapper();String body=jdbc.queryForObject("SELECT content FROM mulino_definitions_DefinitionVersions WHERE organizationId=? LIMIT 1",String.class,ORG);var d=mapper.readValue(body,com.mulino.domain.definitions.Definition.class);var caps=new ArrayList<>(d.capabilities());for(String cap:CAPS)caps.add(new com.mulino.domain.definitions.Definition.Capability(cap,"1.0.0","core-v1","1.0.0","1.0.0",List.of()));var verbs=new ArrayList<>(d.verbs());for(String cap:CAPS)verbs.add(new com.mulino.domain.definitions.Definition.Verb(cap,Set.of("recordRecovery","recordRecallNotice").contains(cap)?"RECORD":"COMMAND",cap,"ACTIVE",Map.of()));var updated=new com.mulino.domain.definitions.Definition(d.organizationId(),uuid(),"recall-v1",d.id(),d.state(),d.contentHash(),d.evaluatorVersion(),d.schemaVersion(),d.nouns(),d.attributes(),verbs,d.relations(),d.goals(),caps);String content=mapper.writeValueAsString(updated);jdbc.update("INSERT INTO mulino_definitions_DefinitionVersions(organizationId,ID,createdAt,version,parentVersionId,state,contentHash,content,evaluatorVersion,schemaVersion) VALUES(?,?,CURRENT_TIMESTAMP,?,?,'PUBLISHED',?,?,?,?)",ORG,updated.id(),updated.version(),updated.parentVersionId(),com.mulino.domain.definitions.DefinitionRepository.sha256(content),content,"core-v1","1.0.0");
  when(localPolicy.rule(any(),anyString())).thenReturn(new PolicyCommandGuard.Selection(Map.of("effectClass","RECALL"),"a".repeat(64),uuid(),"synthetic-v1"));
  var input=provisional(uuid(),"60",true,null);basis=input.event();var received=confirm(input,canonical(input,null),uuid());assertEquals("APPLIED",received.get("outcome"),received.toString());segment=((Map<?,?>)received.get("effects")).get("segmentId").toString();
 }
 Map<String,Object> recall(String cap,Map<String,Object> slots){var cmd=new LinkedHashMap<>(command(cap,uuid(),slots,null));cmd.put("definitionVersion","recall-v1");cmd.put("intentKind",Set.of("recordRecovery","recordRecallNotice").contains(cap)?"RECORD":"COMMAND");return request(()->{var c=auth.context(Instant.now(),Instant.now());try{cmd.put("expectedRevision",recallCommands.prepare(c,cmd).currentRevision());}catch(DomainError e){return e.response();}return gateway.execute(cmd);});}
 Map<String,Object> effects(Map<String,Object>x){assertEquals("APPLIED",x.get("outcome"),x.toString());return (Map<String,Object>)x.get("effects");}
 Map<String,Object>values(Object... kv){var result=new LinkedHashMap<String,Object>();for(int n=0;n<kv.length;n+=2)result.put(kv[n].toString(),kv[n+1]);return result;}
 void open(){investigation=effects(recall("openInvestigation",values("segmentId",segment,"lotId",LOT,"itemId",ITEM,"workId",WORK,"startQuantity","0","quantity","60","unit","BOX","basisEvidenceId",basis,"occurredAt",Instant.now().minusSeconds(1).toString(),"nextAction","Investigate candidate LOT","nextCheckAt",Instant.now().plusSeconds(7200).toString()))).get("investigationId").toString();}
 void propose(String q){var p=effects(recall("proposeRecall",Map.of("investigationId",investigation,"startQuantity","0","quantity",q,"unit","BOX","reason","Exact candidate recall scope")));scope=p.get("scopeId").toString();scopeHash=p.get("scopeHash").toString();version=((Number)p.get("scopeVersion")).intValue();}
 void approve(){approval=effects(recall("approveRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"decision","APPROVE","validUntil",Instant.now().plusSeconds(3600).toString()))).get("approvalId").toString();}
 record Proof(String canonical,Map<String,Object> slots){}
 Proof proof(String kind,String start,String qty,String source,Map<String,Object> extra){String eventKind="RECALL_"+switch(kind){case "RECOVERED"->"RECOVERY";case "DISPOSED"->"DISPOSAL";default->kind;};String actual=uuid();Instant occurred=Instant.now().minusSeconds(1).truncatedTo(java.time.temporal.ChronoUnit.MICROS);var p=new LinkedHashMap<String,Object>();p.putAll(Map.of("scopeId",scope,"scopeVersion",version,"scopeHash",scopeHash,"rootSegmentId",segment,"itemId",ITEM,"lotId",LOT,"startQuantity",start,"quantity",qty,"unit","BOX","actualEventId",actual));p.putAll(Map.of("eventKind",eventKind,"occurredAt",occurred.toString(),"currentPlaceId",PLACE));if(source!=null)p.put("sourceSegmentId",source);p.putAll(extra);String json;try{json=new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(p);}catch(Exception e){throw new IllegalStateException(e);}
  var subject=new Subject(SubjectKind.RECALL_SCOPE,scope);String doc=request(()->records.attachDocument(new DocumentInput(subject,"warehouse",uuid(),"application/json",LocalBlobStore.hash(json.getBytes()),"SYNTHETIC recall fixture",null),json.getBytes())).get("id").toString();String event=request(()->records.recordActivity(new EventInput(subject,eventKind,"warehouse",uuid(),"1",new EffectiveTime(occurred,null,"UTC","INSTANT"),ValueState.KNOWN,json,null,null))).get("id").toString();String claim=request(()->records.recordClaim(new ClaimInput(event,doc,"Recall original",qty,"BOX",ValueState.KNOWN,null))).get("id").toString();String canonical=request(()->new TransactionTemplate(tx).execute(status->{var evt=repository.require("Events",ORG,event);var c=auth.context(Instant.now(),Instant.now());var matched=reconciliation.match(c,new EvidenceReconciliation.Review(claim,doc,scope,null,"synthetic-v1",evt.get("sourceNamespace")+":"+evt.get("externalEventId")+":"+evt.get("sourceVersion"),qty,"BOX",occurred,"Original exact recall range checked"),"matchSourceIdentity");assertEquals("MATCHED",matched.get("outcome"),matched.toString());return reconciliation.link(c,matched.get("id").toString()).get("id").toString();}));
  var slots=new LinkedHashMap<String,Object>();for(String k:List.of("scopeId","scopeHash","rootSegmentId","actualEventId","startQuantity","quantity","unit","currentPlaceId","sourceSegmentId","reason"))if(p.get(k)!=null)slots.put(k,p.get(k));slots.putAll(Map.of("approvalId",approval,"canonicalOccurrenceId",canonical,"kind",kind));return new Proof(canonical,slots);
 }
 @Test void exact25RecoveredThenSame25DisposedLeavesUnknown25AndCannotClose(){open();propose("50");approve();assertEquals(3,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_Restrictions WHERE category='RECALL_INVESTIGATION' AND state='ACTIVE'",Integer.class));assertEquals("CANDIDATE",jdbc.queryForObject("SELECT impactState FROM mulino_trade_recall_Investigations WHERE ID=?",String.class,investigation));var recovery=proof("RECOVERED","0","25",segment,Map.of());var recovered=effects(recall("recordRecovery",recovery.slots()));String leaf=recovered.get("currentSegmentId").toString();assertEquals("25",((Map<?,?>)recovered.get("partition")).get("RECOVERED").toString());var disposal=proof("DISPOSED","0","25",leaf,Map.of());var disposed=effects(recall("recordRecovery",disposal.slots()));var partition=(Map<?,?>)disposed.get("partition");assertEquals("25",partition.get("ACCOUNTED").toString());assertEquals("25",partition.get("UNKNOWN").toString());assertEquals(0,new java.math.BigDecimal("35").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantitySegments WHERE retiredAt IS NULL",java.math.BigDecimal.class)));assertNotEquals("APPLIED",recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",disposal.canonical(),"partitionHash",disposed.get("partitionHash"))).get("outcome"));assertEquals(0,count("mulino_trade_recall_Closures"));var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",disposed.get("partitionHash")));var unknown=recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",disposed.get("partitionHash")));assertEquals("HELD",unknown.get("outcome"),unknown.toString());assertEquals("RECALL_RESIDUAL_UNKNOWN",((Map<?,?>)unknown.get("error")).get("code"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_recall_Closures WHERE investigationId=?",Integer.class,investigation));assertNotEquals("APPLIED",recall("recordRecovery",recovery.slots()).get("outcome"));assertEquals(2,count("mulino_trade_recall_Actions"));}
 @Test void exceptionNeedsAdminAndRetainsHumanResidualAtClosure(){open();propose("50");approve();var recovery=proof("RECOVERED","0","25",segment,Map.of());String leaf=effects(recall("recordRecovery",recovery.slots())).get("currentSegmentId").toString();effects(recall("recordRecovery",proof("DISPOSED","0","25",leaf,Map.of()).slots()));var exception=proof("EXCEPTION","25","25",null,Map.of("reason","Verified unreachable customer evidence and explicit ADMIN exception"));var result=effects(recall("recordRecovery",exception.slots()));assertEquals("0",((Map<?,?>)result.get("partition")).get("UNKNOWN").toString());String duty=result.get("residualDutyId").toString();assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,duty));var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",result.get("partitionHash")));var closed=effects(recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",result.get("partitionHash"))));assertEquals(true,closed.get("residualResponsibilityRetained"));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,duty));}
 @Test void transferredExceptionRetainsCurrentHumanResponsibilityAtClosure(){open();propose("50");approve();var result=effects(recall("recordRecovery",proof("EXCEPTION","0","50",null,Map.of("reason","Approved unresolved exact customer scope")).slots()));String assignment=result.get("residualDutyId").toString(),target=uuid();jdbc.update("INSERT INTO mulino_work_read_Works(organizationId,ID,createdAt,recordedAt,effectiveAt,itemId,definitionVersionId,kind,status,ownerId,supervisorId,lifecycleMode) SELECT organizationId,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,itemId,definitionVersionId,'RECALL_FOLLOWUP','ACTIVE',ownerId,supervisorId,'COMMAND' FROM mulino_work_read_Works WHERE ID=?",target,WORK);for(String cap:List.of("acceptHandover")){jdbc.update("INSERT INTO mulino_identity_CapabilityAssignments(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,?,'ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,cap,ORG);jdbc.update("INSERT INTO mulino_identity_GrantActions VALUES(?,?,?)",ORG,GRANT,cap);}request(()->new TransactionTemplate(tx).execute(status->{var c=auth.context(Instant.now(),Instant.now());var handover=responsibilityService.propose(c,Map.of("workId",WORK,"assignmentId",assignment,"recipientId",ACTOR,"targetWorkId",target,"expiresAt",Instant.now().plusSeconds(1800),"nextAction","Continue unresolved recall response","nextCheckAt",Instant.now().plusSeconds(3600)),true);responsibilityService.decide(c,handover.get("ID").toString(),"ACCEPTED");return true;}));assertEquals("TRANSFERRED",jdbc.queryForObject("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,assignment));var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",result.get("partitionHash")));effects(recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",result.get("partitionHash"))));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE workId=? AND kind='RECALL_EXCEPTION_RESIDUAL' AND status='OPEN' AND valid",Integer.class,target));}
 @Test void changedScopeInvalidatesApprovalAndAdminCannotBypassIndependentQc(){open();propose("50");approve();String previousScope=scope,previousHash=scopeHash;String oldApproval=approval;propose("40");assertNotEquals("APPLIED",recall("approveRecall",Map.of("scopeId",previousScope,"scopeHash",previousHash,"decision","APPROVE","validUntil",Instant.now().plusSeconds(600).toString())).get("outcome"));approve();var rec=proof("RECOVERED","0","25",segment,Map.of());var moved=effects(recall("recordRecovery",rec.slots())).get("currentSegmentId").toString();jdbc.update("INSERT INTO mulino_inventory_Restrictions(organizationId,ID,revision,createdAt,recordedAt,controlScope,action,state,validFrom,validUntil,decisionId,evidenceRef,segmentId,startQuantity,quantity,unit,category,workId,commandId,policyHash) SELECT organizationId,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,controlScope,'ALL','ACTIVE',CURRENT_TIMESTAMP-INTERVAL '1 second',CURRENT_TIMESTAMP+INTERVAL '1 day',?,'SYNTHETIC independent QC hold',ID,0,20,unit,'QC',?,?,? FROM mulino_inventory_QuantitySegments WHERE ID=?",uuid(),uuid(),WORK,uuid(),"a".repeat(64),moved);var disposal=proof("DISPOSED","0","25",moved,Map.of());assertNotEquals("APPLIED",recall("recordRecovery",disposal.slots()).get("outcome"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantityMovements WHERE kind='DISPOSE'",Integer.class));jdbc.update("UPDATE mulino_identity_ManagementAuthorities SET revokedAt=CURRENT_TIMESTAMP WHERE organizationId=?",ORG);assertNotEquals("APPLIED",recall("recordRecovery",proof("SAFE","25","15",null,Map.of()).slots()).get("outcome"));}
 @Test void simulatedPostconditionFailureRollsBackRecallRecovery(){open();propose("50");approve();var p=proof("RECOVERED","0","25",segment,Map.of());int before=count("mulino_inventory_QuantitySegments");doThrow(new IllegalStateException("audit-fail")).when(localPolicy).verifyCommit(any(),eq("recordRecovery"),anyString(),any(),anyMap(),eq(false));assertThrows(IllegalStateException.class,()->recall("recordRecovery",p.slots()));assertEquals(before,count("mulino_inventory_QuantitySegments"));assertEquals(0,count("mulino_trade_recall_Actions"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantitySegments WHERE retiredAt IS NOT NULL",Integer.class));}
 @Test void malformedOriginalAndPartialOutOfScopeCannotCreateCanonicalOrEffect(){open();propose("50");approve();assertThrows(AssertionError.class,()->proof("RECOVERED","40","25",segment,Map.of()));assertEquals(0,count("mulino_trade_recall_Actions"));}

 // ---- s4h-recall regressions (plan §6 반품·회수, §7.1, D18) ----
 static final String OPERATOR=uuid();
 /** A second human with recall RECORD/close capabilities but no ADMIN or MANAGER decision authority. */
 void operator(){jdbc.update("INSERT INTO mulino_identity_Actors(organizationId,ID,kind,stableRequestOwner) VALUES(?,?,'HUMAN',?)",ORG,OPERATOR,OPERATOR);jdbc.update("INSERT INTO mulino_identity_ExternalIdentities(organizationId,ID,actorId,issuer,subject,organizationAlias) VALUES(?,?,?,'https://fixture.invalid','operator','ORG-A')",ORG,uuid(),OPERATOR);jdbc.update("INSERT INTO mulino_identity_Memberships(organizationId,ID,actorId,validFrom,validUntil) VALUES(?,?,?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),OPERATOR);String grant=uuid();jdbc.update("INSERT INTO mulino_identity_Grants(organizationId,ID,actorId,delegatorId,validFrom,validUntil) VALUES(?,?,?,?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,grant,OPERATOR,OPERATOR);jdbc.update("INSERT INTO mulino_identity_GrantScopes VALUES(?,?,'ORGANIZATION',?)",ORG,grant,ORG);jdbc.update("INSERT INTO mulino_identity_AuthorityFences VALUES(?,?,1)",ORG,OPERATOR);
  var caps=new ArrayList<>(CAPS);caps.addAll(List.of("getEvidence","disposeQuantity"));for(String cap:caps){jdbc.update("INSERT INTO mulino_identity_CapabilityAssignments(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,?,'ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),OPERATOR,cap,ORG);jdbc.update("INSERT INTO mulino_identity_GrantActions VALUES(?,?,?)",ORG,grant,cap);}}
 Map<String,Object> asOperator(String cap,Map<String,Object> slots){var recorder=SecurityContextHolder.getContext().getAuthentication();SecurityContextHolder.getContext().setAuthentication(new org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken(org.springframework.security.oauth2.jwt.Jwt.withTokenValue("local-test-context").header("alg","RS256").issuer("https://fixture.invalid").subject("operator").claim("organizationId","ORG-A").build(),List.of()));try{return recall(cap,slots);}finally{SecurityContextHolder.getContext().setAuthentication(recorder);}}
 String code(Map<String,Object> result){return String.valueOf(((Map<?,?>)result.get("error")).get("code"));}
 int closures(){return jdbc.queryForObject("SELECT count(*) FROM mulino_trade_recall_Closures WHERE investigationId=?",Integer.class,investigation);}
 int actions(String kind){return jdbc.queryForObject("SELECT count(*) FROM mulino_trade_recall_Actions WHERE kind=?",Integer.class,kind);}
 java.math.BigDecimal partitionValue(Map<String,Object> effects,String key){return new java.math.BigDecimal(((Map<?,?>)effects.get("partition")).get(key).toString());}

 /** Finding 0: recovery recorded under v1 stays a fact after an ADMIN re-scope; v2 can dispose it and close truthfully. */
 @Test void rescopeAfterRecoveryCarriesPhysicalFactsAndClosesTruthfully(){
  open();propose("25");approve();String leaf=effects(recall("recordRecovery",proof("RECOVERED","0","25",segment,Map.of()).slots())).get("currentSegmentId").toString();
  propose("50");approve();
  var again=recall("recordRecovery",proof("RECOVERED","0","25",leaf,Map.of()).slots());assertEquals("CONFLICT",again.get("outcome"),again.toString());assertEquals("RECALL_RANGE_ALREADY_RECOVERED",code(again));assertEquals(1,actions("RECOVERED"));
  var disposed=effects(recall("recordRecovery",proof("DISPOSED","0","25",leaf,Map.of()).slots()));
  assertEquals(0,new java.math.BigDecimal("25").compareTo(partitionValue(disposed,"DISPOSED")));assertEquals(0,new java.math.BigDecimal("25").compareTo(partitionValue(disposed,"RECOVERED")));assertEquals(0,new java.math.BigDecimal("25").compareTo(partitionValue(disposed,"UNKNOWN")));
  assertEquals(0,new java.math.BigDecimal("35").compareTo(jdbc.queryForObject("SELECT SUM(quantity) FROM mulino_inventory_QuantitySegments WHERE retiredAt IS NULL",java.math.BigDecimal.class)));
  // Excluded 25–60 of v1 still has its open human review; v2's excluded 50–60 is not a second duty for the same units.
  assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE kind='RECALL_EXCLUDED_SCOPE' AND valid AND workId=?",Integer.class,WORK));
  var exception=effects(recall("recordRecovery",proof("EXCEPTION","25","25",null,Map.of("reason","Verified unreachable customer evidence and explicit ADMIN exception")).slots()));assertEquals(0,partitionValue(exception,"UNKNOWN").signum());
  var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",exception.get("partitionHash")));var closed=effects(recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",exception.get("partitionHash"))));
  assertEquals("25",((Map<?,?>)closed.get("partition")).get("DISPOSED").toString());assertEquals("25",((Map<?,?>)closed.get("partition")).get("EXCEPTION").toString());assertEquals(1,closures());}

 /** Finding 7: a range disposed under v1 is DISPOSED under v2 and cannot be relabelled SAFE or CONSUMED_LOST. */
 @Test void disposalUnderEarlierVersionStaysDisposedAndBlocksContradictoryTerminalLabels(){
  open();propose("50");approve();String leaf=effects(recall("recordRecovery",proof("RECOVERED","0","25",segment,Map.of()).slots())).get("currentSegmentId").toString();effects(recall("recordRecovery",proof("DISPOSED","0","25",leaf,Map.of()).slots()));
  propose("40");approve();
  var safe=recall("recordRecovery",proof("SAFE","0","25",null,Map.of()).slots());assertEquals("HELD",safe.get("outcome"),safe.toString());assertEquals("RECALL_PARTITION_CONFLICT",code(safe));
  var lost=recall("recordRecovery",proof("CONSUMED_LOST","10","10",null,Map.of()).slots());assertEquals("HELD",lost.get("outcome"),lost.toString());assertEquals("RECALL_PARTITION_CONFLICT",code(lost));
  assertEquals(0,actions("SAFE")+actions("CONSUMED_LOST"));
  var rest=effects(recall("recordRecovery",proof("SAFE","25","15",null,Map.of()).slots()));assertEquals(0,new java.math.BigDecimal("25").compareTo(partitionValue(rest,"DISPOSED")));assertEquals(0,partitionValue(rest,"UNKNOWN").signum());}

 /** Finding 8: recovered stock still held in controlled storage cannot be closed as consumed/lost or as an unresolved exception. */
 @Test void consumedLostOrExceptionOverStillHeldRecoveredRangeIsHeld(){
  open();propose("50");approve();effects(recall("recordRecovery",proof("RECOVERED","0","25",segment,Map.of()).slots()));
  var lost=recall("recordRecovery",proof("CONSUMED_LOST","0","25",null,Map.of()).slots());assertEquals("HELD",lost.get("outcome"),lost.toString());assertEquals("RECALL_PARTITION_CONFLICT",code(lost));
  var exception=recall("recordRecovery",proof("EXCEPTION","20","10",null,Map.of("reason","ADMIN exception over held stock")).slots());assertEquals("HELD",exception.get("outcome"),exception.toString());assertEquals("RECALL_PARTITION_CONFLICT",code(exception));
  assertEquals(1,count("mulino_trade_recall_Actions"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE kind='RECALL_EXCEPTION_RESIDUAL' AND workId=?",Integer.class,WORK));}

 /** Finding 1: DISPOSED retires stock only with the recorder's current human MANAGER disposal confirmation. */
 @Test void recallDisposalNeedsCurrentHumanManagerConfirmation(){
  operator();open();propose("50");approve();String leaf=effects(recall("recordRecovery",proof("RECOVERED","0","25",segment,Map.of()).slots())).get("currentSegmentId").toString();
  jdbc.update("UPDATE mulino_identity_ManagementAuthorities SET revokedAt=CURRENT_TIMESTAMP WHERE organizationId=? AND capabilityId='disposeQuantity'",ORG);
  var revoked=recall("recordRecovery",proof("DISPOSED","0","25",leaf,Map.of()).slots());assertEquals("REJECTED",revoked.get("outcome"),revoked.toString());assertEquals("FORBIDDEN",code(revoked));
  var byOperator=asOperator("recordRecovery",proof("DISPOSED","0","25",leaf,Map.of()).slots());assertEquals("REJECTED",byOperator.get("outcome"),byOperator.toString());assertEquals("FORBIDDEN",code(byOperator));
  assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantityMovements WHERE kind='DISPOSE'",Integer.class));assertEquals(0,actions("DISPOSED"));
  jdbc.update("INSERT INTO mulino_identity_ManagementAuthorities(organizationId,ID,actorId,capabilityId,scopeKind,scopeId,validFrom,validUntil) VALUES(?,?,?,'disposeQuantity','ORGANIZATION',?,CURRENT_TIMESTAMP-INTERVAL '1 day',CURRENT_TIMESTAMP+INTERVAL '1 day')",ORG,uuid(),ACTOR,ORG);
  effects(recall("recordRecovery",proof("DISPOSED","0","25",leaf,Map.of()).slots()));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantityMovements WHERE kind='DISPOSE'",Integer.class));}

 /** Finding 5: the current actor's ADMIN authority gates EXCEPTION and closure; the approver's authority is not borrowed. */
 @Test void nonAdminCannotRecordExceptionOrCloseRecall(){
  operator();open();propose("50");approve();var exceptionProof=proof("EXCEPTION","0","50",null,Map.of("reason","Approved unresolved exact customer scope"));
  var denied=asOperator("recordRecovery",exceptionProof.slots());assertEquals("REJECTED",denied.get("outcome"),denied.toString());assertEquals("FORBIDDEN",code(denied));assertEquals(0,count("mulino_trade_recall_Actions"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE kind='RECALL_EXCEPTION_RESIDUAL' AND workId=?",Integer.class,WORK));
  var result=effects(recall("recordRecovery",exceptionProof.slots()));var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",result.get("partitionHash")));var close=Map.<String,Object>of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",result.get("partitionHash"));
  var closeDenied=asOperator("closeRecall",close);assertEquals("REJECTED",closeDenied.get("outcome"),closeDenied.toString());assertEquals("FORBIDDEN",code(closeDenied));assertEquals(0,closures());
  effects(recall("closeRecall",close));assertEquals(1,closures());}

 /** Finding 3: historical reads derive investigation state from immutable rows known at knownAt. */
 @org.springframework.beans.factory.annotation.Autowired com.mulino.application.trade.recall.RecallQueries recallQueries;
 Map<?,?> read(Instant knownAt){var c=new DomainContext(ORG,ACTOR,OWNER,Instant.now(),knownAt);return (Map<?,?>)request(()->recallQueries.query(c,new QueryRequest("getRecall",investigation,Map.of("objectType","Recall"),Map.of(),50,null,null,c.asOf(),c.knownAt(),null))).data();}
 @Test void historicalRecallReadsUseStateKnownAtThatTime() throws Exception{
  open();Thread.sleep(20);Instant beforeScope=Instant.now();Thread.sleep(20);propose("50");approve();
  var early=read(beforeScope);assertEquals("INVESTIGATING",early.get("status"),early.toString());assertNull(early.get("currentScopeId"));assertNull(early.get("partition"));
  var list=request(()->{var c=new DomainContext(ORG,ACTOR,OWNER,Instant.now(),beforeScope);return recallQueries.query(c,new QueryRequest("getRecalls",null,Map.of("objectType","Recall","workId",WORK),Map.of(),50,null,null,c.asOf(),c.knownAt(),null));});assertEquals(1,((List<?>)list.data()).size());
  var result=effects(recall("recordRecovery",proof("EXCEPTION","0","50",null,Map.of("reason","Approved unresolved exact customer scope")).slots()));Thread.sleep(20);Instant beforeClose=Instant.now();Thread.sleep(20);
  var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",result.get("partitionHash")));effects(recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",result.get("partitionHash"))));
  var open=read(beforeClose);assertEquals("APPROVED",open.get("status"),open.toString());assertNull(open.get("closedAt"));assertEquals(scope,open.get("currentScopeId"));
  var now=read(Instant.now());assertEquals("CLOSED",now.get("status"));assertNotNull(now.get("closedAt"));}

 /** Unverified P3-0: an EXCEPTION residual gets its own future next check, so a stale investigation check cannot block closure. */
 @Test void exceptionResidualCarriesItsOwnFutureNextCheck(){
  open();propose("50");approve();jdbc.update("UPDATE mulino_trade_recall_Investigations SET nextCheckAt=CURRENT_TIMESTAMP-INTERVAL '1 minute' WHERE ID=?",investigation);
  var exceptionProof=proof("EXCEPTION","0","50",null,Map.of("reason","Approved unresolved exact customer scope"));
  var stale=recall("recordRecovery",exceptionProof.slots());assertEquals("REJECTED",stale.get("outcome"),stale.toString());assertEquals(0,count("mulino_trade_recall_Actions"));
  var slots=new LinkedHashMap<>(exceptionProof.slots());slots.put("nextAction","Locate remaining customer stock");slots.put("nextCheckAt",Instant.now().plusSeconds(7200).toString());var result=effects(recall("recordRecovery",slots));
  var closure=proof("CLOSURE","0","50",null,Map.of("partitionHash",result.get("partitionHash")));effects(recall("closeRecall",Map.of("scopeId",scope,"scopeHash",scopeHash,"approvalId",approval,"canonicalOccurrenceId",closure.canonical(),"partitionHash",result.get("partitionHash"))));
  assertEquals("Locate remaining customer stock",jdbc.queryForObject("SELECT nextAction FROM mulino_work_read_ObligationReferences WHERE ID=?",String.class,result.get("residualDutyId")));}
}
