package com.mulino.core;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
import com.mulino.application.core.*;
import com.sap.cds.ql.Select;
import com.sap.cds.services.persistence.PersistenceService;
import com.sap.cds.services.runtime.CdsRuntime;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.*;
import java.time.*;
import java.util.*;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import org.junit.jupiter.api.*;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.test.context.*;
import org.testcontainers.postgresql.PostgreSQLContainer;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("local")
class S3RegulatoryActualTest {
  static final PostgreSQLContainer PG=new PostgreSQLContainer("postgres@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280");
  static final java.security.KeyPair KEY;
  static final Path KEY_PATH;
  static final Path BLOB_PATH;
  static { try {PG.start();var generator=java.security.KeyPairGenerator.getInstance("RSA");generator.initialize(2048);KEY=generator.generateKeyPair();BLOB_PATH=Files.createTempDirectory("mulino-s1-read-blob-");KEY_PATH=Files.createTempFile("mulino-s1-read-public-",".pem");Files.writeString(KEY_PATH,"-----BEGIN PUBLIC KEY-----\n"+Base64.getMimeEncoder(64,new byte[]{10}).encodeToString(KEY.getPublic().getEncoded())+"\n-----END PUBLIC KEY-----\n");}catch(Exception failure){throw new ExceptionInInitializerError(failure);} }
  @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",PG::getJdbcUrl);r.add("spring.datasource.username",PG::getUsername);r.add("spring.datasource.password",PG::getPassword);r.add("JWT_PUBLIC_KEY",KEY_PATH::toString);r.add("JWT_ISSUER",()->"https://mulino.local.invalid");r.add("JWT_AUDIENCE",()->"mulino-platform");r.add("mulino.evidence.blob-root",BLOB_PATH::toString);}
  @Autowired com.mulino.application.work.WorkLifecycle lifecycle;
  @Autowired com.mulino.domain.work.WorkRepository workRepository;
  @Autowired com.mulino.application.evaluation.AssessmentService assessmentService;
  @Autowired com.mulino.adapters.blob.LocalBlobStore blobs;

  @Autowired JdbcTemplate jdbc;
  @Autowired ApplicationQueries queries;
  @Autowired ApplicationCommands commands;
  @Autowired PersistenceService persistence;
  @Autowired CdsRuntime runtime;
  @Autowired org.springframework.transaction.PlatformTransactionManager transactions;
  @LocalServerPort int port;
  final ObjectMapper json=new ObjectMapper();
  String org,actor,product,item,spec,pack,manufacturer,lot,place,segment,definition,work,goal,obligation,document,profile;
  static final Instant AS_OF=Instant.parse("2026-10-07T09:00:00Z"),KNOWN=Instant.parse("2026-10-07T09:00:01Z");
  String id(){return UUID.randomUUID().toString();}
  void insert(String table,Map<String,Object> row){String columns=String.join(",",row.keySet());jdbc.update("INSERT INTO "+table+" ("+columns+") VALUES ("+String.join(",",Collections.nCopies(row.size(),"?"))+")",row.values().toArray());}
  Map<String,Object> row(Object... values){var m=new LinkedHashMap<String,Object>();for(int i=0;i<values.length;i+=2)m.put((String)values[i],values[i+1]);return m;}
  Map<String,Object> scoped(String id){return row("organizationId",org,"ID",id,"revision",0,"createdAt",Timestamp.from(AS_OF.minusSeconds(10)),"recordedAt",Timestamp.from(KNOWN.minusSeconds(10)));}
  Map<String,Object> workRow(String id){var r=scoped(id);r.put("effectiveAt",Timestamp.from(AS_OF));return r;}
  @BeforeEach void seed(org.junit.jupiter.api.TestInfo info){
    org=id();actor=id();product=id();item=id();spec=id();pack=id();manufacturer=id();lot=id();place=id();segment=id();definition=id();work=id();goal=id();obligation=id();document=id();
    insert("mulino_identity_Organizations",row("ID",org,"externalAlias",org));
    insert("mulino_identity_Actors",row("organizationId",org,"ID",actor,"kind","HUMAN","stableRequestOwner",id()));
    insert("mulino_identity_AuthorityFences",row("organizationId",org,"actorId",actor,"revision",1));
    insert("mulino_identity_ExternalIdentities",row("organizationId",org,"ID",id(),"actorId",actor,"issuer","https://mulino.local.invalid","subject","writer-a","organizationAlias",org));
    insert("mulino_identity_Memberships",row("organizationId",org,"ID",id(),"actorId",actor,"validFrom",Timestamp.from(Instant.now().minusSeconds(3600)),"validUntil",Timestamp.from(Instant.now().plusSeconds(3600))));
    String grant=id();insert("mulino_identity_Grants",row("organizationId",org,"ID",grant,"actorId",actor,"delegatorId",actor,"validFrom",Timestamp.from(Instant.now().minusSeconds(3600)),"validUntil",Timestamp.from(Instant.now().plusSeconds(3600))));
    for(String cap:List.of("getObject","searchObjects","getWork","searchWorks","getInventory","getEvidence","getAssessment","getObligations","getDefinition","createDraft","createWork","cancelDraft","reviseGoal","prepareRegulatoryProcedure","recordSubmission","recordRegulatoryDecision","verifyLabel","getRegulatoryProcedure")){
      insert("mulino_identity_CapabilityAssignments",row("organizationId",org,"ID",id(),"actorId",actor,"capabilityId",cap,"scopeKind","ORGANIZATION","scopeId",org,"validFrom",Timestamp.from(Instant.now().minusSeconds(3600)),"validUntil",Timestamp.from(Instant.now().plusSeconds(3600))));
      insert("mulino_identity_GrantActions",row("organizationId",org,"grantId",grant,"capabilityId",cap));
    }
    insert("mulino_identity_GrantScopes",row("organizationId",org,"grantId",grant,"scopeKind","ORGANIZATION","scopeId",org));
    var p=scoped(product);p.put("name","integration item");insert("mulino_inventory_Products",p);
    var s=scoped(spec);s.putAll(row("productId",product,"version","1","contentHash","1".repeat(64)));insert("mulino_inventory_SpecificationVersions",s);
    var pk=scoped(pack);pk.putAll(row("productId",product,"version","1","contentHash","2".repeat(64)));insert("mulino_inventory_PackagingVersions",pk);
    var i=scoped(item);i.putAll(row("productId",product,"name","integration item","baseUnit","BOX","decimalPlaces",0,"specificationVersionId",spec,"packagingVersionId",pack));insert("mulino_inventory_TradeItems",i);
    var m=scoped(manufacturer);m.put("name","maker");insert("mulino_inventory_Manufacturers",m);
    var l=scoped(lot);l.putAll(row("manufacturerId",manufacturer,"itemId",item,"originalLot","LOT-1"));insert("mulino_inventory_ManufacturingLots",l);
    var loc=scoped(place);loc.putAll(row("name","warehouse","kind","WAREHOUSE"));insert("mulino_inventory_Places",loc);
    var seg=scoped(segment);seg.putAll(row("itemId",item,"lotId",lot,"identificationStatus","CONFIRMED","quantity",new java.math.BigDecimal("100"),"unit","BOX","placeId",place,"controlScope","warehouse","validFrom",Timestamp.from(AS_OF),"mixtureStatus","IDENTIFIED"));insert("mulino_inventory_QuantitySegments",seg);
    try {
      var predicate=Map.<String,Object>of("operator","quantitySum","property","Receipt.quantity","minimum",Map.of("value","1","unit","BOX"),"unit","BOX","evidenceSelector","VERIFIED_DISTINCT");
      var d=new com.mulino.domain.definitions.Definition(org,definition,"1.0.0",null,"PUBLISHED","", "core-v1","1.0.0",List.of(new com.mulino.domain.definitions.Definition.NounType("Receipt",true),new com.mulino.domain.definitions.Definition.NounType("TradeItem",true),new com.mulino.domain.definitions.Definition.NounType("Work",true),new com.mulino.domain.definitions.Definition.NounType("QuantitySegment",true)),List.of(new com.mulino.domain.definitions.Definition.Attribute("Receipt","quantity",com.mulino.domain.definitions.Definition.ValueType.DECIMAL,null,"BOX",0,1,1,"READ",true)),List.of("createDraft","createWork","cancelDraft","reviseGoal","createWorkLink","prepareRegulatoryProcedure","recordSubmission","recordRegulatoryDecision","verifyLabel").stream().map(cap->new com.mulino.domain.definitions.Definition.Verb(cap,Set.of("recordSubmission","recordRegulatoryDecision","verifyLabel").contains(cap)?"RECORD":"COMMAND",cap,cap.endsWith("Procedure")||cap.startsWith("record")||cap.equals("verifyLabel")?"REGULATORY_RECORD":"WORK",Map.of())).toList(),List.of(),List.of(new com.mulino.domain.definitions.Definition.Goal("Arrival","CUMULATIVE_EVENT","ARRIVED","core-v1",predicate)),List.of("createDraft","createWork","cancelDraft","reviseGoal","createWorkLink","prepareRegulatoryProcedure","recordSubmission","recordRegulatoryDecision","verifyLabel").stream().map(cap->new com.mulino.domain.definitions.Definition.Capability(cap,"1.0.0","core-v1","1.0.0","1.0.0",List.of())).toList());
      String content=json.writeValueAsString(d);
      insert("mulino_definitions_DefinitionVersions",row("organizationId",org,"ID",definition,"createdAt",Timestamp.from(AS_OF),"version","1.0.0","state","PUBLISHED","contentHash",com.mulino.domain.definitions.DefinitionRepository.sha256(content),"content",content,"evaluatorVersion","core-v1","schemaVersion","1.0.0"));
    }catch(Exception failure){throw new IllegalStateException(failure);}

    var w=workRow(work);w.putAll(row("itemId",item,"lotId",lot,"definitionVersionId",definition,"kind","PURCHASE","status","WAITING","ownerId",actor,"supervisorId",actor,"waitJson","{\"reason\":\"QC_PENDING\"}"));insert("mulino_work_read_Works",w);
    var g=workRow(goal);g.putAll(row("workId",work,"definitionVersionId",definition,"quantityMode","CUMULATIVE_EVENT","targetQuantity",new java.math.BigDecimal("100"),"unit","BOX","endpoint","ARRIVED","scopeJson","{}"));insert("mulino_work_read_GoalReferences",g);
    var o=workRow(obligation);o.putAll(row("workId",work,"kind","QC_REVIEW","status","OPEN","ownerId",actor,"supervisorId",actor,"nextAction","검사 근거 확인","nextCheckAt",Timestamp.from(KNOWN.plusSeconds(3600)),"scopeJson","{}"));insert("mulino_work_read_ObligationReferences",o);
    profile=id();insert("mulino_evidence_SourceProfiles",row("ID",profile,"organizationId",org,"revision",1,"recordedAt",Timestamp.from(KNOWN),"recordedBy",actor,"namespace","native-fixture","policyVersion","fixture-v1","intakeOwnerId",actor,"supervisorId",actor,"nextAction","review","nextCheckAt",Timestamp.from(KNOWN.plusSeconds(3600))));
    insert("mulino_evidence_DocumentVersions",row("ID",document,"organizationId",org,"revision",1,"recordedAt",Timestamp.from(KNOWN),"recordedBy",actor,"subjectKind","ITEM","subjectId",item,"itemId",item,"sha256","3".repeat(64),"availability","UNKNOWN","byteLength",0L,"mediaType","text/plain","sourceProfileId",profile,"provenance","{}"));
    var e=workRow(id());e.putAll(row("workId",work,"documentVersionId",document,"role","QC"));insert("mulino_work_read_EvidenceReferences",e);
    String policy=id();insert("mulino_governance_PolicyVersions",row("organizationId",org,"ID",policy,"version","fixture-v1","kind","EVIDENCE","content","{}","contentHash",com.mulino.domain.definitions.DefinitionRepository.sha256("{}"),"createdAt",LocalDateTime.ofInstant(AS_OF.minusSeconds(100),ZoneOffset.UTC),"effectiveFrom",LocalDateTime.ofInstant(AS_OF.minusSeconds(100),ZoneOffset.UTC)));
    if(Boolean.TRUE.equals(jdbc.queryForObject("SELECT to_regclass('mulino_governance_activepolicies') IS NOT NULL",Boolean.class)))jdbc.update("INSERT INTO mulino_governance_ActivePolicies(organizationId,kind,policyId,revision) VALUES(?,'EVIDENCE',?,0)",org,policy);
    try {String commandPolicy=id();String content=json.writeValueAsString(Map.of("rules",Map.of("createDraft",Map.of("effectClass","WORK"),"createWork",Map.of("effectClass","WORK"),"cancelDraft",Map.of("effectClass","WORK"),"reviseGoal",Map.of("effectClass","WORK"),"createWorkLink",Map.of("effectClass","WORK"),"prepareRegulatoryProcedure",Map.of("effectClass","REGULATORY_RECORD"),"recordSubmission",Map.of("effectClass","REGULATORY_RECORD"),"recordRegulatoryDecision",Map.of("effectClass","REGULATORY_RECORD"),"verifyLabel",Map.of("effectClass","REGULATORY_RECORD"))));insert("mulino_governance_PolicyVersions",row("organizationId",org,"ID",commandPolicy,"version","command-fixture-v1","kind","COMMAND","content",content,"contentHash",com.mulino.domain.definitions.DefinitionRepository.sha256(content),"createdAt",LocalDateTime.now(ZoneOffset.UTC).minusMinutes(1),"effectiveFrom",LocalDateTime.now(ZoneOffset.UTC).minusMinutes(1)));jdbc.update("INSERT INTO mulino_governance_ActivePolicies(organizationId,kind,policyId,revision) VALUES(?,'COMMAND',?,0)",org,commandPolicy);}catch(Exception failure){throw new IllegalStateException(failure);}
    regulatorySeed(info);login();work=draft(goalInputs());run("activateWork",0,Map.of("workId",work));
  }
  void login(){SecurityContextHolder.getContext().setAuthentication(new JwtAuthenticationToken(Jwt.withTokenValue("trusted-test-context").header("alg","RS256").subject("writer-a").issuer("https://mulino.local.invalid").claim("organizationId",org).claim("stableRequestOwner","forged-owner-ignored").build(),List.of()));}
  @AfterEach void clear(){SecurityContextHolder.clearContext();}
  @AfterAll static void stop()throws Exception{PG.stop();Files.deleteIfExists(KEY_PATH);try(var paths=Files.walk(BLOB_PATH)){for(var p:paths.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
  Map<String,Object> request(String operation,String target,String snapshot){Map<String,Object> body=row("scope",Map.of("organizationId",org,"itemId",item,"lotId",lot),"asOf",AS_OF.toString(),"knownAt",KNOWN.toString());if(target!=null)body.put("id",target);if(snapshot!=null)body.put("snapshotRef",snapshot);return body;}
  Map<String,Object> read(String operation,String target,String snapshot){return runtime.requestContext().run(c->{return queries.query(QueryRequests.parse(operation,request(operation,target,snapshot)));});}

  DomainContext context(){return new DomainContext(org,actor,actor,Instant.now().plusSeconds(60),Instant.now().plusSeconds(60));}
  Map<String,Object> command(String op,int rev,Map<String,Object> slots){return row("capabilityId",op,"expectedRevision",rev,"slots",slots);}
  Map<String,Object> run(String op,int rev,Map<String,Object> slots){return runtime.requestContext().run(ctx->{var template=new org.springframework.transaction.support.TransactionTemplate(transactions);return template.execute(tx->lifecycle.execute(context(),command(op,rev,slots)));});}
  Map<String,Object> goalInputs(){return row("quantityMode","CUMULATIVE_EVENT","targetQuantity","100","unit","BOX","endpoint","ARRIVED","dueAt","2026-10-31T00:00:00Z","scope",Map.of("itemId",item),"timezone","Asia/Seoul","evidencePolicyVersion","fixture-v1","periodStartInclusive",true,"periodEndInclusive",true,"periodStart","2026-10-01T00:00:00Z","periodEnd","2026-10-31T00:00:00Z","eventKind","RECEIPT","contributionScope",Map.of("itemId",item),"deduplication","CANONICAL_OCCURRENCE","conditions",List.of(Map.of("id","Arrival")),"evaluatorVersion","core-v1");}
  String draft(Map<String,Object> goal){var result=run("createDraft",0,row("itemId",item,"definitionVersionId",definition,"kind","PURCHASE","ownerId",actor,"supervisorId",actor,"goal",goal));return String.valueOf(((Map<?,?>)result.get("effects")).get("workId"));}

  Map<String,Object> assess(String id){return runtime.requestContext().run(ctx->{return new org.springframework.transaction.support.TransactionTemplate(transactions).execute(tx->assessmentService.assess(context(),id));});}
  int revision(String id){return jdbc.queryForObject("SELECT revision FROM mulino_work_read_Works WHERE ID=?",Integer.class,id);}
  void occurrence(String workId,String amount,String externalId){
    String event=id(),claim=id(),canonical=id(),doc=id();byte[] bytes=(externalId+amount).getBytes();var blob=blobs.stage(bytes,com.mulino.adapters.blob.LocalBlobStore.hash(bytes));blobs.commit(blob);Instant now=Instant.now().minusSeconds(2);
    var d=row("organizationId",org,"ID",doc,"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"subjectKind","WORK","subjectId",workId,"itemId",item,"workId",workId,"sha256",blob.sha256(),"blobId",blob.id().toString(),"byteLength",blob.size(),"mediaType","text/plain","sourceNamespace","native-fixture","sourceProfileId",profile,"availability","AVAILABLE","provenance","{}");insert("mulino_evidence_DocumentVersions",d);
    var e=row("organizationId",org,"ID",event,"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"subjectKind","WORK","subjectId",workId,"itemId",item,"workId",workId,"effectiveFrom",Timestamp.from(now),"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","kind","RECEIPT","sourceNamespace","native-fixture","sourceProfileId",profile,"externalEventId",externalId,"sourceVersion","1","payloadHash",blob.sha256(),"payload","{}");insert("mulino_evidence_Events",e);
    var in=row("organizationId",org,"ID",id(),"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"subjectKind","WORK","subjectId",workId,"itemId",item,"workId",workId,"eventId",event,"sourceNamespace","native-fixture","sourceProfileId",profile,"externalEventId",externalId,"sourceVersion","1","payloadHash",blob.sha256(),"state","RECEIVED","intakeOwnerId",actor,"supervisorId",actor,"nextAction","compare","nextCheckAt",Timestamp.from(now.plusSeconds(3600)));insert("mulino_evidence_InboxRecords",in);
    var c=row("organizationId",org,"ID",claim,"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"sourceProfileId",profile,"subjectKind","WORK","subjectId",workId,"itemId",item,"workId",workId,"effectiveFrom",Timestamp.from(now),"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","eventId",event,"documentVersionId",doc,"assertion","receipt","quantity",new java.math.BigDecimal(amount),"unit","BOX");insert("mulino_evidence_Claims",c);
    var o=row("organizationId",org,"ID",canonical,"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"sourceProfileId",profile,"subjectKind","WORK","subjectId",workId,"itemId",item,"workId",workId,"effectiveFrom",Timestamp.from(now),"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","kind","RECEIPT","physicalScopeId",id(),"quantity",new java.math.BigDecimal(amount),"unit","BOX","reassessmentState","PENDING");insert("mulino_evidence_CanonicalOccurrences",o);
    var v=row("organizationId",org,"ID",id(),"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"claimId",claim,"canonicalOccurrenceId",canonical,"basisDocumentId",doc,"policyVersion","fixture-v1","sourceMatched",true,"identityMatched",true,"quantityMatched",true,"timeMatched",true,"duplicateChecked",true,"verdict","VERIFIED","reason","synthetic native verified fixture");insert("mulino_evidence_Verifications",v);
  }
 @Autowired com.mulino.application.trade.regulatory.RegulatoryEligibility eligibility;
 String regulatoryPolicy;
 void regulatorySeed(org.junit.jupiter.api.TestInfo info){regulatoryPolicy=id();var pol=scoped(regulatoryPolicy);pol.putAll(row("recordedBy",actor,"revision",1,"version","fixture-v1","authority","FICTIONAL_TEST_AUTHORITY","sourceNamespace","native-fixture","action","SELL","validFrom",Timestamp.from(AS_OF),"fictional",true,"status","ACTIVE","requiresLabel",info.getTestMethod().get().getName().contains("label")));insert("mulino_trade_regulatory_Policies",pol);}
 Map<String,Object> gateway(String capability,int revision,Map<String,Object> slots){var intent=row("capabilityId",capability,"definitionVersion",definition,"intentKind",capability.equals("prepareRegulatoryProcedure")?"COMMAND":"RECORD","capabilityVersion","1.0.0","subjectRefs",List.of(),"slots",slots,"provenance",Map.of(),"expectedRevision",revision,"commandIdempotencyKey",id());return runtime.requestContext().run(ctx->{return commands.execute(intent);});}
 String availableDocument(Map<String,Object> content)throws Exception{String doc=id();byte[] bytes=json.writeValueAsBytes(content);var blob=blobs.stage(bytes,com.mulino.adapters.blob.LocalBlobStore.hash(bytes));blobs.commit(blob);insert("mulino_evidence_DocumentVersions",row("organizationId",org,"ID",doc,"revision",1,"recordedAt",Timestamp.from(Instant.now().minusSeconds(3)),"recordedBy",actor,"subjectKind","ITEM","subjectId",item,"itemId",item,"sha256",blob.sha256(),"blobId",blob.id().toString(),"byteLength",blob.size(),"mediaType","application/json","sourceNamespace","native-fixture","sourceProfileId",profile,"availability","AVAILABLE","provenance","{}"));return doc;}
 String regulatoryOccurrence(String kind,Map<String,Object> payload)throws Exception{
  String doc=availableDocument(payload),event=id(),claim=id(),canonical=id();Instant now=Instant.now().minusSeconds(2);String content=json.writeValueAsString(payload);var e=row("organizationId",org,"ID",event,"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"subjectKind","SEGMENT","subjectId",segment,"itemId",item,"workId",work,"effectiveFrom",Timestamp.from(now),"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","kind",kind,"sourceNamespace","native-fixture","sourceProfileId",profile,"externalEventId",event,"sourceVersion","1","payloadHash",com.mulino.adapters.blob.LocalBlobStore.hash(content.getBytes()),"payload",content);insert("mulino_evidence_Events",e);
  var inbox=new LinkedHashMap<>(e);for(String k:List.of("effectiveFrom","timeZone","timePrecision","valueState","kind","payload"))inbox.remove(k);inbox.put("ID",id());inbox.putAll(row("eventId",event,"state","RECEIVED","intakeOwnerId",actor,"supervisorId",actor,"nextAction","review","nextCheckAt",Timestamp.from(now.plusSeconds(3600))));insert("mulino_evidence_InboxRecords",inbox);
  var cl=row("organizationId",org,"ID",claim,"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"subjectKind","SEGMENT","subjectId",segment,"itemId",item,"workId",work,"eventId",event,"documentVersionId",doc,"sourceProfileId",profile,"effectiveFrom",Timestamp.from(now),"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","assertion",content);insert("mulino_evidence_Claims",cl);
  var ca=new LinkedHashMap<>(cl);ca.put("ID",canonical);for(String k:List.of("eventId","documentVersionId","assertion"))ca.remove(k);ca.putAll(row("kind",kind,"physicalScopeId",segment,"reassessmentState","COMPLETE"));if(payload.containsKey("quantity")){ca.put("quantity",new java.math.BigDecimal(payload.get("quantity").toString()));ca.put("unit",payload.get("unit"));}insert("mulino_evidence_CanonicalOccurrences",ca);
  insert("mulino_evidence_Verifications",row("organizationId",org,"ID",id(),"revision",1,"recordedAt",Timestamp.from(now),"recordedBy",actor,"claimId",claim,"canonicalOccurrenceId",canonical,"basisDocumentId",doc,"policyVersion","fixture-v1","sourceMatched",true,"identityMatched",true,"quantityMatched",true,"timeMatched",true,"duplicateChecked",true,"verdict","VERIFIED","reason","Explicitly fictional regulatory fixture"));return canonical;
 }
 Map<String,Object> bindings(String proc,String version){return row("procedureId",proc,"procedureVersionId",version,"itemId",item,"lotId",lot,"physicalScopeId",segment,"authority","FICTIONAL_TEST_AUTHORITY","policyVersion","fixture-v1");}
 Map<String,Object> prepareProcedure()throws Exception{return gateway("prepareRegulatoryProcedure",0,row("itemId",item,"lotId",lot,"physicalScopeId",segment,"workId",work,"policyId",regulatoryPolicy,"documentVersionId",availableDocument(Map.of("draft",true))));}
 Map<String,Object> effects(Map<String,Object> result){return (Map<String,Object>)result.get("effects");}
 Map<String,Object> submitted(Map<String,Object> prepared)throws Exception{String proc=effects(prepared).get("procedureId").toString(),version=effects(prepared).get("procedureVersionId").toString();String at=Instant.now().minusSeconds(5).toString();var payload=bindings(proc,version);payload.put("occurredAt",at);String occurrence=regulatoryOccurrence("REGULATORY_SUBMISSION",payload);return gateway("recordSubmission",((Number)prepared.get("revision")).intValue(),row("procedureId",proc,"occurredAt",at,"occurrenceId",occurrence));}
 Map<String,Object> decision(Map<String,Object> submitted,String kind,String start,String amount,String previous)throws Exception{String proc=effects(submitted).get("procedureId").toString(),version=effects(submitted).get("procedureVersionId").toString();var slots=row("procedureId",proc,"decision",kind,"action","SELL","startQuantity",start,"quantity",amount,"unit","BOX","validFrom",Instant.now().minusSeconds(10).toString());var payload=bindings(proc,version);payload.putAll(slots);String occurrence=regulatoryOccurrence("REGULATORY_DECISION",payload);slots.put("occurrenceId",occurrence);if(previous!=null)slots.put("previousVersionId",previous);return gateway("recordRegulatoryDecision",((Number)submitted.get("revision")).intValue(),slots);}
 com.mulino.application.trade.regulatory.RegulatoryEligibility.Result eligibility100(){return runtime.requestContext().run(ctx->{return eligibility.assess(context(),item,lot,segment,"SELL",new java.math.BigDecimal("100"),"BOX");});}
 @Test void preparedAndUnconfirmedNeverProveSubmitted()throws Exception{var prepared=prepareProcedure();assertEquals("APPLIED",prepared.get("outcome"));assertEquals("PREPARED",prepared.get("status"));String proc=effects(prepared).get("procedureId").toString();var pending=gateway("recordSubmission",1,row("procedureId",proc,"occurredAt",Instant.now().toString()));assertEquals("SUBMISSION_UNCONFIRMED",pending.get("status"));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE organizationId=? AND kind='REGULATORY_REVIEW' AND status='OPEN'",Integer.class,org));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantityMovements WHERE organizationId=?",Integer.class,org));assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_ProcedureVersions WHERE procedureId=?",Integer.class,proc));var result=eligibility100();assertEquals(0,result.eligibleQuantity().signum());}
 @Test void partialAllowanceAndOverlappingRangesCountOnceAndRevocationPersistsHistory()throws Exception{var submitted=submitted(prepareProcedure());assertEquals("SUBMITTED",submitted.get("status"));var first=decision(submitted,"ALLOWED","0","30",null);var second=decision(first,"ALLOWED","20","10",null);var result=eligibility100();assertEquals(0,new java.math.BigDecimal("30").compareTo(result.eligibleQuantity()));assertEquals(1,result.allowedRanges().size());assertEquals(0,new java.math.BigDecimal("70").compareTo(jdbc.queryForObject("SELECT quantity FROM mulino_work_read_ObligationReferences WHERE organizationId=? AND kind='REGULATORY_REVIEW' AND status='OPEN'",java.math.BigDecimal.class,org)));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE organizationId=? AND kind='REGULATORY_REVIEW' AND status='OPEN'",Integer.class,org));decision(second,"REVOKED","0","30",effects(first).get("versionId").toString());var revoked=eligibility100();assertEquals(0,revoked.eligibleQuantity().signum());assertEquals(3,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_DecisionVersions WHERE organizationId=?",Integer.class,org));assertThrows(org.springframework.dao.DataAccessException.class,()->jdbc.update("DELETE FROM mulino_trade_regulatory_DecisionVersions WHERE organizationId=?",org));}
 @Test void rejectedSupplementedResubmissionRetainsVersionChain()throws Exception{var sub=submitted(prepareProcedure());var rejected=decision(sub,"REJECTED","0","100",null);String proc=effects(rejected).get("procedureId").toString();var prep=gateway("prepareRegulatoryProcedure",3,row("procedureId",proc,"documentVersionId",availableDocument(Map.of("supplement",true))));assertEquals("PREPARED",prep.get("status"));var resub=submitted(prep);assertEquals("SUBMITTED",resub.get("status"));var supplement=decision(resub,"SUPPLEMENTARY_REQUIRED","0","100",null);assertEquals("SUPPLEMENTARY_REQUIRED",supplement.get("status"));assertEquals(6,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_ProcedureVersions WHERE procedureId=?",Integer.class,proc));}
 @Test void completeAllowanceLeavesNoInventedReviewDuty()throws Exception{var sub=submitted(prepareProcedure());decision(sub,"ALLOWED","0","100",null);assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE organizationId=? AND kind='REGULATORY_REVIEW' AND status='OPEN'",Integer.class,org));}
 @Test void revokedOriginalEvidenceRemovesCurrentAllowance()throws Exception{var sub=submitted(prepareProcedure());var allowed=decision(sub,"ALLOWED","0","30",null);String decisionId=effects(allowed).get("versionId").toString();String blob=jdbc.queryForObject("SELECT d.blobId FROM mulino_trade_regulatory_DecisionVersions a JOIN mulino_evidence_Verifications v ON v.canonicalOccurrenceId=a.occurrenceId AND v.organizationId=a.organizationId JOIN mulino_evidence_DocumentVersions d ON d.ID=v.basisDocumentId AND d.organizationId=v.organizationId WHERE a.ID=?",String.class,decisionId);blobs.discard(UUID.fromString(blob));assertEquals(0,eligibility100().eligibleQuantity().signum());assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_DecisionVersions WHERE organizationId=?",Integer.class,org));}
 @Test void labelRejectionVetoAndExpiryBoundary()throws Exception{var sub=submitted(prepareProcedure());var allowed=decision(sub,"ALLOWED","0","100",null);String proc=effects(allowed).get("procedureId").toString();String expiry=Instant.now().plusSeconds(1800).toString();var label=row("procedureId",proc,"decision","VERIFIED","packagingVersionId",pack,"specificationVersionId",spec,"validFrom",Instant.now().minusSeconds(5).toString(),"validUntil",expiry);var payload=bindings(proc,effects(allowed).get("procedureVersionId").toString());payload.putAll(label);label.put("occurrenceId",regulatoryOccurrence("LABEL_VERIFICATION",payload));var verified=gateway("verifyLabel",3,label);var result=eligibility100();assertEquals(0,new java.math.BigDecimal("100").compareTo(result.eligibleQuantity()));assertEquals(Instant.parse(expiry),result.nextValidityBoundary());label.put("decision","REJECTED");payload.put("decision","REJECTED");label.put("occurrenceId",regulatoryOccurrence("LABEL_VERIFICATION",payload));gateway("verifyLabel",4,label);assertEquals(0,eligibility100().eligibleQuantity().signum());assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_LabelVerifications WHERE organizationId=?",Integer.class,org));}
 @Test void crossOrganizationPolicyIsIndistinguishableFromUnavailablePolicy()throws Exception{String other=id(),otherActor=id(),policy=id();insert("mulino_identity_Organizations",row("ID",other,"externalAlias",other));insert("mulino_identity_Actors",row("organizationId",other,"ID",otherActor,"kind","HUMAN","stableRequestOwner",id()));var foreign=scoped(policy);foreign.putAll(row("organizationId",other,"recordedBy",otherActor,"revision",1,"version","fictional-foreign","authority","FICTIONAL_TEST_AUTHORITY","sourceNamespace","native-fixture","action","SELL","validFrom",Timestamp.from(AS_OF),"fictional",true,"status","ACTIVE","requiresLabel",false));insert("mulino_trade_regulatory_Policies",foreign);var slots=row("itemId",item,"lotId",lot,"physicalScopeId",segment,"workId",work,"policyId",policy,"documentVersionId",availableDocument(Map.of("draft",true)));var result=gateway("prepareRegulatoryProcedure",0,slots);assertEquals("FORBIDDEN",((Map<?,?>)result.get("error")).get("code"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_Procedures WHERE organizationId=?",Integer.class,org));}
 @Test void missingProvenanceAndCrossOrganizationAndUnauthorizedHaveNoProcedureEffects()throws Exception{String doc=availableDocument(Map.of("draft",true));var slots=row("itemId",item,"lotId",lot,"physicalScopeId",segment,"workId",work,"policyId",regulatoryPolicy,"documentVersionId",document);var denied=gateway("prepareRegulatoryProcedure",0,slots);assertEquals("HELD",denied.get("outcome"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_Procedures WHERE organizationId=?",Integer.class,org));slots.put("documentVersionId",doc);jdbc.update("DELETE FROM mulino_identity_GrantActions WHERE organizationId=? AND capabilityId='prepareRegulatoryProcedure'",org);assertEquals("REJECTED",gateway("prepareRegulatoryProcedure",0,slots).get("outcome"));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_trade_regulatory_Procedures WHERE organizationId=?",Integer.class,org));}
 void publicEvidenceCapabilities()throws Exception{
  var caps=List.of("prepareRegulatoryProcedure","recordSubmission","recordRegulatoryDecision","verifyLabel","attachEvidence","recordActivity","matchSourceIdentity","linkCanonicalOccurrence");String grant=jdbc.queryForObject("SELECT ID FROM mulino_identity_Grants WHERE organizationId=? LIMIT 1",String.class,org);
  for(String cap:caps.subList(4,8)){insert("mulino_identity_CapabilityAssignments",row("organizationId",org,"ID",id(),"actorId",actor,"capabilityId",cap,"scopeKind","ORGANIZATION","scopeId",org,"validFrom",Timestamp.from(Instant.now().minusSeconds(3600)),"validUntil",Timestamp.from(Instant.now().plusSeconds(3600))));insert("mulino_identity_GrantActions",row("organizationId",org,"grantId",grant,"capabilityId",cap));}
  definition=id();var nouns=List.of(new com.mulino.domain.definitions.Definition.NounType("TradeItem",true),new com.mulino.domain.definitions.Definition.NounType("QuantitySegment",true),new com.mulino.domain.definitions.Definition.NounType("RegulatoryProcedure",true),new com.mulino.domain.definitions.Definition.NounType("Work",true));var verbs=caps.stream().map(cap->new com.mulino.domain.definitions.Definition.Verb(cap,cap.equals("prepareRegulatoryProcedure")?"COMMAND":"RECORD",cap,"RECORD",Map.of())).toList();var capabilities=caps.stream().map(cap->new com.mulino.domain.definitions.Definition.Capability(cap,"1.0.0","core-v1","1.0.0","1.0.0",List.of())).toList();var def=new com.mulino.domain.definitions.Definition(org,definition,"public-regulatory-v1",null,"PUBLISHED","","core-v1","1.0.0",nouns,List.of(),verbs,List.of(),List.of(),capabilities);String definitionJson=json.writeValueAsString(def);insert("mulino_definitions_DefinitionVersions",row("organizationId",org,"ID",definition,"createdAt",Timestamp.from(Instant.now().minusSeconds(5)),"version","public-regulatory-v1","state","PUBLISHED","contentHash",com.mulino.domain.definitions.DefinitionRepository.sha256(definitionJson),"content",definitionJson,"evaluatorVersion","core-v1","schemaVersion","1.0.0"));
  var rules=new TreeMap<String,Object>();for(String cap:caps)rules.put(cap,Map.of("effectClass",Set.of("attachEvidence","recordActivity").contains(cap)?"RECORD":Set.of("matchSourceIdentity","linkCanonicalOccurrence").contains(cap)?"RECONCILIATION":"REGULATORY_RECORD"));String commandPolicy=id(),content=json.writeValueAsString(Map.of("rules",rules));insert("mulino_governance_PolicyVersions",row("organizationId",org,"ID",commandPolicy,"version","public-regulatory-fixture","kind","COMMAND","content",content,"contentHash",com.mulino.domain.definitions.DefinitionRepository.sha256(content),"createdAt",LocalDateTime.now(ZoneOffset.UTC).minusMinutes(1),"effectiveFrom",LocalDateTime.now(ZoneOffset.UTC).minusMinutes(1)));jdbc.update("UPDATE mulino_governance_ActivePolicies SET policyId=?,revision=revision+1 WHERE organizationId=? AND kind='COMMAND'",commandPolicy,org);
 }
 String publicOccurrence(String kind,Map<String,Object> payload,String sourceEvent)throws Exception{
  byte[] bytes=json.writeValueAsBytes(payload);var subject=Map.of("kind","SEGMENT","id",segment);var attached=gateway("attachEvidence",0,row("subject",subject,"sourceNamespace","native-fixture","sourceReference",sourceEvent,"mediaType","application/json","expectedHash",com.mulino.adapters.blob.LocalBlobStore.hash(bytes),"provenance","fictional authored fixture","contentBase64",Base64.getEncoder().encodeToString(bytes)));assertEquals("APPLIED",attached.get("outcome"),attached.toString());String doc=attached.get("id").toString();String time=Instant.now().minusSeconds(3).toString();var slots=row("subject",subject,"kind",kind,"sourceNamespace","native-fixture","externalEventId",sourceEvent,"sourceVersion","1","effectiveFrom",time,"timeZone","UTC","timePrecision","SECOND","valueState","KNOWN","payload",json.writeValueAsString(payload),"documentId",doc,"assertion",json.writeValueAsString(payload));if(payload.containsKey("quantity")){slots.put("quantity",payload.get("quantity"));slots.put("unit",payload.get("unit"));}var recorded=gateway("recordActivity",0,slots);assertEquals("APPLIED",recorded.get("outcome"),recorded.toString());String claim=recorded.get("claimId").toString();var review=row("claimId",claim,"basisDocumentId",doc,"physicalScopeId",segment,"policyVersion","fixture-v1","sourceIdentity","native-fixture:"+sourceEvent+":1","effectiveFrom",time,"reason","Fictional typed original regulatory source");if(payload.containsKey("quantity")){review.put("quantity",payload.get("quantity"));review.put("unit",payload.get("unit"));}var matched=gateway("matchSourceIdentity",1,review);assertEquals("MATCHED",matched.get("evidenceStatus"),matched.toString());var linked=gateway("linkCanonicalOccurrence",1,row("reconciliationId",matched.get("id")));assertEquals("VERIFIED_RECORD_ONLY",linked.get("evidenceStatus"),linked.toString());return linked.get("id").toString();
 }
 @Test void actualPublicOriginalPartial30AndIndependentDecisionVersions()throws Exception{
  publicEvidenceCapabilities();var prepared=prepareProcedure();String proc=effects(prepared).get("procedureId").toString(),version=effects(prepared).get("procedureVersionId").toString();String at=Instant.now().minusSeconds(5).toString();var submission=bindings(proc,version);submission.put("occurredAt",at);submission.put("regulatoryEventId",id());String occurrence=publicOccurrence("REGULATORY_SUBMISSION",submission,id());var submitted=gateway("recordSubmission",1,row("procedureId",proc,"occurredAt",at,"occurrenceId",occurrence));assertEquals("SUBMITTED",submitted.get("status"));var slots=row("procedureId",proc,"decision","ALLOWED","action","SELL","startQuantity","0","quantity","30","unit","BOX","validFrom",Instant.now().minusSeconds(10).toString());var decision=bindings(proc,effects(submitted).get("procedureVersionId").toString());decision.putAll(slots);decision.put("regulatoryEventId",id());String allowed=publicOccurrence("REGULATORY_DECISION",decision,id());slots.put("occurrenceId",allowed);var result=gateway("recordRegulatoryDecision",2,slots);assertEquals("ALLOWED",result.get("status"),result.toString());assertEquals(0,new java.math.BigDecimal("30").compareTo(eligibility100().eligibleQuantity()));assertEquals(0,new java.math.BigDecimal("70").compareTo(jdbc.queryForObject("SELECT quantity FROM mulino_work_read_ObligationReferences WHERE organizationId=? AND kind='REGULATORY_REVIEW' AND status='OPEN'",java.math.BigDecimal.class,org)));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM mulino_inventory_QuantityMovements WHERE organizationId=?",Integer.class,org));
 }
}
