package org.mulino.verification.modelbinding;
import org.mulino.verification.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

/** Captured observation mutants validate assertions only, never product/model behavior. */
final class ModelBindingEvaluatorTest {
    private BindingContract c() throws Exception{return new BindingContract(Path.of(System.getProperty("repo.root")));}
    private JsonNode audit(){return Json.parse("{\"id\":\"a1\",\"classes\":[\"READ_AUDIT\"],\"operation\":\"READ\"}");}
    @Test void auditOnlyReadAllowedButInvoiceAndFutureClassesFail() throws Exception {var c=c();var e=new BindingEvaluator(c);var o=c.corpus.path("cases").get(0).path("turns").get(0).path("oracle");assertDoesNotThrow(()->e.effectWhitelist(o,Json.object(),List.of(audit()),Json.object()));for(String type:List.of("INVOICE","PURCHASE_PROPOSAL","EVIDENCE_LINK","FUTURE_WRITE")){var x=(ObjectNode)audit().deepCopy();x.set("classes",Json.MAPPER.valueToTree(List.of(type)));assertThrows(IllegalArgumentException.class,()->e.effectWhitelist(o,Json.object(),List.of(x),Json.object()));}}
    @Test void effectIdentityNotDocumentCount(){var b=Json.parse("[{\"id\":\"e1\",\"classes\":[\"RECEIPT\"]}]");assertEquals(0,BindingEvaluator.newEffects(b,b).size());var duplicated=Json.parse("[{\"id\":\"e1\",\"classes\":[\"RECEIPT\"]},{\"id\":\"e1\",\"classes\":[\"RECEIPT\"]}]");assertThrows(IllegalArgumentException.class,()->BindingEvaluator.newEffects(b,duplicated));}
    @Test void oldEffectCannotDisappearOrMutate(){var b=Json.parse("[{\"id\":\"e1\",\"classes\":[\"RECEIPT\"]}]");assertThrows(IllegalArgumentException.class,()->BindingEvaluator.newEffects(b,Json.array()));var a=Json.parse("[{\"id\":\"e1\",\"classes\":[\"DISPATCH\"]}]");assertThrows(IllegalArgumentException.class,()->BindingEvaluator.newEffects(b,a));}
    @Test void physicalColumnQuantityMismatchAndMissingRowsFail() throws Exception {var e=new BindingEvaluator(c());var a=Json.parse("{\"path\":\"state.receipt.cumulative.value\",\"operator\":\"eq\",\"expected\":\"60\"}");var rows=Json.parse("{\"data\":{\"rawRows\":[{\"dataset\":\"receiptOccurrence\",\"attribute\":\"quantity\",\"table\":\"receipt_ledger\",\"column\":\"quantity\",\"rowId\":\"r1\",\"physicalScopeId\":\"canonical-1\",\"unit\":\"BOX\",\"value\":\"60\"}]}}");assertDoesNotThrow(()->e.assertSemantic(a,Json.object(),rows,List.of(),Json.object()));((ObjectNode)rows.path("data").path("rawRows").get(0)).put("value","120");assertThrows(AssertionError.class,()->e.assertSemantic(a,Json.object(),rows,List.of(),Json.object()));assertThrows(IllegalArgumentException.class,()->e.assertSemantic(a,Json.object(),Json.object(),List.of(),Json.object()));}
    @Test void responseQuantityCannotReplaceIndependentColumn() throws Exception {var e=new BindingEvaluator(c());var a=Json.parse("{\"path\":\"state.receipt.cumulative.value\",\"expected\":\"60\"}");assertThrows(IllegalArgumentException.class,()->e.assertSemantic(a,Json.parse("{\"response\":{\"receipt\":{\"value\":\"60\"}}}"),Json.object(),List.of(),Json.object()));}
    @Test void orphanDutyRequiresOwnerActionDeadlineNotPresence() throws Exception {var e=new BindingEvaluator(c());var o=Json.parse("{\"obligations\":[{\"kind\":\"REAUTHORIZE\",\"ownerRef\":\"salesOwner\",\"nextAction\":\"obtain grant\",\"nextCheckAt\":\"2026-10-07T04:00:00Z\"}]}");var valid=Json.parse("[{\"kind\":\"REAUTHORIZE\",\"ownerRef\":\"owner-id\",\"nextAction\":\"obtain grant\",\"nextCheckAt\":\"2026-10-07T04:00:00Z\"}]");var aliases=Json.parse("{\"salesOwner\":\"owner-id\"}");assertDoesNotThrow(()->e.obligations(o,Json.object(),valid,aliases));((ObjectNode)valid.get(0)).remove("ownerRef");assertThrows(IllegalArgumentException.class,()->e.obligations(o,Json.object(),valid,aliases));}
    @Test void recalledAndDisposedSamePhysicalTwentyFiveNeverCountFifty() throws Exception {
        var e=new BindingEvaluator(c());var a=Json.parse("{\"path\":\"state.recall.distinctProcessed.value\",\"expected\":\"25\"}");
        var rows=Json.parse("{\"data\":{\"rawRows\":[{\"dataset\":\"recallProcessing\",\"attribute\":\"quantity\",\"table\":\"recall_processing\",\"column\":\"quantity\",\"rowId\":\"recovered-1\",\"physicalScopeId\":\"scope-25\",\"unit\":\"BOX\",\"value\":\"25\"},{\"dataset\":\"recallProcessing\",\"attribute\":\"quantity\",\"table\":\"recall_processing\",\"column\":\"quantity\",\"rowId\":\"disposed-1\",\"physicalScopeId\":\"scope-25\",\"unit\":\"BOX\",\"value\":\"25\"}]}}");
        assertDoesNotThrow(()->e.assertSemantic(a,Json.object(),rows,List.of(),Json.object()));((ObjectNode)rows.path("data").path("rawRows").get(1)).put("physicalScopeId","different-scope");assertThrows(AssertionError.class,()->e.assertSemantic(a,Json.object(),rows,List.of(),Json.object()));
    }
    @Test void conflictingQuantityOrUnitsForSamePhysicalScopeFail() throws Exception {
        var e=new BindingEvaluator(c());var a=Json.parse("{\"path\":\"state.receipt.cumulative.value\",\"expected\":\"60\"}");var rows=Json.parse("{\"data\":{\"rawRows\":[{\"dataset\":\"receiptOccurrence\",\"attribute\":\"quantity\",\"table\":\"occurrence\",\"column\":\"quantity\",\"rowId\":\"d1\",\"physicalScopeId\":\"same-60\",\"unit\":\"BOX\",\"value\":\"60\"},{\"dataset\":\"receiptOccurrence\",\"attribute\":\"quantity\",\"table\":\"occurrence\",\"column\":\"quantity\",\"rowId\":\"d2\",\"physicalScopeId\":\"same-60\",\"unit\":\"BOX\",\"value\":\"60\"}]}}");
        assertDoesNotThrow(()->e.assertSemantic(a,Json.object(),rows,List.of(),Json.object()));((ObjectNode)rows.path("data").path("rawRows").get(1)).put("value","25");assertThrows(IllegalArgumentException.class,()->e.assertSemantic(a,Json.object(),rows,List.of(),Json.object()));((ObjectNode)rows.path("data").path("rawRows").get(1)).put("value","60").put("unit","EA");assertThrows(IllegalArgumentException.class,()->e.assertSemantic(a,Json.object(),rows,List.of(),Json.object()));
    }
    @Test void wrongReadAuditScopeFailsEvenWhenCountFits() throws Exception {var c=c();var e=new BindingEvaluator(c);var o=c.sourceCase(c.binding("M47")).path("turns").get(0).path("oracle");var a=(ObjectNode)audit().deepCopy();a.put("actorRef","actor").put("organizationRef","otherOrg").put("authorizationGrantRef","readOnlyProbeGrant").put("targetRef","AL1").put("accessContextActorRef","actor");assertThrows(IllegalArgumentException.class,()->e.effectWhitelist(o,Json.object(),List.of(a),Json.object()));}
    @Test void singleWrongUnitCannotMatchBoxExpectation() throws Exception {
        var e=new BindingEvaluator(c());var a=Json.parse("{\"path\":\"state.receipt.cumulative.value\",\"expected\":\"60\"}");var row=Json.parse("{\"data\":{\"rawRows\":[{\"dataset\":\"receiptOccurrence\",\"attribute\":\"quantity\",\"table\":\"occurrence\",\"column\":\"quantity\",\"rowId\":\"d1\",\"physicalScopeId\":\"p1\",\"unit\":\"EA\",\"value\":\"60\"}]}}");assertThrows(IllegalArgumentException.class,()->e.assertSemantic(a,Json.object(),row,List.of(),Json.object(),"BOX"));
    }
    @Test void existingHumanDutyCannotBeDeletedWithoutMatchingEffect() throws Exception {
        var e=new BindingEvaluator(c());var before=Json.parse("[{\"id\":\"ob1\",\"ownerRef\":\"human1\",\"status\":\"OPEN\"}]");assertThrows(IllegalArgumentException.class,()->e.preserveObligations(before,Json.array(),List.of()));var unrelated=Json.parse("{\"id\":\"event1\",\"classes\":[\"OBLIGATION\"],\"obligationRef\":\"other-ob\"}");assertThrows(IllegalArgumentException.class,()->e.preserveObligations(before,Json.array(),List.of(unrelated)));assertDoesNotThrow(()->e.preserveObligations(before,before,List.of()));
    }
    private JsonNode m47Call(JsonNode fixture,JsonNode aliases,String profile,String kind){var a=fixture.path("actors").path(profile);ObjectNode call=Json.object();call.put("actorProfile",profile).put("kind",kind).put("authenticated",true).put("wireArtifactRef","actual-wire.json");for(String key:List.of("issuer","subject","audience"))call.set(key,a.path(key));call.set("organizationRef",aliases.path("org"));call.set("authorizationGrantRef",aliases.path(a.path("grant").path("scope").path("grantAlias").asText()));call.set("targetRefs",Json.array().add(aliases.path("AL1")));call.set("constraintFacts",Json.parse("[{\"code\":\"GRANT_REVOKED\",\"grantRevision\":2}]"));call.put("outcome","FORBIDDEN");return call;}
    @Test void m47GroundedPreflightAndServerRejectionAreDistinct() throws Exception {var c=c();com.fasterxml.jackson.databind.JsonNode f=c.fixture(c.binding("M47")),aliases=f.path("aliases"),o=c.sourceCase(c.binding("M47")).path("turns").get(0).path("oracle");var e=new BindingEvaluator(c);var t=Json.object();t.put("terminal",true);t.set("toolCalls",Json.array().add(m47Call(f,aliases,"read-probe-actor","READ")));assertEquals("EVIDENCED_PREFLIGHT_STOP",e.selectPath(o,t,List.of(),aliases,f));((ArrayNode)t.path("toolCalls")).add(m47Call(f,aliases,"command-actor","COMMAND"));assertEquals("SERVER_REJECTION",e.selectPath(o,t,List.of(),aliases,f));}
    @Test void modelSelfLabelWithoutActualReadCannotSelectPreflight() throws Exception {var c=c();com.fasterxml.jackson.databind.JsonNode f=c.fixture(c.binding("M47")),o=c.sourceCase(c.binding("M47")).path("turns").get(0).path("oracle");assertThrows(IllegalArgumentException.class,()->new BindingEvaluator(c).selectPath(o,Json.parse("{\"terminal\":true,\"completionPath\":\"EVIDENCED_PREFLIGHT_STOP\",\"toolCalls\":[]}"),List.of(),f.path("aliases"),f));}
    @Test void readProbeCannotSubmitCommandOrSubstituteGrant() throws Exception {var c=c();com.fasterxml.jackson.databind.JsonNode f=c.fixture(c.binding("M47")),o=c.sourceCase(c.binding("M47")).path("turns").get(0).path("oracle");var call=m47Call(f,f.path("aliases"),"read-probe-actor","COMMAND");var t=Json.object();t.put("terminal",true).set("toolCalls",Json.array().add(call));assertThrows(IllegalArgumentException.class,()->new BindingEvaluator(c).selectPath(o,t,List.of(),f.path("aliases"),f));((ObjectNode)call).put("kind","READ").put("authorizationGrantRef","forged-grant");assertThrows(IllegalArgumentException.class,()->new BindingEvaluator(c).selectPath(o,t,List.of(),f.path("aliases"),f));}
    @Test void preflightCannotHideSuspensionBusinessWrite() throws Exception {var c=c();com.fasterxml.jackson.databind.JsonNode f=c.fixture(c.binding("M47")),o=c.sourceCase(c.binding("M47")).path("turns").get(0).path("oracle");var t=Json.object();t.put("terminal",true).set("toolCalls",Json.array().add(m47Call(f,f.path("aliases"),"read-probe-actor","READ")));assertThrows(IllegalArgumentException.class,()->new BindingEvaluator(c).selectPath(o,t,List.of(Json.parse("{\"id\":\"s1\",\"classes\":[\"ALLOCATION_SUSPENSION\"]}")),f.path("aliases"),f));}
}
