package org.mulino.verification.modelbinding;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.mulino.verification.*;
import java.nio.file.*;
import java.lang.reflect.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

/** Mutants of captured observation contracts only; no product/client execution. */
final class ModelBindingResponseEvidenceTest {
    private BindingContract contract() throws Exception{return new BindingContract(Path.of(System.getProperty("repo.root")));}
    private ObjectNode call(){return (ObjectNode)Json.parse("{\"callId\":\"rpc-replay\",\"capabilityId\":\"confirmReceipt\",\"wireArtifactRef\":\"captured-wire.json\",\"businessResponsePointer\":\"/response/result/structuredContent\",\"issuer\":\"issuer\",\"subject\":\"human\",\"audience\":\"api\",\"organizationRef\":\"org-id\",\"authorizationGrantRef\":\"grant-id\",\"outcome\":\"APPLIED\"}");}
    private JsonNode payload(){return Json.parse("{\"quantity\":\"60\",\"unit\":\"BOX\",\"placeRef\":\"w-id\",\"lotRef\":\"l-id\",\"sourceOccurrenceRef\":\"ev-id\",\"commandIdempotencyKey\":\"receipt-60-key\",\"stableRequestOwner\":\"human\"}");}
    private ObjectNode wire(){var w=(ObjectNode)Json.parse("{\"evidenceClass\":\"CAPTURED_CONTRACT_SELFTEST\",\"actionId\":\"turn-1/agent\",\"scope\":{\"installationId\":\"installation\",\"turnId\":\"turn-1\"},\"requestSentAt\":\"2026-10-08T00:00:01Z\",\"responseReceivedAt\":\"2026-10-08T00:00:02Z\",\"request\":{\"jsonrpc\":\"2.0\",\"id\":\"rpc-replay\",\"method\":\"tools/call\",\"params\":{\"name\":\"confirmReceipt\",\"arguments\":{}}},\"response\":{\"jsonrpc\":\"2.0\",\"id\":\"rpc-replay\",\"result\":{\"structuredContent\":{\"outcome\":\"APPLIED\",\"reusedCommittedResult\":true}}}}");w.set("toolCall",call());var a=Json.object();for(String k:List.of("issuer","subject","audience","organizationRef","authorizationGrantRef"))a.set(k,call().path(k));w.set("authenticatedActor",a);((ObjectNode)w.path("request").path("params")).set("arguments",payload());return w;}
    private CapturedApiObservation api(JsonNode wire){return new CapturedApiObservation(List.of(CapturedApiObservation.decode(call(),wire)),Json.parse("[{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"rpc-replay\"}]"));}
    private JsonNode intent(){return Json.parse("{\"status\":\"STRUCTURED\",\"intentKind\":\"RECORD\",\"capabilityId\":\"confirmReceipt\",\"slots\":{}}");}
    @Test void existingStateAndClientReplayClaimCannotReplaceActualCall(){var none=new CapturedApiObservation(List.of(),Json.array());assertThrows(IllegalArgumentException.class,()->none.requireExecutionCall(intent(),"confirmReceipt","DIRECT"));assertThrows(IllegalArgumentException.class,()->none.requireReplay(payload(),Json.object(),"confirmReceipt"));}
    @Test void authenticReplayNeedsFullSamePayloadAndActualResponse(){var a=api(wire());assertDoesNotThrow(()->a.requireReplay(payload(),Json.object(),"confirmReceipt"));assertDoesNotThrow(()->a.requireExecutionCall(intent(),"confirmReceipt","DIRECT"));}
    @Test void replayQuantityOwnerKeyAndUnitMutantsFail(){for(String field:List.of("quantity","unit","stableRequestOwner","commandIdempotencyKey","placeRef","lotRef","sourceOccurrenceRef")){var w=wire();((ObjectNode)w.path("request").path("params").path("arguments")).put(field,"changed");assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"),field);}}
    @Test void extraReplayPayloadAndRpcEffectKeyConflationFail(){var w=wire();((ObjectNode)w.path("request").path("params").path("arguments")).put("hiddenApproval",true);assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));var x=wire();((ObjectNode)x.path("request")).put("id","receipt-60-key");((ObjectNode)x.path("response")).put("id","receipt-60-key");assertThrows(IllegalArgumentException.class,()->api(x).requireReplay(payload(),Json.object(),"confirmReceipt"));}
    @Test void responseBodyCannotBeSubstitutedByClientSummary() throws Exception {var e=new BindingEvaluator(contract());var a=Json.parse("{\"path\":\"response.reusedCommittedResult\",\"expected\":true}");var client=Json.parse("{\"response\":{\"reusedCommittedResult\":true}}");assertThrows(IllegalArgumentException.class,()->e.assertSemantic(a,client,Json.object(),List.of(),Json.object()));var w=wire();((ObjectNode)w.path("response").path("result").path("structuredContent")).put("reusedCommittedResult",false);assertThrows(AssertionError.class,()->e.assertSemantic(a,client,Json.object(),List.of(),Json.object(),null,api(w)));assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));}
    @Test void requestResponseRpcAndCapabilityMismatchFail(){for(String mutant:List.of("id","capability","auth","missing-response","outcome")){var w=wire();switch(mutant){case "id"->((ObjectNode)w.path("response")).put("id","another-rpc");case "capability"->((ObjectNode)w.path("request").path("params")).put("name","dispatchQuantity");case "auth"->((ObjectNode)w.path("authenticatedActor")).put("authorizationGrantRef","other-grant");case "missing-response"->w.remove("response");case "outcome"->((ObjectNode)w.path("response").path("result").path("structuredContent")).put("outcome","FORBIDDEN");}assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.decode(call(),w),mutant);}}
    @Test void apiSourceRequiresCapturedIdAndUnambiguousPointer(){assertThrows(IllegalArgumentException.class,()->new CapturedApiObservation(List.of(),Json.parse("[{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"invented\"}]")));var c=CapturedApiObservation.decode(call(),wire());assertThrows(IllegalArgumentException.class,()->new CapturedApiObservation(List.of(c),Json.parse("[{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"rpc-replay\"},{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"rpc-replay\"}]")));var bad=call();bad.put("businessResponsePointer","/response/result/~2");var w=wire();w.set("toolCall",bad);assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.decode(bad,w));}
    @Test void capturedCallCannotComeFromSetupOrAnotherTurn(){var w=wire();var scope=w.path("scope").deepCopy();var command=Json.parse("{\"startedAt\":\"2026-10-08T00:00:00Z\",\"completedAt\":\"2026-10-08T00:00:03Z\"}");assertDoesNotThrow(()->CapturedApiObservation.checkCaptureContext(w,scope,w.path("actionId"),command));assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.checkCaptureContext(w,Json.object(),w.path("actionId"),command));assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.checkCaptureContext(w,scope,Json.MAPPER.valueToTree("install"),command));w.put("requestSentAt","2026-10-07T23:59:59Z");assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.checkCaptureContext(w,scope,w.path("actionId"),command));}
    @Test void legalGroundedPreflightNeedsNoCommandRpc(){var empty=new CapturedApiObservation(List.of(),Json.array());assertDoesNotThrow(()->empty.requireExecutionCall(intent(),"closeRecall","EVIDENCED_PREFLIGHT_STOP"));}
    private ObjectNode semantics(JsonNode response,String execution){var s=(ObjectNode)Json.parse("{\"extractor\":{\"independent\":true,\"source\":\"INDEPENDENT_FINAL_RESPONSE_SEMANTICS\",\"name\":\"captured-observation-test\",\"version\":\"1\"},\"coverage\":[\"CLAIMED_EFFECTS\",\"COMPLETION\",\"RESIDUAL_RESPONSIBILITY\"],\"complete\":true,\"claims\":{\"execution\":\"NOT_EXECUTED\",\"completion\":\"BLOCKED\",\"responsibility\":\"PRESERVED\",\"assertions\":[],\"residualObligations\":[]}}");s.set("sourceResponse",response);((ObjectNode)s.path("claims")).put("execution",execution);return s;}
    private void check(JsonNode sem,JsonNode response,String path,JsonNode after) throws Exception {FinalResponseObservation.check(sem,response,path,true,Json.parse("{\"outcome\":\"REJECTED\"}"),Json.object(),after,List.of(),Json.object(),new BindingEvaluator(contract()),new CapturedApiObservation(List.of(),Json.array()));}
    @Test void m52AndM57PreflightCannotClaimAppliedOrFulfilled() throws Exception {for(String wording:List.of("FULFILLED로 종료","All required goods arrived; the work is complete","회수 전량 처리했으므로 종료됐다")){var response=Json.object().put("outcome","APPLIED").put("text",wording);var sem=semantics(response,"NOT_EXECUTED");assertThrows(IllegalArgumentException.class,()->check(sem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));response.put("outcome","REJECTED");((ObjectNode)sem.path("claims")).put("completion","FULFILLED");sem.set("sourceResponse",response);assertThrows(IllegalArgumentException.class,()->check(sem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));}}
    @Test void serverRejectionAlsoCannotClaimClosedOrReleased() throws Exception {var response=Json.object().put("outcome","REJECTED");for(String field:List.of("completion","responsibility")){var sem=semantics(response,"REJECTED");((ObjectNode)sem.path("claims")).put(field,field.equals("completion")?"CLOSED":"RELEASED");assertThrows(IllegalArgumentException.class,()->check(sem,response,"SERVER_REJECTION",Json.object()));}}
    @Test void preflightAndServerRejectionSupportDifferentValidWording() throws Exception {for(String path:List.of("EVIDENCED_PREFLIGHT_STOP","SERVER_REJECTION")){var response=Json.object().put("outcome",path.equals("EVIDENCED_PREFLIGHT_STOP")?"STOPPED":"REJECTED").put("text",path.equals("EVIDENCED_PREFLIGHT_STOP")?"잔여25의 확인이 필요해 요청을 실행하지 않았다":"서버가 종료를 거부했고 담당자의 잔여 책임은 유지된다");assertDoesNotThrow(()->check(semantics(response,path.equals("EVIDENCED_PREFLIGHT_STOP")?"NOT_EXECUTED":"REJECTED"),response,path,Json.parse("{\"data\":{\"data\":{\"obligations\":[]}}}")));}}
    @Test void modelSelfLabelMissingCoverageAndDifferentFinalResponseFail() throws Exception {var response=Json.object().put("outcome","REJECTED");for(String mutant:List.of("self","coverage","response")){var sem=semantics(response,"NOT_EXECUTED");switch(mutant){case "self"->((ObjectNode)sem.path("extractor")).put("independent",false);case "coverage"->sem.set("coverage",Json.array());case "response"->sem.set("sourceResponse",Json.object().put("outcome","APPLIED"));}assertThrows(IllegalArgumentException.class,()->check(sem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));}}
    @Test void falseEffectCountAndRemainingQuantityFail() throws Exception {var response=Json.object().put("outcome","REJECTED");var effectSem=semantics(response,"NOT_EXECUTED");((com.fasterxml.jackson.databind.node.ArrayNode)effectSem.path("claims").path("assertions")).add(Json.parse("{\"semanticPath\":\"effects.businessEffectCount\",\"value\":1}"));assertThrows(AssertionError.class,()->check(effectSem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));var sem=semantics(response,"NOT_EXECUTED");((com.fasterxml.jackson.databind.node.ArrayNode)sem.path("claims").path("residualObligations")).add(Json.parse("{\"kind\":\"RECALL_UNACCOUNTED\",\"ownerRef\":\"admin\",\"quantity\":{\"value\":\"0\",\"unit\":\"BOX\"}}"));var remaining=sem;var after=Json.parse("{\"data\":{\"data\":{\"obligations\":[{\"kind\":\"RECALL_UNACCOUNTED\",\"ownerRef\":\"admin\",\"quantity\":{\"value\":\"25\",\"unit\":\"BOX\"}}]}}}");assertThrows(IllegalArgumentException.class,()->check(remaining,response,"EVIDENCED_PREFLIGHT_STOP",after));}
    @Test void negativePathCannotClaimExecutionEvenWithUnchangedState() throws Exception {var response=Json.object().put("outcome","REJECTED");assertThrows(IllegalArgumentException.class,()->check(semantics(response,"EXECUTED"),response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));}
    @Test void newOwnedSchemasValidateCapturedSamplesAndRejectMissingBodies() throws Exception {var c=contract();var w=wire();assertDoesNotThrow(()->c.validator.schema("verification/model-binding/captured-api.schema.json",w));w.remove("request");assertThrows(IllegalArgumentException.class,()->c.validator.schema("verification/model-binding/captured-api.schema.json",w));var s=semantics(Json.object(),"NOT_EXECUTED");s.put("evidenceClass","CAPTURED_CONTRACT_SELFTEST").put("sourceTranscriptRef","captured-test.json");s.set("scope",Json.object());((ObjectNode)s.path("extractor")).set("command",Json.object());assertDoesNotThrow(()->c.validator.schema("verification/model-binding/final-response-observation.schema.json",s));s.remove("sourceResponse");assertThrows(IllegalArgumentException.class,()->c.validator.schema("verification/model-binding/final-response-observation.schema.json",s));}
    private ObjectNode committedSnapshot(){return (ObjectNode)Json.parse("{\"data\":{\"rawRows\":[{\"dataset\":\"receiptOccurrence\",\"attribute\":\"quantity\",\"rowId\":\"receipt-id\",\"physicalScopeId\":\"scope-id\",\"value\":\"60\"},{\"dataset\":\"receiptOccurrence\",\"attribute\":\"commandIdempotencyKey\",\"rowId\":\"receipt-id\",\"value\":\"receipt-60-key\"},{\"dataset\":\"receiptOccurrence\",\"attribute\":\"stableRequestOwner\",\"rowId\":\"receipt-id\",\"value\":\"human\"}],\"data\":{\"effects\":[{\"id\":\"committed-effect\",\"classes\":[\"RECEIPT\",\"MOVEMENT\",\"OUTBOX\"],\"commandIdempotencyKey\":\"receipt-60-key\",\"stableRequestOwner\":\"human\"}]}}}");}
    private ObjectNode refsWire(){var w=wire();var r=(ObjectNode)w.path("response").path("result").path("structuredContent");r.put("committedReceiptOccurrenceRef","receipt-id").put("committedPhysicalScopeRef","scope-id");r.set("committedEffectRefs",Json.array().add("committed-effect"));return w;}
    @Test void replayReturnsExactExistingOccurrenceAndPhysicalScopeAndEffects(){var snapshot=committedSnapshot();assertDoesNotThrow(()->api(refsWire()).requireReplayReferences(snapshot,snapshot,payload(),"confirmReceipt"));}
    @Test void replayCannotSubstituteOccurrenceScopeOrEffectReferences(){for(String field:List.of("committedReceiptOccurrenceRef","committedPhysicalScopeRef","committedEffectRefs")){var w=refsWire();var r=(ObjectNode)w.path("response").path("result").path("structuredContent");if(field.equals("committedEffectRefs"))r.set(field,Json.array().add("invented-effect"));else r.put(field,field.equals("committedReceiptOccurrenceRef")?"scope-id":"receipt-id");var snapshot=committedSnapshot();assertThrows(IllegalArgumentException.class,()->api(w).requireReplayReferences(snapshot,snapshot,payload(),"confirmReceipt"));}}
    @Test void replayCannotDropOriginalLedgerOrChangeObservedOwner(){var before=committedSnapshot();var after=committedSnapshot();((ObjectNode)after.path("data").path("rawRows").get(2)).put("value","another-human");assertThrows(IllegalArgumentException.class,()->api(refsWire()).requireReplayReferences(before,after,payload(),"confirmReceipt"));var deleted=committedSnapshot();((com.fasterxml.jackson.databind.node.ArrayNode)deleted.path("data").path("data").path("effects")).removeAll();assertThrows(IllegalArgumentException.class,()->api(refsWire()).requireReplayReferences(before,deleted,payload(),"confirmReceipt"));}
    @Test void hostArtifactHashCannotBeReplacedByClientResponse() throws Exception {
        var c=contract();var r=new ModelBindingRunner(c,"M57","SIT",new UnimplementedDriver(),new AgentRunner.Scripted());Path file=Files.createTempFile(c.validator.path("verification/harness/target"),"binding-observation-",".json");
        try{Files.writeString(file,"{\"evidenceClass\":\"CAPTURED_CONTRACT_SELFTEST\"}");String ref=c.validator.root().relativize(file).toString();var execution=Json.object();execution.set("artifactRefs",Json.array().add(ref));var host=Json.object();var extractor=Json.object();var hash=Json.object().put("path",ref).put("sha256",Json.sha256(file)).put("sizeBytes",Files.size(file));extractor.set("inputArtifacts",Json.array().add(hash));host.set("extractor",extractor);var data=Json.object();data.set("hostObservation",host);execution.set("data",data);Method load=ModelBindingRunner.class.getDeclaredMethod("linkedArtifact",JsonNode.class,String.class,boolean.class);load.setAccessible(true);assertEquals("CAPTURED_CONTRACT_SELFTEST",((JsonNode)load.invoke(r,execution,ref,true)).path("evidenceClass").asText());Files.writeString(file,"{\"clientClaim\":\"APPLIED\"}");var failure=assertThrows(InvocationTargetException.class,()->load.invoke(r,execution,ref,true));assertTrue(failure.getCause() instanceof IllegalArgumentException);}
        finally{Files.deleteIfExists(file);}
    }

    @Test void typedReplayDoesNotHideBusinessFieldsOutsideSlots(){var w=wire();var typed=Json.object();var slots=Json.object();payload().fields().forEachRemaining(e->{var slot=Json.object();slot.set("value",e.getValue());slots.set(e.getKey(),slot);});typed.set("slots",slots);typed.put("capabilityId","confirmReceipt");((ObjectNode)w.path("request").path("params")).set("arguments",typed);assertDoesNotThrow(()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));typed.put("approvalOverride",true);assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));}

    @Test void m57PreflightCannotClaimTransferWithUnchangedAdminDuty() throws Exception {var response=Json.object().put("outcome","STOPPED");var sem=semantics(response,"NOT_EXECUTED");((ObjectNode)sem.path("claims")).put("responsibility","TRANSFERRED");var after=Json.parse("{\"data\":{\"data\":{\"obligations\":[{\"id\":\"recall-duty\",\"kind\":\"RECALL_UNACCOUNTED\",\"ownerRef\":\"admin\",\"status\":\"OPEN\"}]}}}");assertThrows(IllegalArgumentException.class,()->check(sem,response,"EVIDENCED_PREFLIGHT_STOP",after));}
    @Test void rejectedCommandCannotClaimTransferWithZeroBusinessEffects() throws Exception {var response=Json.object().put("outcome","REJECTED");var sem=semantics(response,"REJECTED");((ObjectNode)sem.path("claims")).put("responsibility","TRANSFERRED");assertThrows(IllegalArgumentException.class,()->check(sem,response,"SERVER_REJECTION",Json.parse("{\"data\":{\"data\":{\"obligations\":[]}}}")));}
    @Test void actualHandoverRequiresAssignmentRecipientAndClaimedResidualDuty() throws Exception {var response=Json.object().put("outcome","APPLIED");var sem=semantics(response,"EXECUTED");((ObjectNode)sem.path("claims")).put("responsibility","TRANSFERRED");var duty=Json.parse("{\"id\":\"duty\",\"ownerRef\":\"human-recipient\",\"status\":\"OPEN\"}");((com.fasterxml.jackson.databind.node.ArrayNode)sem.path("claims").path("residualObligations")).add(duty);var after=Json.object();var data=Json.object();data.set("obligations",Json.array().add(duty));after.set("data",Json.object().set("data",data));var effect=Json.parse("{\"id\":\"handover-event\",\"classes\":[\"OBLIGATION_ASSIGNMENT\"],\"obligationRef\":\"duty\",\"newOwnerRef\":\"human-recipient\"}");var e=new BindingEvaluator(contract());assertDoesNotThrow(()->FinalResponseObservation.check(sem,response,"DIRECT",false,Json.parse("{\"outcome\":\"APPLIED\"}"),Json.object(),after,List.of(effect),Json.object(),e,new CapturedApiObservation(List.of(),Json.array())));((ObjectNode)effect).put("newOwnerRef","invented-recipient");assertThrows(IllegalArgumentException.class,()->FinalResponseObservation.check(sem,response,"DIRECT",false,Json.parse("{\"outcome\":\"APPLIED\"}"),Json.object(),after,List.of(effect),Json.object(),e,new CapturedApiObservation(List.of(),Json.array())));}
    private Object invoke(ModelBindingRunner runner,String method,Class<?>[] types,Object... arguments) throws Exception {try{Method m=ModelBindingRunner.class.getDeclaredMethod(method,types);m.setAccessible(true);return m.invoke(runner,arguments);}catch(InvocationTargetException failure){if(failure.getCause() instanceof Exception e)throw e;if(failure.getCause() instanceof AssertionError e)throw e;throw failure;}}
    /** Schema/capture integration sample only. The runner never invokes an adapter or a model. */
    private void captureIntegration(boolean context,String mutant) throws Exception {
        var c=contract();String id=context?"M57":"M50",profile=context?"UAT":"SIT",action=context?"turn-1/context":"turn-1/agent";
        var runner=new ModelBindingRunner(c,id,profile,new UnimplementedDriver(),context?new AgentRunner.Actual((a,b,d,e,f)->{throw new AssertionError("No actual model in capture selftest");}):new AgentRunner.Scripted());
        JsonNode fixture=c.fixture(c.binding(id)),aliases=fixture.path("aliases"),actor=fixture.path("actors").path(context?"read-probe-actor":"command-actor");
        Field aliasesField=ModelBindingRunner.class.getDeclaredField("aliasMap");aliasesField.setAccessible(true);aliasesField.set(runner,aliases);
        Field resultsField=ModelBindingRunner.class.getDeclaredField("results");resultsField.setAccessible(true);@SuppressWarnings("unchecked") Map<String,JsonNode> results=(Map<String,JsonNode>)resultsField.get(runner);
        results.put("install",Json.parse("{\"data\":{\"installationId\":\"capture-contract-installation\"}}"));
        var scope=Json.object();scope.set("organizationId",aliases.path("org"));scope.put("installationId","capture-contract-installation").put("caseId",id).put("turnId","turn-1");
        Path file=Files.createTempFile(c.validator.path("verification/harness/target"),"capture-contract-integration-",".json");
        try {
            String ref=c.validator.root().relativize(file).toString();var metadata=call();metadata.put("wireArtifactRef",ref).put("callId",context?"context-rpc":"replay-rpc").put("kind",context?"READ":"COMMAND").put("capabilityId",context?"getObject":"confirmReceipt").put("actorProfile",context?"read-probe-actor":"command-actor").put("authenticated",true);
            for(String key:List.of("issuer","subject","audience"))metadata.set(key,actor.path(key));metadata.set("organizationRef",aliases.path("org"));metadata.set("authorizationGrantRef",aliases.path(actor.path("grant").path("scope").path("grantAlias").asText()));metadata.set("constraintFacts",Json.array());
            var business=Json.object().put("outcome",context?"READ":"APPLIED");if(context)business.set("constraintFacts",Json.array());else business.put("reusedCommittedResult",true);metadata.set("outcome",business.path("outcome"));
            var w=wire();w.put("evidenceClass","ACTUAL_API_CAPTURE").put("actionId",action);w.set("scope",scope);w.set("toolCall",metadata);var auth=Json.object();for(String key:List.of("issuer","subject","audience","organizationRef","authorizationGrantRef"))auth.set(key,metadata.path(key));w.set("authenticatedActor",auth);((ObjectNode)w.path("request").path("params")).set("name",metadata.path("capabilityId"));((ObjectNode)w.path("response").path("result")).set("structuredContent",business);
            if(mutant.equals("wrong-auth"))((ObjectNode)w.path("authenticatedActor")).put("authorizationGrantRef","substituted-grant");
            Files.writeString(file,w.toString());var hash=Json.object().put("path",ref).put("sha256",Json.sha256(file)).put("sizeBytes",Files.size(file));
            var provenance=Json.object().put("adapter","captured-contract-test-only").put("adapterVersion","1").put("buildVersion","SELFTEST").put("source","ACTUAL_AUTHENTICATED_TRANSPORT").put("independent",true).put("scopeComplete",true);var principal=Json.object();for(String key:List.of("issuer","subject","audience"))principal.set(key,actor.path(key));principal.set("organizationId",aliases.path("org"));principal.set("grantId",metadata.path("authorizationGrantRef"));provenance.set("authenticatedActor",principal);provenance.putNull("sourceQuery").putNull("snapshot");
            var data=Json.object();data.set("capturedArtifacts",Json.array().add(hash));if(context){data.set("authenticatedRead",metadata);data.set("permittedContext",Json.object());}else {data.set("capturedApiCalls",Json.array().add(metadata));data.set("apiAssertionSources",Json.array().add(Json.object().put("semanticPath","response.reusedCommittedResult").put("capturedCallId","replay-rpc")));}
            if(mutant.equals("missing-capture"))data.remove("capturedArtifacts");if(mutant.equals("wrong-source"))provenance.put("source","API_PROJECTION");if(mutant.equals("wrong-hash"))hash.put("sha256","0".repeat(64));if(mutant.equals("wrong-principal"))principal.put("subject","another-user");if(mutant.equals("non-independent"))provenance.put("independent",false);if(mutant.equals("legacy-extra"))provenance.put("independentCapture",true);if(mutant.equals("extra-artifact"))hash.put("adapterComputedExpected",true);
            var result=new StepResult(action,StepResult.DriverStatus.EXECUTED,data,business,null,provenance,List.of(ref));
            // Both the real common schema/result validator and the binding save/authentication run.
            c.validator.result(result,context?"query":"agent");
            invoke(runner,"save",new Class<?>[]{String.class,StepResult.class,String.class},action,result,context?"query":"agent");
            if(context){var witness=(JsonNode)invoke(runner,"completionWitness",new Class<?>[]{JsonNode.class,String.class},Json.object(),"turn-1");assertEquals(1,witness.path("contextReads").size());}
            else {var captured=(CapturedApiObservation)invoke(runner,"capturedApis",new Class<?>[]{JsonNode.class,JsonNode.class,String.class},result.toJson(),Json.object(),"turn-1");assertTrue(captured.response("response.reusedCommittedResult").path("reusedCommittedResult").asBoolean());}
            assertEquals("NOT_RUN",runner.status());
        }finally{Files.deleteIfExists(file);}
    }
    @Test void schemaValidExecutedSitCaptureReachesActualBindingLoader() throws Exception {captureIntegration(false,"valid");}
    @Test void schemaValidExecutedUatContextCaptureReachesActualBindingLoader() throws Exception {captureIntegration(true,"valid");}
    @Test void sitCaptureMissingOrWrongAuthenticationSourceOrHashFails() {for(String mutant:List.of("missing-capture","wrong-auth","wrong-source","wrong-hash","wrong-principal","non-independent","legacy-extra","extra-artifact"))assertThrows(IllegalArgumentException.class,()->captureIntegration(false,mutant),mutant);}
    @Test void uatContextMissingOrWrongAuthenticationSourceOrHashFails() {for(String mutant:List.of("missing-capture","wrong-auth","wrong-source","wrong-hash","wrong-principal","non-independent","legacy-extra","extra-artifact"))assertThrows(IllegalArgumentException.class,()->captureIntegration(true,mutant),mutant);}
    private CapturedApiObservation readApi(){
        var call=call();call.put("callId","rpc-read").put("capabilityId","getObject").put("outcome","READ");
        var w=wire();w.set("toolCall",call);((ObjectNode)w.path("request")).put("id","rpc-read");((ObjectNode)w.path("response")).put("id","rpc-read");((ObjectNode)w.path("request").path("params")).put("name","getObject");
        ((ObjectNode)w.path("response").path("result")).set("structuredContent",Json.parse("{\"outcome\":\"READ\",\"onHand\":{\"value\":\"100\",\"unit\":\"BOX\"},\"eligible\":{\"value\":\"40\",\"unit\":\"BOX\"},\"unreservedEligible\":{\"value\":\"40\",\"unit\":\"BOX\"}}"));
        var sources=Json.array();for(String path:List.of("response.onHand.value","response.eligible.value","response.unreservedEligible.value"))sources.add(Json.object().put("semanticPath",path).put("capturedCallId","rpc-read"));
        return new CapturedApiObservation(List.of(CapturedApiObservation.decode(call,w)),sources);
    }
    private ObjectNode readSemantics(JsonNode response,boolean answeredCoverage,String... claims){
        var s=semantics(response,"READ");((ObjectNode)s.path("claims")).put("completion","NOT_CLAIMED").put("responsibility","NOT_CLAIMED");
        if(answeredCoverage)((com.fasterxml.jackson.databind.node.ArrayNode)s.path("coverage")).add(FinalResponseObservation.ANSWERED_READ_VALUES);
        for(String claim:claims)((com.fasterxml.jackson.databind.node.ArrayNode)s.path("claims").path("assertions")).add(Json.parse(claim));
        return s;
    }
    private void checkRead(JsonNode sem,JsonNode response) throws Exception {var c=contract();var oracle=c.sourceCase(c.binding("M01")).path("turns").get(0).path("oracle");FinalResponseObservation.check(sem,response,"DIRECT",false,oracle,Json.object(),Json.parse("{\"data\":{\"data\":{\"obligations\":[]}}}"),List.of(),Json.object(),new BindingEvaluator(c),readApi());}
    @Test void queryAnswerMustStateEveryReadValueWithUnitAgainstAuthenticatedApi() throws Exception {
        var response=Json.object().put("text","보유100 BOX, 판매 가능40 BOX, 미예약40 BOX다");
        String onHand="{\"semanticPath\":\"response.onHand.value\",\"value\":\"100\",\"unit\":\"BOX\"}",eligible="{\"semanticPath\":\"response.eligible.value\",\"value\":\"40\",\"unit\":\"BOX\"}",unreserved="{\"semanticPath\":\"response.unreservedEligible.value\",\"value\":\"40\",\"unit\":\"BOX\"}";
        assertDoesNotThrow(()->checkRead(readSemantics(response,true,onHand,eligible,unreserved),response));
        var silent=Json.object().put("text","조회했습니다");
        assertThrows(IllegalArgumentException.class,()->checkRead(readSemantics(silent,true),silent),"answer without values");
        assertThrows(IllegalArgumentException.class,()->checkRead(readSemantics(response,false,onHand,eligible,unreserved),response),"answered-values coverage missing");
        assertThrows(IllegalArgumentException.class,()->checkRead(readSemantics(response,true,onHand,eligible),response),"one read value omitted");
        assertThrows(IllegalArgumentException.class,()->checkRead(readSemantics(response,true,onHand.replace(",\"unit\":\"BOX\"",""),eligible,unreserved),response),"quantity without unit");
        assertThrows(AssertionError.class,()->checkRead(readSemantics(response,true,onHand.replace("\"100\"","\"60\""),eligible,unreserved),response),"wrong answered value");
    }

}
