package org.mulino.verification.modelbinding;

import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.Test;
import org.mulino.verification.Json;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;

/** Real preparation producer/consumer integration; no product or model execution. */
final class ModelBindingPreparationCoverageTest {
    @Test void generatedPreparationIsConsumedWithoutClaimingRuntime() throws Exception {
        Path root = Path.of(System.getProperty("repo.root")).toRealPath();
        var report = new BindingContract(root).prepare();
        assertEquals("NOT_RUN", report.path("runtimeStatus").asText());
        assertEquals(0, report.path("actualModelCalls").asInt());
        assertTrue(report.path("attempts").isEmpty());
        assertTrue(report.path("usage").isNull());
        assertTrue(report.path("cost").isNull());
        assertFalse(report.path("productGateComplete").asBoolean());

        Path evidence = root.resolve("verification/harness/target/evidence");
        Files.createDirectories(evidence);
        Path reportFile = Files.createTempFile(evidence, "model-preparation-contract-", ".json");
        try {
            // Consume the generated bytes and their real binding/source hashes, not a mock report.
            Json.write(reportFile, report);
            JsonNode actual = consume(root, reportFile);
            assertEquals("PREPARED", actual.path("model").path("preparationStatus").asText());
            assertEquals(60, actual.path("model").path("caseCount").asInt());
            assertEquals(73, actual.path("model").path("turnCount").asInt());
            assertTrue(actual.path("preparationProblems").isEmpty(), actual.toString());
            assertEquals("NOT_RUN", actual.path("model").path("status").asText());
            // Missing actual runtime accounting remains unknown; preparation calls0 is not copied.
            for (String metric : new String[]{"actualModelCalls", "usage", "cost"})
                assertTrue(actual.path("model").path(metric).isNull(), metric);

            report.put("preparationStatus", "PASS");
            Json.write(reportFile, report);
            assertEquals("NOT_RUN", consume(root, reportFile).path("model").path("preparationStatus").asText(),
                    "Runtime PASS must not substitute for the canonical preparation enum");
        } finally {
            Files.deleteIfExists(reportFile);
        }
    }

    private JsonNode consume(Path root, Path report) throws Exception {
        String script = """
                import importlib.util, json, pathlib, sys
                root = pathlib.Path(sys.argv[1])
                spec = importlib.util.spec_from_file_location('preparation_contract_assembly', root / 'verification/coverage/assemble.py')
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                assembly = module.Assembly(root)
                model = assembly.model({'modelBindingReportRef': sys.argv[2]}, {})
                print(json.dumps({'model': model, 'preparationProblems': assembly.preparation_problems}))
                """;
        Process process = new ProcessBuilder("python3", "-c", script, root.toString(), root.relativize(report).toString())
                .directory(root.toFile()).redirectErrorStream(true).start();
        if (!process.waitFor(30, TimeUnit.SECONDS)) {
            process.destroyForcibly().waitFor();
            fail("Coverage consumer timed out");
        }
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        assertEquals(0, process.exitValue(), output);
        return Json.parse(output);
    }
}
