package org.mulino.verification.modelbinding;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.mulino.verification.*;
import java.nio.file.*;
import java.lang.reflect.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

/** Mutants of captured observation contracts only; no product/client execution. */
final class ModelBindingResponseEvidenceTest {
    private BindingContract contract() throws Exception{return new BindingContract(Path.of(System.getProperty("repo.root")));}
    private ObjectNode call(){return (ObjectNode)Json.parse("{\"callId\":\"rpc-replay\",\"capabilityId\":\"confirmReceipt\",\"wireArtifactRef\":\"captured-wire.json\",\"businessResponsePointer\":\"/response/result/structuredContent\",\"issuer\":\"issuer\",\"subject\":\"human\",\"audience\":\"api\",\"organizationRef\":\"org-id\",\"authorizationGrantRef\":\"grant-id\",\"outcome\":\"APPLIED\"}");}
    private JsonNode payload(){return Json.parse("{\"quantity\":\"60\",\"unit\":\"BOX\",\"placeRef\":\"w-id\",\"lotRef\":\"l-id\",\"sourceOccurrenceRef\":\"ev-id\",\"commandIdempotencyKey\":\"receipt-60-key\",\"stableRequestOwner\":\"human\"}");}
    private ObjectNode wire(){var w=(ObjectNode)Json.parse("{\"evidenceClass\":\"CAPTURED_CONTRACT_SELFTEST\",\"actionId\":\"turn-1/agent\",\"scope\":{\"installationId\":\"installation\",\"turnId\":\"turn-1\"},\"requestSentAt\":\"2026-10-08T00:00:01Z\",\"responseReceivedAt\":\"2026-10-08T00:00:02Z\",\"request\":{\"jsonrpc\":\"2.0\",\"id\":\"rpc-replay\",\"method\":\"tools/call\",\"params\":{\"name\":\"confirmReceipt\",\"arguments\":{}}},\"response\":{\"jsonrpc\":\"2.0\",\"id\":\"rpc-replay\",\"result\":{\"structuredContent\":{\"outcome\":\"APPLIED\",\"reusedCommittedResult\":true}}}}");w.set("toolCall",call());var a=Json.object();for(String k:List.of("issuer","subject","audience","organizationRef","authorizationGrantRef"))a.set(k,call().path(k));w.set("authenticatedActor",a);((ObjectNode)w.path("request").path("params")).set("arguments",payload());return w;}
    private CapturedApiObservation api(JsonNode wire){return new CapturedApiObservation(List.of(CapturedApiObservation.decode(call(),wire)),Json.parse("[{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"rpc-replay\"}]"));}
    private JsonNode intent(){return Json.parse("{\"status\":\"STRUCTURED\",\"intentKind\":\"RECORD\",\"capabilityId\":\"confirmReceipt\",\"slots\":{}}");}
    @Test void existingStateAndClientReplayClaimCannotReplaceActualCall(){var none=new CapturedApiObservation(List.of(),Json.array());assertThrows(IllegalArgumentException.class,()->none.requireExecutionCall(intent(),"confirmReceipt","DIRECT"));assertThrows(IllegalArgumentException.class,()->none.requireReplay(payload(),Json.object(),"confirmReceipt"));}
    @Test void authenticReplayNeedsFullSamePayloadAndActualResponse(){var a=api(wire());assertDoesNotThrow(()->a.requireReplay(payload(),Json.object(),"confirmReceipt"));assertDoesNotThrow(()->a.requireExecutionCall(intent(),"confirmReceipt","DIRECT"));}
    @Test void replayQuantityOwnerKeyAndUnitMutantsFail(){for(String field:List.of("quantity","unit","stableRequestOwner","commandIdempotencyKey","placeRef","lotRef","sourceOccurrenceRef")){var w=wire();((ObjectNode)w.path("request").path("params").path("arguments")).put(field,"changed");assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"),field);}}
    @Test void extraReplayPayloadAndRpcEffectKeyConflationFail(){var w=wire();((ObjectNode)w.path("request").path("params").path("arguments")).put("hiddenApproval",true);assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));var x=wire();((ObjectNode)x.path("request")).put("id","receipt-60-key");((ObjectNode)x.path("response")).put("id","receipt-60-key");assertThrows(IllegalArgumentException.class,()->api(x).requireReplay(payload(),Json.object(),"confirmReceipt"));}
    @Test void responseBodyCannotBeSubstitutedByClientSummary() throws Exception {var e=new BindingEvaluator(contract());var a=Json.parse("{\"path\":\"response.reusedCommittedResult\",\"expected\":true}");var client=Json.parse("{\"response\":{\"reusedCommittedResult\":true}}");assertThrows(IllegalArgumentException.class,()->e.assertSemantic(a,client,Json.object(),List.of(),Json.object()));var w=wire();((ObjectNode)w.path("response").path("result").path("structuredContent")).put("reusedCommittedResult",false);assertThrows(AssertionError.class,()->e.assertSemantic(a,client,Json.object(),List.of(),Json.object(),null,api(w)));assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));}
    @Test void requestResponseRpcAndCapabilityMismatchFail(){for(String mutant:List.of("id","capability","auth","missing-response","outcome")){var w=wire();switch(mutant){case "id"->((ObjectNode)w.path("response")).put("id","another-rpc");case "capability"->((ObjectNode)w.path("request").path("params")).put("name","dispatchQuantity");case "auth"->((ObjectNode)w.path("authenticatedActor")).put("authorizationGrantRef","other-grant");case "missing-response"->w.remove("response");case "outcome"->((ObjectNode)w.path("response").path("result").path("structuredContent")).put("outcome","FORBIDDEN");}assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.decode(call(),w),mutant);}}
    @Test void apiSourceRequiresCapturedIdAndUnambiguousPointer(){assertThrows(IllegalArgumentException.class,()->new CapturedApiObservation(List.of(),Json.parse("[{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"invented\"}]")));var c=CapturedApiObservation.decode(call(),wire());assertThrows(IllegalArgumentException.class,()->new CapturedApiObservation(List.of(c),Json.parse("[{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"rpc-replay\"},{\"semanticPath\":\"response.reusedCommittedResult\",\"capturedCallId\":\"rpc-replay\"}]")));var bad=call();bad.put("businessResponsePointer","/response/result/~2");var w=wire();w.set("toolCall",bad);assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.decode(bad,w));}
    @Test void capturedCallCannotComeFromSetupOrAnotherTurn(){var w=wire();var scope=w.path("scope").deepCopy();var command=Json.parse("{\"startedAt\":\"2026-10-08T00:00:00Z\",\"completedAt\":\"2026-10-08T00:00:03Z\"}");assertDoesNotThrow(()->CapturedApiObservation.checkCaptureContext(w,scope,w.path("actionId"),command));assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.checkCaptureContext(w,Json.object(),w.path("actionId"),command));assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.checkCaptureContext(w,scope,Json.MAPPER.valueToTree("install"),command));w.put("requestSentAt","2026-10-07T23:59:59Z");assertThrows(IllegalArgumentException.class,()->CapturedApiObservation.checkCaptureContext(w,scope,w.path("actionId"),command));}
    @Test void legalGroundedPreflightNeedsNoCommandRpc(){var empty=new CapturedApiObservation(List.of(),Json.array());assertDoesNotThrow(()->empty.requireExecutionCall(intent(),"closeRecall","EVIDENCED_PREFLIGHT_STOP"));}
    private ObjectNode semantics(JsonNode response,String execution){var s=(ObjectNode)Json.parse("{\"extractor\":{\"independent\":true,\"source\":\"INDEPENDENT_FINAL_RESPONSE_SEMANTICS\",\"name\":\"captured-observation-test\",\"version\":\"1\"},\"coverage\":[\"CLAIMED_EFFECTS\",\"COMPLETION\",\"RESIDUAL_RESPONSIBILITY\"],\"complete\":true,\"claims\":{\"execution\":\"NOT_EXECUTED\",\"completion\":\"BLOCKED\",\"responsibility\":\"PRESERVED\",\"assertions\":[],\"residualObligations\":[]}}");s.set("sourceResponse",response);((ObjectNode)s.path("claims")).put("execution",execution);return s;}
    private void check(JsonNode sem,JsonNode response,String path,JsonNode after) throws Exception {FinalResponseObservation.check(sem,response,path,true,Json.parse("{\"outcome\":\"REJECTED\"}"),Json.object(),after,List.of(),Json.object(),new BindingEvaluator(contract()),new CapturedApiObservation(List.of(),Json.array()));}
    @Test void m52AndM57PreflightCannotClaimAppliedOrFulfilled() throws Exception {for(String wording:List.of("FULFILLED로 종료","All required goods arrived; the work is complete","회수 전량 처리했으므로 종료됐다")){var response=Json.object().put("outcome","APPLIED").put("text",wording);var sem=semantics(response,"NOT_EXECUTED");assertThrows(IllegalArgumentException.class,()->check(sem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));response.put("outcome","REJECTED");((ObjectNode)sem.path("claims")).put("completion","FULFILLED");sem.set("sourceResponse",response);assertThrows(IllegalArgumentException.class,()->check(sem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));}}
    @Test void serverRejectionAlsoCannotClaimClosedOrReleased() throws Exception {var response=Json.object().put("outcome","REJECTED");for(String field:List.of("completion","responsibility")){var sem=semantics(response,"REJECTED");((ObjectNode)sem.path("claims")).put(field,field.equals("completion")?"CLOSED":"RELEASED");assertThrows(IllegalArgumentException.class,()->check(sem,response,"SERVER_REJECTION",Json.object()));}}
    @Test void preflightAndServerRejectionSupportDifferentValidWording() throws Exception {for(String path:List.of("EVIDENCED_PREFLIGHT_STOP","SERVER_REJECTION")){var response=Json.object().put("outcome",path.equals("EVIDENCED_PREFLIGHT_STOP")?"STOPPED":"REJECTED").put("text",path.equals("EVIDENCED_PREFLIGHT_STOP")?"잔여25의 확인이 필요해 요청을 실행하지 않았다":"서버가 종료를 거부했고 담당자의 잔여 책임은 유지된다");assertDoesNotThrow(()->check(semantics(response,path.equals("EVIDENCED_PREFLIGHT_STOP")?"NOT_EXECUTED":"REJECTED"),response,path,Json.parse("{\"data\":{\"data\":{\"obligations\":[]}}}")));}}
    @Test void modelSelfLabelMissingCoverageAndDifferentFinalResponseFail() throws Exception {var response=Json.object().put("outcome","REJECTED");for(String mutant:List.of("self","coverage","response")){var sem=semantics(response,"NOT_EXECUTED");switch(mutant){case "self"->((ObjectNode)sem.path("extractor")).put("independent",false);case "coverage"->sem.set("coverage",Json.array());case "response"->sem.set("sourceResponse",Json.object().put("outcome","APPLIED"));}assertThrows(IllegalArgumentException.class,()->check(sem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));}}
    @Test void falseEffectCountAndRemainingQuantityFail() throws Exception {var response=Json.object().put("outcome","REJECTED");var effectSem=semantics(response,"NOT_EXECUTED");((com.fasterxml.jackson.databind.node.ArrayNode)effectSem.path("claims").path("assertions")).add(Json.parse("{\"semanticPath\":\"effects.businessEffectCount\",\"value\":1}"));assertThrows(AssertionError.class,()->check(effectSem,response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));var sem=semantics(response,"NOT_EXECUTED");((com.fasterxml.jackson.databind.node.ArrayNode)sem.path("claims").path("residualObligations")).add(Json.parse("{\"kind\":\"RECALL_UNACCOUNTED\",\"ownerRef\":\"admin\",\"quantity\":{\"value\":\"0\",\"unit\":\"BOX\"}}"));var remaining=sem;var after=Json.parse("{\"data\":{\"data\":{\"obligations\":[{\"kind\":\"RECALL_UNACCOUNTED\",\"ownerRef\":\"admin\",\"quantity\":{\"value\":\"25\",\"unit\":\"BOX\"}}]}}}");assertThrows(IllegalArgumentException.class,()->check(remaining,response,"EVIDENCED_PREFLIGHT_STOP",after));}
    @Test void negativePathCannotClaimExecutionEvenWithUnchangedState() throws Exception {var response=Json.object().put("outcome","REJECTED");assertThrows(IllegalArgumentException.class,()->check(semantics(response,"EXECUTED"),response,"EVIDENCED_PREFLIGHT_STOP",Json.object()));}
    @Test void newOwnedSchemasValidateCapturedSamplesAndRejectMissingBodies() throws Exception {var c=contract();var w=wire();assertDoesNotThrow(()->c.validator.schema("verification/model-binding/captured-api.schema.json",w));w.remove("request");assertThrows(IllegalArgumentException.class,()->c.validator.schema("verification/model-binding/captured-api.schema.json",w));var s=semantics(Json.object(),"NOT_EXECUTED");s.put("evidenceClass","CAPTURED_CONTRACT_SELFTEST").put("sourceTranscriptRef","captured-test.json");s.set("scope",Json.object());((ObjectNode)s.path("extractor")).set("command",Json.object());assertDoesNotThrow(()->c.validator.schema("verification/model-binding/final-response-observation.schema.json",s));s.remove("sourceResponse");assertThrows(IllegalArgumentException.class,()->c.validator.schema("verification/model-binding/final-response-observation.schema.json",s));}
    private ObjectNode committedSnapshot(){return (ObjectNode)Json.parse("{\"data\":{\"rawRows\":[{\"dataset\":\"receiptOccurrence\",\"attribute\":\"quantity\",\"rowId\":\"receipt-id\",\"physicalScopeId\":\"scope-id\",\"value\":\"60\"},{\"dataset\":\"receiptOccurrence\",\"attribute\":\"commandIdempotencyKey\",\"rowId\":\"receipt-id\",\"value\":\"receipt-60-key\"},{\"dataset\":\"receiptOccurrence\",\"attribute\":\"stableRequestOwner\",\"rowId\":\"receipt-id\",\"value\":\"human\"}],\"data\":{\"effects\":[{\"id\":\"committed-effect\",\"classes\":[\"RECEIPT\",\"MOVEMENT\",\"OUTBOX\"],\"commandIdempotencyKey\":\"receipt-60-key\",\"stableRequestOwner\":\"human\"}]}}}");}
    private ObjectNode refsWire(){var w=wire();var r=(ObjectNode)w.path("response").path("result").path("structuredContent");r.put("committedReceiptOccurrenceRef","receipt-id").put("committedPhysicalScopeRef","scope-id");r.set("committedEffectRefs",Json.array().add("committed-effect"));return w;}
    @Test void replayReturnsExactExistingOccurrenceAndPhysicalScopeAndEffects(){var snapshot=committedSnapshot();assertDoesNotThrow(()->api(refsWire()).requireReplayReferences(snapshot,snapshot,payload(),"confirmReceipt"));}
    @Test void replayCannotSubstituteOccurrenceScopeOrEffectReferences(){for(String field:List.of("committedReceiptOccurrenceRef","committedPhysicalScopeRef","committedEffectRefs")){var w=refsWire();var r=(ObjectNode)w.path("response").path("result").path("structuredContent");if(field.equals("committedEffectRefs"))r.set(field,Json.array().add("invented-effect"));else r.put(field,field.equals("committedReceiptOccurrenceRef")?"scope-id":"receipt-id");var snapshot=committedSnapshot();assertThrows(IllegalArgumentException.class,()->api(w).requireReplayReferences(snapshot,snapshot,payload(),"confirmReceipt"));}}
    @Test void replayCannotDropOriginalLedgerOrChangeObservedOwner(){var before=committedSnapshot();var after=committedSnapshot();((ObjectNode)after.path("data").path("rawRows").get(2)).put("value","another-human");assertThrows(IllegalArgumentException.class,()->api(refsWire()).requireReplayReferences(before,after,payload(),"confirmReceipt"));var deleted=committedSnapshot();((com.fasterxml.jackson.databind.node.ArrayNode)deleted.path("data").path("data").path("effects")).removeAll();assertThrows(IllegalArgumentException.class,()->api(refsWire()).requireReplayReferences(before,deleted,payload(),"confirmReceipt"));}
    @Test void hostArtifactHashCannotBeReplacedByClientResponse() throws Exception {
        var c=contract();var r=new ModelBindingRunner(c,"M57","SIT",new UnimplementedDriver(),new AgentRunner.Scripted());Path file=Files.createTempFile(c.validator.path("verification/harness/target"),"binding-observation-",".json");
        try{Files.writeString(file,"{\"evidenceClass\":\"CAPTURED_CONTRACT_SELFTEST\"}");String ref=c.validator.root().relativize(file).toString();var execution=Json.object();execution.set("artifactRefs",Json.array().add(ref));var host=Json.object();var extractor=Json.object();var hash=Json.object().put("path",ref).put("sha256",Json.sha256(file)).put("sizeBytes",Files.size(file));extractor.set("inputArtifacts",Json.array().add(hash));host.set("extractor",extractor);var data=Json.object();data.set("hostObservation",host);execution.set("data",data);Method load=ModelBindingRunner.class.getDeclaredMethod("linkedArtifact",JsonNode.class,String.class,boolean.class);load.setAccessible(true);assertEquals("CAPTURED_CONTRACT_SELFTEST",((JsonNode)load.invoke(r,execution,ref,true)).path("evidenceClass").asText());Files.writeString(file,"{\"clientClaim\":\"APPLIED\"}");var failure=assertThrows(InvocationTargetException.class,()->load.invoke(r,execution,ref,true));assertTrue(failure.getCause() instanceof IllegalArgumentException);}
        finally{Files.deleteIfExists(file);}
    }

    @Test void typedReplayDoesNotHideBusinessFieldsOutsideSlots(){var w=wire();var typed=Json.object();var slots=Json.object();payload().fields().forEachRemaining(e->{var slot=Json.object();slot.set("value",e.getValue());slots.set(e.getKey(),slot);});typed.set("slots",slots);typed.put("capabilityId","confirmReceipt");((ObjectNode)w.path("request").path("params")).set("arguments",typed);assertDoesNotThrow(()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));typed.put("approvalOverride",true);assertThrows(IllegalArgumentException.class,()->api(w).requireReplay(payload(),Json.object(),"confirmReceipt"));}

}
