package com.mulino.application.trade.purchase;

import com.mulino.application.core.*;
import com.mulino.application.identity.IdentityAuthorization;
import com.mulino.application.policy.PolicyCommandGuard;
import com.mulino.application.runtime.RuntimeDutyPort;
import com.mulino.application.work.WorkAccess;
import com.mulino.domain.identity.IdentityRepository;
import com.mulino.domain.trade.purchase.PurchaseRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import org.springframework.stereotype.Component;

/** Commercial decisions are immutable and distinct from physical arrival facts. */
@Component
public class PurchaseCommands implements CommandHandler,PurchaseLinePort {
 private final PurchaseConditions conditions;private final PurchaseRepository r;private final WorkAccess works;private final IdentityRepository identities;
 private final IdentityAuthorization auth;private final PolicyCommandGuard policy;private final TransactionalOutboxPort outbox;
 private final com.mulino.application.trade.TradeEvidence evidence;private final RuntimeDutyPort duties;private final ExecutionClock clock;private final ObjectMapper json=new ObjectMapper();
 public PurchaseCommands(PurchaseRepository r,WorkAccess works,IdentityRepository identities,IdentityAuthorization auth,PolicyCommandGuard policy,TransactionalOutboxPort outbox,RuntimeDutyPort duties,ExecutionClock clock,com.mulino.application.trade.TradeEvidence evidence,PurchaseConditions conditions){this.r=r;this.works=works;this.identities=identities;this.auth=auth;this.policy=policy;this.outbox=outbox;this.duties=duties;this.clock=clock;this.evidence=evidence;this.conditions=conditions;}
 public Set<String> capabilities(){return Set.of("proposePurchase","revisePurchase","approvePurchase","dispatchPurchaseOrder","recordSupplierReply","cancelPurchase");}
 public Set<String> definitionVersions(){return Set.of("1.0.0","definition-v1");}
 public Set<String> intentKinds(){return Set.of("COMMAND","RECORD");}
 private static Map<String,Object> map(Object v){if(!(v instanceof Map<?,?> m))throw DomainError.invalid("Object required");return (Map<String,Object>)m;}
 private static Object unwrap(Object v){return v instanceof Map<?,?> m&&m.containsKey("value")?m.get("value"):v;}
 private static String text(Map<String,Object> p,String k){Object v=unwrap(p.get(k));if(!(v instanceof String s)||s.isBlank())throw DomainError.invalid("Missing "+k);return s;}
 private static String uuid(Map<String,Object> p,String k){String id=text(p,k);CommandRequests.uuid(id);return id;}
 private static int number(Object x){return ((Number)x).intValue();}
 private static Instant instant(Object x){return x instanceof Instant t?t:Instant.parse(x.toString());}
 private static BigDecimal amount(Object x,boolean positive){try{var q=new BigDecimal(unwrap(x).toString());if(q.scale()>12||q.precision()>38||(positive?q.signum()<=0:q.signum()<0))throw DomainError.invalid("Invalid decimal");return q;}catch(NumberFormatException|NullPointerException ex){throw DomainError.invalid("Decimal string required");}}
 private static String dimension(Map<String,Object> p,String field,String dim){Object v=p.get(field);if(v instanceof Map<?,?> m&&m.get(dim)!=null)return m.get(dim).toString();return text(p,dim);}
 private Map<String,Object> parameters(Map<String,Object> i){return map(i.get("slots"));}
 private String operation(Map<String,Object> i){return text(i,"capabilityId");}
 private Map<String,Object> lineForOrder(DomainContext c,String id){r.require(c,"Orders",id);return r.rows(c,"OrderLines").stream().filter(x->id.equals(x.get("orderId"))).findFirst().orElseThrow(DomainError::forbidden);}
 private Map<String,Object> target(DomainContext c,Map<String,Object> i){var p=parameters(i);String op=operation(i);if(op.equals("proposePurchase"))return works.require(c,uuid(p,"workId"),false);if(op.equals("recordSupplierReply")||op.equals("cancelPurchase"))return lineForOrder(c,uuid(p,"purchaseId"));return r.revision(c,uuid(p,"proposalId"));}
 public CommandPreparation prepare(DomainContext c,Map<String,Object> i){
  var p=parameters(i);String op=operation(i);var t=target(c,i);String work=op.equals("proposePurchase")?t.get("ID").toString():t.get("workId").toString();var w=works.require(c,work,false);
  String item=t.get("itemId").toString(),destination=op.equals("proposePurchase")?uuid(p,"destinationId"):t.get("destinationId").toString();
  var scopes=new LinkedHashMap<String,List<String>>();scopes.put("ITEM",List.of(item));scopes.put("WORK",List.of(work));scopes.put("PLACE",List.of(destination));
  var actors=new HashSet<String>(List.of(w.get("ownerId").toString(),w.get("supervisorId").toString()));var fences=new ArrayList<String>(List.of("work:"+work));
  String targetId;int revision,proposalRevision;
  if(op.equals("proposePurchase")){targetId=work;revision=number(w.get("revision"));proposalRevision=1;scopes.put("SUPPLIER",List.of(uuid(p,"supplierId")));fences.add("purchase-create:"+work);}
  else if(op.equals("recordSupplierReply")||op.equals("cancelPurchase")){targetId=t.get("ID").toString();revision=number(t.get("revision"));proposalRevision=number(t.get("proposalRevision"));fences.add("purchase/line/"+targetId);fences.add("purchase:"+t.get("proposalId"));var pr=r.revision(c,t.get("proposalId").toString());scopes.put("SUPPLIER",List.of(pr.get("supplierId").toString()));}
  else{targetId=uuid(p,"proposalId");revision=number(t.get("revision"));proposalRevision=revision+(op.equals("revisePurchase")?1:0);fences.add("purchase:"+targetId);scopes.put("SUPPLIER",List.of(t.get("supplierId").toString()));
   if(op.equals("dispatchPurchaseOrder")){var a=r.require(c,"Approvals",uuid(p,"approvalId"));actors.add(a.get("approverId").toString());}
   if(op.equals("revisePurchase")){var changes=map(unwrap(p.get("changes")));for(var pair:Map.of("itemId","ITEM","destinationId","PLACE","supplierId","SUPPLIER").entrySet())if(changes.containsKey(pair.getKey())){String changed=uuid(changes,pair.getKey());var ids=new ArrayList<>(scopes.get(pair.getValue()));if(!ids.contains(changed))ids.add(changed);scopes.put(pair.getValue(),ids);}}
  }
  return new CommandPreparation(scopes,fences,actors,"PURCHASE",null,op.equals("proposePurchase")?null:t.get("proposalId").toString(),proposalRevision,targetId,revision);
 }
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object> i,CommandPreparation prep){var t=target(c,i);var items=new HashSet<String>(Set.of(t.get("itemId").toString()));var p=parameters(i);if(operation(i).equals("revisePurchase")){var ch=map(unwrap(p.get("changes")));if(ch.containsKey("itemId"))items.add(uuid(ch,"itemId"));}var bindings=new ArrayList<SubjectBinding>();bindings.add(SubjectBinding.optional("TradeItem",items));bindings.add(SubjectBinding.optional("Work",Set.of(operation(i).equals("proposePurchase")?t.get("ID").toString():t.get("workId").toString())));if(Set.of("recordSupplierReply","cancelPurchase").contains(operation(i)))bindings.add(SubjectBinding.optional("PurchaseOrder",Set.of(t.get("orderId").toString())));return bindings;}
 public Map<String,Object> execute(DomainContext c,Map<String,Object> i){var p=parameters(i);String op=operation(i);var t=target(c,i);var result=new LinkedHashMap<String,Object>();result.put("outcome","APPLIED");
  switch(op){
   case "proposePurchase"->{String work=uuid(p,"workId");var w=works.require(c,work,true);if(!Set.of("ACTIVE","WAITING").contains(w.get("status")))throw DomainError.invalid("Purchase needs active work");Map<String,Object> revision=new LinkedHashMap<>();for(String key:List.of("quantity","price","supplierId","destinationId","dueAt","endpoint","quantityMode"))revision.put(key,p.get(key));revision.put("itemId",p.containsKey("itemId")?uuid(p,"itemId"):w.get("itemId"));if(!revision.get("itemId").equals(w.get("itemId")))throw DomainError.invalid("Proposal and work item differ");String id=UUID.randomUUID().toString();r.insert("Proposals",row(c,"ID",id,"workId",work,"currentRevision",1,"status","PROPOSED","createdAt",clock.instant()));revision=validatedRevision(c,revision,id,work,1);if(p.containsKey("goalVersionId")){String goal=uuid(p,"goalVersionId");if(!Objects.equals(works.currentGoal(c,work).get("ID"),goal))throw DomainError.invalid("Goal changed");revision.put("goalVersionId",goal);}r.insert("ProposalRevisions",revision);result.putAll(proposalResult(revision));works.markInvalidation(c,work,true);}
   case "revisePurchase"->{String id=uuid(p,"proposalId");var root=r.require(c,"Proposals",id);if("CANCELLED".equals(root.get("status")))throw DomainError.invalid("Cancelled proposal");var changes=map(unwrap(p.get("changes")));if(!Set.of("quantity","price","itemId","supplierId","destinationId","dueAt","endpoint","quantityMode").containsAll(changes.keySet())||changes.isEmpty())throw DomainError.invalid("Unsupported proposal change");var values=new LinkedHashMap<String,Object>(t);values.putAll(changes);var revision=validatedRevision(c,values,id,t.get("workId").toString(),number(t.get("revision"))+1);revision.put("reason",text(p,"reason"));r.insert("ProposalRevisions",revision);r.update(c,"Proposals",id,Map.of("currentRevision",revision.get("revision"),"status","PROPOSED"));works.markInvalidation(c,t.get("workId").toString(),true);result.putAll(proposalResult(revision));}
   case "approvePurchase"->{manager(c,prepare(c,i).scopes());sameHash(t,text(p,"proposalHash"));String decision=text(p,"decision");if(!Set.of("APPROVE","REJECT","CONDITIONAL").contains(decision))throw DomainError.invalid("Unsupported decision");Object conditions=unwrap(p.getOrDefault("conditions",List.of()));if(!(conditions instanceof List<?> list)||list.size()>32)throw DomainError.invalid("Conditions list required");if(decision.equals("CONDITIONAL")&&((List<?>)conditions).isEmpty())throw DomainError.invalid("Conditional approval needs predicate");if(decision.equals("APPROVE")&&!((List<?>)conditions).isEmpty())throw DomainError.invalid("Unconditional approval cannot hide conditions");Instant until=Instant.parse(text(p,"validUntil"));if(!until.isAfter(clock.instant()))throw new DomainError("HELD","APPROVAL_EXPIRED","Approval expired at execution time");String id=UUID.randomUUID().toString();r.insert("Approvals",row(c,"ID",id,"proposalId",t.get("proposalId"),"proposalRevision",t.get("revision"),"proposalHash",t.get("proposalHash"),"approverId",c.actorId(),"policyHash",policy.rule(c,"dispatchPurchaseOrder").policyHash(),"decision",decision,"conditionsJson",encode(this.conditions.bind(c,t.get("workId").toString(),(List<?>)conditions)),"decidedAt",clock.instant(),"validUntil",until));r.update(c,"Proposals",t.get("proposalId").toString(),Map.of("status",decision.equals("APPROVE")?"APPROVED":decision.equals("REJECT")?"REJECTED":"CONDITIONAL"));result.putAll(proposalResult(t));result.put("approvalId",id);result.put("businessStatus",decision.equals("APPROVE")?"APPROVED":decision.equals("REJECT")?"REJECTED":"CONDITIONAL");}
   case "dispatchPurchaseOrder"->{sameHash(t,text(p,"proposalHash"));var a=r.require(c,"Approvals",uuid(p,"approvalId"));approveForDispatch(c,i,t,a);Map<String,Object> conditionProof="CONDITIONAL".equals(a.get("decision"))?conditions.evaluate(c,t,a):Map.of("decision","UNCONDITIONAL");if(r.rows(c,"Orders").stream().anyMatch(o->Objects.equals(o.get("proposalId"),t.get("proposalId"))&&Objects.equals(o.get("proposalRevision"),t.get("revision"))))throw new DomainError("CONFLICT","ORDER_ALREADY_DISPATCHED","Order revision already dispatched");String order=UUID.randomUUID().toString(),line=UUID.randomUUID().toString();String ext=text(p,"externalOperationId");String out=outbox.enqueue(c,CommandExecution.commandId(),ext,"dispatchPurchaseOrder",Map.of("orderId",order,"proposalHash",t.get("proposalHash"),"workId",t.get("workId"),"itemId",t.get("itemId"),"quantity",t.get("quantity").toString(),"unit",t.get("unit"),"channel",text(p,"channel")));r.insert("Orders",row(c,"ID",order,"proposalId",t.get("proposalId"),"proposalRevision",t.get("revision"),"proposalHash",t.get("proposalHash"),"approvalId",a.get("ID"),"channel",text(p,"channel"),"externalOperationId",ext,"outboxId",out,"createdAt",clock.instant(),"conditionAssessmentJson",encode(conditionProof)));var l=row(c,"ID",line,"orderId",order,"proposalId",t.get("proposalId"),"proposalRevision",t.get("revision"),"status","DISPATCH_PENDING","revision",1);for(String k:List.of("workId","itemId","destinationId","quantity","unit"))l.put(k,t.get(k));r.insert("OrderLines",l);r.update(c,"Proposals",t.get("proposalId").toString(),Map.of("status","ORDERED"));duty(c,t.get("workId").toString(),"SUPPLIER_DISPATCH_RECONCILIATION","발주 전달 결과와 공급자 수락을 대조한다");result.putAll(Map.of("objectId",order,"orderId",order,"poLineId",line,"outboxId",out,"revision",1,"businessStatus","DISPATCH_PENDING","supplierAcceptance","UNKNOWN","arrivalQuantity","0"));}
   case "recordSupplierReply"->{String reply=text(p,"reply");if(!Set.of("ACCEPT","REJECT","CHANGE").contains(reply))throw DomainError.invalid("Unsupported supplier reply");var q=amount(p.get("proposedQuantity"),false);String unit=dimension(p,"proposedQuantity","unit");if(!unit.equals(t.get("unit")))throw DomainError.invalid("Reply unit differs");if(reply.equals("ACCEPT")&&q.compareTo(amount(t.get("quantity"),true))!=0)throw DomainError.invalid("Acceptance cannot change ordered quantity");String evidence=uuid(p,"evidence");var document=r.external(c,"mulino.evidence.DocumentVersions",evidence);if(!Objects.equals(document.get("itemId"),t.get("itemId")))throw DomainError.invalid("Supplier reply evidence item differs");auth.authorizeScope(c,"recordSupplierReply","SOURCE",document.get("sourceProfileId").toString());String canonical=p.containsKey("canonicalOccurrenceId")?uuid(p,"canonicalOccurrenceId"):r.externalRows(c,"mulino.evidence.Verifications").stream().filter(v->evidence.equals(v.get("basisDocumentId"))&&"VERIFIED".equals(v.get("verdict"))).map(v->v.get("canonicalOccurrenceId").toString()).findFirst().orElseThrow(()->new DomainError("HELD","EVIDENCE_UNVERIFIED","Supplier reply needs verified canonical evidence"));var replyFact=this.evidence.requireCanonical(c,canonical,"SUPPLIER_"+reply,t.get("itemId").toString(),t.get("orderId").toString(),q,unit);if(!Objects.equals(replyFact.get("subjectId"),t.get("orderId"))||!"PURCHASE_ORDER".equals(replyFact.get("subjectKind")))throw DomainError.invalid("Supplier reply belongs to a different order");r.insert("SupplierReplies",row(c,"ID",UUID.randomUUID().toString(),"orderId",t.get("orderId"),"reply",reply,"canonicalOccurrenceId",canonical,"proposedQuantity",q,"unit",unit,"evidenceId",evidence,"recordedAt",clock.instant()));String state=reply.equals("ACCEPT")?"SUPPLIER_ACCEPTED":reply.equals("REJECT")?"SUPPLIER_REJECTED":"SUPPLIER_CHANGE_PENDING";r.update(c,"OrderLines",t.get("ID").toString(),Map.of("status",state,"revision",number(t.get("revision"))+1,"recordedAt",clock.instant(),"effectiveAt",clock.instant()));works.markInvalidation(c,t.get("workId").toString(),true);if(!reply.equals("ACCEPT"))duty(c,t.get("workId").toString(),"SUPPLIER_REPLY_REVIEW","공급자 거절 또는 변경을 확인하고 새 승인 범위를 정한다");result.putAll(Map.of("objectId",t.get("orderId"),"revision",number(t.get("revision"))+1,"businessStatus",state,"supplierAcceptance",reply,"arrivalQuantity","0"));}
   case "cancelPurchase"->{var q=amount(p.get("quantity"),true);String unit=dimension(p,"quantity","unit");if(!unit.equals(t.get("unit")))throw DomainError.invalid("Cancellation unit differs");BigDecimal committed=executed(c,t.get("ID").toString());BigDecimal previously=cancelled(c,t.get("ID").toString());if(q.add(previously).add(committed).compareTo(amount(t.get("quantity"),true))>0)throw DomainError.invalid("Cancellation cannot erase shipped, received or invoiced effects");String acceptance=text(p,"externalAcceptance");if(!acceptance.equals("UNKNOWN"))throw DomainError.invalid("External cancellation requires separately verified acceptance");String cancel=UUID.randomUUID().toString();String out=outbox.enqueue(c,CommandExecution.commandId(),cancel,"cancelPurchase",Map.of("orderId",t.get("orderId"),"lineId",t.get("ID"),"quantity",q.toPlainString(),"unit",unit,"reason",text(p,"reason")));r.insert("Cancellations",row(c,"ID",cancel,"orderId",t.get("orderId"),"lineId",t.get("ID"),"quantity",q,"unit",unit,"reason",text(p,"reason"),"externalAcceptance","UNKNOWN","outboxId",out,"recordedAt",clock.instant()));r.update(c,"OrderLines",t.get("ID").toString(),Map.of("revision",number(t.get("revision"))+1,"status","CANCELLATION_PENDING","recordedAt",clock.instant(),"effectiveAt",clock.instant()));duty(c,t.get("workId").toString(),"PURCHASE_CANCELLATION_ACCEPTANCE","공급자 취소 수락과 이미 출하·수령·청구된 범위를 확인한다");works.markInvalidation(c,t.get("workId").toString(),true);result.putAll(Map.of("objectId",t.get("orderId"),"cancellationId",cancel,"revision",number(t.get("revision"))+1,"businessStatus","CANCELLATION_PENDING","externalAcceptance","UNKNOWN","preservedExecutedQuantity",committed.stripTrailingZeros().toPlainString(),"cancelledRequestedQuantity",q.toPlainString()));}
   default->throw DomainError.unsupported();
  }
  result.putIfAbsent("effects",Map.of("purchaseId",result.getOrDefault("objectId",result.getOrDefault("proposalId",""))));return result;
 }
 private Map<String,Object> validatedRevision(DomainContext c,Map<String,Object> p,String proposal,String work,int revision){String item=uuid(p,"itemId"),supplier=uuid(p,"supplierId"),destination=uuid(p,"destinationId");var product=r.external(c,"mulino.inventory.TradeItems",item);r.require(c,"Suppliers",supplier);r.external(c,"mulino.inventory.Places",destination);BigDecimal quantity=amount(p.get("quantity"),true),price=amount(p.get("price"),false);String unit=dimension(p,"quantity","unit"),currency=dimension(p,"price","currency");if(!Objects.equals(product.get("baseUnit"),unit)||quantity.stripTrailingZeros().scale()>number(product.get("decimalPlaces")))throw DomainError.invalid("Item unit or precision differs");if(!currency.matches("[A-Z]{3}"))throw DomainError.invalid("Currency required");String endpoint=text(p,"endpoint"),mode=text(p,"quantityMode");if(!Set.of("ARRIVED","RECEIVED","DISPATCHED","ACCEPTED","SELL_ELIGIBLE").contains(endpoint)||!com.mulino.domain.work.GoalInput.MODES.contains(mode))throw DomainError.invalid("Unsupported purchase goal");var values=row(c,"ID",UUID.randomUUID().toString(),"proposalId",proposal,"revision",revision,"workId",work,"itemId",item,"supplierId",supplier,"destinationId",destination,"quantity",quantity,"unit",unit,"price",price,"currency",currency,"dueAt",instant(unwrap(p.get("dueAt"))),"endpoint",endpoint,"quantityMode",mode,"recordedAt",clock.instant());var hashInput=new TreeMap<String,Object>();for(String k:List.of("proposalId","revision","workId","itemId","supplierId","destinationId","quantity","unit","price","currency","dueAt","endpoint","quantityMode"))hashInput.put(k,values.get(k).toString());values.put("proposalHash",CommandRequests.hash(hashInput));return values;}
 private void sameHash(Map<String,Object> revision,String hash){if(!Objects.equals(hash,revision.get("proposalHash")))throw new DomainError("HELD","APPROVAL_HASH_MISMATCH","Proposal changed");}
 private void manager(DomainContext c,Map<String,List<String>> scopes){if(!"HUMAN".equals(identities.actor(c.organizationId(),c.actorId()).orElseThrow(DomainError::forbidden).get("kind")))throw DomainError.forbidden();if(!auth.permittedScopes(c,"approvePurchase",scopes))throw DomainError.forbidden();if(identities.rows("ManagementAuthorities",c.organizationId()).stream().noneMatch(x->Objects.equals(x.get("actorId"),c.actorId())&&Objects.equals(x.get("capabilityId"),"approvePurchase")&&active(x)&&("ORGANIZATION".equals(x.get("scopeKind"))&&c.organizationId().equals(x.get("scopeId"))||scopes.getOrDefault(x.get("scopeKind"),List.of()).contains(x.get("scopeId")))))throw DomainError.forbidden();}
 private boolean active(Map<String,Object> x){Instant now=clock.instant();return x.get("validFrom")!=null&&x.get("validUntil")!=null&&!now.isBefore(instant(x.get("validFrom")))&&now.isBefore(instant(x.get("validUntil")))&&(x.get("revokedAt")==null||now.isBefore(instant(x.get("revokedAt"))));}
 private void approveForDispatch(DomainContext c,Map<String,Object> i,Map<String,Object> t,Map<String,Object>a){if(!Objects.equals(t.get("proposalId"),a.get("proposalId"))||!Objects.equals(t.get("revision"),a.get("proposalRevision"))||!Objects.equals(t.get("proposalHash"),a.get("proposalHash")))throw new DomainError("HELD","APPROVAL_HASH_MISMATCH","Changed proposal requires new approval");if(!Set.of("APPROVE","CONDITIONAL").contains(a.get("decision")))throw new DomainError("HELD","APPROVAL_REJECTED","Rejected decision cannot dispatch");if(!clock.instant().isBefore(instant(a.get("validUntil"))))throw new DomainError("HELD","APPROVAL_EXPIRED","Approval expired");if(!policy.rule(c,"dispatchPurchaseOrder").policyHash().equals(a.get("policyHash")))throw new DomainError("HELD","APPROVAL_POLICY_CHANGED","Current policy differs from approval");manager(new DomainContext(c.organizationId(),a.get("approverId").toString(),c.stableRequestOwner(),c.asOf(),c.knownAt()),prepare(c,i).scopes());}
 private Map<String,Object> proposalResult(Map<String,Object> p){return Map.of("proposalId",p.get("proposalId"),"proposalRevision",p.get("revision"),"proposalHash",p.get("proposalHash"),"revision",p.get("revision"),"workId",p.get("workId"),"businessStatus","PROPOSED");}
 private Map<String,Object> row(DomainContext c,Object... kv){var m=new LinkedHashMap<String,Object>();m.put("organizationId",c.organizationId());for(int n=0;n<kv.length;n+=2)m.put((String)kv[n],kv[n+1]);return m;}
 private String encode(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw DomainError.invalid("Invalid JSON");}}
 private void duty(DomainContext c,String work,String kind,String action){duties.ensureRuntimeDuty(c,work,CommandExecution.commandId(),kind,action,clock.instant().plusSeconds(3600));}
 public Map<String,Object> requireLine(DomainContext c,String id){var line=r.require(c,"OrderLines",id);var result=new LinkedHashMap<>(line);result.put("acceptedQuantity",line.get("quantity"));result.put("cancelRequestedQuantity",cancelled(c,id));return result;}
 public Map<String,Object> creditReceipt(DomainContext c,String lineId,String occurrence,BigDecimal q,String unit){r.fence(c,"purchase/line/"+lineId);r.fence(c,"purchase-credit:"+occurrence);var line=requireLine(c,lineId);var actual=r.external(c,"mulino.evidence.CanonicalOccurrences",occurrence);evidence.requireCanonical(c,occurrence,"PHYSICAL_RECEIPT",line.get("itemId").toString(),actual.get("physicalScopeId").toString(),amount(actual.get("quantity"),true),unit);if(!Set.of("PHYSICAL_RECEIPT","RECEIPT","ARRIVED","RECEIVED").contains(actual.get("kind"))||!Objects.equals(line.get("itemId"),actual.get("itemId"))||!Objects.equals(line.get("destinationId"),actual.get("placeId"))||!unit.equals(actual.get("unit"))||!unit.equals(line.get("unit"))||q.signum()<=0||q.compareTo(amount(actual.get("quantity"),true))>0)throw DomainError.invalid("Receipt differs from ordered canonical scope");var existing=r.rows(c,"ReceiptCredits").stream().filter(x->occurrence.equals(x.get("occurrenceId"))&&lineId.equals(x.get("lineId"))).findFirst();if(existing.isPresent()&&lineId.equals(existing.get().get("lineId")))throw new DomainError("CONFLICT","RECEIPT_ALREADY_CREDITED","Canonical arrival already credited to this line");BigDecimal allocated=r.rows(c,"ReceiptCredits").stream().filter(x->occurrence.equals(x.get("occurrenceId"))).map(x->amount(x.get("actualQuantity"),true)).reduce(BigDecimal.ZERO,BigDecimal::add);if(allocated.add(q).compareTo(amount(actual.get("quantity"),true))>0)throw DomainError.invalid("Canonical receipt capacity already allocated");BigDecimal prior=r.rows(c,"ReceiptCredits").stream().filter(x->lineId.equals(x.get("lineId"))).map(x->amount(x.get("contributedQuantity"),false)).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal remaining=amount(line.get("quantity"),true).subtract(prior).max(BigDecimal.ZERO);BigDecimal credited=q.min(remaining),excess=q.subtract(credited);r.insert("ReceiptCredits",row(c,"ID",UUID.randomUUID().toString(),"lineId",lineId,"occurrenceId",occurrence,"actualQuantity",q,"contributedQuantity",credited,"excessQuantity",excess,"unit",unit,"recordedAt",clock.instant()));recordExecutionEffect(c,lineId,"RECEIVED",occurrence,q,unit);works.markInvalidation(c,line.get("workId").toString(),true);if(excess.signum()>0) duty(c,line.get("workId").toString(),"PURCHASE_EXCESS_RECONCILIATION","초과 실수령량을 원 발주 완료량과 별도로 대조한다");return Map.of("contributedQuantity",credited,"excessQuantity",excess,"cumulativeQuantity",prior.add(credited));}
 public void recordExecutionEffect(DomainContext c,String lineId,String kind,String reference,BigDecimal q,String unit){r.fence(c,"purchase/line/"+lineId);var l=requireLine(c,lineId);CommandRequests.uuid(reference);if(!Set.of("SHIPPED","RECEIVED","INVOICED").contains(kind)||q.signum()<=0||!unit.equals(l.get("unit")))throw DomainError.invalid("Invalid executed effect");var old=r.rows(c,"ExecutionEffects").stream().filter(x->lineId.equals(x.get("lineId"))&&kind.equals(x.get("kind"))&&reference.equals(x.get("referenceId"))).findFirst();if(old.isPresent()){if(q.compareTo(amount(old.get().get("quantity"),true))!=0)throw DomainError.invalid("Execution reference changed");return;}r.insert("ExecutionEffects",row(c,"ID",UUID.randomUUID().toString(),"lineId",lineId,"kind",kind,"referenceId",reference,"quantity",q,"unit",unit,"recordedAt",clock.instant()));}
 private BigDecimal cancelled(DomainContext c,String id){return r.rows(c,"Cancellations").stream().filter(x->id.equals(x.get("lineId"))).map(x->amount(x.get("quantity"),true)).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private BigDecimal executed(DomainContext c,String id){var sums=new HashMap<String,BigDecimal>();for(var x:r.rows(c,"ExecutionEffects"))if(id.equals(x.get("lineId")))sums.merge(x.get("kind").toString(),amount(x.get("quantity"),true),BigDecimal::add);return sums.values().stream().max(BigDecimal::compareTo).orElse(BigDecimal.ZERO);}
}
