package com.mulino.application.trade.regulatory;
import com.mulino.application.core.*;
import com.mulino.domain.trade.regulatory.RegulatoryRepository;
import com.mulino.domain.inventory.InventoryRepository;
import com.mulino.application.trade.TradeImpact;
import com.mulino.domain.work.WorkRepository;
import java.util.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.trade.regulatory.RegulatoryInputs.*;
@Component
public class RegulatoryCommands implements CommandHandler {
 private final RegulatoryRepository r;private final InventoryRepository stock;private final RegulatoryEvidence evidence;private final WorkRepository work;private final RegulatoryResponsibilities impact;
 public RegulatoryCommands(RegulatoryRepository r,InventoryRepository stock,RegulatoryEvidence evidence,WorkRepository work,RegulatoryResponsibilities impact){this.r=r;this.stock=stock;this.evidence=evidence;this.work=work;this.impact=impact;}
 public Set<String> capabilities(){return Set.of("prepareRegulatoryProcedure","recordSubmission","recordRegulatoryDecision","verifyLabel");}
 public Set<String> intentKinds(){return Set.of("COMMAND","RECORD");}
 private Map<String,Object> procedure(DomainContext c,Map<String,Object> p){return r.require(c,"Procedures",id(p,"procedureId"));}
 private Map<String,Object> policy(DomainContext c,Map<String,Object> proc){var pol=r.require(c,"Policies",proc.get("policyId").toString());if(!"ACTIVE".equals(pol.get("status"))||!valid(pol,c.asOf()))throw new DomainError("HELD","POLICY_UNRESOLVED","Current regulatory policy missing");return pol;}
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object> i,CommandPreparation prep){var p=slots(i);var proc=i.get("capabilityId").equals("prepareRegulatoryProcedure")&&!p.containsKey("procedureId")?p:procedure(c,p);return List.of(SubjectBinding.optional("TradeItem",Set.of(id(proc,"itemId"))),SubjectBinding.optional("QuantitySegment",Set.of(id(proc,"physicalScopeId"))),SubjectBinding.optional("Work",Set.of(id(proc,"workId"))));}
 public CommandPreparation prepare(DomainContext c,Map<String,Object> i){var p=slots(i);String cap=text(i,"capabilityId");if(!capabilities().contains(cap))throw DomainError.unsupported();boolean create=cap.equals("prepareRegulatoryProcedure")&&!p.containsKey("procedureId");
  if(!(cap.equals("prepareRegulatoryProcedure")?"COMMAND":"RECORD").equals(i.get("intentKind")))throw DomainError.invalid("Regulatory intent kind mismatch");
  Set<String> keys=switch(cap){case "prepareRegulatoryProcedure"->Set.of("procedureId","itemId","lotId","physicalScopeId","workId","policyId","documentVersionId");case "recordSubmission"->Set.of("procedureId","occurredAt","occurrenceId");case "recordRegulatoryDecision"->Set.of("procedureId","decision","action","startQuantity","quantity","unit","validFrom","validUntil","occurrenceId","previousVersionId");default->Set.of("procedureId","decision","packagingVersionId","specificationVersionId","validFrom","validUntil","occurrenceId");};if(!keys.containsAll(p.keySet()))throw DomainError.invalid("Unsupported regulatory slot");
  var proc=create?p:procedure(c,p);var item=stock.current(c,"TradeItems",id(proc,"itemId"));var lot=stock.current(c,"ManufacturingLots",id(proc,"lotId"));var seg=stock.current(c,"QuantitySegments",id(proc,"physicalScopeId"));
  if(!id(proc,"itemId").equals(lot.get("itemId"))||!id(proc,"itemId").equals(seg.get("itemId"))||!id(proc,"lotId").equals(seg.get("lotId")))throw DomainError.invalid("Item LOT physical scope mismatch");work.require(c,id(proc,"workId"),true);var pol=policy(c,proc);
  if(cap.equals("prepareRegulatoryProcedure")){evidence.document(c,id(p,"documentVersionId"),id(proc,"itemId"));if(!create){for(String k:List.of("itemId","lotId","physicalScopeId","workId","policyId"))if(p.containsKey(k)&&!Objects.equals(p.get(k),proc.get(k)))throw DomainError.invalid("Resubmission scope cannot change");String s=current(c,proc).get("status").toString();if(!Set.of("PREPARED","SUBMISSION_UNCONFIRMED","SUPPLEMENTARY_REQUIRED","REJECTED").contains(s))throw DomainError.invalid("Procedure cannot be reprepared");}}
  if(cap.equals("recordSubmission")){String s=current(c,proc).get("status").toString();if(!Set.of("PREPARED","SUBMISSION_UNCONFIRMED").contains(s))throw DomainError.invalid("Prepared procedure required");if(time(p,"occurredAt").isAfter(c.knownAt()))throw DomainError.invalid("Submission time is future");if(p.containsKey("occurrenceId"))evidence.require(c,id(p,"occurrenceId"),"REGULATORY_SUBMISSION",proc,pol,Map.of("procedureId",proc.get("ID"),"procedureVersionId",proc.get("currentVersionId"),"occurredAt",p.get("occurredAt")));}
  if(cap.equals("recordRegulatoryDecision")){if(!"SUBMITTED".equals(current(c,proc).get("status")))throw DomainError.invalid("Verified submission required");if(!Set.of("ALLOWED","REJECTED","SUPPLEMENTARY_REQUIRED","REVOKED").contains(text(p,"decision")))throw DomainError.invalid("Decision invalid");if(!pol.get("action").equals(text(p,"action"))||!item.get("baseUnit").equals(text(p,"unit")))throw DomainError.invalid("Policy action/unit mismatch");var start=quantity(p,"startQuantity");var n=quantity(p,"quantity");if(start.add(n).compareTo(new java.math.BigDecimal(seg.get("quantity").toString()))>0)throw DomainError.invalid("Decision exceeds physical scope");interval(p);if(p.containsKey("previousVersionId")){var old=r.require(c,"DecisionVersions",id(p,"previousVersionId"));if(!proc.get("ID").equals(old.get("procedureId")))throw DomainError.invalid("Decision predecessor mismatch");if(r.rows(c,"DecisionVersions").stream().anyMatch(x->old.get("ID").equals(x.get("previousVersionId"))))throw DomainError.invalid("Decision predecessor superseded");}evidence.require(c,id(p,"occurrenceId"),"REGULATORY_DECISION",proc,pol,expected(p,proc));}
  if(cap.equals("verifyLabel")){if(!Set.of("VERIFIED","REJECTED").contains(text(p,"decision")))throw DomainError.invalid("Label decision invalid");if(!item.get("packagingVersionId").equals(id(p,"packagingVersionId"))||!item.get("specificationVersionId").equals(id(p,"specificationVersionId")))throw DomainError.invalid("Label version mismatch");interval(p);evidence.require(c,id(p,"occurrenceId"),"LABEL_VERIFICATION",proc,pol,expected(p,proc));}
  var scopes=new LinkedHashMap<String,List<String>>();for(String k:List.of("itemId","physicalScopeId","workId"))scopes.put(k.equals("itemId")?"ITEM":k.equals("workId")?"WORK":"TARGET",List.of(id(proc,k)));if(!create)scopes.put("TARGET",List.of(proc.get("ID").toString(),id(proc,"physicalScopeId")));
  if(p.containsKey("documentVersionId"))scopes.put("SOURCE",List.of(evidence.source(c,"DocumentVersions",id(p,"documentVersionId"))));if(p.containsKey("occurrenceId"))scopes.put("SOURCE",List.of(evidence.source(c,"CanonicalOccurrences",id(p,"occurrenceId"))));
  return CommandPreparation.ordinary(scopes,List.of("inventory/segment/"+id(proc,"physicalScopeId"),"work/"+id(proc,"workId"),"regulatory/"+(create?id(proc,"physicalScopeId"):proc.get("ID"))),"REGULATORY_RECORD",create?null:proc.get("ID").toString(),create?null:((Number)proc.get("revision")).intValue());
 }
 private Map<String,Object> expected(Map<String,Object> p,Map<String,Object> proc){var e=new LinkedHashMap<String,Object>(p);e.remove("occurrenceId");e.remove("previousVersionId");e.put("procedureVersionId",proc.get("currentVersionId"));return e;}
 private void interval(Map<String,Object> p){var from=time(p,"validFrom");if(p.containsKey("validUntil")&&!time(p,"validUntil").isAfter(from))throw DomainError.invalid("Invalid regulatory interval");}
 private Map<String,Object> current(DomainContext c,Map<String,Object> proc){return r.require(c,"ProcedureVersions",proc.get("currentVersionId").toString());}
 public Map<String,Object> execute(DomainContext c,Map<String,Object> i){prepare(c,i);var p=slots(i);String cap=text(i,"capabilityId");boolean create=cap.equals("prepareRegulatoryProcedure")&&!p.containsKey("procedureId");var proc=create?row(c):new LinkedHashMap<>(procedure(c,p));if(create){for(String k:List.of("itemId","lotId","physicalScopeId","workId","policyId"))proc.put(k,p.get(k));proc.put("revision",0);r.insert("Procedures",proc);}var pol=policy(c,proc);var v=row(c);v.put("revision",((Number)proc.get("revision")).intValue()+1);for(String k:List.of("itemId","lotId","physicalScopeId","policyId"))v.put(k,proc.get(k));v.put("procedureId",proc.get("ID"));String status;
  if(cap.equals("recordRegulatoryDecision")||cap.equals("verifyLabel")){
   v.put("procedureVersionId",proc.get("currentVersionId"));for(String k:p.keySet())if(!k.equals("procedureId"))v.put(k,p.get(k));for(String k:List.of("validFrom","validUntil"))if(p.containsKey(k))v.put(k,time(p,k));
   if(cap.equals("recordRegulatoryDecision")){v.put("authority",pol.get("authority"));v.put("startQuantity",quantity(p,"startQuantity"));v.put("quantity",quantity(p,"quantity"));r.insert("DecisionVersions",v);}else r.insert("LabelVerifications",v);status=text(p,"decision");
   // A rejected/supplementary outcome requires a fresh preparation/submission version.
   if(Set.of("REJECTED","SUPPLEMENTARY_REQUIRED").contains(status)&&cap.equals("recordRegulatoryDecision")){var next=new LinkedHashMap<>(current(c,proc));next.putAll(row(c));next.put("previousVersionId",proc.get("currentVersionId"));next.put("status",status);r.insert("ProcedureVersions",next);proc.put("currentVersionId",next.get("ID"));}
  }else {v.put("workId",proc.get("workId"));v.put("previousVersionId",proc.get("currentVersionId"));if(cap.equals("prepareRegulatoryProcedure")){status="PREPARED";v.put("documentVersionId",p.get("documentVersionId"));}else{status=p.containsKey("occurrenceId")?"SUBMITTED":"SUBMISSION_UNCONFIRMED";v.put("occurredAt",time(p,"occurredAt"));v.put("occurrenceId",p.get("occurrenceId"));v.put("documentVersionId",current(c,proc).get("documentVersionId"));}v.put("status",status);r.insert("ProcedureVersions",v);proc.put("currentVersionId",v.get("ID"));}
  int revision=((Number)proc.get("revision")).intValue();r.advance(c,proc.get("ID").toString(),revision,proc.get("currentVersionId").toString());impact.changed(c,proc,v,status);
  return Map.of("outcome","APPLIED","revision",revision+1,"status",status,"effects",Map.of("procedureId",proc.get("ID"),"versionId",v.get("ID"),"procedureVersionId",proc.get("currentVersionId")),"quantityEffects",List.of());
 }
}
