-- Immutable regulatory facts; preparation never proves external submission.
CREATE TABLE mulino_trade_regulatory_Policies(
 ID varchar(36) PRIMARY KEY,
 organizationId varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 recordedBy varchar(36) NOT NULL,
 version varchar(160) NOT NULL,
 authority varchar(160) NOT NULL,
 sourceNamespace varchar(160) NOT NULL,
 action varchar(80) NOT NULL,
 validFrom timestamptz NOT NULL,
 validUntil timestamptz,
 fictional boolean NOT NULL,
 status varchar(24) NOT NULL,
 requiresLabel boolean NOT NULL,
 UNIQUE(organizationId,ID),
 FOREIGN KEY(organizationId,recordedBy) REFERENCES mulino_identity_Actors(organizationId,ID)
);
CREATE TRIGGER regulatory_policies_immutable BEFORE UPDATE OR DELETE ON mulino_trade_regulatory_Policies FOR EACH ROW EXECUTE FUNCTION mulino_evidence_reject_mutation();
CREATE TABLE mulino_trade_regulatory_Procedures(
 ID varchar(36) PRIMARY KEY,
 organizationId varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 recordedBy varchar(36) NOT NULL,
 itemId varchar(36),
 lotId varchar(36),
 physicalScopeId varchar(36),
 workId varchar(36),
 policyId varchar(36),
 currentVersionId varchar(36),
 UNIQUE(organizationId,ID),
 FOREIGN KEY(organizationId,recordedBy) REFERENCES mulino_identity_Actors(organizationId,ID),
 FOREIGN KEY(organizationId,itemId) REFERENCES mulino_inventory_TradeItems(organizationId,ID),
 FOREIGN KEY(organizationId,lotId) REFERENCES mulino_inventory_ManufacturingLots(organizationId,ID),
 FOREIGN KEY(organizationId,physicalScopeId) REFERENCES mulino_inventory_QuantitySegments(organizationId,ID),
 FOREIGN KEY(organizationId,workId) REFERENCES mulino_work_read_Works(organizationId,ID),
 FOREIGN KEY(organizationId,policyId) REFERENCES mulino_trade_regulatory_Policies(organizationId,ID)
);
CREATE TABLE mulino_trade_regulatory_ProcedureVersions(
 ID varchar(36) PRIMARY KEY,
 organizationId varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 recordedBy varchar(36) NOT NULL,
 procedureId varchar(36),
 previousVersionId varchar(36),
 itemId varchar(36),
 lotId varchar(36),
 physicalScopeId varchar(36),
 workId varchar(36),
 policyId varchar(36),
 status varchar(40),
 documentVersionId varchar(36),
 occurrenceId varchar(36),
 occurredAt timestamptz,
 UNIQUE(organizationId,ID),
 FOREIGN KEY(organizationId,recordedBy) REFERENCES mulino_identity_Actors(organizationId,ID),
 FOREIGN KEY(organizationId,itemId) REFERENCES mulino_inventory_TradeItems(organizationId,ID),
 FOREIGN KEY(organizationId,lotId) REFERENCES mulino_inventory_ManufacturingLots(organizationId,ID),
 FOREIGN KEY(organizationId,physicalScopeId) REFERENCES mulino_inventory_QuantitySegments(organizationId,ID),
 FOREIGN KEY(organizationId,workId) REFERENCES mulino_work_read_Works(organizationId,ID),
 FOREIGN KEY(organizationId,policyId) REFERENCES mulino_trade_regulatory_Policies(organizationId,ID),
 FOREIGN KEY(organizationId,procedureId) REFERENCES mulino_trade_regulatory_Procedures(organizationId,ID),
 FOREIGN KEY(organizationId,documentVersionId) REFERENCES mulino_evidence_DocumentVersions(organizationId,ID),
 FOREIGN KEY(organizationId,occurrenceId) REFERENCES mulino_evidence_CanonicalOccurrences(organizationId,ID),
 FOREIGN KEY(organizationId,previousVersionId) REFERENCES mulino_trade_regulatory_ProcedureVersions(organizationId,ID)
);
CREATE TRIGGER regulatory_procedureversions_immutable BEFORE UPDATE OR DELETE ON mulino_trade_regulatory_ProcedureVersions FOR EACH ROW EXECUTE FUNCTION mulino_evidence_reject_mutation();
CREATE TABLE mulino_trade_regulatory_DecisionVersions(
 ID varchar(36) PRIMARY KEY,
 organizationId varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 recordedBy varchar(36) NOT NULL,
 procedureId varchar(36),
 procedureVersionId varchar(36),
 previousVersionId varchar(36),
 itemId varchar(36),
 lotId varchar(36),
 physicalScopeId varchar(36),
 policyId varchar(36),
 action varchar(80) NOT NULL,
 decision varchar(32) NOT NULL,
 authority varchar(160) NOT NULL,
 startQuantity numeric(38,12) NOT NULL,
 quantity numeric(38,12) NOT NULL,
 unit varchar(24),
 validFrom timestamptz NOT NULL,
 validUntil timestamptz,
 occurrenceId varchar(36),
 UNIQUE(organizationId,ID),
 FOREIGN KEY(organizationId,recordedBy) REFERENCES mulino_identity_Actors(organizationId,ID),
 FOREIGN KEY(organizationId,itemId) REFERENCES mulino_inventory_TradeItems(organizationId,ID),
 FOREIGN KEY(organizationId,lotId) REFERENCES mulino_inventory_ManufacturingLots(organizationId,ID),
 FOREIGN KEY(organizationId,physicalScopeId) REFERENCES mulino_inventory_QuantitySegments(organizationId,ID),
 FOREIGN KEY(organizationId,policyId) REFERENCES mulino_trade_regulatory_Policies(organizationId,ID),
 FOREIGN KEY(organizationId,procedureId) REFERENCES mulino_trade_regulatory_Procedures(organizationId,ID),
 FOREIGN KEY(organizationId,procedureVersionId) REFERENCES mulino_trade_regulatory_ProcedureVersions(organizationId,ID),
 FOREIGN KEY(organizationId,occurrenceId) REFERENCES mulino_evidence_CanonicalOccurrences(organizationId,ID),
 FOREIGN KEY(organizationId,previousVersionId) REFERENCES mulino_trade_regulatory_DecisionVersions(organizationId,ID),
 CHECK(startQuantity>=0 AND quantity>=0),
 CHECK(validUntil IS NULL OR validUntil>validFrom),
 CHECK(decision IN ('ALLOWED','REJECTED','SUPPLEMENTARY_REQUIRED','REVOKED'))
);
CREATE TRIGGER regulatory_decisionversions_immutable BEFORE UPDATE OR DELETE ON mulino_trade_regulatory_DecisionVersions FOR EACH ROW EXECUTE FUNCTION mulino_evidence_reject_mutation();
CREATE TABLE mulino_trade_regulatory_LabelVerifications(
 ID varchar(36) PRIMARY KEY,
 organizationId varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 recordedBy varchar(36) NOT NULL,
 procedureId varchar(36),
 procedureVersionId varchar(36),
 itemId varchar(36),
 lotId varchar(36),
 physicalScopeId varchar(36),
 policyId varchar(36),
 packagingVersionId varchar(36),
 specificationVersionId varchar(36),
 decision varchar(24),
 validFrom timestamptz NOT NULL,
 validUntil timestamptz,
 occurrenceId varchar(36),
 UNIQUE(organizationId,ID),
 FOREIGN KEY(organizationId,recordedBy) REFERENCES mulino_identity_Actors(organizationId,ID),
 FOREIGN KEY(organizationId,itemId) REFERENCES mulino_inventory_TradeItems(organizationId,ID),
 FOREIGN KEY(organizationId,lotId) REFERENCES mulino_inventory_ManufacturingLots(organizationId,ID),
 FOREIGN KEY(organizationId,physicalScopeId) REFERENCES mulino_inventory_QuantitySegments(organizationId,ID),
 FOREIGN KEY(organizationId,policyId) REFERENCES mulino_trade_regulatory_Policies(organizationId,ID),
 FOREIGN KEY(organizationId,procedureId) REFERENCES mulino_trade_regulatory_Procedures(organizationId,ID),
 FOREIGN KEY(organizationId,procedureVersionId) REFERENCES mulino_trade_regulatory_ProcedureVersions(organizationId,ID),
 FOREIGN KEY(organizationId,occurrenceId) REFERENCES mulino_evidence_CanonicalOccurrences(organizationId,ID),
 FOREIGN KEY(organizationId,packagingVersionId) REFERENCES mulino_inventory_PackagingVersions(organizationId,ID),
 FOREIGN KEY(organizationId,specificationVersionId) REFERENCES mulino_inventory_SpecificationVersions(organizationId,ID)
);
CREATE TRIGGER regulatory_labelverifications_immutable BEFORE UPDATE OR DELETE ON mulino_trade_regulatory_LabelVerifications FOR EACH ROW EXECUTE FUNCTION mulino_evidence_reject_mutation();
