-- 반품은 원 인도 이력과 별개이며 기존 실물 이동만 기록한다.
CREATE TABLE mulino_trade_returns_Authorizations(
 organizationId varchar(36) NOT NULL,
 ID varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 workId varchar(36),
 deliveryId varchar(36),
 customerId varchar(36),
 itemId varchar(36),
 lotId varchar(36),
 rangeRootId varchar(36),
 startQuantity numeric(38,12),
 quantity numeric(38,12),
 unit varchar(40),
 destinationId varchar(36),
 actorId varchar(36),
 validUntil timestamptz,
 policyHash varchar(64),
 commandId varchar(36),
 reason varchar(320),
 PRIMARY KEY(organizationId,ID),
 CHECK(quantity>0 AND startQuantity>=0),
 FOREIGN KEY(organizationId,workId) REFERENCES mulino_work_read_Works(organizationId,ID),
 FOREIGN KEY(organizationId,itemId) REFERENCES mulino_inventory_TradeItems(organizationId,ID),
 FOREIGN KEY(organizationId,lotId) REFERENCES mulino_inventory_ManufacturingLots(organizationId,ID),
 FOREIGN KEY(organizationId,destinationId) REFERENCES mulino_inventory_Places(organizationId,ID),
 FOREIGN KEY(organizationId,actorId) REFERENCES mulino_identity_Actors(organizationId,ID)
);
CREATE TRIGGER returns_authorizations_immutable BEFORE UPDATE OR DELETE ON mulino_trade_returns_Authorizations FOR EACH ROW EXECUTE FUNCTION mulino_evidence_reject_mutation();
CREATE TABLE mulino_trade_returns_Observations(
 organizationId varchar(36) NOT NULL,
 ID varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 authorizationId varchar(36),
 eventId varchar(36),
 workId varchar(36),
 deliveryId varchar(36),
 customerId varchar(36),
 itemId varchar(36),
 lotId varchar(36),
 rangeRootId varchar(36),
 startQuantity numeric(38,12),
 quantity numeric(38,12),
 unit varchar(40),
 placeId varchar(36),
 occurredAt timestamptz,
 nextCheckAt timestamptz,
 state varchar(40),
 PRIMARY KEY(organizationId,ID),
 CHECK(quantity>0 AND startQuantity>=0),
 FOREIGN KEY(organizationId,workId) REFERENCES mulino_work_read_Works(organizationId,ID),
 FOREIGN KEY(organizationId,itemId) REFERENCES mulino_inventory_TradeItems(organizationId,ID),
 FOREIGN KEY(organizationId,lotId) REFERENCES mulino_inventory_ManufacturingLots(organizationId,ID),
 FOREIGN KEY(organizationId,placeId) REFERENCES mulino_inventory_Places(organizationId,ID),
 FOREIGN KEY(organizationId,authorizationId) REFERENCES mulino_trade_returns_Authorizations(organizationId,ID)
);
CREATE TABLE mulino_trade_returns_Receipts(
 organizationId varchar(36) NOT NULL,
 ID varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 observationId varchar(36),
 authorizationId varchar(36),
 eventId varchar(36),
 canonicalOccurrenceId varchar(36),
 workId varchar(36),
 deliveryId varchar(36),
 customerId varchar(36),
 itemId varchar(36),
 lotId varchar(36),
 rangeRootId varchar(36),
 startQuantity numeric(38,12),
 quantity numeric(38,12),
 unit varchar(40),
 placeId varchar(36),
 segmentId varchar(36),
 restrictionId varchar(36),
 occurredAt timestamptz,
 commandId varchar(36),
 PRIMARY KEY(organizationId,ID),
 CHECK(quantity>0 AND startQuantity>=0),
 FOREIGN KEY(organizationId,workId) REFERENCES mulino_work_read_Works(organizationId,ID),
 FOREIGN KEY(organizationId,itemId) REFERENCES mulino_inventory_TradeItems(organizationId,ID),
 FOREIGN KEY(organizationId,lotId) REFERENCES mulino_inventory_ManufacturingLots(organizationId,ID),
 FOREIGN KEY(organizationId,placeId) REFERENCES mulino_inventory_Places(organizationId,ID),
 FOREIGN KEY(organizationId,authorizationId) REFERENCES mulino_trade_returns_Authorizations(organizationId,ID),
 FOREIGN KEY(organizationId,observationId) REFERENCES mulino_trade_returns_Observations(organizationId,ID),
 FOREIGN KEY(organizationId,segmentId) REFERENCES mulino_inventory_QuantitySegments(organizationId,ID),
 FOREIGN KEY(organizationId,canonicalOccurrenceId) REFERENCES mulino_evidence_CanonicalOccurrences(organizationId,ID)
);
CREATE TRIGGER returns_receipts_immutable BEFORE UPDATE OR DELETE ON mulino_trade_returns_Receipts FOR EACH ROW EXECUTE FUNCTION mulino_evidence_reject_mutation();
CREATE TABLE mulino_trade_returns_Dispositions(
 organizationId varchar(36) NOT NULL,
 ID varchar(36) NOT NULL,
 revision integer NOT NULL,
 createdAt timestamptz NOT NULL,
 recordedAt timestamptz NOT NULL,
 returnId varchar(36),
 workId varchar(36),
 decision varchar(40),
 actorId varchar(36),
 evidenceId varchar(36),
 policyHash varchar(64),
 commandId varchar(36),
 reason varchar(320),
 PRIMARY KEY(organizationId,ID),
 FOREIGN KEY(organizationId,workId) REFERENCES mulino_work_read_Works(organizationId,ID),
 FOREIGN KEY(organizationId,actorId) REFERENCES mulino_identity_Actors(organizationId,ID)
);
CREATE TRIGGER returns_dispositions_immutable BEFORE UPDATE OR DELETE ON mulino_trade_returns_Dispositions FOR EACH ROW EXECUTE FUNCTION mulino_evidence_reject_mutation();
CREATE UNIQUE INDEX returns_one_event ON mulino_trade_returns_Receipts(organizationId,eventId);
CREATE UNIQUE INDEX returns_one_canonical ON mulino_trade_returns_Receipts(organizationId,canonicalOccurrenceId);
ALTER TABLE mulino_trade_returns_Receipts ADD CONSTRAINT returns_physical_overlap EXCLUDE USING gist (organizationId WITH =, rangeRootId WITH =, numrange(startQuantity,startQuantity+quantity,'[)') WITH &&);
