CREATE TABLE mulino_identity_Organizations (ID VARCHAR(36) PRIMARY KEY, externalAlias VARCHAR(80) NOT NULL UNIQUE, revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0), createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, recordedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE mulino_identity_Actors (organizationId VARCHAR(36) NOT NULL REFERENCES mulino_identity_Organizations(ID), ID VARCHAR(36) NOT NULL, kind VARCHAR(20) NOT NULL CHECK(kind IN ('HUMAN','AGENT','EXTERNAL')), stableRequestOwner VARCHAR(36) NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0), createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, recordedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(organizationId,ID));

CREATE TABLE mulino_identity_ExternalIdentities (organizationId VARCHAR(36) NOT NULL, ID VARCHAR(36) NOT NULL, actorId VARCHAR(36) NOT NULL, issuer VARCHAR(500) NOT NULL, subject VARCHAR(200) NOT NULL, organizationAlias VARCHAR(80) NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0), createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, recordedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(organizationId,ID), FOREIGN KEY(organizationId,actorId) REFERENCES mulino_identity_Actors(organizationId,ID), UNIQUE(issuer,subject,organizationAlias));

CREATE TABLE mulino_identity_Memberships (organizationId VARCHAR(36) NOT NULL, ID VARCHAR(36) NOT NULL, actorId VARCHAR(36) NOT NULL, validFrom TIMESTAMPTZ NOT NULL, validUntil TIMESTAMPTZ NOT NULL, revokedAt TIMESTAMPTZ, revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0), createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, recordedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(organizationId,ID), FOREIGN KEY(organizationId,actorId) REFERENCES mulino_identity_Actors(organizationId,ID), CHECK(validUntil > validFrom));

CREATE TABLE mulino_identity_CapabilityAssignments (organizationId VARCHAR(36) NOT NULL, ID VARCHAR(36) NOT NULL, actorId VARCHAR(36) NOT NULL, capabilityId VARCHAR(100) NOT NULL, scopeKind VARCHAR(20) NOT NULL CHECK(scopeKind IN ('ORGANIZATION','TARGET','WORK','ITEM','PLACE','SOURCE')), scopeId VARCHAR(36) NOT NULL, validFrom TIMESTAMPTZ NOT NULL, validUntil TIMESTAMPTZ NOT NULL, revokedAt TIMESTAMPTZ, revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0), createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, recordedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(organizationId,ID), FOREIGN KEY(organizationId,actorId) REFERENCES mulino_identity_Actors(organizationId,ID), CHECK(validUntil > validFrom));

CREATE TABLE mulino_identity_Grants (organizationId VARCHAR(36) NOT NULL, ID VARCHAR(36) NOT NULL, actorId VARCHAR(36) NOT NULL, delegatorId VARCHAR(36) NOT NULL, validFrom TIMESTAMPTZ NOT NULL, validUntil TIMESTAMPTZ NOT NULL, revokedAt TIMESTAMPTZ, revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0), createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, recordedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(organizationId,ID), FOREIGN KEY(organizationId,actorId) REFERENCES mulino_identity_Actors(organizationId,ID), CHECK(validUntil > validFrom), FOREIGN KEY(organizationId,delegatorId) REFERENCES mulino_identity_Actors(organizationId,ID));

CREATE TABLE mulino_identity_GrantActions (organizationId VARCHAR(36) NOT NULL, grantId VARCHAR(36) NOT NULL, capabilityId VARCHAR(100) NOT NULL, PRIMARY KEY(organizationId,grantId,capabilityId), FOREIGN KEY(organizationId,grantId) REFERENCES mulino_identity_Grants(organizationId,ID));

CREATE TABLE mulino_identity_GrantScopes (organizationId VARCHAR(36) NOT NULL, grantId VARCHAR(36) NOT NULL, scopeKind VARCHAR(20) NOT NULL CHECK(scopeKind IN ('ORGANIZATION','TARGET','WORK','ITEM','PLACE','SOURCE')), scopeId VARCHAR(36) NOT NULL, PRIMARY KEY(organizationId,grantId,scopeKind,scopeId), FOREIGN KEY(organizationId,grantId) REFERENCES mulino_identity_Grants(organizationId,ID));

CREATE TABLE mulino_identity_AuthorityFences (organizationId VARCHAR(36) NOT NULL, actorId VARCHAR(36) NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision > 0), PRIMARY KEY(organizationId,actorId), FOREIGN KEY(organizationId,actorId) REFERENCES mulino_identity_Actors(organizationId,ID));
