
CREATE TABLE mulino_evidence_SourceProfiles (
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  namespace VARCHAR(160),
  policyVersion VARCHAR(160),
  intakeOwnerId VARCHAR(36),
  supervisorId VARCHAR(36),
  nextAction VARCHAR(320),
  nextCheckAt TIMESTAMP,
  PRIMARY KEY(ID)
);

CREATE TABLE mulino_evidence_DocumentVersions (
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  subjectKind VARCHAR(20),
  subjectId VARCHAR(36),
  itemId VARCHAR(36),
  placeId VARCHAR(36),
  workId VARCHAR(36),
  sha256 VARCHAR(64),
  blobId VARCHAR(36),
  byteLength BIGINT,
  mediaType VARCHAR(160),
  sourceNamespace VARCHAR(160),
  sourceProfileId VARCHAR(36),
  sourceReference VARCHAR(320),
  availability VARCHAR(24),
  supersedesId VARCHAR(36),
  provenance TEXT,
  PRIMARY KEY(ID)
);

CREATE TABLE mulino_evidence_Events (
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  subjectKind VARCHAR(20),
  subjectId VARCHAR(36),
  itemId VARCHAR(36),
  placeId VARCHAR(36),
  workId VARCHAR(36),
  effectiveFrom TIMESTAMP,
  effectiveUntil TIMESTAMP,
  timeZone VARCHAR(80),
  timePrecision VARCHAR(20),
  valueState VARCHAR(24),
  kind VARCHAR(80),
  sourceNamespace VARCHAR(160),
  sourceProfileId VARCHAR(36),
  externalEventId VARCHAR(160),
  sourceVersion VARCHAR(80),
  payloadHash VARCHAR(64),
  payload TEXT,
  supersedesId VARCHAR(36),
  invalidatesId VARCHAR(36),
  PRIMARY KEY(ID)
);

CREATE TABLE mulino_evidence_Claims (
  sourceProfileId VARCHAR(36),
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  subjectKind VARCHAR(20),
  subjectId VARCHAR(36),
  itemId VARCHAR(36),
  placeId VARCHAR(36),
  workId VARCHAR(36),
  effectiveFrom TIMESTAMP,
  effectiveUntil TIMESTAMP,
  timeZone VARCHAR(80),
  timePrecision VARCHAR(20),
  valueState VARCHAR(24),
  eventId VARCHAR(36),
  documentVersionId VARCHAR(36),
  assertion TEXT,
  quantity DECIMAL(38, 12),
  unit VARCHAR(24),
  supersedesId VARCHAR(36),
  PRIMARY KEY(ID)
);

CREATE TABLE mulino_evidence_InboxRecords (
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  subjectKind VARCHAR(20),
  subjectId VARCHAR(36),
  itemId VARCHAR(36),
  placeId VARCHAR(36),
  workId VARCHAR(36),
  eventId VARCHAR(36),
  sourceNamespace VARCHAR(160),
  sourceProfileId VARCHAR(36),
  externalEventId VARCHAR(160),
  sourceVersion VARCHAR(80),
  payloadHash VARCHAR(64),
  state VARCHAR(24),
  conflictsWithId VARCHAR(36),
  intakeOwnerId VARCHAR(36),
  supervisorId VARCHAR(36),
  nextAction VARCHAR(320),
  nextCheckAt TIMESTAMP,
  PRIMARY KEY(ID)
);

CREATE TABLE mulino_evidence_CanonicalOccurrences (
  sourceProfileId VARCHAR(36),
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  subjectKind VARCHAR(20),
  subjectId VARCHAR(36),
  itemId VARCHAR(36),
  placeId VARCHAR(36),
  workId VARCHAR(36),
  effectiveFrom TIMESTAMP,
  effectiveUntil TIMESTAMP,
  timeZone VARCHAR(80),
  timePrecision VARCHAR(20),
  valueState VARCHAR(24),
  kind VARCHAR(80),
  physicalScopeId VARCHAR(36),
  quantity DECIMAL(38, 12),
  unit VARCHAR(24),
  supersedesId VARCHAR(36),
  reassessmentState VARCHAR(24),
  PRIMARY KEY(ID)
);

CREATE TABLE mulino_evidence_Verifications (
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  claimId VARCHAR(36),
  canonicalOccurrenceId VARCHAR(36),
  basisDocumentId VARCHAR(36),
  policyVersion VARCHAR(160),
  sourceMatched BOOLEAN,
  identityMatched BOOLEAN,
  quantityMatched BOOLEAN,
  timeMatched BOOLEAN,
  duplicateChecked BOOLEAN,
  verdict VARCHAR(24),
  reason VARCHAR(640),
  PRIMARY KEY(ID)
);

CREATE TABLE mulino_evidence_EvidenceLinks (
  ID VARCHAR(36) NOT NULL,
  organizationId VARCHAR(36),
  revision INTEGER,
  createdAt TIMESTAMP,
  recordedAt TIMESTAMP,
  recordedBy VARCHAR(36),
  documentVersionId VARCHAR(36),
  eventId VARCHAR(36),
  claimId VARCHAR(36),
  canonicalOccurrenceId VARCHAR(36),
  role VARCHAR(40),
  PRIMARY KEY(ID)
);

