package com.mulino.application.responsibility;

import com.mulino.application.core.*;
import com.mulino.application.identity.IdentityAuthorization;
import com.mulino.application.work.*;
import com.mulino.domain.identity.IdentityRepository;
import com.mulino.domain.responsibility.ResponsibilityRepository;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import org.springframework.stereotype.Service;

/** Invoked only inside the common command or runtime transaction, never commits independently. */
@Service
public class ResponsibilityService implements WorkResponsibility {
 private final ResponsibilityRepository r; private final WorkAccess work;
 private final IdentityRepository identities; private final IdentityAuthorization auth; private final ResponsibilityEvidence evidence;
 public ResponsibilityService(ResponsibilityRepository r,WorkAccess work,IdentityRepository identities,IdentityAuthorization auth,ResponsibilityEvidence evidence){this.r=r;this.work=work;this.identities=identities;this.auth=auth;this.evidence=evidence;}
 private static String text(Map<String,Object> m,String k){Object v=m.get(k);if(v==null||v.toString().isBlank())throw DomainError.invalid("Missing "+k);return v.toString();}
 private static Instant at(Object v){return v instanceof Instant i?i:Instant.parse(v.toString());}
 private static BigDecimal quantity(Object v){BigDecimal q=new BigDecimal(v.toString());if(q.signum()<=0||q.scale()>12||q.precision()>38)throw DomainError.invalid("Invalid duty quantity");return q;}
 private void human(DomainContext c,String id){if(!"HUMAN".equals(identities.actor(c.organizationId(),id).orElseThrow(DomainError::forbidden).get("kind")))throw DomainError.invalid("Human owner required");if(!identities.rows("Memberships",c.organizationId()).stream().anyMatch(x->id.equals(x.get("actorId"))&&active(x,Instant.now())))throw DomainError.invalid("Inactive human responsibility");}
 private static boolean active(Map<String,Object>x,Instant now){return x.get("validFrom")!=null&&x.get("validUntil")!=null&&!now.isBefore(at(x.get("validFrom")))&&now.isBefore(at(x.get("validUntil")))&&(x.get("revokedAt")==null||now.isBefore(at(x.get("revokedAt"))));}
 private Map<String,Object> row(DomainContext c,String id){var m=new LinkedHashMap<String,Object>();m.put("organizationId",c.organizationId());m.put("ID",id);m.put("revision",0);m.put("createdAt",c.knownAt());m.put("recordedAt",c.knownAt());return m;}
 public void activated(DomainContext c,Map<String,Object>w,Map<String,Object>goal){r.fence(c.organizationId(),text(w,"ID"));human(c,text(w,"ownerId"));human(c,text(w,"supervisorId"));}
 public void requireSettled(DomainContext c,String workId){r.fence(c.organizationId(),workId);if(assignments(c,workId).stream().anyMatch(ResponsibilityService::open))throw new DomainError("REJECTED","UNRESOLVED_DUTY","Unresolved valid duties require accepted follow-up responsibility");}
 public void followup(DomainContext c,String original,String target,Map<String,Object>p){/* Creating a follow-up is not recipient acceptance. */ work.require(c,original,true);work.require(c,target,true);}
 private List<Map<String,Object>> assignments(DomainContext c,String workId){return r.rows("Assignments",c.organizationId()).stream().filter(x->workId.equals(x.get("workId"))).toList();}
 private static boolean open(Map<String,Object>x){return "OPEN".equals(x.get("status"))&&!Boolean.FALSE.equals(x.get("valid"));}
 public Map<String,Object> openDuty(DomainContext c,Map<String,Object>p){String workId=text(p,"workId");r.fence(c.organizationId(),workId);var w=work.require(c,workId,true);if(!Set.of("ACTIVE","WAITING").contains(w.get("status")))throw DomainError.invalid("Duty needs active work");human(c,text(w,"ownerId"));human(c,text(w,"supervisorId"));String kind=text(p,"kind"),scope=text(p,"scopeJson"),source=text(p,"sourceId"),version=text(p,"sourceVersion"),sourceKind=text(p,"sourceKind");if(!Set.of("OCCURRENCE","DECISION").contains(sourceKind))throw DomainError.invalid("Unsupported duty source");String key=hash(sourceKind+"|"+source+"|"+version+"|"+kind+"|"+scope);r.fence(c.organizationId(),key);var old=r.rows("Roots",c.organizationId()).stream().filter(x->key.equals(x.get("dutyKey"))).findFirst();if(old.isPresent())return old.get();
 var root=row(c,UUID.randomUUID().toString());root.putAll(Map.of("dutyKey",key,"sourceId",source,"sourceKind",sourceKind,"sourceVersion",version,"kind",kind,"scopeJson",scope));BigDecimal q=p.get("quantity")==null?null:quantity(p.get("quantity"));if(q!=null){root.put("quantity",q);root.put("unit",text(p,"unit"));}r.insert("Roots",root);
 var s=row(c,UUID.randomUUID().toString());s.putAll(Map.of("rootId",root.get("ID"),"startQuantity",BigDecimal.ZERO,"quantity",q==null?BigDecimal.ONE:q,"scopeJson",scope,"leaf",true));if(q!=null)s.put("unit",root.get("unit"));r.insert("Scopes",s);var a=assignment(c,root,s,w,text(p,"nextAction"),at(p.get("nextCheckAt")),null);r.insert("Assignments",a);return a;}
 private Map<String,Object> assignment(DomainContext c,Map<String,Object>root,Map<String,Object>s,Map<String,Object>w,String action,Instant next,String predecessor){var a=row(c,UUID.randomUUID().toString());a.putAll(Map.of("effectiveAt",c.asOf(),"workId",w.get("ID"),"rootId",root.get("ID"),"scopeId",s.get("ID"),"kind",root.get("kind"),"status","OPEN","ownerId",w.get("ownerId"),"supervisorId",w.get("supervisorId"),"nextAction",action));a.put("nextCheckAt",next);a.put("scopeJson",s.get("scopeJson"));a.put("valid",true);if(root.get("quantity")!=null){a.put("quantity",s.get("quantity"));a.put("unit",root.get("unit"));}if(predecessor!=null)a.put("predecessorId",predecessor);return a;}
 public Map<String,Object> propose(DomainContext c,Map<String,Object>p,boolean transfer){String workId=text(p,"workId");r.fence(c.organizationId(),workId);var w=work.require(c,workId,true);if(!c.actorId().equals(w.get("ownerId")))throw DomainError.forbidden();String recipient=text(p,"recipientId");human(c,recipient);String target=transfer?text(p,"targetWorkId"):workId;var tw=work.require(c,target,true);if(!Set.of("ACTIVE","WAITING").contains(tw.get("status")))throw DomainError.invalid("Target work inactive");if(transfer&&!recipient.equals(tw.get("ownerId")))throw DomainError.invalid("Target owner must accept");var h=row(c,UUID.randomUUID().toString());h.putAll(Map.of("kind",transfer?"TRANSFER":"OWNER","workId",workId,"targetWorkId",target,"previousOwnerId",w.get("ownerId"),"recipientId",recipient,"status","PROPOSED","expiresAt",at(p.get("expiresAt")),"nextAction",text(p,"nextAction"),"nextCheckAt",at(p.get("nextCheckAt"))));if(!at(h.get("expiresAt")).isAfter(Instant.now()))throw DomainError.invalid("Proposal expired");if(transfer){var a=r.require("Assignments",c.organizationId(),text(p,"assignmentId"));if(!open(a)||!workId.equals(a.get("workId")))throw DomainError.invalid("Duty not current");h.put("assignmentId",a.get("ID"));if(p.get("quantity")!=null)h.put("quantity",quantity(p.get("quantity")));}r.insert("Handovers",h);return h;}
 public Map<String,Object> decide(DomainContext c,String id,String decision){var h=r.require("Handovers",c.organizationId(),id);r.fence(c.organizationId(),text(h,"workId"));r.fence(c.organizationId(),id);h=r.require("Handovers",c.organizationId(),id);if(!"PROPOSED".equals(h.get("status")))throw DomainError.invalid("Handover already decided");boolean expired=!Instant.now().isBefore(at(h.get("expiresAt")));if("EXPIRED".equals(decision)&&!expired)throw DomainError.invalid("Not expired");if(!"EXPIRED".equals(decision)&&!c.actorId().equals(h.get("recipientId")))throw DomainError.forbidden();if("ACCEPTED".equals(decision)&&expired)throw DomainError.invalid("Expired handover");var w=work.require(c,text(h,"workId"),true);if(!h.get("previousOwnerId").equals(w.get("ownerId")))throw DomainError.invalid("Owner changed");if("ACCEPTED".equals(decision)){human(c,text(h,"recipientId"));auth.authorizeScope(c,"acceptHandover","WORK",text(h,"targetWorkId"));if("TRANSFER".equals(h.get("kind")))transfer(c,h);else{work.replaceOwner(c,text(h,"workId"),text(h,"previousOwnerId"),text(h,"recipientId"));for(var a:assignments(c,text(h,"workId")))if(open(a))r.update("Assignments",c.organizationId(),text(a,"ID"),Map.of("ownerId",h.get("recipientId"),"nextAction",h.get("nextAction"),"nextCheckAt",h.get("nextCheckAt"),"revision",((Number)a.get("revision")).intValue()+1));}}
 r.update("Handovers",c.organizationId(),id,Map.of("status",decision,"revision",((Number)h.get("revision")).intValue()+1));return r.require("Handovers",c.organizationId(),id);}
 private void transfer(DomainContext c,Map<String,Object>h){var a=r.require("Assignments",c.organizationId(),text(h,"assignmentId"));r.fence(c.organizationId(),text(a,"rootId"));a=r.require("Assignments",c.organizationId(),text(h,"assignmentId"));if(!open(a))throw DomainError.invalid("Duty already moved");String target=text(h,"targetWorkId");var w=work.require(c,target,true);if(!Set.of("ACTIVE","WAITING").contains(w.get("status"))||!h.get("recipientId").equals(w.get("ownerId")))throw DomainError.invalid("Recipient no longer target owner");for(var previous:r.rows("Assignments",c.organizationId()))if(a.get("scopeId").equals(previous.get("scopeId"))&&target.equals(previous.get("workId")))throw DomainError.invalid("Transfer cycle");var root=r.require("Roots",c.organizationId(),text(a,"rootId"));var scope=r.require("Scopes",c.organizationId(),text(a,"scopeId"));BigDecimal full=(BigDecimal)scope.get("quantity"),q=h.get("quantity")==null?full:quantity(h.get("quantity"));if(q.compareTo(full)>0)throw DomainError.invalid("Transfer exceeds scope");r.update("Assignments",c.organizationId(),text(a,"ID"),Map.of("status","TRANSFERRED","valid",false,"revision",((Number)a.get("revision")).intValue()+1));if(q.compareTo(full)<0){if(root.get("quantity")==null)throw DomainError.invalid("Nonquantity duty cannot split");r.update("Scopes",c.organizationId(),text(scope,"ID"),Map.of("leaf",false));var remaining=child(c,scope,(BigDecimal)scope.get("startQuantity"),full.subtract(q));var moving=child(c,scope,((BigDecimal)scope.get("startQuantity")).add(full.subtract(q)),q);r.insert("Assignments",assignment(c,root,remaining,work.require(c,text(a,"workId"),true),text(a,"nextAction"),at(a.get("nextCheckAt")),text(a,"ID")));scope=moving;}r.insert("Assignments",assignment(c,root,scope,w,text(h,"nextAction"),at(h.get("nextCheckAt")),text(a,"ID")));}
 private Map<String,Object> child(DomainContext c,Map<String,Object>parent,BigDecimal start,BigDecimal q){var s=row(c,UUID.randomUUID().toString());s.putAll(Map.of("rootId",parent.get("rootId"),"parentScopeId",parent.get("ID"),"startQuantity",start,"quantity",q,"leaf",true,"scopeJson",parent.get("scopeJson")));s.put("unit",parent.get("unit"));r.insert("Scopes",s);return s;}
 public Map<String,Object> settle(DomainContext c,Map<String,Object>p,boolean waive){String id=text(p,"assignmentId");var a=r.require("Assignments",c.organizationId(),id);r.fence(c.organizationId(),text(a,"rootId"));a=r.require("Assignments",c.organizationId(),id);if(!open(a))throw DomainError.invalid("Duty not open");String ev=text(p,"evidenceId");if(waive)evidence.requireWaiver(c,text(a,"kind"),text(a,"rootId"),ev,text(p,"reason"));else evidence.requireResolution(c,text(a,"kind"),text(a,"rootId"),text(a,"scopeId"),ev);r.update("Assignments",c.organizationId(),id,Map.of("status",waive?"WAIVED":"RESOLVED","evidenceId",ev,"basis",waive?text(p,"reason"):"VERIFIED_RESOLUTION","revision",((Number)a.get("revision")).intValue()+1));return r.require("Assignments",c.organizationId(),id);}
 public Map<String,Object> gap(DomainContext c,String workId){var w=work.require(c,workId,false);boolean gap;try{human(c,text(w,"ownerId"));gap=false;}catch(DomainError e){gap=true;}return Map.of("workId",workId,"responsibilityGap",gap,"ownerId",w.get("ownerId"),"supervisorId",w.get("supervisorId"));}
 private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
