package com.mulino.application.trade.recall;
import com.mulino.application.core.*;
import com.mulino.application.trade.*;
import com.mulino.application.work.WorkAccess;
import com.mulino.application.policy.PolicyCommandGuard;
import com.mulino.domain.evidence.EvidenceRepository;
import com.mulino.domain.identity.IdentityRepository;
import com.mulino.domain.inventory.*;
import com.mulino.domain.trade.recall.*;
import com.mulino.domain.responsibility.ResponsibilityRepository;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.trade.recall.RecallInputs.*;
@Component
public final class RecallCommands implements CommandHandler {
 private final RecallRepository r;private final InventoryRepository inventory;private final RecallStockPrimitives stock;private final WorkAccess works;private final ReadAuthorizer auth;private final IdentityRepository identity;private final TradeEvidence evidence;private final EvidenceRepository sources;private final PolicyCommandGuard policies;private final ExecutionClock clock;private final TradeImpact impact;private final ResponsibilityRepository responsibility;
 public RecallCommands(RecallRepository r,InventoryRepository inventory,RecallStockPrimitives stock,WorkAccess works,ReadAuthorizer auth,IdentityRepository identity,TradeEvidence evidence,EvidenceRepository sources,PolicyCommandGuard policies,ExecutionClock clock,TradeImpact impact,ResponsibilityRepository responsibility){this.r=r;this.inventory=inventory;this.stock=stock;this.works=works;this.auth=auth;this.identity=identity;this.evidence=evidence;this.sources=sources;this.policies=policies;this.clock=clock;this.impact=impact;this.responsibility=responsibility;}
 public Set<String> capabilities(){return Set.of("openInvestigation","proposeRecall","approveRecall","recordRecallNotice","recordRecovery","closeRecall");}
 public Set<String> intentKinds(){return Set.of("COMMAND","RECORD");}
 private Map<String,Object> investigation(DomainContext c,Map<String,Object>s){return r.current(c.organizationId(),"Investigations",id(s,"investigationId"));}
 private Map<String,Object> scope(DomainContext c,Map<String,Object>s){var sc=r.current(c.organizationId(),"Scopes",id(s,"scopeId"));var inv=r.current(c.organizationId(),"Investigations",sc.get("investigationId").toString());if(!Objects.equals(sc.get("ID"),inv.get("currentScopeId"))||"CLOSED".equals(inv.get("status")))throw new DomainError("HELD","RECALL_SCOPE_CHANGED","Recall scope is superseded or closed");return sc;}
 /** One canonical decimal text for the first response, replay and partition hash. */
 private static Map<String,Object> plain(Map<String,BigDecimal> partition){var out=new LinkedHashMap<String,Object>();partition.forEach((k,v)->out.put(k,v.stripTrailingZeros().toPlainString()));return Collections.unmodifiableMap(out);}
 private static Set<String> allowed(String op){return switch(op){case "openInvestigation"->Set.of("segmentId","lotId","itemId","workId","startQuantity","quantity","unit","basisEvidenceId","occurredAt","nextAction","nextCheckAt");case "proposeRecall"->Set.of("investigationId","startQuantity","quantity","unit","reason");case "approveRecall"->Set.of("scopeId","scopeHash","decision","validUntil");case "recordRecallNotice","recordRecovery"->Set.of("scopeId","approvalId","scopeHash","canonicalOccurrenceId","actualEventId","kind","rootSegmentId","startQuantity","quantity","unit","sourceSegmentId","currentPlaceId","returnId","reason","nextAction","nextCheckAt");case "closeRecall"->Set.of("scopeId","approvalId","scopeHash","canonicalOccurrenceId","partitionHash");default->throw DomainError.unsupported();};}
 public CommandPreparation prepare(DomainContext c,Map<String,Object>i){var s=slots(i);String op=text(i,"capabilityId");if(!allowed(op).containsAll(s.keySet()))throw DomainError.invalid("Unsupported recall slots");if(!Objects.equals(i.get("intentKind"),Set.of("recordRecallNotice","recordRecovery").contains(op)?"RECORD":"COMMAND"))throw DomainError.invalid("Recall intent kind mismatch");
  Map<String,Object> t=op.equals("openInvestigation")?inventory.current(c,"QuantitySegments",id(s,"segmentId")):op.equals("proposeRecall")?investigation(c,s):scope(c,s);String root=op.equals("openInvestigation")?t.get("ID").toString():op.equals("proposeRecall")?t.get("segmentId").toString():t.get("rootSegmentId").toString();String work=op.equals("openInvestigation")?id(s,"workId"):t.get("workId").toString();var w=works.require(c,work,false);
  var scoped=new LinkedHashMap<String,List<String>>();scoped.put("ITEM",List.of(t.get("itemId").toString()));scoped.put("WORK",List.of(work));scoped.put("TARGET",List.of(t.get("ID").toString(),root).stream().distinct().toList());var places=new TreeSet<String>();places.add(inventory.current(c,"QuantitySegments",root).get("placeId").toString());if(s.get("currentPlaceId")!=null){inventory.current(c,"Places",id(s,"currentPlaceId"));places.add(s.get("currentPlaceId").toString());}if(s.get("sourceSegmentId")!=null){var leaf=inventory.current(c,"QuantitySegments",id(s,"sourceSegmentId"));if(!Objects.equals(leaf.get("itemId"),t.get("itemId"))||!Objects.equals(leaf.get("lotId"),t.get("lotId")))throw DomainError.invalid("Recovery segment identity mismatch");places.add(leaf.get("placeId").toString());}scoped.put("PLACE",List.copyOf(places));
  var actors=new TreeSet<String>(List.of(w.get("ownerId").toString(),w.get("supervisorId").toString()));if(s.get("approvalId")!=null)actors.add(r.current(c.organizationId(),"Approvals",id(s,"approvalId")).get("approverId").toString());var fences=new TreeSet<String>(List.of("inventory/item/"+t.get("itemId"),"inventory/segment/"+root,"recall/"+(op.equals("openInvestigation")?root:op.equals("proposeRecall")?t.get("ID"):t.get("investigationId")),"work:"+work));fences.add("inventory/control/"+inventory.current(c,"QuantitySegments",root).get("controlScope"));places.forEach(x->fences.add("inventory/place/"+x));if(s.get("sourceSegmentId")!=null)fences.add("inventory/segment/"+s.get("sourceSegmentId"));
  if(op.equals("closeRecall")){for(var action:r.rows(c,"Actions"))if(t.get("investigationId").equals(action.get("investigationId"))&&"EXCEPTION".equals(action.get("kind"))){var original=responsibility.require("Assignments",c.organizationId(),action.get("residualDutyId").toString());for(var duty:responsibility.rows("Assignments",c.organizationId()))if(original.get("rootId").equals(duty.get("rootId"))&&Boolean.TRUE.equals(duty.get("valid"))){actors.add(duty.get("ownerId").toString());actors.add(duty.get("supervisorId").toString());fences.add("work:"+duty.get("workId"));}}}authorizeEvery(c,op,scoped);return new CommandPreparation(scoped,List.copyOf(fences),actors,"RECALL",null,null,0,t.get("ID").toString(),n(t.getOrDefault("revision",0)));
 }
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object>i,CommandPreparation p){var s=slots(i);String op=text(i,"capabilityId");var t=op.equals("openInvestigation")?inventory.current(c,"QuantitySegments",id(s,"segmentId")):op.equals("proposeRecall")?investigation(c,s):scope(c,s);return List.of(SubjectBinding.optional("TradeItem",Set.of(t.get("itemId").toString())),SubjectBinding.optional("Work",Set.of(op.equals("openInvestigation")?id(s,"workId"):t.get("workId").toString())));}
 public Map<String,Object> execute(DomainContext c,Map<String,Object>i){var preparation=prepare(c,i);inventory.fence(c,preparation.fenceKeys());prepare(c,i);var s=slots(i);String op=text(i,"capabilityId");var effects=new LinkedHashMap<String,Object>();
  switch(op){
   case "openInvestigation"->{var seg=inventory.current(c,"QuantitySegments",id(s,"segmentId"));String work=id(s,"workId");var w=works.require(c,work,true);if(!Objects.equals(seg.get("itemId"),id(s,"itemId"))||!Objects.equals(seg.get("lotId"),id(s,"lotId"))||!Objects.equals(seg.get("itemId"),w.get("itemId")))throw DomainError.invalid("Investigation LOT/item/work mismatch");var q=InventoryQuantity.parse(text(s,"quantity"),n(inventory.current(c,"TradeItems",seg.get("itemId").toString()).get("decimalPlaces")));var start=decimal(s.get("startQuantity"),false);if(start.add(q).compareTo((BigDecimal)seg.get("quantity"))>0||!seg.get("unit").equals(s.get("unit")))throw DomainError.invalid("Investigation exceeds physical scope");var basis=sources.require("Events",c.organizationId(),id(s,"basisEvidenceId"));if(!Objects.equals(basis.get("itemId"),seg.get("itemId")))throw DomainError.invalid("Investigation evidence item mismatch");auth.authorizeScopes(c,"getEvidence",com.mulino.domain.evidence.EvidenceTypes.scopes(basis));Instant occurred=at(s.get("occurredAt")),next=at(s.get("nextCheckAt"));if(occurred.isAfter(c.knownAt())||!next.isAfter(clock.instant()))throw DomainError.invalid("Investigation time invalid");var row=row(c);row.putAll(Map.of("itemId",seg.get("itemId"),"lotId",seg.get("lotId"),"segmentId",seg.get("ID"),"workId",work,"startQuantity",start,"quantity",q,"unit",seg.get("unit"),"basisEvidenceId",basis.get("ID"),"occurredAt",occurred));row.putAll(Map.of("impactState","CANDIDATE","status","INVESTIGATING","ownerId",w.get("ownerId"),"supervisorId",w.get("supervisorId"),"nextAction",text(s,"nextAction"),"nextCheckAt",next));r.insert("Investigations",row);var held=stock.investigate(c,seg.get("ID").toString(),start,q,work,row.get("ID").toString(),basis.get("ID").toString(),next,policies.rule(c,"openInvestigation").policyHash());impact.recorded(c,work,row.get("ID").toString(),"RECALL_INVESTIGATION",seg.get("ID").toString(),text(s,"nextAction"),next);effects.putAll(Map.of("investigationId",row.get("ID"),"impactState","CANDIDATE","restrictionIds",held));}
   case "proposeRecall"->{var inv=investigation(c,s);if("CLOSED".equals(inv.get("status")))throw DomainError.invalid("Investigation closed");if(inv.get("currentScopeId")!=null)admin(c,preparation.scopes());var q=InventoryQuantity.parse(text(s,"quantity"),n(inventory.current(c,"TradeItems",inv.get("itemId").toString()).get("decimalPlaces")));var start=decimal(s.get("startQuantity"),false);if(start.compareTo((BigDecimal)inv.get("startQuantity"))<0||start.add(q).compareTo(((BigDecimal)inv.get("startQuantity")).add((BigDecimal)inv.get("quantity")))>0||!inv.get("unit").equals(s.get("unit")))throw DomainError.invalid("Recall scope exceeds investigation");var sc=row(c);sc.putAll(Map.of("investigationId",inv.get("ID"),"version",n(inv.get("revision"))+1,"rootSegmentId",inv.get("segmentId"),"startQuantity",start,"quantity",q,"unit",inv.get("unit"),"itemId",inv.get("itemId"),"lotId",inv.get("lotId"),"workId",inv.get("workId"),"reason",text(s,"reason")));var semantic=new TreeMap<String,Object>();for(String k:List.of("investigationId","version","rootSegmentId","startQuantity","quantity","unit","itemId","lotId","workId","reason"))semantic.put(k,sc.get(k).toString());sc.put("scopeHash",CommandRequests.hash(semantic));r.insert("Scopes",sc);var omitted=QualityRanges.subtract(QualityRanges.subtract(List.of(new QualityRanges.Range((BigDecimal)inv.get("startQuantity"),((BigDecimal)inv.get("startQuantity")).add((BigDecimal)inv.get("quantity")))),List.of(new QualityRanges.Range(start,start.add(q)))),openExcluded(c,inv));for(var gap:omitted)impact.recorded(c,inv.get("workId").toString(),sc.get("ID").toString(),"RECALL_EXCLUDED_SCOPE",inv.get("segmentId").toString(),inv.get("nextAction").toString(),at(inv.get("nextCheckAt")),Map.of("scopeId",sc.get("ID"),"startQuantity",gap.start().toPlainString()),gap.end().subtract(gap.start()),inv.get("unit").toString());r.update(c,"Investigations",inv.get("ID").toString(),Map.of("currentScopeId",sc.get("ID"),"revision",n(inv.get("revision"))+1,"status","PROPOSED"));effects.putAll(Map.of("scopeId",sc.get("ID"),"scopeVersion",sc.get("version"),"scopeHash",sc.get("scopeHash")));}
   case "approveRecall"->{var sc=scope(c,s);admin(c,preparation.scopes());hash(sc,s);String decision=text(s,"decision");if(!Set.of("APPROVE","REJECT").contains(decision))throw DomainError.invalid("Recall decision invalid");Instant until=at(s.get("validUntil"));if(!until.isAfter(clock.instant()))throw DomainError.invalid("Approval expired");var a=row(c);a.put("revision",r.rows(c,"Approvals").stream().filter(x->sc.get("ID").equals(x.get("scopeId"))).mapToInt(x->n(x.get("revision"))).max().orElse(0)+1);a.putAll(Map.of("scopeId",sc.get("ID"),"scopeVersion",sc.get("version"),"scopeHash",sc.get("scopeHash"),"approverId",c.actorId(),"decision",decision,"validUntil",until,"policyHash",policies.rule(c,"approveRecall").policyHash()));r.insert("Approvals",a);r.update(c,"Investigations",sc.get("investigationId").toString(),Map.of("status",decision.equals("APPROVE")?"APPROVED":"REJECTED"));effects.putAll(Map.of("approvalId",a.get("ID"),"scopeId",sc.get("ID"),"noticeRecorded",false,"submissionConfirmed",false));}
   case "recordRecallNotice","recordRecovery"->{var sc=scope(c,s);var a=approval(c,sc,s,preparation.scopes());String kind=op.equals("recordRecallNotice")?"NOTICE":text(s,"kind");if(op.equals("recordRecovery")&&!Set.of("RECOVERED","DISPOSED","SAFE","CONSUMED_LOST","EXCEPTION").contains(kind))throw DomainError.invalid("Recall processing kind invalid");var q=InventoryQuantity.parse(text(s,"quantity"),n(inventory.current(c,"TradeItems",sc.get("itemId").toString()).get("decimalPlaces")));BigDecimal start=decimal(s.get("startQuantity"),false);bounds(sc,start,q);if(!Objects.equals(sc.get("rootSegmentId"),id(s,"rootSegmentId"))||!Objects.equals(sc.get("unit"),s.get("unit")))throw DomainError.invalid("Recall root or unit mismatch");String occurrence=id(s,"canonicalOccurrenceId");String eventKind="RECALL_"+switch(kind){case "RECOVERED"->"RECOVERY";case "DISPOSED"->"DISPOSAL";default->kind;};var fact=evidence.requireCanonical(c,occurrence,eventKind,sc.get("itemId").toString(),sc.get("ID").toString(),q,sc.get("unit").toString());if(!Objects.equals(fact.get("occurrenceIdentity"),id(s,"actualEventId")))throw held();var payload=payload(c,fact);for(String k:List.of("actualEventId","scopeId","scopeHash","rootSegmentId","startQuantity","quantity","unit","currentPlaceId"))if(!Objects.equals(String.valueOf(s.get(k)),String.valueOf(payload.get(k))))throw held();for(String k:List.of("sourceSegmentId","returnId","reason"))if(!Objects.equals(s.get(k),payload.get(k)))throw held();
    var existing=r.rows(c,"Actions");if(existing.stream().anyMatch(x->id(s,"actualEventId").equals(x.get("actualEventId"))||occurrence.equals(x.get("canonicalOccurrenceId"))))throw new DomainError("CONFLICT","RECALL_EVENT_ALREADY_APPLIED","Physical recall event already applied");
    // Physical processing is a fact of the investigation's root range, not of one scope version (plan §6 반품·회수, D18).
    var inv=r.current(c.organizationId(),"Investigations",sc.get("investigationId").toString());var facts=existing.stream().filter(x->inv.get("ID").equals(x.get("investigationId"))).toList();var range=new QualityRanges.Range(start,start.add(q));String root=sc.get("rootSegmentId").toString();
    var recoveredOnRoot=existing.stream().filter(x->"RECOVERED".equals(x.get("kind"))&&root.equals(x.get("rootSegmentId"))).toList();var recoveredOverlap=QualityRanges.intersect(List.of(range),recoveredOnRoot.stream().map(RecallPartition::range).toList());
    if(kind.equals("RECOVERED")&&!recoveredOverlap.isEmpty())throw new DomainError("CONFLICT","RECALL_RANGE_ALREADY_RECOVERED","Physical recall range already recovered");
    if(kind.equals("RECOVERED")&&facts.stream().anyMatch(x->"CONSUMED_LOST".equals(x.get("kind"))&&!QualityRanges.intersect(List.of(range),List.of(RecallPartition.range(x))).isEmpty()))throw new DomainError("HELD","RECALL_PARTITION_CONFLICT","Range recorded as consumed or lost cannot also be recovered");
    if(Set.of("CONSUMED_LOST","EXCEPTION").contains(kind))for(var held:recoveredOverlap)if(stock.heldQuantity(c,root,held.start(),held.end().subtract(held.start())).signum()>0)throw new DomainError("HELD","RECALL_PARTITION_CONFLICT","Recovered stock still held in controlled storage must be disposed or found safe");
    var action=row(c);action.putAll(Map.of("scopeId",sc.get("ID"),"investigationId",inv.get("ID"),"approvalId",a.get("ID"),"canonicalOccurrenceId",occurrence,"actualEventId",id(s,"actualEventId"),"kind",kind,"rootSegmentId",root,"startQuantity",start,"quantity",q,"unit",sc.get("unit")));action.put("occurredAt",fact.get("effectiveFrom"));for(String k:List.of("sourceSegmentId","currentPlaceId","returnId","reason"))if(s.get(k)!=null)action.put(k,s.get(k));
    if(RecallPartition.TERMINAL.contains(kind)){var prospective=new ArrayList<>(facts);prospective.add(action);RecallPartition.quantities((BigDecimal)inv.get("startQuantity"),(BigDecimal)inv.get("quantity"),prospective);}
    if(kind.equals("RECOVERED")){if(!"INTERNAL_STORAGE".equals(inventory.current(c,"Places",id(s,"currentPlaceId")).get("kind")))throw DomainError.invalid("Recovery requires internal controlled storage");if(s.get("returnId")!=null){var returned=r.externalRows(c,"mulino.trade.returns.Receipts").stream().filter(x->id(s,"returnId").equals(x.get("ID"))).findFirst().orElseThrow(DomainError::forbidden);if(!Objects.equals(returned.get("itemId"),sc.get("itemId"))||!Objects.equals(returned.get("lotId"),sc.get("lotId"))||!Objects.equals(returned.get("placeId"),s.get("currentPlaceId"))||!Objects.equals(returned.get("segmentId"),s.get("sourceSegmentId"))||!Objects.equals(returned.get("unit"),sc.get("unit")))throw held();var currentLeaf=inventory.current(c,"QuantitySegments",returned.get("segmentId").toString());if(currentLeaf.get("retiredAt")!=null||!Objects.equals(currentLeaf.get("placeId"),returned.get("placeId")))throw held();evidence.requireCanonical(c,returned.get("canonicalOccurrenceId").toString(),"RETURN_RECEIPT",sc.get("itemId").toString(),returned.get("observationId").toString(),(BigDecimal)returned.get("quantity"),sc.get("unit").toString());stock.existingRecovery(c,sc.get("rootSegmentId").toString(),start,q,returned.get("segmentId").toString(),s.get("currentPlaceId").toString());action.put("currentSegmentId",returned.get("segmentId"));}else{String leaf=stock.recover(c,sc.get("rootSegmentId").toString(),start,q,id(s,"sourceSegmentId"),id(s,"currentPlaceId"),at(fact.get("effectiveFrom")),occurrence);action.put("currentSegmentId",leaf);}}
    // Stock decrease needs the current human MANAGER disposal confirmation on every scope value (plan §7.1); the recall ADMIN approval is checked by approval().
    if(kind.equals("DISPOSED")){manager(c,"disposeQuantity",preparation.scopes());if(!Objects.equals(inventory.current(c,"QuantitySegments",id(s,"sourceSegmentId")).get("placeId"),s.get("currentPlaceId")))throw held();var recovered=recoveredOnRoot.stream().map(RecallPartition::range).toList();if(!QualityRanges.subtract(List.of(range),recovered).isEmpty())throw DomainError.invalid("Disposal requires previously recovered same physical subset");stock.dispose(c,sc.get("rootSegmentId").toString(),start,q,id(s,"sourceSegmentId"),at(fact.get("effectiveFrom")),occurrence);}
    if(kind.equals("EXCEPTION")){admin(c,preparation.scopes());text(s,"reason");String nextAction=s.get("nextAction")!=null?text(s,"nextAction"):inv.get("nextAction").toString();Instant next=at(s.get("nextCheckAt")!=null?s.get("nextCheckAt"):inv.get("nextCheckAt"));if(!next.isAfter(clock.instant()))throw DomainError.invalid("Exception residual responsibility needs a future next check");var duty=impact.recorded(c,sc.get("workId").toString(),action.get("ID").toString(),"RECALL_EXCEPTION_RESIDUAL",sc.get("ID").toString(),nextAction,next,Map.of("scopeId",sc.get("ID"),"scopeHash",sc.get("scopeHash"),"startQuantity",start.toPlainString()),q,sc.get("unit").toString());if(duty.get("ID")==null)throw DomainError.invalid("Current residual duty required");action.put("residualDutyId",duty.get("ID"));}
    r.insert("Actions",action);var currentPartition=plain(partition(c,sc));effects.putAll(Map.of("actionId",action.get("ID"),"kind",kind,"partition",currentPartition,"partitionHash",CommandRequests.hash(currentPartition)));if(action.get("currentSegmentId")!=null)effects.put("currentSegmentId",action.get("currentSegmentId"));if(action.get("residualDutyId")!=null)effects.put("residualDutyId",action.get("residualDutyId"));}
   case "closeRecall"->{var sc=scope(c,s);var a=approval(c,sc,s,preparation.scopes());admin(c,preparation.scopes());var visible=RecallPartition.clip((BigDecimal)sc.get("startQuantity"),(BigDecimal)sc.get("quantity"),facts(c,sc)).stream().map(x->x.get("ID")).collect(java.util.stream.Collectors.toSet());var actions=facts(c,sc).stream().filter(x->visible.contains(x.get("ID"))).toList();var partition=partition(c,sc);if(partition.get("UNKNOWN").signum()>0)throw new DomainError("HELD","RECALL_RESIDUAL_UNKNOWN","Unknown physical scope cannot close without verified explicit ADMIN exception and human responsibility");for(var action:actions){String eventKind="RECALL_"+switch(action.get("kind").toString()){case "RECOVERED"->"RECOVERY";case "DISPOSED"->"DISPOSAL";default->action.get("kind").toString();};evidence.requireCanonical(c,action.get("canonicalOccurrenceId").toString(),eventKind,sc.get("itemId").toString(),action.get("scopeId").toString(),(BigDecimal)action.get("quantity"),sc.get("unit").toString());}String partitionHash=CommandRequests.hash(plain(partition));if(!partitionHash.equals(text(s,"partitionHash")))throw new DomainError("HELD","RECALL_PARTITION_CHANGED","Recall processing changed");for(var action:actions)if("EXCEPTION".equals(action.get("kind")))residual(c,action,sc);String occurrence=id(s,"canonicalOccurrenceId");var fact=evidence.requireCanonical(c,occurrence,"RECALL_CLOSURE",sc.get("itemId").toString(),sc.get("ID").toString(),(BigDecimal)sc.get("quantity"),sc.get("unit").toString());if(!partitionHash.equals(payload(c,fact).get("partitionHash")))throw held();var close=row(c);close.putAll(Map.of("investigationId",sc.get("investigationId"),"scopeId",sc.get("ID"),"approvalId",a.get("ID"),"scopeHash",sc.get("scopeHash"),"partitionJson",json(partition),"evidenceId",occurrence,"closedBy",c.actorId()));r.insert("Closures",close);r.update(c,"Investigations",sc.get("investigationId").toString(),Map.of("status","CLOSED","closedAt",clock.instant()));effects.putAll(Map.of("closureId",close.get("ID"),"partition",plain(partition),"residualResponsibilityRetained",partition.get("EXCEPTION").signum()>0));}
   default->throw DomainError.unsupported();
  }
  return Map.of("outcome","APPLIED","revision",op.equals("proposeRecall")?n(effects.get("scopeVersion")):preparation.currentRevision(),"effects",effects);
 }
 private void residual(DomainContext c,Map<String,Object>a,Map<String,Object>sc){
  var original=responsibility.require("Assignments",c.organizationId(),a.get("residualDutyId").toString());String rootId=original.get("rootId").toString();responsibility.fence(c.organizationId(),rootId);var root=responsibility.require("Roots",c.organizationId(),rootId);
  if(!"RECALL_EXCEPTION_RESIDUAL".equals(root.get("kind"))||!(root.get("quantity") instanceof BigDecimal full)||full.compareTo((BigDecimal)a.get("quantity"))!=0||!Objects.equals(root.get("unit"),a.get("unit")))throw DomainError.invalid("Current exception residual root required");
  var assignments=responsibility.rows("Assignments",c.organizationId()).stream().filter(d->rootId.equals(d.get("rootId"))&&Boolean.TRUE.equals(d.get("valid"))).toList();var covered=new ArrayList<QualityRanges.Range>();
  for(var duty:assignments){if(!"OPEN".equals(duty.get("status"))||!"RECALL_EXCEPTION_RESIDUAL".equals(duty.get("kind"))||duty.get("nextAction")==null||duty.get("nextCheckAt")==null||!at(duty.get("nextCheckAt")).isAfter(clock.instant()))throw DomainError.invalid("Current exception residual responsibility required");var range=responsibility.require("Scopes",c.organizationId(),duty.get("scopeId").toString());if(!Boolean.TRUE.equals(range.get("leaf")))throw DomainError.invalid("Current exception responsibility leaf required");covered.add(RecallPartition.range(range));for(String k:List.of("ownerId","supervisorId"))if(!"HUMAN".equals(identity.actor(c.organizationId(),duty.get(k).toString()).orElseThrow(DomainError::forbidden).get("kind")))throw DomainError.forbidden();}
  if(QualityRanges.quantity(covered).compareTo(full)!=0||QualityRanges.quantity(covered).compareTo(covered.stream().map(x->x.end().subtract(x.start())).reduce(BigDecimal.ZERO,BigDecimal::add))!=0||!QualityRanges.subtract(List.of(new QualityRanges.Range(BigDecimal.ZERO,full)),covered).isEmpty())throw DomainError.invalid("Complete disjoint residual responsibility coverage required");
 }
 private Map<String,Object> payload(DomainContext c,Map<String,Object>fact){var refs=(List<?>)fact.get("evidenceRefs");var event=sources.require("Events",c.organizationId(),refs.get(3).toString());try{return new com.fasterxml.jackson.databind.ObjectMapper().readValue(event.get("payload").toString(),Map.class);}catch(Exception e){throw held();}}
 private Map<String,Object> approval(DomainContext c,Map<String,Object>sc,Map<String,Object>s,Map<String,List<String>> scopes){hash(sc,s);var a=r.current(c.organizationId(),"Approvals",id(s,"approvalId"));var approvals=r.rows(c,"Approvals").stream().filter(x->sc.get("ID").equals(x.get("scopeId"))).sorted(Comparator.comparingInt(x->n(x.get("revision")))).toList();if(approvals.isEmpty()||!a.get("ID").equals(approvals.getLast().get("ID"))||!"APPROVE".equals(a.get("decision"))||!Objects.equals(sc.get("scopeHash"),a.get("scopeHash"))||!Objects.equals(sc.get("version"),a.get("scopeVersion"))||!Objects.equals(sc.get("ID"),a.get("scopeId"))||!clock.instant().isBefore(at(a.get("validUntil"))))throw new DomainError("HELD","RECALL_APPROVAL_STALE","Current exact ADMIN recall approval required");if(!policies.rule(c,"approveRecall").policyHash().equals(a.get("policyHash")))throw new DomainError("HELD","APPROVAL_POLICY_CHANGED","Recall policy changed");admin(new DomainContext(c.organizationId(),a.get("approverId").toString(),c.stableRequestOwner(),c.asOf(),c.knownAt()),scopes);return a;}
 private List<Map<String,Object>> facts(DomainContext c,Map<String,Object>sc){return r.rows(c,"Actions").stream().filter(x->sc.get("investigationId").equals(x.get("investigationId"))).toList();}
 /** Excluded ranges of earlier versions whose human review duty is still open; a re-scope does not duplicate them. */
 private List<QualityRanges.Range> openExcluded(DomainContext c,Map<String,Object> inv){
  var versions=r.rows(c,"Scopes").stream().filter(x->inv.get("ID").equals(x.get("investigationId"))).map(x->x.get("ID").toString()).collect(java.util.stream.Collectors.toSet());var open=new ArrayList<QualityRanges.Range>();var mapper=new com.fasterxml.jackson.databind.ObjectMapper();var assignments=responsibility.rows("Assignments",c.organizationId());
  for(var root:responsibility.rows("Roots",c.organizationId())){if(!"RECALL_EXCLUDED_SCOPE".equals(root.get("kind"))||!(root.get("quantity") instanceof BigDecimal q))continue;
   try{var residual=mapper.readTree(root.get("scopeJson").toString()).path("residual");if(!versions.contains(residual.path("scopeId").asText()))continue;
    if(assignments.stream().anyMatch(a->root.get("ID").equals(a.get("rootId"))&&Boolean.TRUE.equals(a.get("valid"))&&"OPEN".equals(a.get("status")))){var from=new BigDecimal(residual.path("startQuantity").asText());open.add(new QualityRanges.Range(from,from.add(q)));}
   }catch(java.io.IOException|NumberFormatException e){throw DomainError.invalid("Invalid excluded recall duty scope");}}
  return QualityRanges.union(open);
 }
 private Map<String,BigDecimal> partition(DomainContext c,Map<String,Object>sc){return RecallPartition.quantities((BigDecimal)sc.get("startQuantity"),(BigDecimal)sc.get("quantity"),RecallPartition.clip((BigDecimal)sc.get("startQuantity"),(BigDecimal)sc.get("quantity"),facts(c,sc)));}
 private void admin(DomainContext c,Map<String,List<String>> scopes){manager(c,"approveRecall",scopes);}
 /** Current human decision authority on every scope value, never on any one alternative (plan §7.1). */
 private void manager(DomainContext c,String cap,Map<String,List<String>> scopes){authorizeEvery(c,cap,scopes);if(!"HUMAN".equals(identity.actor(c.organizationId(),c.actorId()).orElseThrow(DomainError::forbidden).get("kind"))||!ManagementCoverage.covers(identity.rows("ManagementAuthorities",c.organizationId()),c.organizationId(),c.actorId(),cap,scopes,this::active))throw DomainError.forbidden();}
 private void authorizeEvery(DomainContext c,String cap,Map<String,List<String>>scopes){for(var dimension:scopes.entrySet())for(String value:dimension.getValue()){var one=new LinkedHashMap<>(scopes);one.put(dimension.getKey(),List.of(value));auth.authorizeScopes(c,cap,one);}}
 private boolean active(Map<String,Object>x){Instant now=clock.instant();return x.get("validFrom")!=null&&x.get("validUntil")!=null&&!now.isBefore(at(x.get("validFrom")))&&now.isBefore(at(x.get("validUntil")))&&(x.get("revokedAt")==null||now.isBefore(at(x.get("revokedAt"))));}
 private static void hash(Map<String,Object>sc,Map<String,Object>s){if(!Objects.equals(sc.get("scopeHash"),text(s,"scopeHash")))throw new DomainError("HELD","APPROVAL_HASH_MISMATCH","Recall scope changed");}
 private static void bounds(Map<String,Object>sc,BigDecimal start,BigDecimal q){if(start.compareTo((BigDecimal)sc.get("startQuantity"))<0||start.add(q).compareTo(((BigDecimal)sc.get("startQuantity")).add((BigDecimal)sc.get("quantity")))>0)throw DomainError.invalid("Recovery exceeds approved recall physical range");}
}
