package com.mulino.application.trade.recall;
import com.mulino.application.core.*;
import com.mulino.domain.trade.recall.*;
import com.mulino.domain.inventory.*;
import java.util.*;
import org.springframework.stereotype.Component;
@Component
public final class RecallQueries implements QueryHandler,ObjectReadProvider {
 private final RecallRepository r;private final ReadAuthorizer auth;private final InventoryRepository inventory;
 public RecallQueries(RecallRepository r,ReadAuthorizer auth,InventoryRepository inventory){this.r=r;this.auth=auth;this.inventory=inventory;}
 public Set<String> operations(){return Set.of("getRecall","getRecalls","traceRecall");}
 public Set<String> objectTypes(){return Set.of("Recall","RecallScope");}
 private Map<String,List<String>> scopes(Map<String,Object>x){return Map.of("TARGET",List.of(x.get("ID").toString()),"ITEM",List.of(x.get("itemId").toString()),"WORK",List.of(x.get("workId").toString()));}
 public QueryResult query(DomainContext c,QueryRequest q){if(!Set.of("objectType","organizationId","itemId","lotId","workId").containsAll(q.scope().keySet()))throw DomainError.invalid("Unsupported recall query scope");if(q.scope().get("organizationId")!=null&&!c.organizationId().equals(q.scope().get("organizationId")))throw DomainError.forbidden();String type=Objects.toString(q.scope().getOrDefault("objectType",q.filters().get("type")),"Recall");String entity=type.equals("RecallScope")?"Scopes":"Investigations";if(!objectTypes().contains(type))throw DomainError.invalid("Recall noun invalid");String after=ReadCursor.decode(q.cursor(),c,q);var rows=r.rows(c,entity).stream().filter(x->List.of("itemId","lotId","workId").stream().allMatch(k->q.scope().get(k)==null||Objects.equals(q.scope().get(k),x.get(k)))).filter(x->x.get("occurredAt")==null||!StockPrimitives.instant(x.get("occurredAt")).isAfter(c.asOf())).filter(x->auth.permittedScopes(c,q.operation(),scopes(x))).filter(x->q.id()==null||q.id().equals(x.get("ID"))).sorted(Comparator.comparing(x->x.get("ID").toString())).filter(x->after==null||x.get("ID").toString().compareTo(after)>0).toList();if(q.id()!=null&&rows.isEmpty())throw DomainError.forbidden();var selected=rows.stream().limit(q.limit()).map(x->view(c,x,entity,q.operation())).toList();return new QueryResult(q.id()==null?selected:selected.getFirst(),q.scope(),List.of("CANDIDATE_IMPACT_IS_NOT_CONFIRMED_CONTAMINATION"),List.of(),rows.stream().map(x->Objects.toString(x.get("basisEvidenceId"),Objects.toString(x.get("scopeHash"),""))).toList(),rows.size()>q.limit()?ReadCursor.encode(rows.get(q.limit()-1).get("ID").toString(),c,q):null);}
 private Map<String,Object> view(DomainContext c,Map<String,Object>x,String entity,String op){var result=new LinkedHashMap<String,Object>(x);String scope=entity.equals("Scopes")?x.get("ID").toString():Objects.toString(x.get("currentScopeId"),null);if(scope!=null){var sc=r.require(c,"Scopes",scope);if(auth.permittedScopes(c,op,scopes(sc))){var actions=r.rows(c,"Actions").stream().filter(a->scope.equals(a.get("scopeId"))&&!StockPrimitives.instant(a.get("occurredAt")).isAfter(c.asOf())).toList();result.put("partition",RecallPartition.quantities((java.math.BigDecimal)sc.get("startQuantity"),(java.math.BigDecimal)sc.get("quantity"),actions));result.put("actions",actions);result.put("scopeId",scope);result.put("scopeHash",sc.get("scopeHash"));result.put("scopeVersion",sc.get("version"));}}
  String root=entity.equals("Scopes")?x.get("rootSegmentId").toString():x.get("segmentId").toString();var connected=new HashSet<String>(Set.of(root));var edges=inventory.rows(c,"GenealogyEdges").stream().filter(e->!StockPrimitives.instant(e.get("occurredAt")).isAfter(c.asOf())).toList();boolean changed;do{changed=false;for(var e:edges)if(connected.contains(e.get("sourceId"))||connected.contains(e.get("targetId"))){changed|=connected.add(e.get("sourceId").toString());changed|=connected.add(e.get("targetId").toString());}}while(changed);var segments=inventory.rows(c,"QuantitySegments").stream().filter(s->connected.contains(s.get("ID"))).filter(s->auth.permittedScopes(c,op,Map.of("TARGET",List.of(s.get("ID").toString()),"ITEM",List.of(s.get("itemId").toString()),"PLACE",List.of(s.get("placeId").toString())))).toList();Set<String> visible=segments.stream().map(s->s.get("ID").toString()).collect(java.util.stream.Collectors.toSet());result.put("traceSegments",segments);result.put("genealogy",edges.stream().filter(e->visible.contains(e.get("sourceId"))&&visible.contains(e.get("targetId"))).toList());result.put("traceValueState",visible.containsAll(connected)?"CANDIDATE":"UNKNOWN_RESTRICTED_SCOPE");result.put("knownAt",c.knownAt());result.put("asOf",c.asOf());result.put("contaminationConfirmed",false);return (Map<String,Object>)TransportValues.normalize(result);}
}
