package com.mulino.application.trade.sales;
import com.mulino.application.core.*;import com.mulino.application.trade.*;import com.mulino.domain.trade.sales.SalesRepository;import com.mulino.domain.inventory.*;
import com.fasterxml.jackson.databind.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.stereotype.Component;
@Component
public class DeliveryEvidenceScope implements TradeEvidenceScopePort {
 private final SalesRepository r;private final DispatchCargoPort dispatch;
 public DeliveryEvidenceScope(SalesRepository r,DispatchCargoPort dispatch){this.r=r;this.dispatch=dispatch;}
 public Set<String> eventKinds(){return Set.of("PHYSICAL_DELIVERY");}
 public Scope require(DomainContext c,String physical,Map<String,Object>claim,Map<String,Object>event,Map<String,Object>doc,byte[]original){try{var mapper=new ObjectMapper();var source=mapper.readTree(original);var report=mapper.readTree(event.get("payload").toString());var row=r.require(c,"Observations",physical);if(row.get("dispatchId")==null)throw held();var d=dispatch.requireDispatch(c,row.get("dispatchId").toString());exactDispatch(row,d);boolean correction=source.hasNonNull("correctionOfDeliveryId");Map<String,Object> originalDelivery=null;if(correction){if(!source.path("correctionOfDeliveryId").equals(report.path("correctionOfDeliveryId")))throw held();originalDelivery=r.require(c,"Deliveries",source.path("correctionOfDeliveryId").asText());if(!physical.equals(originalDelivery.get("observationId"))||event.get("supersedesId")==null)throw held();}
  for(String k:List.of("deliveryEventId","dispatchId","cargoScopeId","salesLineId","customerId","itemId","lotId","rangeRootId","physicalScopeId","startQuantity","quantity","unit","placeId","occurredAt"))if(!source.hasNonNull(k)||!source.path(k).equals(report.path(k)))throw held();CommandRequests.uuid(source.path("deliveryEventId").asText());
  for(String k:List.of("dispatchId","cargoScopeId","salesLineId","customerId","itemId","lotId","rangeRootId","unit","placeId"))if(!Objects.equals(row.get(k),source.path(k).asText()))throw held();if(!physical.equals(source.path("physicalScopeId").asText())||!Objects.equals(row.get("itemId"),claim.get("itemId"))||!Objects.equals(row.get("itemId"),event.get("itemId"))||!Objects.equals(row.get("workId"),claim.get("workId"))||!Objects.equals(row.get("workId"),event.get("workId"))||!Objects.equals(row.get("placeId"),claim.get("placeId")))throw held();
  BigDecimal quantity=new BigDecimal(source.path("quantity").asText()),start=new BigDecimal(source.path("startQuantity").asText());Instant at=Instant.parse(source.path("occurredAt").asText());if((correction?quantity.signum()<0||quantity.compareTo((BigDecimal)originalDelivery.get("quantity"))>0:quantity.compareTo((BigDecimal)row.get("quantity"))!=0)||start.compareTo((BigDecimal)row.get("startQuantity"))!=0||!(claim.get("quantity") instanceof BigDecimal q)||q.compareTo(quantity)!=0||!Objects.equals(row.get("unit"),claim.get("unit"))||!at.equals(StockPrimitives.instant(row.get("occurredAt")))||!at.equals(StockPrimitives.instant(claim.get("effectiveFrom")))||!at.equals(StockPrimitives.instant(event.get("effectiveFrom"))))throw held();
  return new Scope(Map.of("itemId",row.get("itemId"),"placeId",row.get("placeId"),"workId",row.get("workId")),Map.of("TARGET",List.of(physical,row.get("dispatchId").toString(),row.get("salesLineId").toString()),"ITEM",List.of(row.get("itemId").toString()),"PLACE",List.of(row.get("placeId").toString()),"WORK",List.of(row.get("workId").toString())),source.path("deliveryEventId").asText());
 }catch(java.io.IOException|IllegalArgumentException e){throw held();}}
 static void exactDispatch(Map<String,Object>row,Map<String,Object>d){for(String k:List.of("cargoScopeId","salesLineId","customerId","workId","itemId","lotId","rangeRootId","unit"))if(!Objects.equals(row.get(k),d.get(k)))throw held();BigDecimal start=(BigDecimal)row.get("startQuantity"),ds=(BigDecimal)d.get("startQuantity"),q=(BigDecimal)row.get("quantity");if(start.compareTo(ds)<0||start.add(q).compareTo(ds.add((BigDecimal)d.get("quantity")))>0||StockPrimitives.instant(row.get("occurredAt")).isBefore(StockPrimitives.instant(d.get("occurredAt"))))throw held();}
 private static DomainError held(){return new DomainError("HELD","EVIDENCE_UNVERIFIED","Original delivery identity, interval, time and prior dispatch must reconcile");}
}
