package com.mulino.application.trade.sales;
import com.mulino.application.core.*;import com.mulino.application.trade.*;import com.mulino.application.work.WorkAccess;import com.mulino.application.responsibility.ResponsibilityService;import com.mulino.domain.trade.sales.SalesRepository;import com.mulino.domain.evidence.*;import com.mulino.domain.inventory.*;
import java.math.BigDecimal;import java.util.*;import org.springframework.stereotype.Component;
@Component
public class DeliveryCorrection implements DeliveryCorrectionPort,SalesDeliveryCreditPort {
 private final SalesRepository r;private final TradeEvidence verified;private final EvidenceRepository evidence;private final WorkAccess work;private final ResponsibilityService duties;private final com.mulino.domain.responsibility.ResponsibilityRepository dutyRows;
 public DeliveryCorrection(SalesRepository r,TradeEvidence verified,EvidenceRepository evidence,WorkAccess work,ResponsibilityService duties,com.mulino.domain.responsibility.ResponsibilityRepository dutyRows){this.r=r;this.verified=verified;this.evidence=evidence;this.work=work;this.duties=duties;this.dutyRows=dutyRows;}
 private static final String KIND="DELIVERY_CORRECTED_DEFICIT";
 /**
  * Recognized quantity of a corrected actual delivery. The corrected fact keeps the original start coordinate (DeliveryEvidenceScope),
  * so it asserts [start,start+q). The legitimate coordinates stored at confirmation are intersected with that interval (plan §4.2: a
  * known subset is used exactly). A row without consistent stored coordinates uses the conservative lower bound
  * max(0, legitimate-(original-q)) instead of assuming every missing unit was the ineligible part.
  */
 static BigDecimal recognized(Map<String,Object> d,BigDecimal q){BigDecimal legitimate=(BigDecimal)d.get("legitimateQuantity"),original=(BigDecimal)d.get("quantity"),start=(BigDecimal)d.get("startQuantity");var stored=ranges(d.get("legitimateRangesJson"));if(stored!=null&&QualityRanges.quantity(stored).compareTo(legitimate)==0)return QualityRanges.quantity(QualityRanges.intersect(stored,List.of(new QualityRanges.Range(start,start.add(q)))));return legitimate.subtract(original.subtract(q)).max(BigDecimal.ZERO);}
 static List<QualityRanges.Range> ranges(Object json){if(json==null)return null;try{var out=new ArrayList<QualityRanges.Range>();for(var x:new com.fasterxml.jackson.databind.ObjectMapper().readTree(json.toString()))out.add(new QualityRanges.Range(new BigDecimal(x.path("startQuantity").asText()),new BigDecimal(x.path("endQuantity").asText())));return QualityRanges.union(out);}catch(Exception invalid){return null;}}
 /**
  * Deficit coordinates [0,deficit) still owned by a valid closure: an OPEN (or transferred-and-open) duty, or a MANAGER waiver
  * (plan §4.3: a valid waiver is not revived). A RESOLVED leaf was discharged only by the correction that was current then
  * (DeliveryDeficitResponsibilities); the correction being applied supersedes it, so that resolution no longer covers a deficit
  * that re-emerges (§4.3 re-evaluation, §5.3 a new event may be a new duty).
  */
 private List<QualityRanges.Range> covered(DomainContext c,String deliveryId){var out=new ArrayList<QualityRanges.Range>();var mapper=new com.fasterxml.jackson.databind.ObjectMapper();
  for(var root:dutyRows.rows("Roots",c.organizationId())){if(!KIND.equals(root.get("kind")))continue;BigDecimal base;try{var scope=mapper.readTree(root.get("scopeJson").toString());if(!deliveryId.equals(scope.path("deliveryId").asText()))continue;base=new BigDecimal(scope.path("startQuantity").asText());}catch(Exception invalid){continue;}
   for(var a:dutyRows.rows("Assignments",c.organizationId()))if(root.get("ID").equals(a.get("rootId"))&&!Boolean.FALSE.equals(a.get("valid"))&&Set.of("OPEN","WAIVED").contains(a.get("status"))){var leaf=dutyRows.require("Scopes",c.organizationId(),a.get("scopeId").toString());BigDecimal from=base.add((BigDecimal)leaf.get("startQuantity"));out.add(new QualityRanges.Range(from,from.add((BigDecimal)leaf.get("quantity"))));}}
  return QualityRanges.union(out);}
 public Map<String,Object> correctionImpact(DomainContext c,String deliveryId,String canonical){r.fence(c,"sales/delivery-correction/"+deliveryId);var d=r.require(c,"Deliveries",deliveryId);var fact=evidence.require("CanonicalOccurrences",c.organizationId(),canonical);var q=(BigDecimal)fact.get("quantity");verified.requireCanonical(c,canonical,"PHYSICAL_DELIVERY",d.get("itemId").toString(),d.get("observationId").toString(),q,d.get("unit").toString());var prior=r.rows(c,"DeliveryCorrections").stream().filter(x->deliveryId.equals(x.get("deliveryId"))).max(Comparator.comparingInt(x->((Number)x.get("revision")).intValue()));String previous=prior.map(x->x.get("canonicalOccurrenceId").toString()).orElse(d.get("canonicalOccurrenceId").toString());var existing=r.rows(c,"DeliveryCorrections").stream().filter(x->deliveryId.equals(x.get("deliveryId"))&&canonical.equals(x.get("canonicalOccurrenceId"))).findFirst();if(existing.isPresent())return Map.of("deliveryId",deliveryId,"currentQuantity",existing.get().get("quantity"),"duplicate",true);
  if(!previous.equals(fact.get("supersedesId"))||q.signum()<0||q.compareTo((BigDecimal)d.get("quantity"))>0||!Objects.equals(d.get("workId"),fact.get("workId"))||!Objects.equals(d.get("placeId"),fact.get("placeId"))||!StockPrimitives.instant(d.get("occurredAt")).equals(StockPrimitives.instant(fact.get("effectiveFrom"))))throw DomainError.invalid("Delivery correction must supersede exact current actual fact; no reverse movement inferred");
  var row=SalesRows.row(c,StockPrimitives.id(),StockPrimitives.instant(d.get("occurredAt")));BigDecimal legitimate=recognized(d,q);row.put("revision",prior.map(x->((Number)x.get("revision")).intValue()+1).orElse(1));row.putAll(Map.of("deliveryId",deliveryId,"canonicalOccurrenceId",canonical,"quantity",q,"legitimateQuantity",legitimate,"unit",d.get("unit")));r.insert("DeliveryCorrections",row);work.markInvalidation(c,d.get("workId").toString(),true);
  BigDecimal deficit=((BigDecimal)d.get("legitimateQuantity")).subtract(legitimate);
  var uncovered=deficit.signum()>0?QualityRanges.subtract(List.of(new QualityRanges.Range(BigDecimal.ZERO,deficit)),covered(c,deliveryId)):List.<QualityRanges.Range>of();
  for(var gap:QualityRanges.union(uncovered)){BigDecimal amount=gap.end().subtract(gap.start());if(amount.signum()<=0)continue;var target=work.require(c,d.get("workId").toString(),true);if("CLOSED".equals(target.get("status")))target=work.ensureFollowup(c,d.get("workId").toString(),d.get("canonicalOccurrenceId").toString(),KIND,"정정된 실제 인도의 부족량과 후속 책임을 확인한다",c.knownAt().plusSeconds(3600));
   // The correcting occurrence is the source: a deficit that re-emerges after a resolution gets a new stable root instead of
   // deduplicating onto the old RESOLVED one.
   var params=new LinkedHashMap<String,Object>();params.putAll(Map.of("workId",target.get("ID"),"sourceKind","OCCURRENCE","sourceId",canonical,"sourceVersion",String.valueOf(fact.getOrDefault("revision",0)),"kind",KIND,"scopeJson","{\"deliveryId\":\""+deliveryId+"\",\"originalWorkId\":\""+d.get("workId")+"\",\"startQuantity\":\""+InventoryQuantity.text(gap.start())+"\",\"endQuantity\":\""+InventoryQuantity.text(gap.end())+"\"}","quantity",amount,"unit",d.get("unit")));params.put("nextAction","정정된 실제 인도의 부족량과 후속 책임을 확인한다");params.put("nextCheckAt",c.knownAt().plusSeconds(3600));duties.openDuty(c,params);}
  return Map.of("deliveryId",deliveryId,"currentQuantity",q,"recognizedQuantity",legitimate,"deficitQuantity",deficit,"physicalEffects",List.of());
 }
 public Map<String,Object> deliveryCredit(DomainContext c,String lineId,String deliveryId){var line=r.require(c,"OrderLines",lineId);var d=r.require(c,"Deliveries",deliveryId);if(!lineId.equals(d.get("salesLineId"))||!Objects.equals(line.get("itemId"),d.get("itemId"))||!Objects.equals(line.get("customerId"),d.get("customerId"))||!Objects.equals(line.get("unit"),d.get("unit"))||!Objects.equals(line.get("workId"),d.get("workId")))throw DomainError.invalid("Invoice delivery does not belong to exact sales line");var current=r.rows(c,"DeliveryCorrections").stream().filter(x->deliveryId.equals(x.get("deliveryId"))).max(Comparator.comparingInt(x->((Number)x.get("revision")).intValue()));BigDecimal quantity=current.map(x->(BigDecimal)x.get("quantity")).orElse((BigDecimal)d.get("quantity"));String canonical=current.map(x->x.get("canonicalOccurrenceId").toString()).orElse(d.get("canonicalOccurrenceId").toString());verified.requireCanonical(c,canonical,"PHYSICAL_DELIVERY",d.get("itemId").toString(),d.get("observationId").toString(),quantity,d.get("unit").toString());return Map.of("actualQuantity",quantity,"contributedQuantity",current.map(x->x.get("legitimateQuantity")).orElse(d.get("legitimateQuantity")),"unit",d.get("unit"),"canonicalOccurrenceId",canonical,"deliveryId",deliveryId,"lineId",lineId);}
}
