package com.mulino.application.trade.sales;
import com.mulino.application.core.*;import com.mulino.application.trade.*;import com.mulino.application.work.WorkAccess;import com.mulino.application.responsibility.ResponsibilityService;import com.mulino.domain.trade.sales.SalesRepository;import com.mulino.domain.evidence.*;import com.mulino.domain.inventory.*;
import java.math.BigDecimal;import java.util.*;import org.springframework.stereotype.Component;
@Component
public class DeliveryCorrection implements DeliveryCorrectionPort,SalesDeliveryCreditPort {
 private final SalesRepository r;private final TradeEvidence verified;private final EvidenceRepository evidence;private final WorkAccess work;private final ResponsibilityService duties;
 public DeliveryCorrection(SalesRepository r,TradeEvidence verified,EvidenceRepository evidence,WorkAccess work,ResponsibilityService duties){this.r=r;this.verified=verified;this.evidence=evidence;this.work=work;this.duties=duties;}
 public Map<String,Object> correctionImpact(DomainContext c,String deliveryId,String canonical){r.fence(c,"sales/delivery-correction/"+deliveryId);var d=r.require(c,"Deliveries",deliveryId);var fact=evidence.require("CanonicalOccurrences",c.organizationId(),canonical);var q=(BigDecimal)fact.get("quantity");verified.requireCanonical(c,canonical,"PHYSICAL_DELIVERY",d.get("itemId").toString(),d.get("observationId").toString(),q,d.get("unit").toString());var prior=r.rows(c,"DeliveryCorrections").stream().filter(x->deliveryId.equals(x.get("deliveryId"))).max(Comparator.comparing(x->StockPrimitives.instant(x.get("recordedAt"))));String previous=prior.map(x->x.get("canonicalOccurrenceId").toString()).orElse(d.get("canonicalOccurrenceId").toString());var existing=r.rows(c,"DeliveryCorrections").stream().filter(x->deliveryId.equals(x.get("deliveryId"))&&canonical.equals(x.get("canonicalOccurrenceId"))).findFirst();if(existing.isPresent())return Map.of("deliveryId",deliveryId,"currentQuantity",existing.get().get("quantity"),"duplicate",true);
  if(!previous.equals(fact.get("supersedesId"))||q.signum()<0||q.compareTo((BigDecimal)d.get("quantity"))>0||!Objects.equals(d.get("workId"),fact.get("workId"))||!Objects.equals(d.get("placeId"),fact.get("placeId"))||!StockPrimitives.instant(d.get("occurredAt")).equals(StockPrimitives.instant(fact.get("effectiveFrom"))))throw DomainError.invalid("Delivery correction must supersede exact current actual fact; no reverse movement inferred");
  var row=StockPrimitives.row(c,StockPrimitives.id(),c.asOf());BigDecimal legitimate=q.min((BigDecimal)d.get("legitimateQuantity"));row.putAll(Map.of("deliveryId",deliveryId,"canonicalOccurrenceId",canonical,"quantity",q,"legitimateQuantity",legitimate,"unit",d.get("unit")));r.insert("DeliveryCorrections",row);work.markInvalidation(c,d.get("workId").toString(),true);
  BigDecimal deficit=((BigDecimal)d.get("legitimateQuantity")).subtract(legitimate);if(deficit.signum()>0){var target=work.require(c,d.get("workId").toString(),true);if("CLOSED".equals(target.get("status")))target=work.ensureFollowup(c,d.get("workId").toString(),d.get("canonicalOccurrenceId").toString(),"DELIVERY_CORRECTED_DEFICIT","정정된 실제 인도의 부족량과 후속 책임을 확인한다",c.knownAt().plusSeconds(3600));var original=evidence.require("CanonicalOccurrences",c.organizationId(),d.get("canonicalOccurrenceId").toString());var params=new LinkedHashMap<String,Object>();params.putAll(Map.of("workId",target.get("ID"),"sourceKind","OCCURRENCE","sourceId",d.get("canonicalOccurrenceId"),"sourceVersion",String.valueOf(original.getOrDefault("revision",0)),"kind","DELIVERY_CORRECTED_DEFICIT","scopeJson","{\"deliveryId\":\""+deliveryId+"\",\"originalWorkId\":\""+d.get("workId")+"\"}","quantity",deficit,"unit",d.get("unit")));params.put("nextAction","정정된 실제 인도의 부족량과 후속 책임을 확인한다");params.put("nextCheckAt",c.knownAt().plusSeconds(3600));duties.openDuty(c,params);}
  return Map.of("deliveryId",deliveryId,"currentQuantity",q,"recognizedQuantity",legitimate,"deficitQuantity",deficit,"physicalEffects",List.of());
 }
 public Map<String,Object> deliveryCredit(DomainContext c,String lineId,String deliveryId){var line=r.require(c,"OrderLines",lineId);var d=r.require(c,"Deliveries",deliveryId);if(!lineId.equals(d.get("salesLineId"))||!Objects.equals(line.get("itemId"),d.get("itemId"))||!Objects.equals(line.get("customerId"),d.get("customerId"))||!Objects.equals(line.get("unit"),d.get("unit"))||!Objects.equals(line.get("workId"),d.get("workId")))throw DomainError.invalid("Invoice delivery does not belong to exact sales line");var current=r.rows(c,"DeliveryCorrections").stream().filter(x->deliveryId.equals(x.get("deliveryId"))).max(Comparator.comparing(x->StockPrimitives.instant(x.get("recordedAt"))));BigDecimal quantity=current.map(x->(BigDecimal)x.get("quantity")).orElse((BigDecimal)d.get("quantity"));String canonical=current.map(x->x.get("canonicalOccurrenceId").toString()).orElse(d.get("canonicalOccurrenceId").toString());verified.requireCanonical(c,canonical,"PHYSICAL_DELIVERY",d.get("itemId").toString(),d.get("observationId").toString(),quantity,d.get("unit").toString());return Map.of("actualQuantity",quantity,"contributedQuantity",current.map(x->x.get("legitimateQuantity")).orElse(d.get("legitimateQuantity")),"unit",d.get("unit"),"canonicalOccurrenceId",canonical,"deliveryId",deliveryId,"lineId",lineId);}
}
