package com.mulino.application.trade.sales;
import com.mulino.application.core.*;import com.mulino.application.trade.*;import com.mulino.application.work.WorkAccess;
import com.mulino.domain.evidence.*;import com.mulino.domain.inventory.*;import com.mulino.domain.trade.sales.SalesRepository;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.stereotype.Component;
import static com.mulino.application.inventory.InventoryCommands.*;
@Component
public class DeliveryCommands implements CommandHandler,DeliveredCargoPort {
 private final SalesRepository r;private final InventoryRepository inventory;private final EvidenceRepository evidence;private final TradeEvidence verified;private final DispatchCargoPort dispatch;private final FulfillmentStockPrimitives stock;private final TradeImpact impact;private final WorkAccess work;private final SalesCommands sales;private final ReadAuthorizer auth;private final TradeObservationRemedy remedy;private final StockPrimitives stockLocks;
 public DeliveryCommands(SalesRepository r,InventoryRepository inventory,EvidenceRepository evidence,TradeEvidence verified,DispatchCargoPort dispatch,FulfillmentStockPrimitives stock,TradeImpact impact,WorkAccess work,SalesCommands sales,ReadAuthorizer auth,TradeObservationRemedy remedy,StockPrimitives stockLocks){this.r=r;this.inventory=inventory;this.evidence=evidence;this.verified=verified;this.dispatch=dispatch;this.stock=stock;this.impact=impact;this.work=work;this.sales=sales;this.auth=auth;this.remedy=remedy;this.stockLocks=stockLocks;}
 public Set<String> capabilities(){return Set.of("recordDelivery","recordObservedMovement");}public Set<String> intentKinds(){return Set.of("RECORD");}
 private boolean confirm(Map<String,Object>s){return s.get("canonicalOccurrenceId")!=null;}
 public CommandPreparation prepare(DomainContext c,Map<String,Object>i){var s=slots(i);boolean confirmation=confirm(s);Map<String,Object>row;
  if(confirmation){if(!Set.of("observationId","canonicalOccurrenceId").containsAll(s.keySet())||!"recordDelivery".equals(i.get("capabilityId")))throw DomainError.invalid("Confirmation slots mismatch");uuid(s,"canonicalOccurrenceId");row=r.require(c,"Observations",uuid(s,"observationId"));}
  else {if(!Set.of("observationId","eventId","dispatchId","cargoScopeId","salesLineId","workId","customerId","itemId","lotId","rangeRootId","startQuantity","quantity","unit","placeId","occurredAt","nextCheckAt","nextAction").containsAll(s.keySet()))throw DomainError.invalid("Observed delivery slots mismatch");row=s;for(String k:List.of("eventId","workId","customerId","itemId","rangeRootId","placeId"))uuid(s,k);for(String k:List.of("observationId","dispatchId","cargoScopeId","salesLineId","lotId"))if(s.get(k)!=null)uuid(s,k);var item=inventory.current(c,"TradeItems",uuid(s,"itemId"));inventory.current(c,"Places",uuid(s,"placeId"));r.require(c,"Customers",uuid(s,"customerId"));work.require(c,uuid(s,"workId"),false);if(!Objects.equals(item.get("baseUnit"),s.get("unit")))throw DomainError.invalid("Delivery base unit differs");InventoryQuantity.parse(s.get("quantity"),((Number)item.get("decimalPlaces")).intValue());if(SalesCommands.decimal(s.get("startQuantity"),true).signum()>0)InventoryQuantity.parse(s.get("startQuantity"),((Number)item.get("decimalPlaces")).intValue());time(c,s);if(!Instant.parse(text(s,"nextCheckAt",80)).isAfter(c.knownAt()))throw DomainError.invalid("Future delivery reconciliation check required");text(s,"nextAction",320);var e=evidence.require("Events",c.organizationId(),uuid(s,"eventId"));if(!Set.of("PHYSICAL_DELIVERY","OBSERVED_MOVEMENT").contains(e.get("kind"))||!Objects.equals(e.get("workId"),s.get("workId"))||!Objects.equals(e.get("itemId"),s.get("itemId")))throw DomainError.invalid("Delivery event differs from intake");auth.authorizeScopes(c,i.get("capabilityId").toString(),EvidenceTypes.scopes(e));}
  var fences=new TreeSet<String>(List.of("sales/delivery/"+row.get("rangeRootId"),"inventory/item/"+row.get("itemId"),"evidence-subject:"+row.get("workId")));var targets=new ArrayList<String>(List.of(Objects.toString(row.get("ID"),Objects.toString(s.get("observationId"),row.get("rangeRootId").toString()))));var places=new ArrayList<String>(List.of(row.get("placeId").toString()));if(row.get("dispatchId")!=null){fences.add("inventory/dispatch/"+row.get("dispatchId"));if(confirmation){var priorDispatch=dispatch.requireDispatch(c,row.get("dispatchId").toString());var transit=inventory.current(c,"QuantitySegments",priorDispatch.get("transitSegmentId").toString());fences.addAll(stockLocks.fences(transit));targets.add(priorDispatch.get("ID").toString());targets.add(priorDispatch.get("salesLineId").toString());targets.add(transit.get("ID").toString());places.add(transit.get("placeId").toString());for(var leaf:inventory.currentRows(c,"QuantitySegments"))if(row.get("itemId").equals(leaf.get("itemId"))&&leaf.get("retiredAt")==null)fences.addAll(stockLocks.fences(leaf));}}return CommandPreparation.ordinary(Map.of("TARGET",targets,"ITEM",List.of(row.get("itemId").toString()),"PLACE",places,"WORK",List.of(row.get("workId").toString())),new ArrayList<>(fences),"RECORD",Objects.toString(row.get("ID"),null),confirmation?((Number)row.get("revision")).intValue():null);
 }
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object>i,CommandPreparation p){var s=slots(i);var row=confirm(s)?r.require(c,"Observations",uuid(s,"observationId")):s;var out=new ArrayList<SubjectBinding>(List.of(SubjectBinding.optional("Work",Set.of(row.get("workId").toString())),SubjectBinding.optional("TradeItem",Set.of(row.get("itemId").toString()))));if(confirm(s))out.add(SubjectBinding.optional("DeliveryObservation",Set.of(row.get("ID").toString())));return out;}
 public Map<String,Object> execute(DomainContext c,Map<String,Object>i){var p=prepare(c,i);inventory.fence(c,p.fenceKeys());var s=slots(i);
  if(!confirm(s)){String id=s.get("observationId")==null?StockPrimitives.id():uuid(s,"observationId");var row=SalesRows.row(c,id,time(c,s));row.putAll(s);row.remove("observationId");row.put("quantity",InventoryQuantity.parse(s.get("quantity"),((Number)inventory.current(c,"TradeItems",s.get("itemId").toString()).get("decimalPlaces")).intValue()));row.put("startQuantity",SalesCommands.decimal(s.get("startQuantity"),true));row.put("occurredAt",time(c,s));row.put("nextCheckAt",Instant.parse(s.get("nextCheckAt").toString()));row.put("state","PROVISIONAL");r.insert("Observations",row);impact.recorded(c,row.get("workId").toString(),id,"DELIVERY_RECONCILIATION",id,row.get("nextAction").toString(),StockPrimitives.instant(row.get("nextCheckAt")));return Map.of("outcome","APPLIED","revision",1,"effects",Map.of("observationId",id,"physicalQuantity","0","contributedQuantity","0"));}
  var row=r.require(c,"Observations",uuid(s,"observationId"));if(row.get("dispatchId")==null||row.get("salesLineId")==null)throw new DomainError("HELD","DELIVERY_UNMATCHED","Observed report has no prior actual dispatch");var d=dispatch.requireDispatch(c,row.get("dispatchId").toString());DeliveryEvidenceScope.exactDispatch(row,d);String canonical=uuid(s,"canonicalOccurrenceId");var fact=verified.requireCanonical(c,canonical,"PHYSICAL_DELIVERY",row.get("itemId").toString(),row.get("ID").toString(),(BigDecimal)row.get("quantity"),row.get("unit").toString());if(!Objects.equals(fact.get("workId"),row.get("workId"))||!Objects.equals(fact.get("placeId"),row.get("placeId"))||!StockPrimitives.instant(fact.get("effectiveFrom")).equals(StockPrimitives.instant(row.get("occurredAt"))))throw DomainError.invalid("Canonical delivery time/place/work differs");
  var prior=r.rows(c,"Deliveries").stream().filter(x->canonical.equals(x.get("canonicalOccurrenceId"))).findFirst();if(prior.isPresent())return result(prior.get(),true);
  var actual=stock.observeDelivery(c,d.get("ID").toString(),canonical,(BigDecimal)row.get("startQuantity"),(BigDecimal)row.get("quantity"),StockPrimitives.instant(row.get("occurredAt")),CommandExecution.commandId());BigDecimal legitimate=actual.get("legitimateQuantity") instanceof BigDecimal q?q:BigDecimal.ZERO;@SuppressWarnings("unchecked") List<QualityRanges.Range> legitimateRanges=actual.get("legitimateRanges") instanceof List<?> l?(List<QualityRanges.Range>)l:List.of();
  // The dispatch fixed the order line of its revision; the delivery endpoint is judged against the order contract in force now
  // (plan §6 판매: 인도 끝점은 주문 계약대로 평가). A due date agreed after dispatch moves the promise; destination and
  // customer cannot change once execution is committed (SalesCommands).
  var line=sales.currentLine(c,row.get("salesLineId").toString());if(!Objects.equals(line.get("destinationId"),row.get("placeId"))||!Objects.equals(line.get("customerId"),row.get("customerId"))||StockPrimitives.instant(row.get("occurredAt")).isAfter(StockPrimitives.instant(line.get("dueAt")))){legitimate=BigDecimal.ZERO;legitimateRanges=List.of();}
  var delivery=SalesRows.row(c,StockPrimitives.id(),StockPrimitives.instant(row.get("occurredAt")));delivery.put("legitimateRangesJson",rangesJson(legitimateRanges));for(String k:List.of("dispatchId","cargoScopeId","salesLineId","workId","customerId","itemId","lotId","rangeRootId","startQuantity","quantity","unit","placeId","occurredAt"))delivery.put(k,row.get(k));delivery.putAll(Map.of("observationId",row.get("ID"),"canonicalOccurrenceId",canonical,"segmentId",actual.get("segmentId"),"legitimateQuantity",legitimate));r.insert("Deliveries",delivery);r.update(c,"Observations",row.get("ID").toString(),Map.of("state","CONFIRMED","revision",2));remedy.reconcileDeliveryObservation(c,row.get("ID").toString(),delivery.get("ID").toString());sales.recordExecutionEffect(c,row.get("salesLineId").toString(),"DELIVERED",delivery.get("ID").toString(),(BigDecimal)row.get("quantity"),row.get("unit").toString());impact.invalidate(c,row.get("workId").toString());BigDecimal violated=((BigDecimal)row.get("quantity")).subtract(legitimate);if(violated.signum()>0)impact.recorded(c,row.get("workId").toString(),delivery.get("ID").toString(),"DELIVERY_RESTRICTION_RESPONSE",row.get("rangeRootId").toString(),"실제 인도와 판매 제한 또는 기한 위반의 대응을 확인한다",StockPrimitives.instant(row.get("nextCheckAt")),Map.of("deliveryId",delivery.get("ID")),violated,row.get("unit").toString());return result(delivery,false);
 }
 static String rangesJson(List<QualityRanges.Range> ranges){var out=new StringBuilder("[");for(var x:QualityRanges.union(ranges)){if(out.length()>1)out.append(',');out.append("{\"startQuantity\":\"").append(InventoryQuantity.text(x.start())).append("\",\"endQuantity\":\"").append(InventoryQuantity.text(x.end())).append("\"}");}return out.append(']').toString();}
 private Map<String,Object> result(Map<String,Object>d,boolean duplicate){return Map.of("outcome","APPLIED","revision",1,"effects",Map.of("deliveryId",d.get("ID"),"segmentId",d.get("segmentId"),"physicalQuantity",InventoryQuantity.text(d.get("quantity")),"contributedQuantity",InventoryQuantity.text(d.get("legitimateQuantity")),"duplicate",duplicate));}
 public Map<String,Object> requireDelivery(DomainContext c,String id){var d=new LinkedHashMap<>(r.require(c,"Deliveries",id));d.put("customerPlaceId",d.get("placeId"));d.put("currentQuantity",currentDeliveryQuantity(c,id));return d;}
 public BigDecimal currentDeliveryQuantity(DomainContext c,String id){var d=r.require(c,"Deliveries",id);return r.rows(c,"DeliveryCorrections").stream().filter(x->id.equals(x.get("deliveryId"))).max(Comparator.comparingInt(x->((Number)x.get("revision")).intValue())).map(x->(BigDecimal)x.get("quantity")).orElse((BigDecimal)d.get("quantity"));}
}
