package com.mulino.application.trade.sales;
import com.mulino.application.core.*;import com.mulino.domain.trade.sales.SalesRepository;import com.mulino.domain.inventory.*;import com.mulino.domain.evidence.EvidenceSubjectPort;
import java.util.*;import org.springframework.stereotype.Component;
@Component
public class SalesQueries implements QueryHandler,ObjectReadProvider,EvidenceSubjectPort {
 private final SalesRepository r;private final ReadAuthorizer auth;
 public SalesQueries(SalesRepository r,ReadAuthorizer auth){this.r=r;this.auth=auth;}
 public Set<String> operations(){return Set.of("getSalesOrder","getSalesOrders","getDelivery","getDeliveries");}
 public Set<String> objectTypes(){return Set.of("SalesOrder","SalesOrderRevision","SalesOrderLine","Delivery","DeliveryObservation","Customer");}
 public Set<String> subjectKinds(){return Set.of("SALES_ORDER","SALES_ORDER_LINE","DELIVERY","DELIVERY_OBSERVATION");}
 private String entity(String type){return switch(type){case "Customer"->"Customers";case "SalesOrder"->"Orders";case "SalesOrderRevision"->"OrderRevisions";case "SalesOrderLine"->"OrderLines";case "Delivery"->"Deliveries";case "DeliveryObservation"->"Observations";default->throw DomainError.invalid("Unsupported sales noun");};}
 public Map<String,Object> require(String org,String kind,String id){return r.subject(org,switch(kind){case "SALES_ORDER"->"Orders";case "SALES_ORDER_LINE"->"OrderLines";case "DELIVERY"->"Deliveries";case "DELIVERY_OBSERVATION"->"Observations";default->throw DomainError.unsupported();},id);}
 private Map<String,List<String>> scopes(Map<String,Object>x){var scopes=new LinkedHashMap<String,List<String>>();scopes.put("TARGET",List.of(x.get("ID").toString()));if(x.get("workId")!=null)scopes.put("WORK",List.of(x.get("workId").toString()));if(x.get("itemId")!=null)scopes.put("ITEM",List.of(x.get("itemId").toString()));if(x.get("placeId")!=null||x.get("destinationId")!=null)scopes.put("PLACE",List.of(Objects.toString(x.get("placeId"),x.get("destinationId")==null?null:x.get("destinationId").toString())));return scopes;}
 public QueryResult query(DomainContext c,QueryRequest q){if(!Set.of("type").containsAll(q.filters().keySet()))throw DomainError.invalid("Unsupported sales filter");if(q.scope().get("objectType")!=null&&q.filters().get("type")!=null&&!Objects.equals(q.scope().get("objectType"),q.filters().get("type")))throw DomainError.invalid("Conflicting sales noun");if(!Set.of("objectType","organizationId","workId","itemId","customerId","orderId","salesLineId","dispatchId","rangeRootId","lotId","placeId").containsAll(q.scope().keySet()))throw DomainError.invalid("Unsupported sales query scope");if(q.scope().get("organizationId")!=null&&!c.organizationId().equals(q.scope().get("organizationId")))throw DomainError.forbidden();String type=Objects.toString(q.scope().getOrDefault("objectType",q.filters().get("type")),q.operation().contains("Delivery")||q.operation().contains("Deliveries")?"Delivery":"SalesOrder");String table=entity(type),after=ReadCursor.decode(q.cursor(),c,q);var rows=r.rows(c,table).stream().filter(x->!StockPrimitives.instant(x.get("effectiveAt")).isAfter(c.asOf())&&(x.get("occurredAt")==null||!StockPrimitives.instant(x.get("occurredAt")).isAfter(c.asOf()))).filter(x->q.id()==null||q.id().equals(x.get("ID"))).filter(x->List.of("workId","itemId","customerId","orderId","salesLineId","dispatchId","rangeRootId","lotId","placeId").stream().allMatch(k->q.scope().get(k)==null||Objects.equals(q.scope().get(k),x.get(k)))).filter(x->auth.permittedScopes(c,q.operation(),scopes(x))).sorted(Comparator.comparing(x->x.get("ID").toString())).filter(x->after==null||x.get("ID").toString().compareTo(after)>0).toList();if(q.id()!=null&&rows.isEmpty())throw DomainError.forbidden();var values=rows.stream().limit(q.limit()).map(x->project(c,table,x)).map(TransportValues::normalize).toList();return new QueryResult(q.id()==null?values:values.getFirst(),q.scope(),table.equals("Observations")?rows.stream().filter(x->!"CONFIRMED".equals(x.get("state"))).map(x->x.get("ID")+":DELIVERY_UNCONFIRMED").toList():List.of(),List.of(),rows.stream().map(x->Objects.toString(x.get("canonicalOccurrenceId"),Objects.toString(x.get("eventId"),""))).filter(x->!x.isEmpty()).toList(),rows.size()>q.limit()?ReadCursor.encode(rows.get(q.limit()-1).get("ID").toString(),c,q):null);}
 private boolean at(DomainContext c,Map<String,Object>x){return !StockPrimitives.instant(x.get("effectiveAt")).isAfter(c.asOf());}
 private Map<String,Object> project(DomainContext c,String entity,Map<String,Object>x){var result=new LinkedHashMap<>(x);if(entity.equals("Orders")){var revisions=r.rows(c,"OrderRevisions").stream().filter(a->x.get("ID").equals(a.get("orderId"))&&at(c,a)&&auth.permittedScopes(c,"getSalesOrder",scopes(a))).toList();result.put("revisions",revisions);int visible=revisions.stream().mapToInt(a->((Number)a.get("revisionNumber")).intValue()).max().orElse(0);result.put("currentRevision",visible);result.put("revision",visible);result.put("lines",r.rows(c,"OrderLines").stream().filter(a->x.get("ID").equals(a.get("orderId"))&&at(c,a)&&auth.permittedScopes(c,"getSalesOrder",scopes(a))).toList());}if(entity.equals("Deliveries"))result.put("corrections",r.rows(c,"DeliveryCorrections").stream().filter(a->x.get("ID").equals(a.get("deliveryId"))&&at(c,a)).sorted(Comparator.comparingInt(a->((Number)a.get("revision")).intValue())).toList());return result;}
}
