package com.mulino.application.trade.sales;
import com.mulino.application.core.*;
import com.mulino.application.trade.*;
import com.mulino.application.work.WorkAccess;
import com.mulino.domain.inventory.*;
import com.mulino.domain.trade.sales.SalesRepository;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.inventory.InventoryCommands.*;
@Component
public class SalesCommands implements CommandHandler,SalesOrderLinePort,SalesExecutionPort {
 private final SalesRepository r;private final InventoryRepository inventory;private final WorkAccess works;
 public SalesCommands(SalesRepository r,InventoryRepository inventory,WorkAccess works){this.r=r;this.inventory=inventory;this.works=works;}
 public Set<String> capabilities(){return Set.of("createSalesOrder","reviseSalesOrder");}
 private Map<String,Object> valid(DomainContext c,Map<String,Object>s){
  if(!Set.of("orderId","workId","customerId","itemId","quantity","unit","price","currency","dueAt","destinationId","deliveryEndpoint","qualityTerms","packageTerms","reason").containsAll(s.keySet()))throw DomainError.invalid("Unsupported sales order slots");
  for(String k:List.of("workId","customerId","itemId","destinationId"))uuid(s,k);works.require(c,uuid(s,"workId"),false);r.require(c,"Customers",uuid(s,"customerId"));inventory.current(c,"Places",uuid(s,"destinationId"));var item=inventory.current(c,"TradeItems",uuid(s,"itemId"));
  String unit=text(s,"unit",40);if(!unit.equals(item.get("baseUnit")))throw DomainError.invalid("Sales base unit mismatch");var row=new LinkedHashMap<>(s);row.put("quantity",InventoryQuantity.parse(s.get("quantity"),((Number)item.get("decimalPlaces")).intValue()));row.put("price",decimal(s.get("price"),true));String currency=text(s,"currency",3);if(!currency.matches("[A-Z]{3}"))throw DomainError.invalid("Currency required");row.put("dueAt",Instant.parse(text(s,"dueAt",80)));if(!"DELIVERED".equals(text(s,"deliveryEndpoint",40)))throw DomainError.invalid("Supported endpoint is DELIVERED");text(s,"qualityTerms",500);text(s,"packageTerms",500);return row;
 }
 public CommandPreparation prepare(DomainContext c,Map<String,Object>i){var s=slots(i);var v=valid(c,s);boolean revise="reviseSalesOrder".equals(i.get("capabilityId"));var root=revise?r.require(c,"Orders",uuid(s,"orderId")):null;if(root!=null&&!Objects.equals(root.get("workId"),s.get("workId")))throw DomainError.invalid("Sales revision work cannot change");return CommandPreparation.ordinary(Map.of("TARGET",List.of(revise?root.get("ID").toString():s.get("workId").toString()),"WORK",List.of(s.get("workId").toString()),"ITEM",List.of(s.get("itemId").toString()),"PLACE",List.of(s.get("destinationId").toString())),List.of("sales/order/"+(revise?root.get("ID"):s.get("workId"))),"SALES_ORDER",revise?root.get("ID").toString():null,revise?((Number)root.get("currentRevision")).intValue():null);}
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object>i,CommandPreparation p){var s=slots(i);var out=new ArrayList<SubjectBinding>(List.of(SubjectBinding.optional("Work",Set.of(uuid(s,"workId"))),SubjectBinding.optional("TradeItem",Set.of(uuid(s,"itemId")))));if(s.get("orderId")!=null)out.add(SubjectBinding.optional("SalesOrder",Set.of(uuid(s,"orderId"))));return out;}
 public Map<String,Object> execute(DomainContext c,Map<String,Object>i){var p=prepare(c,i);for(var f:p.fenceKeys())r.fence(c,f);var s=slots(i);var v=valid(c,s);boolean revise="reviseSalesOrder".equals(i.get("capabilityId"));String order=revise?uuid(s,"orderId"):StockPrimitives.id();int n=1;String previous=null;
  if(revise){text(s,"reason",500);var root=r.require(c,"Orders",order);n=((Number)root.get("currentRevision")).intValue()+1;var current=r.rows(c,"OrderRevisions").stream().filter(x->order.equals(x.get("orderId"))&&((Number)x.get("revisionNumber")).intValue()==((Number)root.get("currentRevision")).intValue()).findFirst().orElseThrow(DomainError::forbidden);var old=r.rows(c,"OrderLines").stream().filter(x->current.get("ID").equals(x.get("revisionId"))).findFirst().orElseThrow(DomainError::forbidden);Set<String> family=new HashSet<>();for(var l:r.rows(c,"OrderLines"))if(order.equals(l.get("orderId")))family.add(l.get("ID").toString());if(inventory.currentRows(c,"SegmentAllocations").stream().anyMatch(a->family.contains(a.get("orderLineId"))&&Set.of("EXECUTABLE","SUSPENDED").contains(a.get("state"))))throw new DomainError("HELD","SALES_ALLOCATION_PRESERVED","Release or reconcile existing allocations before sales revision");previous=old.get("ID").toString();BigDecimal committed=executed(c,previous);if(committed.signum()>0&&(!List.of("customerId","itemId","unit","destinationId","deliveryEndpoint","qualityTerms","packageTerms","currency","price").stream().allMatch(k->same(old.get(k),v.get(k)))||((BigDecimal)v.get("quantity")).compareTo(committed)<0))throw new DomainError("HELD","SALES_EXECUTION_PRESERVED","Revision cannot erase or redirect confirmed dispatch, delivery or invoice");}
  else {var root=SalesRows.row(c,order,c.asOf());root.putAll(Map.of("workId",s.get("workId"),"currentRevision",1));r.insert("Orders",root);}
  String revision=StockPrimitives.id(),line=StockPrimitives.id();var rev=SalesRows.row(c,revision,c.asOf());rev.putAll(Map.of("orderId",order,"workId",s.get("workId"),"customerId",s.get("customerId"),"revisionNumber",n,"reason",Objects.toString(s.get("reason"),"최초 판매 의도를 발행한다")));r.insert("OrderRevisions",rev);
  var l=SalesRows.row(c,line,c.asOf());for(String k:List.of("workId","customerId","itemId","quantity","unit","price","currency","dueAt","destinationId","deliveryEndpoint","qualityTerms","packageTerms"))l.put(k,v.get(k));l.putAll(Map.of("orderId",order,"revisionId",revision));if(previous!=null)l.put("previousLineId",previous);r.insert("OrderLines",l);r.update(c,"Orders",order,Map.of("currentRevision",n,"revision",n));works.markInvalidation(c,s.get("workId").toString(),true);return Map.of("outcome","APPLIED","revision",n,"effects",Map.of("orderId",order,"lineId",line,"salesLineId",line,"revisionId",revision));
 }
 public Map<String,Object> requireLine(DomainContext c,String id){var l=new LinkedHashMap<>(r.require(c,"OrderLines",id));var root=r.require(c,"Orders",l.get("orderId").toString());var revision=r.require(c,"OrderRevisions",l.get("revisionId").toString());l.put("currentRevision",((Number)revision.get("revisionNumber")).intValue()==((Number)root.get("currentRevision")).intValue());return l;}
 public BigDecimal remainingQuantity(DomainContext c,String id){var line=requireLine(c,id);if(!Boolean.TRUE.equals(line.get("currentRevision")))return BigDecimal.ZERO;return ((BigDecimal)line.get("quantity")).subtract(dispatched(c,id)).max(BigDecimal.ZERO);}
 private BigDecimal dispatched(DomainContext c,String id){var line=requireLine(c,id);Set<String>ids=new HashSet<>(Set.of(id));while(line.get("previousLineId")!=null){line=requireLine(c,line.get("previousLineId").toString());if(!ids.add(line.get("ID").toString()))throw DomainError.invalid("Revision cycle");}return r.rows(c,"ExecutionEffects").stream().filter(x->ids.contains(x.get("lineId"))&&"DISPATCHED".equals(x.get("kind"))).map(x->(BigDecimal)x.get("quantity")).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private BigDecimal delivered(DomainContext c,String id){var line=requireLine(c,id);Set<String>ids=new HashSet<>(Set.of(id));while(line.get("previousLineId")!=null){line=requireLine(c,line.get("previousLineId").toString());if(!ids.add(line.get("ID").toString()))throw DomainError.invalid("Revision cycle");}BigDecimal sum=BigDecimal.ZERO;for(var d:r.rows(c,"Deliveries"))if(ids.contains(d.get("salesLineId"))){var current=r.rows(c,"DeliveryCorrections").stream().filter(x->d.get("ID").equals(x.get("deliveryId"))).max(Comparator.comparingInt(x->((Number)x.get("revision")).intValue()));sum=sum.add(current.map(x->(BigDecimal)x.get("legitimateQuantity")).orElse((BigDecimal)d.get("legitimateQuantity")));}return sum;}
 public void recordExecutionEffect(DomainContext c,String lineId,String kind,String reference,BigDecimal q,String unit){var line=requireLine(c,lineId);r.fence(c,"sales/order/"+line.get("orderId"));r.fence(c,"sales/line/"+lineId);if(!Set.of("DISPATCHED","DELIVERED","INVOICED").contains(kind)||q.signum()<=0||!unit.equals(line.get("unit")))throw DomainError.invalid("Invalid sales execution effect");var old=r.rows(c,"ExecutionEffects").stream().filter(x->lineId.equals(x.get("lineId"))&&kind.equals(x.get("kind"))&&reference.equals(x.get("referenceId"))).findFirst();if(old.isPresent()){if(q.compareTo((BigDecimal)old.get().get("quantity"))!=0)throw DomainError.invalid("Execution reference changed");return;}var row=SalesRows.row(c,StockPrimitives.id(),c.asOf());row.putAll(Map.of("lineId",lineId,"kind",kind,"referenceId",reference,"quantity",q,"unit",unit));r.insert("ExecutionEffects",row);}
 private BigDecimal executed(DomainContext c,String id){var line=requireLine(c,id);Set<String> ancestry=new HashSet<>(Set.of(id));while(line.get("previousLineId")!=null){String prev=line.get("previousLineId").toString();if(!ancestry.add(prev))throw DomainError.invalid("Sales revision cycle");line=requireLine(c,prev);}Map<String,BigDecimal> sums=new HashMap<>();for(var x:r.rows(c,"ExecutionEffects"))if(ancestry.contains(x.get("lineId")))sums.merge(x.get("kind").toString(),(BigDecimal)x.get("quantity"),BigDecimal::add);return sums.values().stream().max(BigDecimal::compareTo).orElse(BigDecimal.ZERO);}
 static BigDecimal decimal(Object o,boolean zero){if(!(o instanceof String s)||!s.matches("(?:0|[1-9][0-9]*)(?:\\.[0-9]{1,12})?"))throw DomainError.invalid("Decimal text required");var q=new BigDecimal(s);if(q.precision()-q.scale()>26||q.signum()<0||!zero&&q.signum()==0)throw DomainError.invalid("Decimal overflow");return q;}
 static boolean same(Object a,Object b){return a instanceof BigDecimal x&&b instanceof BigDecimal y?x.compareTo(y)==0:Objects.equals(a,b);}
}
