package com.mulino.application.work;

import com.mulino.application.core.*;
import com.mulino.domain.work.*;
import com.mulino.domain.definitions.DefinitionRepository;
import com.mulino.domain.identity.IdentityRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.stereotype.Component;

@Component
public class WorkLifecycle implements CommandHandler {
 private final WorkRepository repository; private final IdentityRepository identities; private final DefinitionRepository definitions;
 private final ObjectProvider<WorkAssessmentGuard> assessments; private final ObjectProvider<WorkResponsibility> responsibility;
 private final ObjectMapper json=new ObjectMapper(); private final ExecutionClock clock;
 public WorkLifecycle(WorkRepository repository,IdentityRepository identities,DefinitionRepository definitions,ObjectProvider<WorkAssessmentGuard> assessments,ObjectProvider<WorkResponsibility> responsibility,ExecutionClock clock){this.repository=repository;this.identities=identities;this.definitions=definitions;this.assessments=assessments;this.responsibility=responsibility;this.clock=clock;}
 public Set<String> capabilities(){return Set.of("work.createDraft.v1","work.cancelDraft.v1","work.activateWork.v1","work.waitWork.v1","work.resumeWork.v1","work.reviseGoal.v1","work.closeWork.v1","work.createFollowup.v1","work.createWorkLink.v1");}
 public CommandPreparation prepare(DomainContext c,Map<String,Object> intent){var p=parameters(intent);String op=operation(intent);validateKeys(op,p);if(p.get("goal") instanceof Map<?,?>)GoalInput.validate(map(p.get("goal")),false);
  if(op.equals("createDraft")){String item=id(p,"itemId");return new CommandPreparation(Map.of("ITEM",List.of(item)),List.of("work-create:"+item),new HashSet<>(List.of(id(p,"ownerId"),id(p,"supervisorId"))),"WORK",null,null,0,null,null);}
  String id=id(p,"workId");var w=repository.require(c,id,false);var works=new ArrayList<String>(List.of(id));var items=new ArrayList<String>(List.of(String.valueOf(w.get("itemId"))));var fences=new ArrayList<String>(List.of("work:"+id));var actors=new HashSet<String>(List.of(String.valueOf(w.get("ownerId")),String.valueOf(w.get("supervisorId"))));
  if(op.equals("createWorkLink")){String target=id(p,"targetWorkId");var targetWork=repository.require(c,target,false);works.add(target);items.add(String.valueOf(targetWork.get("itemId")));fences.add("work:"+target);fences.add("work-graph:"+c.organizationId());}
  if(op.equals("createFollowup")){var draft=map(p.get("draft"));validateKeys("createDraft",draft);items.add(id(draft,"itemId"));actors.add(id(draft,"ownerId"));actors.add(id(draft,"supervisorId"));}
  return new CommandPreparation(Map.of("WORK",works,"TARGET",works,"ITEM",items),fences,actors,"WORK",null,null,0,id,((Number)w.get("revision")).intValue());
 }
 public Map<String,Object> execute(DomainContext c,Map<String,Object> intent){var p=parameters(intent);String op=operation(intent);if(op.equals("createDraft"))return create(c,p,null);
  String id=id(p,"workId");var w=repository.require(c,id,true);if(!Objects.equals(w.get("lifecycleMode"),"COMMAND"))throw new DomainError("NEEDS_INPUT","IMPORTED_WORK","Imported reference requires explicit lifecycle migration");
  int rev=((Number)w.get("revision")).intValue();if(!(intent.get("expectedRevision") instanceof Number n)||n.intValue()!=rev)throw new DomainError("CONFLICT","REVISION_CONFLICT","Work revision changed");
  String state=String.valueOf(w.get("status"));var changes=new LinkedHashMap<String,Object>();String goalId=String.valueOf(w.get("currentGoalVersionId"));
  switch(op){
   case "cancelDraft"->{state(state,"DRAFT");duties().requireSettled(c,id);changes.put("status","CLOSED");changes.put("closeReason","CANCELLED");GoalInput.text(p,"reason");}
   case "activateWork"->{state(state,"DRAFT");var goal=repository.currentGoal(c,id);var slots=decode(goal.get("slotsJson"));GoalInput.validate(slots,true);guard().requireSupportedGoal(c,goal);human(c,String.valueOf(w.get("ownerId")));human(c,String.valueOf(w.get("supervisorId")));definitions.get(c.organizationId(),String.valueOf(w.get("definitionVersionId")));duties().activated(c,w,goal);changes.put("status","ACTIVE");}
   case "waitWork"->{state(state,"ACTIVE");var wait=map(p.get("wait"));if(!wait.keySet().equals(Set.of("reason","target","resumePredicate","verifier","nextCheckAt","overdueAction")))throw DomainError.invalid("Complete wait contract required");for(String key:List.of("reason","target","verifier","overdueAction"))GoalInput.text(wait,key);Instant.parse(GoalInput.text(wait,"nextCheckAt"));if(!(wait.get("resumePredicate") instanceof Map))throw DomainError.invalid("Typed resume predicate required");changes.put("waitJson",encode(wait));changes.put("status","WAITING");}
   case "resumeWork"->{state(state,"WAITING");guard().requireResume(c,w,decode(w.get("waitJson")),map(p.get("evidence")));changes.put("status","ACTIVE");changes.put("waitJson",null);}
   case "reviseGoal"->{if(!Set.of("DRAFT","ACTIVE","WAITING").contains(state))throw DomainError.invalid("Closed goal cannot change");GoalInput.text(p,"reason");var slots=map(p.get("goal"));GoalInput.validate(slots,!state.equals("DRAFT"));var old=repository.currentGoal(c,id);goalId=goal(c,w,slots,String.valueOf(old.get("ID")),((Number)old.get("goalVersion")).intValue()+1);guard().goalChanged(c,id,String.valueOf(old.get("ID")),goalId);changes.put("currentGoalVersionId",goalId);changes.put("pendingInvalidation",true);}
   case "closeWork"->{if(!Set.of("ACTIVE","WAITING").contains(state))throw DomainError.invalid("Only active/waiting work closes");String reason=GoalInput.text(p,"reason");if(!Set.of("FULFILLED","CANCELLED","IMPOSSIBLE","SUPERSEDED").contains(reason))throw DomainError.invalid("Invalid close reason");duties().requireSettled(c,id);if(reason.equals("FULFILLED")){if(Boolean.TRUE.equals(w.get("pendingInvalidation")))throw new DomainError("HELD","ASSESSMENT_PENDING","Pending invalidation prevents fulfillment");guard().requireFulfilled(c,w,repository.currentGoal(c,id));}changes.put("status","CLOSED");changes.put("closeReason",reason);}
   case "createFollowup"->{state(state,"CLOSED");var result=create(c,map(p.get("draft")),id);String child=String.valueOf(((Map<?,?>)result.get("effects")).get("workId"));duties().followup(c,id,child,p);return result;}
   case "createWorkLink"->{String target=id(p,"targetWorkId");repository.require(c,target,true);String kind=GoalInput.text(p,"kind");if(!Set.of("CONTRIBUTES_TO","DEPENDS_ON","SHARES_ACTIVITY").contains(kind)||id.equals(target))throw DomainError.invalid("Invalid work link");if(kind.equals("DEPENDS_ON")&&reachable(c,target,id,new HashSet<>()))throw DomainError.invalid("Blocking dependency cycle");link(c,id,target,kind);}
   default->throw DomainError.unsupported();
  }
  changes.put("revision",rev+1);changes.put("recordedAt",clock.instant());changes.put("effectiveAt",clock.instant());repository.update(c,id,changes);var snapshot=new LinkedHashMap<>(w);snapshot.putAll(changes);transition(c,snapshot,op,state,(String)p.get("reason"));return result(id,goalId,rev+1,"ACCEPTED");
 }
 private Map<String,Object> create(DomainContext c,Map<String,Object> p,String original){validateKeys("createDraft",p);String id=UUID.randomUUID().toString();String owner=id(p,"ownerId"),supervisor=id(p,"supervisorId");human(c,owner);human(c,supervisor);String definition=id(p,"definitionVersionId");definitions.get(c.organizationId(),definition);var w=row(c,id);w.put("itemId",id(p,"itemId"));if(p.containsKey("lotId"))w.put("lotId",id(p,"lotId"));w.put("definitionVersionId",definition);w.put("kind",GoalInput.text(p,"kind"));w.put("status","DRAFT");w.put("ownerId",owner);w.put("supervisorId",supervisor);w.put("lifecycleMode","COMMAND");w.put("pendingInvalidation",false);repository.insert("mulino.work.read.Works",w);var slots=p.containsKey("goal")?map(p.get("goal")):Map.<String,Object>of();GoalInput.validate(slots,false);String goal=goal(c,w,slots,null,1);repository.update(c,id,Map.of("currentGoalVersionId",goal));w.put("currentGoalVersionId",goal);if(original!=null)link(c,original,id,"FOLLOWUP");transition(c,w,"createDraft",null,null);return result(id,goal,0,"ACCEPTED");}
 private String goal(DomainContext c,Map<String,Object> work,Map<String,Object> slots,String previous,int version){String id=UUID.randomUUID().toString();var g=row(c,id);g.put("workId",work.get("ID"));g.put("definitionVersionId",work.get("definitionVersionId"));if(slots.containsKey("quantityMode"))g.put("quantityMode",slots.get("quantityMode"));g.put("scopeJson",encode(slots.getOrDefault("scope",Map.of())));g.put("slotsJson",encode(slots));g.put("provenanceJson",encode(slots.getOrDefault("provenance",Map.of())));g.put("goalVersion",version);if(previous!=null)g.put("previousGoalId",previous);for(String key:List.of("unit","endpoint","evidencePolicyVersion","timezone"))if(slots.containsKey(key))g.put(key,slots.get(key));if(slots.containsKey("targetQuantity"))g.put("targetQuantity",new java.math.BigDecimal(String.valueOf(slots.get("targetQuantity"))));if(slots.containsKey("dueAt"))g.put("dueAt",Instant.parse(String.valueOf(slots.get("dueAt"))));repository.insert("mulino.work.read.GoalReferences",g);return id;}
 private void link(DomainContext c,String source,String target,String kind){var link=new LinkedHashMap<String,Object>();link.put("organizationId",c.organizationId());link.put("ID",UUID.randomUUID().toString());link.put("sourceWorkId",source);link.put("targetWorkId",target);link.put("kind",kind);link.put("createdAt",clock.instant());repository.insert("mulino.work.WorkLinks",link);}
 private boolean reachable(DomainContext c,String from,String target,Set<String> seen){if(from.equals(target))return true;if(!seen.add(from))return false;return repository.links(c).stream().filter(l->from.equals(l.get("sourceWorkId"))&&"DEPENDS_ON".equals(l.get("kind"))).anyMatch(l->reachable(c,String.valueOf(l.get("targetWorkId")),target,seen));}
 private void transition(DomainContext c,Map<String,Object> w,String op,String previous,String reason){var r=new LinkedHashMap<String,Object>();r.put("organizationId",c.organizationId());r.put("ID",UUID.randomUUID().toString());r.put("workId",w.get("ID"));r.put("revision",w.get("revision"));r.put("operation",op);r.put("previousState",previous);r.put("state",w.get("status"));r.put("actorId",c.actorId());r.put("reason",reason);r.put("recordedAt",clock.instant());r.put("snapshotJson",encode(TransportValues.normalize(w)));repository.insert("mulino.work.WorkTransitions",r);}
 private Map<String,Object> row(DomainContext c,String id){var r=new LinkedHashMap<String,Object>();r.put("organizationId",c.organizationId());r.put("ID",id);r.put("revision",0);r.put("createdAt",clock.instant());r.put("recordedAt",clock.instant());r.put("effectiveAt",clock.instant());return r;}
 private void human(DomainContext c,String id){var actor=identities.actor(c.organizationId(),id).orElseThrow(DomainError::forbidden);if(!"HUMAN".equals(actor.get("kind")))throw DomainError.invalid("Current human responsibility required");
  Instant now=clock.instant();boolean current=identities.rows("Memberships",c.organizationId()).stream().anyMatch(m->id.equals(m.get("actorId"))&&m.get("revokedAt")==null&&!now.isBefore(Instant.parse(String.valueOf(m.get("validFrom"))))&&(m.get("validUntil")==null||now.isBefore(Instant.parse(String.valueOf(m.get("validUntil"))))));if(!current)throw DomainError.invalid("Current owner membership required");}
 private WorkAssessmentGuard guard(){var guard=assessments.getIfAvailable();if(guard==null)throw DomainError.unsupported();return guard;}
 private WorkResponsibility duties(){var duties=responsibility.getIfAvailable();if(duties==null)throw DomainError.unsupported();return duties;}
 private void state(String state,String required){if(!state.equals(required))throw DomainError.invalid("Invalid lifecycle transition");}
 private Map<String,Object> result(String id,String goal,int revision,String outcome){return Map.of("outcome",outcome,"revision",revision,"effects",Map.of("workId",id,"goalVersionId",goal),"quantityEffects",List.of());}
 private String operation(Map<String,Object> intent){String cap=GoalInput.text(intent,"capabilityId");return cap.substring("work.".length(),cap.length()-3);}
 private Map<String,Object> parameters(Map<String,Object> intent){var slots=map(intent.get("slots"));var result=new LinkedHashMap<String,Object>();slots.forEach((k,v)->{if(v instanceof Map<?,?> typed&&typed.containsKey("value")&&typed.containsKey("type"))result.put(k,typed.get("value"));else result.put(k,v);});return result;}
 @SuppressWarnings("unchecked") private Map<String,Object> map(Object o){if(!(o instanceof Map))throw DomainError.invalid("Object slots required");return (Map<String,Object>)o;}
 private String id(Map<String,Object> p,String key){String s=GoalInput.text(p,key);try{UUID.fromString(s);}catch(Exception e){throw DomainError.invalid("UUID required for "+key);}return s;}
 private String encode(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw DomainError.invalid("Invalid goal JSON");}}
 private Map<String,Object> decode(Object o){try{return json.readValue(String.valueOf(o),Map.class);}catch(Exception e){throw DomainError.invalid("Missing stored goal inputs");}}
 private void validateKeys(String op,Map<String,Object> p){Set<String> keys=switch(op){case "createDraft"->Set.of("itemId","lotId","definitionVersionId","kind","ownerId","supervisorId","goal","conversationRequestId","originalText");case "waitWork"->Set.of("workId","wait");case "resumeWork"->Set.of("workId","evidence");case "reviseGoal"->Set.of("workId","goal","reason");case "closeWork","cancelDraft"->Set.of("workId","reason");case "createFollowup"->Set.of("workId","draft","reason","obligationIds");case "createWorkLink"->Set.of("workId","targetWorkId","kind");default->Set.of("workId");};if(!keys.containsAll(p.keySet()))throw DomainError.invalid("Unsupported lifecycle slot");}
}
