package com.mulino.application.trade.settlement;
import com.mulino.application.core.*;
import com.mulino.application.trade.*;
import com.mulino.application.policy.PolicyCommandGuard;
import com.mulino.domain.identity.IdentityRepository;
import com.mulino.domain.trade.settlement.*;
import com.mulino.adapters.blob.LocalBlobStore;
import com.mulino.application.work.WorkAccess;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.trade.settlement.SettlementInputs.*;
import static com.mulino.domain.trade.settlement.SettlementAmounts.*;
/** References only. Common gateway supplies revision, current grants, audit and idempotency transaction. */
@Component
public class SettlementCommands implements CommandHandler {
 private final SettlementRepository r;private final SettlementTradeFacts facts;private final TradeEvidence evidence;private final LocalBlobStore blobs;private final ReadAuthorizer read;private final TradeImpact impact;private final WorkAccess works;private final IdentityRepository identities;private final PolicyCommandGuard policy;private final ExecutionClock clock;private final SettlementState state;
 public SettlementCommands(SettlementRepository r,SettlementTradeFacts facts,TradeEvidence evidence,LocalBlobStore blobs,ReadAuthorizer read,TradeImpact impact,WorkAccess works,IdentityRepository identities,PolicyCommandGuard policy,ExecutionClock clock,SettlementState state){this.state=state;this.r=r;this.facts=facts;this.evidence=evidence;this.blobs=blobs;this.read=read;this.impact=impact;this.works=works;this.identities=identities;this.policy=policy;this.clock=clock;}
 public Set<String> capabilities(){return Set.of("recordInvoice","recordCharge","matchInvoice","recordSettlementAdjustment","recordPaymentReference");}
 public Set<String> intentKinds(){return Set.of("RECORD","COMMAND");}
 public Set<String> definitionVersions(){return Set.of("1.0.0","definition-v1");}
 private Map<String,Object> slots(Map<String,Object> i){return map(i.get("slots"));}
 private String op(Map<String,Object> i){return text(i,"capabilityId");}
 private String scope(Map<String,Object> p){String s=p.containsKey("scopeKind")?text(p,"scopeKind"):p.containsKey("saleLineId")?"SALE":"PURCHASE";if(!Set.of("PURCHASE","SALE").contains(s))throw DomainError.invalid("Scope kind required");return s;}
 private Map<String,Object> lineInput(Map<String,Object> p){return p.containsKey("line")?map(p.get("line")):p;}
 private String lineId(Map<String,Object> p){var l=lineInput(p);return id(l,scope(p).equals("PURCHASE")?"purchaseLineId":"saleLineId");}
 private String reference(Map<String,Object> p){var l=lineInput(p);return id(l,scope(p).equals("PURCHASE")?(l.containsKey("receiptOccurrenceId")?"receiptOccurrenceId":"receiptOccurrenceKey"):"deliveryId");}
 private Map<String,Object> target(DomainContext c,Map<String,Object> i){var p=slots(i);return op(i).equals("recordInvoice")?facts.line(c,scope(p),lineId(p)):r.require(c,"Invoices",id(p,"invoiceId"));}
 static Map<String,List<String>> scopes(Map<String,Object> t){var m=new LinkedHashMap<String,List<String>>();m.put("ITEM",List.of(t.get("itemId").toString()));m.put("WORK",List.of(t.get("workId").toString()));if(t.get("destinationId")!=null)m.put("PLACE",List.of(t.get("destinationId").toString()));for(var e:Map.of("supplierId","SUPPLIER","customerId","CUSTOMER").entrySet())if(t.get(e.getKey())!=null)m.put(e.getValue(),List.of(t.get(e.getKey()).toString()));return m;}
 public CommandPreparation prepare(DomainContext c,Map<String,Object> i){var p=slots(i);var t=target(c,i);boolean create=op(i).equals("recordInvoice");String key=create?lineId(p):t.get("lineId").toString();var fences=new ArrayList<>(List.of("settlement/line/"+key,"work:"+t.get("workId")));if(create){var doc=document(c,id(p,"evidence"));fences.add("settlement/source/"+doc.get("sourceProfileId")+"/"+sourceKey(p,doc));}else fences.add("settlement/invoice/"+t.get("ID"));return new CommandPreparation(scopes(create?t:facts.line(c,t.get("scopeKind").toString(),key)),fences,Set.of(c.actorId()),"SETTLEMENT",null,null,0,t.get("ID").toString(),((Number)t.get("revision")).intValue());}
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object> i,CommandPreparation prep){var t=target(c,i);var b=new ArrayList<SubjectBinding>();b.add(SubjectBinding.optional("TradeItem",Set.of(t.get("itemId").toString())));b.add(SubjectBinding.optional("Work",Set.of(t.get("workId").toString())));if(!op(i).equals("recordInvoice"))b.add(SubjectBinding.optional("Invoice",Set.of(t.get("ID").toString())));return b;}
 public Map<String,Object> execute(DomainContext c,Map<String,Object> i){var p=slots(i);var t=target(c,i);String operation=op(i);if(!operation.equals("recordInvoice"))r.fence(c,"settlement/invoice/"+t.get("ID"));var result=new LinkedHashMap<String,Object>();result.put("outcome","APPLIED");
  switch(operation){
   case "recordInvoice" -> invoice(c,p,t,result);
   case "matchInvoice" -> match(c,p,t,result);
   case "recordCharge" -> {var amount=nonnegative(value(p.get("amount")));String currency=currency(dim(p,"amount","currency")),kind=text(p,"kind");var proof=proof(c,p,t,"CHARGE",null,null);var source=original(c,id(p,"evidence"));requireFields(source,Map.of("invoiceId",t.get("ID"),"kind",kind,"amount",amount,"currency",currency));String id=UUID.randomUUID().toString();r.insert("Charges",row(c,"ID",id,"invoiceId",t.get("ID"),"kind",kind,"amount",amount,"currency",currency,"occurrenceId",proof.get("ID"),"evidenceId",SettlementInputs.id(p,"evidence")));result.put("chargeId",id);}
   case "recordPaymentReference" -> {var amount=nonnegative(value(p.get("amount")));String currency=currency(dim(p,"amount","currency")),ref=text(p,"externalPaymentReference");if(r.rows(c,"PaymentReferences").stream().anyMatch(x->t.get("ID").equals(x.get("invoiceId"))&&ref.equals(x.get("externalPaymentReference"))))throw new DomainError("CONFLICT","PAYMENT_REFERENCE_ALREADY_RECORDED","External payment reference already recorded for this invoice");Instant at=Instant.parse(text(p,"observedAt"));if(at.isAfter(c.knownAt()))throw DomainError.invalid("Future payment observation");var proof=proof(c,p,t,"PAYMENT_REFERENCE",null,null);requireFields(original(c,id(p,"evidence")),Map.of("invoiceId",t.get("ID"),"amount",amount,"currency",currency,"externalPaymentReference",ref,"observedAt",at));String id=UUID.randomUUID().toString();r.insert("PaymentReferences",row(c,"ID",id,"invoiceId",t.get("ID"),"amount",amount,"currency",currency,"externalPaymentReference",ref,"observedAt",at,"evidenceId",SettlementInputs.id(p,"evidence"),"occurrenceId",proof.get("ID"),"bankEffect",BigDecimal.ZERO));result.put("paymentReferenceId",id);result.put("paymentAuthorized",false);}
   case "recordSettlementAdjustment" -> adjustment(c,p,t,result);
   default -> throw DomainError.unsupported();
  }
  result.putIfAbsent("invoiceId",t.get("ID"));result.put("bankEffect","0");result.put("taxIssuanceEffect","0");result.put("revision",1);var effects=new LinkedHashMap<String,Object>();for(String k:List.of("invoiceId","chargeId","matchId","adjustmentId","paymentReferenceId"))if(result.get(k)!=null)effects.put(k,result.get(k));effects.put("bankEffect","0");effects.put("taxIssuanceEffect","0");result.put("effects",effects);return result;
 }
 private void invoice(DomainContext c,Map<String,Object> p,Map<String,Object> l,Map<String,Object> out){String scope=scope(p),kind=text(p,"invoiceKind");if(!Set.of("COMMERCIAL","DOMESTIC_TAX","CREDIT_NOTE","CORRECTION").contains(kind))throw DomainError.invalid("Invoice kind required");var li=lineInput(p);BigDecimal q=positive(value(li.get("quantity"))),price=nonnegative(value(li.get("unitPrice"))),amount=nonnegative(value(p.get("originalAmount")));String unit=dim(li,"quantity","unit"),cur=currency(dim(p,"originalAmount","currency"));if(!unit.equals(l.get("unit"))||!cur.equals(currency(dim(li,"unitPrice","currency")))||product(q,price).compareTo(amount)!=0)throw DomainError.invalid("Invoice arithmetic or dimension mismatch");var productItem=r.external(c,"mulino.inventory.TradeItems",l.get("itemId").toString());if(q.stripTrailingZeros().scale()>((Number)productItem.get("decimalPlaces")).intValue())throw DomainError.invalid("Invoice quantity exceeds item precision");String ref=reference(p),eid=id(p,"evidence");var doc=document(c,eid);var source=original(c,eid);String key=sourceKey(p,doc),ns=text(source,"sourceNamespace"),version=text(source,"sourceVersion");String hash=doc.get("sha256").toString();r.fence(c,"settlement/source/"+doc.get("sourceProfileId")+"/"+key);
  for(var old:r.rows(c,"Invoices"))if(ns.equals(old.get("sourceNamespace"))&&key.equals(old.get("sourceKey"))&&version.equals(old.get("sourceVersion"))){throw new DomainError("CONFLICT",hash.equals(old.get("sourceHash"))?"INVOICE_ALREADY_RECORDED":"INVOICE_SOURCE_CONFLICT","Invoice source key already recorded");}
  // §6 정산·§4.3: a correction is a reference to one exact original invoice, attested by the immutable original.
  String related=null;if(Set.of("CREDIT_NOTE","CORRECTION").contains(kind)){if(!p.containsKey("relatedInvoiceId"))throw DomainError.invalid("Correction invoice requires the original invoice it corrects");related=id(p,"relatedInvoiceId");var old=r.require(c,"Invoices",related);if(!Objects.equals(old.get("lineId"),l.get("ID"))||!Objects.equals(old.get("scopeKind"),scope)||!tVisible(c,old))throw DomainError.invalid("Correction invoice scope differs");}else if(p.containsKey("relatedInvoiceId"))throw DomainError.invalid("Only CREDIT_NOTE/CORRECTION invoices reference an original invoice");
  var expected=new LinkedHashMap<String,Object>(Map.of("lineId",l.get("ID"),"referenceId",ref,"scopeKind",scope,"invoiceKind",kind,"itemId",l.get("itemId"),"quantity",q,"unit",unit,"unitPrice",price,"originalAmount",amount,"currency",cur));expected.put("sourceKey",key);expected.put("sourceNamespace",ns);expected.put("sourceVersion",version);if(related!=null)expected.put("relatedInvoiceId",related);requireFields(source,expected);
  // D19: the conversion snapshot of the original is preserved; slot and original must both carry it or both omit it.
  if((source.get("fxSnapshot")!=null)!=p.containsKey("fxSnapshot"))throw held();
  String invoice=UUID.randomUUID().toString();var row=row(c,"ID",invoice,"workId",l.get("workId"),"itemId",l.get("itemId"),"lineId",l.get("ID"),"referenceId",ref,"scopeKind",scope,"invoiceKind",kind,"sourceNamespace",ns,"sourceKey",key,"sourceVersion",version,"sourceHash",hash,"evidenceId",eid,"quantity",q,"unit",unit,"unitPrice",price,"originalAmount",amount,"currency",cur,"taxReferenceOnly",kind.equals("DOMESTIC_TAX"));
  if(p.containsKey("fxSnapshot")){var fm=map(p.get("fxSnapshot"));if(!(source.get("fxSnapshot") instanceof Map<?,?> sm)||!encode(fm).equals(encode(sm)))throw held();var fx=fx(cur,amount,fm);row.putAll(Map.of("fxPair",fx.pair(),"fxRate",fx.rate(),"fxDate",fx.date(),"fxSource",fx.source(),"fxPolicyVersion",fx.policyVersion(),"fxRounding",fx.rounding(),"convertedAmount",fx.convertedAmount()));}
  if(related!=null){row.put("relatedInvoiceId",related);var duty=impact.recorded(c,l.get("workId").toString(),invoice,"SETTLEMENT_DIFFERENCE",invoice,"정정 송장을 원 송장과 대조해 검토한다",clock.instant().plusSeconds(3600),Map.of("invoiceId",related,"correctionInvoiceId",invoice,"currency",cur),null,null);out.put("dutyRootId",duty.get("rootId"));}
  r.insert("Invoices",row);out.put("invoiceId",invoice);out.put("invoiceKind",kind);out.put("originalAmount",amount.toPlainString());out.put("currency",cur);if(row.get("convertedAmount")!=null)out.put("convertedAmount",row.get("convertedAmount").toString());out.put("evidenceState","CLAIM_REQUIRES_CANONICAL_REVIEW");
 }
 private void match(DomainContext c,Map<String,Object> p,Map<String,Object> t,Map<String,Object> out){String iid=t.get("ID").toString();if(Set.of("CREDIT_NOTE","CORRECTION").contains(t.get("invoiceKind")))throw new DomainError("HELD","SETTLEMENT_CORRECTION_REVIEW_REQUIRED","Correction invoice is a reference; a human must review it against the original invoice, not match it as new fulfillment");if(r.rows(c,"Matches").stream().anyMatch(x->iid.equals(x.get("invoiceId"))))throw new DomainError("CONFLICT","INVOICE_ALREADY_MATCHED","Immutable match already exists");String sk=t.get("scopeKind").toString(),line=t.get("lineId").toString(),reference=t.get("referenceId").toString();for(String k:List.of("purchaseLineId","saleLineId"))if(p.containsKey(k)&&!line.equals(id(p,k)))throw DomainError.invalid("Match line differs");for(String k:List.of("receiptOccurrenceId","receiptOccurrenceKey","deliveryId"))if(p.containsKey(k)&&!reference.equals(id(p,k)))throw DomainError.invalid("Match contribution differs");
  // §6 정산·D13: only the current recognized contribution is billable; actual excess or a superseded receipt chain is not.
  // §4.2 lock-then-reread: the request knownAt was fixed before the gateway fences, so a correction of this exact contribution that
  // committed while this command waited would be invisible to it. Lock the contribution scope with the key its writers take (SALE:
  // the delivery-correction fence; PURCHASE: the receipt credit fence) and re-read the current contribution under that lock.
  var l=facts.line(c,sk,line);r.fence(c,"SALE".equals(sk)?"sales/delivery-correction/"+reference:"purchase-credit:"+reference);var contribution=state.contribution(c.knownThrough(clock.instant()),sk,line,reference);BigDecimal received=SettlementState.recognized(contribution),ordered=positive(l.get("quantity")),iq=positive(t.get("quantity")),price=nonnegative(l.get("price"));String unit=t.get("unit").toString();if(!unit.equals(l.get("unit"))||!unit.equals(contribution.get("unit")))throw DomainError.invalid("Match unit differs");var proof=proof(c,p,t,"INVOICE",iq,unit);BigDecimal quantity=received.min(ordered).min(iq),expected=product(received.min(ordered),price),amount=nonnegative(t.get("originalAmount"));String currency=currency(l.get("currency")),icurrency=currency(t.get("currency"));boolean cd=!currency.equals(icurrency);BigDecimal diff=cd?null:amount.subtract(expected),qd=iq.subtract(received),pd=nonnegative(t.get("unitPrice")).subtract(price);var sameKind=r.rows(c,"Matches").stream().filter(x->line.equals(x.get("lineId"))&&Objects.equals(r.require(c,"Invoices",x.get("invoiceId").toString()).get("invoiceKind"),t.get("invoiceKind"))).toList();BigDecimal prior=sameKind.stream().filter(x->reference.equals(x.get("referenceId"))).map(x->decimal(x.get("quantity"))).reduce(BigDecimal.ZERO,BigDecimal::add),linePrior=sameKind.stream().map(x->decimal(x.get("quantity"))).reduce(BigDecimal.ZERO,BigDecimal::add);boolean overlap=prior.add(quantity).compareTo(received)>0||linePrior.add(quantity).compareTo(ordered)>0;String status=overlap||cd||qd.signum()!=0||pd.signum()!=0||diff!=null&&diff.signum()!=0?"DIFFERENCE":"MATCHED";
  if(p.containsKey("matchQuantity")&&number(p,"matchQuantity").compareTo(quantity)!=0||p.containsKey("orderedAmount")&&(number(p,"orderedAmount").compareTo(expected)!=0||!currency.equals(dim(p,"orderedAmount","currency"))))throw DomainError.invalid("Caller match scalar differs from actual facts");
  String mid=UUID.randomUUID().toString();var row=row(c,"ID",mid,"invoiceId",iid,"lineId",line,"referenceId",reference,"occurrenceId",contribution.get("occurrenceId"),"invoiceOccurrenceId",proof.get("ID"),"scopeKind",sk,"orderedQuantity",ordered,"receivedQuantity",received,"invoiceQuantity",iq,"quantity",quantity,"unit",unit,"unitPrice",price,"orderedAmount",expected,"invoiceAmount",amount,"currency",currency,"invoiceCurrency",icurrency,"quantityDifference",qd,"priceDifference",pd,"originalDifference",diff,"currencyDifference",cd,"scopeDifference",overlap,"status",status);
  if(status.equals("DIFFERENCE")){var duty=impact.recorded(c,t.get("workId").toString(),iid,"SETTLEMENT_DIFFERENCE",iid,"원천 물량과 근거를 대조한다",clock.instant().plusSeconds(3600),Map.of("invoiceId",iid,"matchId",mid,"currency",icurrency),null,null);row.put("dutyRootId",duty.get("rootId"));}
  // INVOICED execution is the non-overlapping recognized quantity only; a DOMESTIC_TAX document is a reference, not execution.
  r.insert("Matches",row);BigDecimal fresh=quantity.min(received.subtract(prior).max(BigDecimal.ZERO)).min(ordered.subtract(linePrior).max(BigDecimal.ZERO));if(!"DOMESTIC_TAX".equals(t.get("invoiceKind"))&&fresh.signum()>0)facts.invoiced(c,sk,line,iid,fresh,unit);out.put("invoicedQuantity",fresh.toPlainString());out.put("receivedQuantity",received.toPlainString());out.put("matchId",mid);out.put("businessStatus",status);out.put("settlementResult",status.equals("MATCHED")?"SATISFIED":"UNSATISFIED");out.put("quantityDifference",qd.toPlainString());out.put("quantityDifferenceUnit",unit);out.put("priceDifference",pd.toPlainString());if(diff!=null)out.put("originalDifference",diff.toPlainString());out.put("currencyDifference",cd);out.put("scopeDifference",overlap);
 }
 private void adjustment(DomainContext c,Map<String,Object> p,Map<String,Object> t,Map<String,Object> out){String iid=t.get("ID").toString(),mode=text(p,"mode");if(!Set.of("PROPOSE","CONFIRM").contains(mode))throw DomainError.invalid("Adjustment mode required");var match=r.rows(c,"Matches").stream().filter(x->iid.equals(x.get("invoiceId"))).findFirst().orElseThrow(()->DomainError.invalid("Invoice match required"));// An adjustment targets an open settlement duty of this match: its own difference or a later contribution change (plan §6 정산, §5.3).
  var openRoots=state.matchRoots(c,match).stream().filter(root->state.open(c,root)).toList();if(openRoots.isEmpty())throw new DomainError("REJECTED","SETTLEMENT_DIFFERENCE_NOT_OPEN","Adjustment requires an open settlement difference duty of this invoice match");
  // §7.1·§5.3: a proposal is bound to the one open duty it adjusts (in its hash); CONFIRM re-derives that root from the currently
  // open roots, so a proposal made for a root that has since closed cannot be confirmed against another root opened later.
  String rootId;if(p.containsKey("dutyRootId")){rootId=id(p,"dutyRootId");if(!openRoots.contains(rootId))throw new DomainError("REJECTED","SETTLEMENT_DIFFERENCE_NOT_OPEN","Named settlement difference duty of this invoice match is not open");}else if(openRoots.size()==1)rootId=openRoots.getFirst();else throw DomainError.invalid("Several settlement difference duties are open; the adjustment must name dutyRootId");if(Boolean.TRUE.equals(match.get("currencyDifference")))throw DomainError.invalid("Currency mismatch requires authoritative correction, no scalar tolerance");BigDecimal amount=number(p,"amount");if(amount.signum()==0)throw DomainError.invalid("Zero settlement adjustment changes nothing");String currency=currency(dim(p,"amount","currency")),reason=text(p,"reason");if(!currency.equals(t.get("currency")))throw DomainError.invalid("Adjustment currency differs");var proof=proof(c,p,t,"SETTLEMENT_ADJUSTMENT",null,null);requireFields(original(c,id(p,"evidence")),Map.of("invoiceId",iid,"mode",mode,"amount",amount,"currency",currency,"reason",reason));String hash=proposalHash(iid,match.get("ID").toString(),amount,currency,reason,rootId);var row=row(c,"invoiceId",iid,"matchId",match.get("ID"),"mode",mode,"amount",amount,"currency",currency,"reason",reason,"evidenceId",id(p,"evidence"),"occurrenceId",proof.get("ID"),"status",mode.equals("PROPOSE")?"PROPOSED":"CONFIRMED","proposalHash",hash);
  if(mode.equals("CONFIRM")){manager(c,prepare(c,Map.of("capabilityId","recordSettlementAdjustment","slots",p)).scopes());String proposal=id(p,"proposalId");var proposed=r.require(c,"Adjustments",proposal);if(!"PROPOSED".equals(proposed.get("status"))||!iid.equals(proposed.get("invoiceId"))||!hash.equals(proposed.get("proposalHash"))||!hash.equals(text(p,"proposalHash")))throw new DomainError("HELD","APPROVAL_HASH_MISMATCH","Adjustment proposal changed");if(r.rows(c,"Adjustments").stream().anyMatch(x->proposal.equals(x.get("proposalId"))&&"CONFIRMED".equals(x.get("status"))))throw new DomainError("CONFLICT","ADJUSTMENT_ALREADY_CONFIRMED","Proposal already confirmed");var rule=policy.rule(c,"recordSettlementAdjustment");if(!rule.policyVersion().equals(text(p,"policyVersion")))throw new DomainError("HELD","APPROVAL_POLICY_CHANGED","Settlement policy provenance differs");row.putAll(Map.of("proposalId",proposal,"approverId",c.actorId(),"policyHash",rule.policyHash(),"policyVersion",text(p,"policyVersion"),"decisionHash",hash));requireFields(original(c,id(p,"evidence")),Map.of("proposalId",proposal,"proposalHash",hash,"policyVersion",text(p,"policyVersion")));}
  r.insert("Adjustments",row);out.put("adjustmentId",row.get("ID"));out.put("proposalHash",hash);out.put("dutyRootId",rootId);out.put("businessStatus",row.get("status"));out.put("originalDifference",Objects.toString(match.get("originalDifference"),"UNKNOWN"));out.put("settlementDifference",remaining(c,match).toPlainString());
 }
 /** Adjustment proposal identity: the exact match, amount, reason and the target settlement difference root. */
 static String proposalHash(String invoiceId,String matchId,BigDecimal amount,String currency,String reason,String rootId){return CommandRequests.hash(Map.of("invoiceId",invoiceId,"matchId",matchId,"amount",amount.stripTrailingZeros().toPlainString(),"currency",currency,"reason",reason,"dutyRootId",rootId));}
 public BigDecimal remaining(DomainContext c,Map<String,Object> match){if(match.get("originalDifference")==null)throw DomainError.invalid("Currency variance unknown");var approved=r.rows(c,"Adjustments").stream().filter(x->match.get("ID").equals(x.get("matchId"))&&"CONFIRMED".equals(x.get("status"))).map(x->decimal(x.get("amount"))).reduce(BigDecimal.ZERO,BigDecimal::add);return decimal(match.get("originalDifference")).subtract(approved);}
 private void manager(DomainContext c,Map<String,List<String>> scopes){if(!"HUMAN".equals(identities.actor(c.organizationId(),c.actorId()).orElseThrow(DomainError::forbidden).get("kind")))throw DomainError.forbidden();if(identities.rows("ManagementAuthorities",c.organizationId()).stream().noneMatch(x->c.actorId().equals(x.get("actorId"))&&"recordSettlementAdjustment".equals(x.get("capabilityId"))&&active(x)&&("ORGANIZATION".equals(x.get("scopeKind"))&&c.organizationId().equals(x.get("scopeId"))||scopes.getOrDefault(x.get("scopeKind"),List.of()).contains(x.get("scopeId")))))throw DomainError.forbidden();}
 private boolean active(Map<String,Object> x){Instant now=clock.instant();return x.get("validFrom")!=null&&x.get("validUntil")!=null&&!now.isBefore(Instant.parse(x.get("validFrom").toString()))&&now.isBefore(Instant.parse(x.get("validUntil").toString()))&&(x.get("revokedAt")==null||now.isBefore(Instant.parse(x.get("revokedAt").toString())));}
 private String sourceKey(Map<String,Object> p,Map<String,Object> doc){return p.containsKey("sourceKey")?text(p,"sourceKey"):text(originalFrom(doc),"sourceKey");}
 private Map<String,Object> originalFrom(Map<String,Object> d){try{return new com.fasterxml.jackson.databind.ObjectMapper().readValue(blobs.read(UUID.fromString(d.get("blobId").toString()),d.get("sha256").toString()),Map.class);}catch(java.io.IOException|NullPointerException e){throw held();}}
 private Map<String,Object> document(DomainContext c,String id){var d=r.external(c,"mulino.evidence.DocumentVersions",id);read.authorizeScopes(c,"getEvidence",com.mulino.domain.evidence.EvidenceTypes.scopes(d));if(!"AVAILABLE".equals(d.get("availability"))||d.get("blobId")==null||!tVisible(c,d))throw held();return d;}
 private boolean tVisible(DomainContext c,Map<String,Object> row){return !Instant.parse(row.get("recordedAt").toString()).isAfter(c.knownAt());}
 private Map<String,Object> original(DomainContext c,String id){return originalFrom(document(c,id));}
 static void requireFields(Map<String,Object> source,Map<String,Object> expected){for(var e:expected.entrySet()){Object actual=source.get(e.getKey()),value=e.getValue();if(value instanceof BigDecimal d){if(actual==null||decimal(actual).compareTo(d)!=0)throw held();}else if(value instanceof Instant instant){if(actual==null||!instant.equals(Instant.parse(actual.toString())))throw held();}else if(!Objects.equals(Objects.toString(value,null),Objects.toString(actual,null)))throw held();}}
 private Map<String,Object> proof(DomainContext c,Map<String,Object> p,Map<String,Object> invoice,String kind,BigDecimal quantity,String unit){String eid=p.containsKey("evidence")?id(p,"evidence"):invoice.get("evidenceId").toString();String occurrence=p.containsKey("canonicalOccurrenceId")?id(p,"canonicalOccurrenceId"):r.externalRows(c,"mulino.evidence.Verifications").stream().filter(x->eid.equals(x.get("basisDocumentId"))&&"VERIFIED".equals(x.get("verdict"))).map(x->x.get("canonicalOccurrenceId").toString()).findFirst().orElseThrow(SettlementInputs::held);var proof=evidence.requireCanonical(c,occurrence,kind,invoice.get("itemId").toString(),invoice.get("ID").toString(),quantity,unit);var verification=r.external(c,"mulino.evidence.Verifications",proof.get("verificationId").toString());if(!eid.equals(verification.get("basisDocumentId")))throw held();if(!invoice.get("ID").equals(proof.get("subjectId"))||!"INVOICE".equals(proof.get("subjectKind")))throw held();return proof;}
}
