package com.mulino.application.trade.settlement;
import com.mulino.application.core.*;
import com.mulino.domain.trade.settlement.SettlementRepository;
import java.util.*;
import java.math.BigDecimal;
import java.time.Instant;
import org.springframework.stereotype.Component;
import static com.mulino.domain.trade.settlement.SettlementAmounts.*;
/** Noun and verb share immutable invoice, match, evidence and duty snapshot. */
@Component
public class SettlementQueries implements QueryHandler,ObjectReadProvider {
 private final SettlementRepository r;private final ReadAuthorizer auth;private final SettlementTradeFacts facts;private final SettlementState state;
 public SettlementQueries(SettlementRepository r,ReadAuthorizer auth,SettlementTradeFacts facts,SettlementState state){this.r=r;this.auth=auth;this.facts=facts;this.state=state;}
 public Set<String> operations(){return Set.of("getSettlement");}
 public Set<String> objectTypes(){return Set.of("Invoice");}
 private boolean visible(DomainContext c,Map<String,Object> x){return !Instant.parse(x.get("recordedAt").toString()).isAfter(c.knownAt())&&(x.get("effectiveAt")==null||!Instant.parse(x.get("effectiveAt").toString()).isAfter(c.asOf()));}
 private List<Map<String,Object>> related(DomainContext c,String table,String invoice){return r.rows(c,table).stream().filter(x->invoice.equals(x.get("invoiceId"))&&visible(c,x)).toList();}
 public QueryResult query(DomainContext c,QueryRequest q){if(q.id()==null)throw DomainError.invalid("Invoice ID required");if(!Set.of("organizationId","itemId","workId","invoiceId","type","objectType").containsAll(q.scope().keySet())||!Set.of("type","sort").containsAll(q.filters().keySet()))throw DomainError.invalid("Unsupported settlement query scope or filter");if(q.filters().containsKey("sort")&&!"ID".equals(q.filters().get("sort")))throw DomainError.invalid("Unsupported settlement sort");if(q.filters().get("type")!=null&&!"Invoice".equals(q.filters().get("type")))throw DomainError.invalid("Unsupported invoice type");var invoice=r.require(c,"Invoices",q.id());for(var entry:q.scope().entrySet()){Object expected=entry.getKey().equals("invoiceId")?invoice.get("ID"):Set.of("type","objectType").contains(entry.getKey())?"Invoice":invoice.get(entry.getKey());if(!Objects.equals(expected,entry.getValue()))throw DomainError.forbidden();}if(!visible(c,invoice))throw DomainError.forbidden();auth.authorizeScopes(c,q.operation().equals("getSettlement")?"getSettlement":"getObject",SettlementCommands.scopes(facts.line(c,invoice.get("scopeKind").toString(),invoice.get("lineId").toString())));var data=new LinkedHashMap<>(invoice);var matches=related(c,"Matches",q.id());var adjustments=related(c,"Adjustments",q.id());var charges=related(c,"Charges",q.id());var payments=related(c,"PaymentReferences",q.id());data.put("type","Invoice");data.put("matches",matches);data.put("charges",charges);data.put("adjustments",adjustments);data.put("paymentReferences",payments);data.put("bankEffect","0");data.put("taxIssuanceEffect","0");data.put("paymentAuthorized",false);var settlement=new LinkedHashMap<String,Object>();settlement.put("result","UNVERIFIED");settlement.put("currency",invoice.get("currency"));
  // §6 정산·§4.3: the same predicate as duty closure, re-derived from current recognized facts at read time.
  if(!matches.isEmpty()){var m=matches.getFirst();settlement.putAll(state.assess(c,m,adjustments));if(m.get("dutyRootId")!=null)data.put("dutyRootId",m.get("dutyRootId"));}
  // A CREDIT_NOTE/CORRECTION under open human review keeps the original invoice unverified and visible.
  var correctionRoots=state.correctionRoots(c);var corrections=r.rows(c,"Invoices").stream().filter(x->q.id().equals(x.get("relatedInvoiceId"))&&visible(c,x)).toList();var reviewRoots=new ArrayList<Object>();for(var x:corrections){Object root=correctionRoots.get(x.get("ID").toString());if(root!=null)reviewRoots.add(root);}if(correctionRoots.containsKey(q.id()))reviewRoots.add(correctionRoots.get(q.id()));data.put("corrections",corrections);data.put("reviewDutyRootIds",reviewRoots);if(corrections.stream().anyMatch(x->state.open(c,correctionRoots.get(x.get("ID").toString())))){settlement.put("result","UNVERIFIED");settlement.put("correctionReviewOpen",true);}
  data.put("settlement",settlement);auth.authorizeScopes(c,"getWork",Map.of("ITEM",List.of(invoice.get("itemId").toString()),"WORK",List.of(invoice.get("workId").toString())));auth.authorizeScopes(c,"getObligations",Map.of("ITEM",List.of(invoice.get("itemId").toString()),"WORK",List.of(invoice.get("workId").toString())));var work=r.external(c,"mulino.work.read.Works",invoice.get("workId").toString());if(!visible(c,work))throw DomainError.forbidden();var goals=r.externalRows(c,"mulino.work.read.GoalReferences").stream().filter(x->invoice.get("workId").equals(x.get("workId"))&&visible(c,x)).toList();data.put("logistics",Map.of("workId",work.get("ID"),"status",work.get("status"),"goals",goals));var duties=r.externalRows(c,"mulino.work.read.ObligationReferences").stream().filter(x->visible(c,x)&&(invoice.get("workId").equals(x.get("workId"))||data.get("dutyRootId")!=null&&data.get("dutyRootId").equals(x.get("rootId"))||x.get("rootId")!=null&&reviewRoots.contains(x.get("rootId")))).toList();for(var duty:duties)auth.authorizeScopes(c,"getObligations",Map.of("ITEM",List.of(invoice.get("itemId").toString()),"WORK",List.of(duty.get("workId").toString())));data.put("obligations",duties);var refs=new ArrayList<String>(List.of(invoice.get("evidenceId").toString()));matches.forEach(x->refs.add(x.get("invoiceOccurrenceId").toString()));return new QueryResult(data,Map.of("organizationId",c.organizationId(),"itemId",invoice.get("itemId"),"workId",invoice.get("workId")),matches.isEmpty()?List.of("INVOICE_UNMATCHED"):List.of(),List.of(),refs,null);
 }
}
