package com.mulino.responsibility;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.junit.jupiter.api.Assertions.*;
/** Independent SQL oracle against fresh PostgreSQL, not mocked assignment counts. */
class ResponsibilityPostgresTest {
 static final PostgreSQLContainer PG=new PostgreSQLContainer("postgres@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280");
 static final String org=id(),owner=id(),work=id(),item=id(),product=id(),definition=id(),spec=id(),pack=id();
 static String id(){return UUID.randomUUID().toString();}
 static Connection db()throws Exception{return DriverManager.getConnection(PG.getJdbcUrl(),PG.getUsername(),PG.getPassword());}
 static void sql(Connection c,String s,Object...values)throws Exception{try(var p=c.prepareStatement(s)){for(int i=0;i<values.length;i++)p.setObject(i+1,values[i]);p.execute();}}
 @BeforeAll static void start()throws Exception{PG.start();try(var c=db()){
 var files=Files.list(Path.of("../database/migrations")).filter(p->p.getFileName().toString().matches("V([1-7]|9|10)__.*\\.sql")).sorted(Comparator.comparingInt(p->Integer.parseInt(p.getFileName().toString().split("__")[0].substring(1)))).toList();for(var p:files)c.createStatement().execute(Files.readString(p));
 sql(c,"INSERT INTO mulino_identity_Organizations(ID,externalAlias) VALUES(?,'test')",org);sql(c,"INSERT INTO mulino_identity_Actors(organizationId,ID,kind,stableRequestOwner) VALUES(?,?,'HUMAN',?)",org,owner,id());
 sql(c,"INSERT INTO mulino_inventory_Products(organizationId,ID,name) VALUES(?,?,'product')",org,product);sql(c,"INSERT INTO mulino_inventory_SpecificationVersions(organizationId,ID,productId,version,contentHash) VALUES(?,?,?,'1',?)",org,spec,product,"1".repeat(64));sql(c,"INSERT INTO mulino_inventory_PackagingVersions(organizationId,ID,productId,version,contentHash) VALUES(?,?,?,'1',?)",org,pack,product,"2".repeat(64));sql(c,"INSERT INTO mulino_inventory_TradeItems(organizationId,ID,productId,name,baseUnit,decimalPlaces,specificationVersionId,packagingVersionId) VALUES(?,?,?,'item','EA',0,?,?)",org,item,product,spec,pack);
 sql(c,"INSERT INTO mulino_definitions_DefinitionVersions(organizationId,ID,createdAt,version,state,contentHash,content,evaluatorVersion,schemaVersion) VALUES(?,?,now(),'1','DRAFT',?,'{}','test','1')",org,definition,"1".repeat(64));
 sql(c,"INSERT INTO mulino_work_read_Works(organizationId,ID,createdAt,recordedAt,effectiveAt,itemId,definitionVersionId,kind,status,ownerId,supervisorId) VALUES(?,?,now(),now(),now(),?,?,'FOLLOWUP','ACTIVE',?,?)",org,work,item,definition,owner,owner);
 }}
 @AfterAll static void stop(){PG.stop();}
 String[] duty()throws Exception{String root=id(),scope=id(),assignment=id();try(var c=db()){c.setAutoCommit(false);sql(c,"INSERT INTO mulino_responsibility_Roots(organizationId,ID,createdAt,recordedAt,dutyKey,sourceId,sourceKind,sourceVersion,kind,scopeJson,quantity,unit) VALUES(?,?,now(),now(),?,?,'OCCURRENCE','1','QC','{}',100,'EA')",org,root,id(),id());sql(c,"INSERT INTO mulino_responsibility_Scopes(organizationId,ID,createdAt,recordedAt,rootId,startQuantity,quantity,scopeJson) VALUES(?,?,now(),now(),?,0,100,'{}')",org,scope,root);assignment(c,assignment,root,scope);c.commit();}return new String[]{root,scope,assignment};}
 void assignment(Connection c,String aid,String root,String scope)throws Exception{sql(c,"INSERT INTO mulino_work_read_ObligationReferences(organizationId,ID,createdAt,recordedAt,effectiveAt,workId,kind,status,ownerId,supervisorId,nextAction,nextCheckAt,quantity,unit,scopeJson,rootId,scopeId,valid) VALUES(?,?,now(),now(),now(),?,'QC','OPEN',?,?,'review',now()+interval '1 day',100,'EA','{}',?,?,true)",org,aid,work,owner,owner,root,scope);}
 @Test void failedPendingEffectRollsBackOriginalDuty()throws Exception{var d=duty();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_work_read_ObligationReferences SET status='TRANSFERRED',valid=false WHERE organizationId=? AND ID=?",org,d[2]);assertThrows(SQLException.class,c::commit);c.rollback();}try(var c=db();var s=c.createStatement();var rs=s.executeQuery("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE ID='"+d[2]+"' AND status='OPEN' AND valid")){assertTrue(rs.next());assertEquals(1,rs.getInt(1));}}
 @Test void rootWithoutAssignmentAndQuantityLossFailAtCommit()throws Exception{var d=duty();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_responsibility_Scopes SET quantity=90 WHERE organizationId=? AND ID=?",org,d[1]);assertThrows(SQLException.class,c::commit);c.rollback();}}
 @Test void twoConcurrentTransfersHaveOneWinnerOneCurrentAssignment()throws Exception{var d=duty();var ready=new CountDownLatch(2);var go=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);Callable<Boolean> attempt=()->{try(var c=db()){c.setAutoCommit(false);ready.countDown();go.await();sql(c,"SELECT ID FROM mulino_responsibility_Roots WHERE organizationId=? AND ID=? FOR UPDATE",org,d[0]);try(var p=c.prepareStatement("UPDATE mulino_work_read_ObligationReferences SET status='TRANSFERRED',valid=false WHERE ID=? AND status='OPEN'")){p.setString(1,d[2]);if(p.executeUpdate()!=1){c.rollback();return false;}}assignment(c,id(),d[0],d[1]);c.commit();return true;}};try{var a=pool.submit(attempt);var b=pool.submit(attempt);assertTrue(ready.await(10,TimeUnit.SECONDS));go.countDown();assertNotEquals(a.get(15,TimeUnit.SECONDS),b.get(15,TimeUnit.SECONDS));}finally{pool.shutdownNow();}try(var c=db();var p=c.prepareStatement("SELECT count(*),sum(quantity),count(distinct ownerId) FROM mulino_work_read_ObligationReferences WHERE rootId=? AND status='OPEN' AND valid")){p.setString(1,d[0]);try(var rs=p.executeQuery()){assertTrue(rs.next());assertEquals(1,rs.getInt(1));assertEquals(0,new java.math.BigDecimal("100").compareTo(rs.getBigDecimal(2)));assertEquals(1,rs.getInt(3));}}}
 @Test void partialTransferConservesLeafAndAssignmentQuantityWithoutParentDoubleCount()throws Exception{var d=duty();String a=id(),b=id();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_work_read_ObligationReferences SET status='TRANSFERRED',valid=false WHERE ID=?",d[2]);sql(c,"UPDATE mulino_responsibility_Scopes SET leaf=false WHERE ID=?",d[1]);for(var child:List.of(new Object[]{a,0,60},new Object[]{b,60,40})){sql(c,"INSERT INTO mulino_responsibility_Scopes(organizationId,ID,createdAt,recordedAt,rootId,parentScopeId,startQuantity,quantity,scopeJson) VALUES(?,?,now(),now(),?,?,?,?,'{}')",org,child[0],d[0],d[1],child[1],child[2]);String aid=id();assignment(c,aid,d[0],child[0].toString());sql(c,"UPDATE mulino_work_read_ObligationReferences SET quantity=? WHERE ID=?",child[2],aid);}c.commit();}try(var c=db();var p=c.prepareStatement("SELECT count(*),sum(quantity) FROM mulino_work_read_ObligationReferences WHERE rootId=? AND valid AND status='OPEN'")){p.setString(1,d[0]);try(var rs=p.executeQuery()){assertTrue(rs.next());assertEquals(2,rs.getInt(1));assertEquals(0,new java.math.BigDecimal("100").compareTo(rs.getBigDecimal(2)));}}}
 @Test void currentAssignmentCannotLieAboutLeafQuantity()throws Exception{var d=duty();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_work_read_ObligationReferences SET quantity=90 WHERE ID=?",d[2]);assertThrows(SQLException.class,c::commit);c.rollback();}}

}
