package com.mulino.responsibility;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.junit.jupiter.api.Assertions.*;
/** Independent SQL oracle against fresh PostgreSQL, not mocked assignment counts. */
class ResponsibilityPostgresTest {
 static final PostgreSQLContainer PG=new PostgreSQLContainer("postgres@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280");
 static final String org=id(),owner=id(),work=id(),item=id(),product=id(),definition=id(),spec=id(),pack=id();
 static String id(){return UUID.randomUUID().toString();}
 static Connection db()throws Exception{return DriverManager.getConnection(PG.getJdbcUrl(),PG.getUsername(),PG.getPassword());}
 static void sql(Connection c,String s,Object...values)throws Exception{try(var p=c.prepareStatement(s)){for(int i=0;i<values.length;i++)p.setObject(i+1,values[i]);p.execute();}}
 @BeforeAll static void start()throws Exception{PG.start();try(var c=db()){
 var files=Files.list(Path.of("../database/migrations")).filter(p->p.getFileName().toString().matches("V([1-7]|9|10)__.*\\.sql")).sorted(Comparator.comparingInt(p->Integer.parseInt(p.getFileName().toString().split("__")[0].substring(1)))).toList();for(var p:files)c.createStatement().execute(Files.readString(p));
 sql(c,"INSERT INTO mulino_identity_Organizations(ID,externalAlias) VALUES(?,'test')",org);sql(c,"INSERT INTO mulino_identity_Actors(organizationId,ID,kind,stableRequestOwner) VALUES(?,?,'HUMAN',?)",org,owner,id());
 sql(c,"INSERT INTO mulino_inventory_Products(organizationId,ID,name) VALUES(?,?,'product')",org,product);sql(c,"INSERT INTO mulino_inventory_SpecificationVersions(organizationId,ID,productId,version,contentHash) VALUES(?,?,?,'1',?)",org,spec,product,"1".repeat(64));sql(c,"INSERT INTO mulino_inventory_PackagingVersions(organizationId,ID,productId,version,contentHash) VALUES(?,?,?,'1',?)",org,pack,product,"2".repeat(64));sql(c,"INSERT INTO mulino_inventory_TradeItems(organizationId,ID,productId,name,baseUnit,decimalPlaces,specificationVersionId,packagingVersionId) VALUES(?,?,?,'item','EA',0,?,?)",org,item,product,spec,pack);
 sql(c,"INSERT INTO mulino_definitions_DefinitionVersions(organizationId,ID,createdAt,version,state,contentHash,content,evaluatorVersion,schemaVersion) VALUES(?,?,now(),'1','DRAFT',?,'{}','test','1')",org,definition,"1".repeat(64));
 sql(c,"INSERT INTO mulino_work_read_Works(organizationId,ID,createdAt,recordedAt,effectiveAt,itemId,definitionVersionId,kind,status,ownerId,supervisorId) VALUES(?,?,now(),now(),now(),?,?,'FOLLOWUP','ACTIVE',?,?)",org,work,item,definition,owner,owner);
 }}
 @AfterAll static void stop(){PG.stop();}
 String[] duty()throws Exception{String root=id(),scope=id(),assignment=id();try(var c=db()){c.setAutoCommit(false);sql(c,"INSERT INTO mulino_responsibility_Roots(organizationId,ID,createdAt,recordedAt,dutyKey,sourceId,sourceKind,sourceVersion,kind,scopeJson,quantity,unit) VALUES(?,?,now(),now(),?,?,'OCCURRENCE','1','QC','{}',100,'EA')",org,root,id(),id());sql(c,"INSERT INTO mulino_responsibility_Scopes(organizationId,ID,createdAt,recordedAt,rootId,startQuantity,quantity,scopeJson) VALUES(?,?,now(),now(),?,0,100,'{}')",org,scope,root);assignment(c,assignment,root,scope);c.commit();}return new String[]{root,scope,assignment};}
 void assignment(Connection c,String aid,String root,String scope)throws Exception{sql(c,"INSERT INTO mulino_work_read_ObligationReferences(organizationId,ID,createdAt,recordedAt,effectiveAt,workId,kind,status,ownerId,supervisorId,nextAction,nextCheckAt,quantity,unit,scopeJson,rootId,scopeId,valid) VALUES(?,?,now(),now(),now(),?,'QC','OPEN',?,?,'review',now()+interval '1 day',100,'EA','{}',?,?,true)",org,aid,work,owner,owner,root,scope);}
 @Test void failedPendingEffectRollsBackOriginalDuty()throws Exception{var d=duty();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_work_read_ObligationReferences SET status='TRANSFERRED',valid=false WHERE organizationId=? AND ID=?",org,d[2]);assertThrows(SQLException.class,c::commit);c.rollback();}try(var c=db();var s=c.createStatement();var rs=s.executeQuery("SELECT count(*) FROM mulino_work_read_ObligationReferences WHERE ID='"+d[2]+"' AND status='OPEN' AND valid")){assertTrue(rs.next());assertEquals(1,rs.getInt(1));}}
 @Test void rootWithoutAssignmentAndQuantityLossFailAtCommit()throws Exception{var d=duty();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_responsibility_Scopes SET quantity=90 WHERE organizationId=? AND ID=?",org,d[1]);assertThrows(SQLException.class,c::commit);c.rollback();}}
 @Test void twoConcurrentTransfersHaveOneWinnerOneCurrentAssignment()throws Exception{var d=duty();var ready=new CountDownLatch(2);var go=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);Callable<Boolean> attempt=()->{try(var c=db()){c.setAutoCommit(false);ready.countDown();go.await();sql(c,"SELECT ID FROM mulino_responsibility_Roots WHERE organizationId=? AND ID=? FOR UPDATE",org,d[0]);try(var p=c.prepareStatement("UPDATE mulino_work_read_ObligationReferences SET status='TRANSFERRED',valid=false WHERE ID=? AND status='OPEN'")){p.setString(1,d[2]);if(p.executeUpdate()!=1){c.rollback();return false;}}assignment(c,id(),d[0],d[1]);c.commit();return true;}};try{var a=pool.submit(attempt);var b=pool.submit(attempt);assertTrue(ready.await(10,TimeUnit.SECONDS));go.countDown();assertNotEquals(a.get(15,TimeUnit.SECONDS),b.get(15,TimeUnit.SECONDS));}finally{pool.shutdownNow();}try(var c=db();var p=c.prepareStatement("SELECT count(*),sum(quantity),count(distinct ownerId) FROM mulino_work_read_ObligationReferences WHERE rootId=? AND status='OPEN' AND valid")){p.setString(1,d[0]);try(var rs=p.executeQuery()){assertTrue(rs.next());assertEquals(1,rs.getInt(1));assertEquals(0,new java.math.BigDecimal("100").compareTo(rs.getBigDecimal(2)));assertEquals(1,rs.getInt(3));}}}
 @Test void partialTransferConservesLeafAndAssignmentQuantityWithoutParentDoubleCount()throws Exception{var d=duty();String a=id(),b=id();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_work_read_ObligationReferences SET status='TRANSFERRED',valid=false WHERE ID=?",d[2]);sql(c,"UPDATE mulino_responsibility_Scopes SET leaf=false WHERE ID=?",d[1]);for(var child:List.of(new Object[]{a,0,60},new Object[]{b,60,40})){sql(c,"INSERT INTO mulino_responsibility_Scopes(organizationId,ID,createdAt,recordedAt,rootId,parentScopeId,startQuantity,quantity,scopeJson) VALUES(?,?,now(),now(),?,?,?,?,'{}')",org,child[0],d[0],d[1],child[1],child[2]);String aid=id();assignment(c,aid,d[0],child[0].toString());sql(c,"UPDATE mulino_work_read_ObligationReferences SET quantity=? WHERE ID=?",child[2],aid);}c.commit();}try(var c=db();var p=c.prepareStatement("SELECT count(*),sum(quantity) FROM mulino_work_read_ObligationReferences WHERE rootId=? AND valid AND status='OPEN'")){p.setString(1,d[0]);try(var rs=p.executeQuery()){assertTrue(rs.next());assertEquals(2,rs.getInt(1));assertEquals(0,new java.math.BigDecimal("100").compareTo(rs.getBigDecimal(2)));}}}
 @Test void currentAssignmentCannotLieAboutLeafQuantity()throws Exception{var d=duty();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_work_read_ObligationReferences SET quantity=90 WHERE ID=?",d[2]);assertThrows(SQLException.class,c::commit);c.rollback();}}

 String[] splitDuty()throws Exception{var d=duty();String left=id(),right=id(),a=id(),b=id();try(var c=db()){c.setAutoCommit(false);sql(c,"UPDATE mulino_work_read_ObligationReferences SET status='TRANSFERRED',valid=false WHERE ID=?",d[2]);sql(c,"UPDATE mulino_responsibility_Scopes SET leaf=false WHERE ID=?",d[1]);sql(c,"INSERT INTO mulino_responsibility_Scopes(organizationId,ID,createdAt,recordedAt,rootId,parentScopeId,startQuantity,quantity,scopeJson) VALUES(?,?,now(),now(),?,?,0,50,'{}'),(?,?,now(),now(),?,?,50,50,'{}')",org,left,d[0],d[1],org,right,d[0],d[1]);assignment(c,a,d[0],left);assignment(c,b,d[0],right);sql(c,"UPDATE mulino_work_read_ObligationReferences SET quantity=50 WHERE ID IN (?,?)",a,b);c.commit();}return new String[]{d[0],left,right,a,b};}
 String[] verifiedResponse(int quantity)throws Exception{String profile=id(),doc=id(),event=id(),claim=id(),occurrence=id(),verification=id();try(var c=db()){
 sql(c,"INSERT INTO mulino_evidence_SourceProfiles(ID,organizationId,revision,recordedAt,recordedBy,namespace,policyVersion,intakeOwnerId,supervisorId,nextAction,nextCheckAt) VALUES(?,?,1,now(),?,?,'fixture',?,?,'review',now())",profile,org,owner,profile,owner,owner);
 sql(c,"INSERT INTO mulino_evidence_DocumentVersions(ID,organizationId,revision,recordedAt,recordedBy,subjectKind,subjectId,workId,sha256,byteLength,mediaType,sourceProfileId,availability,provenance) VALUES(?,?,1,now(),?,'WORK',?,?,?,0,'text/plain',?,'UNKNOWN','{}')",doc,org,owner,work,work,"1".repeat(64),profile);
 sql(c,"INSERT INTO mulino_evidence_Events(ID,organizationId,revision,recordedAt,recordedBy,subjectKind,subjectId,workId,effectiveFrom,timeZone,timePrecision,valueState,kind,sourceNamespace,sourceProfileId,externalEventId,sourceVersion,payloadHash,payload) VALUES(?,?,1,now(),?,'WORK',?,?,now(),'UTC','INSTANT','KNOWN','RESPONSE_COMPLETED',?,?,?,'1',?,'{}')",event,org,owner,work,work,profile,profile,event,"2".repeat(64));
 sql(c,"INSERT INTO mulino_evidence_Claims(ID,organizationId,revision,recordedAt,recordedBy,subjectKind,subjectId,workId,eventId,documentVersionId,effectiveFrom,valueState,sourceProfileId,assertion,quantity,unit) VALUES(?,?,1,now(),?,'WORK',?,?,?,?,now(),'KNOWN',?,'{}',?,'EA')",claim,org,owner,work,work,event,doc,profile,quantity);
 sql(c,"INSERT INTO mulino_evidence_CanonicalOccurrences(ID,organizationId,revision,recordedAt,recordedBy,subjectKind,subjectId,workId,sourceProfileId,effectiveFrom,valueState,kind,physicalScopeId,quantity,unit,reassessmentState) VALUES(?,?,1,now(),?,'WORK',?,?,?,now(),'KNOWN','RESPONSE_COMPLETED',?,?,'EA','COMPLETE')",occurrence,org,owner,work,work,profile,id(),quantity);
 sql(c,"INSERT INTO mulino_evidence_Verifications(ID,organizationId,revision,recordedAt,recordedBy,claimId,canonicalOccurrenceId,basisDocumentId,policyVersion,sourceMatched,identityMatched,quantityMatched,timeMatched,duplicateChecked,verdict,reason) VALUES(?,?,1,now(),?,?,?,?,'fixture',true,true,true,true,true,'VERIFIED','actual completed response')",verification,org,owner,claim,occurrence,doc);
 }return new String[]{occurrence,verification};}
 String binding(String root,String[] evidence,int quantity)throws Exception{String binding=id();try(var c=db()){sql(c,"INSERT INTO mulino_responsibility_CompletionBindings(organizationId,ID,createdAt,recordedAt,occurrenceId,rootId,startQuantity,quantity,unit,verificationId,coverageId) VALUES(?,?,now(),now(),?,?,0,?,'EA',?,?)",org,binding,evidence[0],root,quantity,evidence[1],id());}return binding;}
 void credit(Connection c,String binding,String root,String scope,String assignment,int start)throws Exception{sql(c,"INSERT INTO mulino_responsibility_ResolutionCredits(organizationId,ID,createdAt,recordedAt,bindingId,rootId,scopeId,assignmentId,startQuantity,quantity) VALUES(?,?,now(),now(),?,?,?,?,?,50)",org,id(),binding,root,scope,assignment,start);sql(c,"UPDATE mulino_work_read_ObligationReferences SET status='RESOLVED',evidenceId=(SELECT occurrenceId FROM mulino_responsibility_CompletionBindings WHERE ID=?),basis='VERIFIED_RESOLUTION' WHERE ID=?",binding,assignment);}
 @Test void partialCompletionFiftyCannotResolveBothFiftyLeavesInPostgres()throws Exception{var d=splitDuty();var evidence=verifiedResponse(50);String binding=binding(d[0],evidence,50);try(var c=db()){c.setAutoCommit(false);credit(c,binding,d[0],d[1],d[3],0);c.commit();}try(var c=db()){c.setAutoCommit(false);credit(c,binding,d[0],d[2],d[4],50);assertThrows(SQLException.class,c::commit);c.rollback();}try(var c=db();var p=c.prepareStatement("SELECT status FROM mulino_work_read_ObligationReferences WHERE ID=?")){p.setString(1,d[4]);try(var rs=p.executeQuery()){assertTrue(rs.next());assertEquals("OPEN",rs.getString(1));}}}
 @Test void fullCompletionHundredResolvesTwoDisjointFiftyLeavesInPostgres()throws Exception{var d=splitDuty();var evidence=verifiedResponse(100);String binding=binding(d[0],evidence,100);try(var c=db()){c.setAutoCommit(false);credit(c,binding,d[0],d[1],d[3],0);credit(c,binding,d[0],d[2],d[4],50);c.commit();}try(var c=db();var p=c.prepareStatement("SELECT count(*),sum(quantity) FROM mulino_responsibility_ResolutionCredits WHERE bindingId=?")){p.setString(1,binding);try(var rs=p.executeQuery()){assertTrue(rs.next());assertEquals(2,rs.getInt(1));assertEquals(0,new java.math.BigDecimal("100").compareTo(rs.getBigDecimal(2)));}}}

 @Test void concurrentPartialCompletionCreditNeverDischargesHundred()throws Exception{var d=splitDuty();var evidence=verifiedResponse(50);String binding=binding(d[0],evidence,50);var go=new CountDownLatch(1);var ready=new CountDownLatch(2);var pool=Executors.newFixedThreadPool(2);java.util.function.IntFunction<Callable<Boolean>> attempt=side->()->{try(var c=db()){c.setAutoCommit(false);ready.countDown();go.await();try{credit(c,binding,d[0],d[1+side],d[3+side],50*side);c.commit();return true;}catch(SQLException rejected){c.rollback();return false;}}};try{var a=pool.submit(attempt.apply(0));var b=pool.submit(attempt.apply(1));assertTrue(ready.await(10,TimeUnit.SECONDS));go.countDown();assertTrue(a.get(15,TimeUnit.SECONDS));assertFalse(b.get(15,TimeUnit.SECONDS));}finally{pool.shutdownNow();}try(var c=db();var p=c.prepareStatement("SELECT count(*),sum(quantity) FROM mulino_responsibility_ResolutionCredits WHERE bindingId=?")){p.setString(1,binding);try(var rs=p.executeQuery()){assertTrue(rs.next());assertEquals(1,rs.getInt(1));assertEquals(0,new java.math.BigDecimal("50").compareTo(rs.getBigDecimal(2)));}}}

}
