package com.mulino.application.inventory;

import com.mulino.application.core.*;
import com.mulino.application.quality.QualityEligibility;
import com.mulino.application.trade.SalesOrderLinePort;
import com.mulino.application.trade.TradeImpact;
import com.mulino.domain.inventory.*;
import java.math.BigDecimal;
import java.util.*;
import org.springframework.stereotype.Component;
import static com.mulino.application.inventory.InventoryCommands.*;

@Component
public final class FulfillmentCommands implements CommandHandler {
 private final InventoryRepository r;private final StockPrimitives stock;private final FulfillmentStockPrimitives primitive;private final QualityEligibility quality;private final ReadAuthorizer auth;private final org.springframework.beans.factory.ObjectProvider<SalesOrderLinePort> sales;private final TradeImpact impact;private final ExecutionClock clock;private final org.springframework.beans.factory.ObjectProvider<com.mulino.application.trade.SalesExecutionPort> salesEffects;
 public FulfillmentCommands(InventoryRepository r,StockPrimitives stock,FulfillmentStockPrimitives primitive,QualityEligibility quality,ReadAuthorizer auth,org.springframework.beans.factory.ObjectProvider<SalesOrderLinePort> sales,TradeImpact impact,ExecutionClock clock,org.springframework.beans.factory.ObjectProvider<com.mulino.application.trade.SalesExecutionPort> salesEffects){this.r=r;this.stock=stock;this.primitive=primitive;this.quality=quality;this.auth=auth;this.sales=sales;this.impact=impact;this.clock=clock;this.salesEffects=salesEffects;}
 public Set<String> capabilities(){return Set.of("reserveQuantity","replaceAllocation","releaseAllocation","pickQuantity","dispatchQuantity");}
 public Set<String> intentKinds(){return Set.of("COMMAND");}
 private SalesOrderLinePort sales(){var port=sales.getIfAvailable();if(port==null)throw new DomainError("HELD","SALES_CONTRACT_UNAVAILABLE","Sales line service unavailable");return port;}
 public CommandPreparation prepare(DomainContext c,Map<String,Object> intent){
  String cap=text(intent,"capabilityId",80);if(!capabilities().contains(cap)||!"COMMAND".equals(intent.get("intentKind")))throw DomainError.invalid("Fulfillment command required");var slots=slots(intent);
  Set<String> allowed=switch(cap){case "reserveQuantity"->Set.of("segmentId","salesLineId","startQuantity","quantity","unit");case "replaceAllocation"->Set.of("allocationId","segmentId","startQuantity","quantity","unit");case "dispatchQuantity"->Set.of("allocationId","transitPlaceId","occurredAt","evidenceRef");default->Set.of("allocationId");};if(!allowed.containsAll(slots.keySet()))throw DomainError.invalid("Unsupported fulfillment slot");
  boolean reserve=cap.equals("reserveQuantity"),replace=cap.equals("replaceAllocation");Map<String,Object> allocation=reserve?null:r.current(c,"SegmentAllocations",uuid(slots,"allocationId"));
  if(allocation!=null&&!Set.of("EXECUTABLE","SUSPENDED").contains(allocation.get("state")))throw new DomainError("CONFLICT","STALE_REVISION","Allocation terminal or replaced");
  String segmentId=reserve||replace?uuid(slots,"segmentId"):(String)allocation.get("segmentId");var segment=r.current(c,"QuantitySegments",segmentId);String lineId=reserve?uuid(slots,"salesLineId"):(String)allocation.get("orderLineId");var line=sales().requireLine(c,lineId);String customer=(String)line.get("customerId"),work=(String)line.get("workId");if(!cap.equals("releaseAllocation")&&Boolean.FALSE.equals(line.get("currentRevision")))throw new DomainError("CONFLICT","STALE_REVISION","Historical sales line cannot execute");
  if(!Objects.equals(segment.get("itemId"),line.get("itemId"))||!Objects.equals(segment.get("unit"),line.get("unit")))throw DomainError.invalid("Sales line item/unit mismatch");
  var fences=new TreeSet<>(stock.fences(segment));fences.add("inventory/sales-line/"+lineId);fences.add("sales/line/"+lineId);if(line.get("orderId")!=null)fences.add("sales/order/"+line.get("orderId"));if(allocation!=null){fences.add("inventory/allocation/"+allocation.get("ID"));fences.addAll(stock.fences(r.current(c,"QuantitySegments",(String)allocation.get("segmentId"))));}
  var scope=Map.of("TARGET",List.of(segmentId),"ITEM",List.of((String)segment.get("itemId")),"PLACE",List.of((String)segment.get("placeId")),"WORK",List.of(work));auth.authorizeScopes(c,cap,scope);
  // Plan §7.1/§6: authority is an intersection over every physical scope the command changes. The replaced
  // allocation's segment is deactivated by replace, so it needs the same scope authority releaseAllocation needs.
  if(replace){var replaced=r.current(c,"QuantitySegments",(String)allocation.get("segmentId"));auth.authorizeScopes(c,cap,Map.of("TARGET",List.of((String)replaced.get("ID")),"ITEM",List.of((String)replaced.get("itemId")),"PLACE",List.of((String)replaced.get("placeId")),"WORK",List.of(work)));}
  if(reserve||replace){requireWarehouse(c,segment);stock.leaf(c,segmentId,c.knownAt());String unit=text(slots,"unit",40);BigDecimal q=stock.quantity(c,segment,slots.get("quantity"),unit),start=coordinate(c,segment,slots,unit);if(start.add(q).compareTo(StockPrimitives.amount(segment))>0)throw DomainError.invalid("Reservation exceeds physical scope");
   var result=quality.assess(current(c),segment,"SELL",customer);var wanted=List.of(new QualityRanges.Range(start,start.add(q)));if(QualityRanges.quantity(QualityRanges.intersect(result.ranges(),wanted)).compareTo(q)!=0)throw new DomainError("REJECTED","INSUFFICIENT_ELIGIBLE_QUANTITY","Current exact sale interval not eligible");
   BigDecimal obligated=BigDecimal.ZERO;for(var a:r.currentRows(c,"SegmentAllocations"))if(Set.of("EXECUTABLE","SUSPENDED").contains(a.get("state"))&&(allocation==null||!a.get("ID").equals(allocation.get("ID")))){if(lineId.equals(a.get("orderLineId")))obligated=obligated.add((BigDecimal)a.get("quantity"));if(segmentId.equals(a.get("segmentId"))&&(a.get("startQuantity")==null||!QualityRanges.intersect(wanted,List.of(QualityEligibility.range(a))).isEmpty()))throw new DomainError("REJECTED","INSUFFICIENT_ELIGIBLE_QUANTITY","Physical interval already reserved");}
   if(q.add(obligated).compareTo(sales().remainingQuantity(c,lineId))>0)throw new DomainError("REJECTED","SALES_LINE_QUANTITY_EXCEEDED","Reservation exceeds sales line outstanding quantity");
   if(replace&&q.compareTo((BigDecimal)allocation.get("quantity"))!=0)throw DomainError.invalid("Replacement must preserve obligation quantity");
  }
  if(cap.equals("pickQuantity")||cap.equals("dispatchQuantity")){stock.leaf(c,segmentId,c.knownAt());if(!"EXECUTABLE".equals(allocation.get("state")))throw new DomainError("REJECTED","INSUFFICIENT_ELIGIBLE_QUANTITY","Suspended allocation cannot execute");var sale=quality.assess(current(c),segment,"SELL",customer);if(QualityRanges.quantity(QualityRanges.intersect(sale.ranges(),List.of(QualityEligibility.range(allocation)))).compareTo((BigDecimal)allocation.get("quantity"))!=0)throw new DomainError("REJECTED","INSUFFICIENT_ELIGIBLE_QUANTITY","Current exact sale permission denied");if(cap.equals("dispatchQuantity")){requireWarehouse(c,segment);if(allocation.get("pickedAt")==null)throw DomainError.invalid("Pick before dispatch required");quality.assess(current(c),segment,"DISPATCH",customer);var dispatch=quality.assess(current(c),segment,"DISPATCH",customer);if(QualityRanges.quantity(QualityRanges.intersect(dispatch.ranges(),List.of(QualityEligibility.range(allocation)))).compareTo((BigDecimal)allocation.get("quantity"))!=0)throw new DomainError("REJECTED","INSUFFICIENT_ELIGIBLE_QUANTITY","Current dispatch authority denied");String transit=uuid(slots,"transitPlaceId");if(!"TRANSIT".equals(r.current(c,"Places",transit).get("kind")))throw DomainError.invalid("Transit place required");fences.add("inventory/place/"+transit);auth.authorizeScopes(c,cap,Map.of("TARGET",List.of(segmentId),"ITEM",List.of((String)segment.get("itemId")),"PLACE",List.of(transit),"WORK",List.of(work)));requireContinuousAuthority(c,segment,allocation,customer,time(c,slots));text(slots,"evidenceRef",240);}}
  return CommandPreparation.ordinary(scope,new ArrayList<>(fences),cap.equals("reserveQuantity")||replace?"RESERVE":cap.equals("dispatchQuantity")?"DISPATCH":"ALLOCATION",allocation==null?segmentId:(String)allocation.get("ID"),((Number)(allocation==null?segment:allocation).get("revision")).intValue());
 }
 public List<SubjectBinding> subjectBindings(DomainContext c,Map<String,Object> intent,CommandPreparation p){var s=slots(intent);String cap=text(intent,"capabilityId",80);String line=cap.equals("reserveQuantity")?uuid(s,"salesLineId"):(String)r.current(c,"SegmentAllocations",uuid(s,"allocationId")).get("orderLineId");return List.of(SubjectBinding.optional("QuantitySegment",Set.copyOf(p.scopes().get("TARGET"))),SubjectBinding.optional("Work",Set.copyOf(p.scopes().get("WORK"))),SubjectBinding.optional("TradeItem",Set.copyOf(p.scopes().get("ITEM"))),SubjectBinding.optional("SalesOrderLine",Set.of(line)));}
 public Map<String,Object> execute(DomainContext c,Map<String,Object> intent){prepare(c,intent);var s=slots(intent);String cap=text(intent,"capabilityId",80),command=CommandExecution.commandId();Map<String,Object> result;
  if(cap.equals("reserveQuantity")||cap.equals("replaceAllocation")){var old=cap.equals("replaceAllocation")?r.current(c,"SegmentAllocations",uuid(s,"allocationId")):null;String lineId=old==null?uuid(s,"salesLineId"):(String)old.get("orderLineId");var line=sales().requireLine(c,lineId);var segment=r.current(c,"QuantitySegments",uuid(s,"segmentId"));if(old!=null)primitive.transition(c,(String)old.get("ID"),"REPLACED");var eligible=quality.assess(current(c),segment,"SELL",(String)line.get("customerId"));result=primitive.reserve(c,segment,lineId,(String)line.get("customerId"),(String)line.get("workId"),new BigDecimal(s.get("startQuantity").toString()),new BigDecimal(s.get("quantity").toString()),eligible.nextValidityBoundary(),command,old==null?null:(String)old.get("ID"));impact.invalidate(c,(String)line.get("workId"));}
  else {var a=r.current(c,"SegmentAllocations",uuid(s,"allocationId"));if(cap.equals("releaseAllocation"))primitive.transition(c,(String)a.get("ID"),"RELEASED");else if(cap.equals("pickQuantity"))primitive.pick(c,(String)a.get("ID"));else {var line=sales().requireLine(c,(String)a.get("orderLineId"));result=primitive.dispatch(c,(String)a.get("ID"),uuid(s,"transitPlaceId"),(String)line.get("destinationId"),time(c,s),text(s,"evidenceRef",240),command);var effectPort=salesEffects.getIfAvailable();if(effectPort==null)throw new DomainError("HELD","SALES_CONTRACT_UNAVAILABLE","Sales execution service unavailable");effectPort.recordExecutionEffect(c,(String)a.get("orderLineId"),"DISPATCHED",(String)result.get("ID"),(BigDecimal)result.get("quantity"),(String)result.get("unit"));impact.invalidate(c,(String)a.get("workId"));return response(result,"dispatchId");}impact.invalidate(c,(String)a.get("workId"));result=r.current(c,"SegmentAllocations",(String)a.get("ID"));}
  return response(result,"allocationId");
 }
 /**
  * A dispatch dated in the past moves the goods at that instant. Current eligibility alone would launder a movement made while
  * a hold, a missing basis or an expired permission applied (plan §4.2: an already-occurred unauthorized movement is recorded
  * through observation reconciliation, never promoted to a normal dispatch; §6: dispatch authorizes execution under current
  * eligibility). The occurrence cannot precede the authorized pick, and SELL and DISPATCH must cover the exact allocation range
  * at the occurrence instant and at every permission boundary up to now, because a late validity sweep must not let a guard
  * pass what the sweep would have suspended (implementation-contracts: sweeper가 늦어도 실행 guard가 출고를 막아야 한다).
  */
 private void requireContinuousAuthority(DomainContext c,Map<String,Object> segment,Map<String,Object> allocation,String customer,java.time.Instant at){
  // The pick is part of the authorized execution; a movement dated before it is a past fact, not this command's effect.
  if(allocation.get("pickedAt")!=null&&at.isBefore(StockPrimitives.instant(allocation.get("pickedAt"))))throw DomainError.invalid("Dispatch occurrence cannot precede its authorized pick");
  var now=clock.instant();var wanted=List.of(QualityEligibility.range(allocation));BigDecimal q=(BigDecimal)allocation.get("quantity");var instants=new TreeSet<java.time.Instant>();instants.add(at);
  java.util.function.Consumer<Object> add=v->{if(v!=null){var t=StockPrimitives.instant(v);if(t.isAfter(at)&&!t.isAfter(now))instants.add(t);}};
  for(String table:List.of("Restrictions","DispositionBases"))for(var row:r.rows(c,table)){add.accept(row.get("validFrom"));add.accept(row.get("releasedAt"));if(row.get("validUntil")!=null)add.accept(StockPrimitives.instant(row.get("validUntil")).plusNanos(1000));}
  var lot=r.object(c,"ManufacturingLots",(String)segment.get("lotId"));if(lot.get("expiresAt")!=null)add.accept(StockPrimitives.instant(lot.get("expiresAt")).plusNanos(1000));
  var checked=new HashSet<java.time.Instant>();
  while(!instants.isEmpty()){var t=instants.pollFirst();if(!checked.add(t))continue;if(checked.size()>500)throw new DomainError("REJECTED","INSUFFICIENT_ELIGIBLE_QUANTITY","Dispatch authority history too fragmented to verify");var historical=new DomainContext(c.organizationId(),c.actorId(),c.stableRequestOwner(),t,now);
   for(String action:List.of("SELL","DISPATCH")){var result=quality.assess(historical,segment,action,customer);if(QualityRanges.quantity(QualityRanges.intersect(result.ranges(),wanted)).compareTo(q)!=0)throw new DomainError("REJECTED","INSUFFICIENT_ELIGIBLE_QUANTITY","Dispatch occurrence time is outside continuous sale and dispatch authority");if(result.nextValidityBoundary()!=null)add.accept(result.nextValidityBoundary());}}
 }
 /** Allocation coordinates use the item scale too: a coordinate finer than the unit cannot be split out later (plan §3.1 decimal precision). */
 private BigDecimal coordinate(DomainContext c,Map<String,Object> segment,Map<String,Object> slots,String unit){var start=com.mulino.application.quality.QualityCommands.decimal(slots,"startQuantity");if(start.signum()>0)stock.quantity(c,segment,slots.get("startQuantity"),unit);return start;}
 private void requireWarehouse(DomainContext c,Map<String,Object> segment){if(!"INTERNAL_STORAGE".equals(r.current(c,"Places",(String)segment.get("placeId")).get("kind"))||!r.internalCustodian(c,(String)segment.get("custodianId")))throw new DomainError("REJECTED","SCOPE_INELIGIBLE","Confirmed warehouse custody required for fulfillment");}
 private DomainContext current(DomainContext c){var now=clock.instant();return new DomainContext(c.organizationId(),c.actorId(),c.stableRequestOwner(),now,now);}
 private Map<String,Object> response(Map<String,Object> row,String key){var effects=new LinkedHashMap<String,Object>(row);effects.put(key,row.get("ID"));for(String field:List.of("quantity","startQuantity"))if(effects.get(field) instanceof BigDecimal q)effects.put(field,InventoryQuantity.text(q));return Map.of("outcome","APPLIED","revision",row.get("revision"),"effects",effects);}
}
